.travis.yml
npm-shrinkwrap.json
readme.md

Adds initial travis CI. We'll do the docs deploy later

[BPK-551] Add travis integration

---

npm-shrinkwrap.json
package.json

In prep for upgrading Theo I discovered some low hanging fruit. I have verified the storybook dev environment as well as the docs dev environment & production build.
The @storybook/react upgrade has fixed the double build issue we were experiencing before:

Upgrade @storybook/addon-actions, @storybook/react & webpack-dev-server

---

.storybook/config.js
.storybook/webpack.config.js
changelog.md
packages/bpk-component-text/index.js
packages/bpk-component-text/package.json
packages/bpk-component-text/readme.md
packages/bpk-component-text/src/BpkText-test.js
packages/bpk-component-text/src/BpkText.js
packages/bpk-component-text/src/BpkText.scss
packages/bpk-component-text/src/__snapshots__/BpkText-test.js.snap
packages/bpk-component-text/src/__snapshots__/withTextStyle-test.js.snap
packages/bpk-component-text/src/withTextStyle-test.js
packages/bpk-component-text/src/withTextStyle.js
packages/bpk-component-text/stories.js
packages/bpk-component-text/stories.scss
packages/bpk-docs/package.json
packages/bpk-docs/src/components/Paragraph/Paragraph.js
packages/bpk-docs/src/components/Paragraph/Paragraph.scss
packages/bpk-docs/src/components/Paragraph/index.js
packages/bpk-docs/src/pages/TypographyPage/TypographyPage.js

This can be reviewed. WIP because I still need to write up the docs

[BPK-816] text component

---

packages/bpk-docs/src/pages/BackpackReactScriptsPage/BackpackReactScriptsPage.js
packages/bpk-docs/src/pages/GettingStartedPage/GettingStartedPage.js

Remove references to internal urls

---

changelog.md
packages/bpk-component-table/src/BpkTableCell-test.js
packages/bpk-component-table/src/BpkTableCell.js
packages/bpk-component-table/src/__snapshots__/BpkTableCell-test.js.snap

Ability to apply a CSS class to a table cell BpkTableCell component through the className property

Enable BpkTableCell custom styling

---

packages/bpk-docs/src/components/Heading/Heading.js

Fixed comments raised in https://github.com/Skyscanner/backpack/pull/22

[BPK-817] Fixed review comments missed in previous PR.

---

.github/PULL_REQUEST_TEMPLATE.md

[No JIRA] Add pull request template

---

changelog.md
packages/bpk-react-utils/src/Portal.js

+ [x] If I've updated `npm-shrinkwrap.json` those chagnes are intentional.

[BPK-799] Fix popover behaviour when dragging for mobile

---

changelog.md
packages/bpk-component-modal/src/BpkModalDialog.js
packages/bpk-component-modal/src/bpk-modal-dialog.scss
packages/bpk-react-utils/src/Portal.js

[BPK-799] Fix issues with modal interaction is Safari on IOS

---

packages/bpk-tokens/src/base/modals.json
packages/bpk-tokens/tokens/base.ios.json
packages/bpk-tokens/tokens/base.raw.json

**Note:** I assumed this is too trivial a change to put in the changelog, but let me know if not and I'll add it. If I've forgotten to do anything else let me know!

Fixed an incorrect token type.

---

NPM_OWNERS

After this is merged, a squad member other than me will need to run `./scripts/npm/update-owners.sh`.

Added shaundon (me) to NPM_OWNERS

---

packages/bpk-docs/src/constants/redirect-routes.js
packages/bpk-docs/src/constants/routes.js
packages/bpk-docs/src/layouts/DocsLayout/DocsLayout.js
packages/bpk-docs/src/pages/BannerAlertsPage/BannerAlertsPage.js
packages/bpk-docs/src/pages/BannerAlertsPage/index.js
packages/bpk-docs/src/routes/Routes.js
webpack.config.babel.js

[BPK-837] Rename 'Notifications' to 'Banner alerts' in docs

---

contributing.md
packages/bpk-docs/src/routes/Routes.js

[No Jira] couple of things

---

.travis.yml
dangerfile.js
npm-shrinkwrap.json
package.json

Couple of things I'd like to mention:
- I didn't add the licence header to `dangerfile.js` because I looked at other config type files and they don't have it, e.g. `gulpfile.babel.js`, so I assumed that's the convention.
- I also didn't see any non `package/*` changes highlighted in the changelog, so I …

[BPK-846] Add Danger to workflow

---

dangerfile.js

Make Danger always say something nice

---

packages/bpk-component-image/src/BpkBackgroundImage.js
packages/bpk-component-image/src/BpkImage.js

[BPK-231] Fix styling of images when javascript is unavailable

---

packages/bpk-component-image/index.js
packages/bpk-component-image/readme.md
packages/bpk-component-image/src/BpkImage-test.js
packages/bpk-component-image/src/BpkImage.js
packages/bpk-component-image/src/__snapshots__/BpkImage-test.js.snap
packages/bpk-component-image/stories.js
packages/bpk-docs/src/pages/ImagesPage/ImagesPage.js

[BPK-231] Add proper support for userland styles

---

contributing.md

Add watchman install to RN setup instructions

---

contributing.md

[no-jira] Added more context to RN Android setup

---

.storybook/config.js

adds theme selector

---

packages/bpk-mixins/_index.scss
packages/bpk-mixins/src/mixins/_buttons.scss
packages/bpk-mixins/src/mixins/_theming.scss
packages/bpk-mixins/src/mixins/_typography.scss

add theming to bpk-link

---

changelog.md

[skip ci] - Fix changelog

---

packages/bpk-component-calendar/src/bpk-calendar-date.scss
packages/bpk-component-calendar/src/bpk-calendar-nav.scss

adds theming to the calendar

---

changelog.md
native/packages/react-native-bpk-component-text/readme.md
native/packages/react-native-bpk-component-text/src/BpkText.android-test.js
native/packages/react-native-bpk-component-text/src/BpkText.ios-test.js
native/packages/react-native-bpk-component-text/src/BpkText.js
native/packages/react-native-bpk-component-text/src/__snapshots__/BpkText.android-test.js.snap
native/packages/react-native-bpk-component-text/src/__snapshots__/BpkText.ios-test.js.snap
native/packages/react-native-bpk-component-text/stories.js
native/storybook/addons.js
native/storybook/storybook.js
package.json

Also improved the storybook dramatically.

[BPK-944] Add emphasize prop to RN text component.

---

packages/bpk-docs/src/pages/GettingStartedPage/GettingStartedPage.js

[BPK-922] Add RN instructions to getting started

---

packages/bpk-docs/src/pages/FormsPage/FormsPage.js

[BPK-926] Fix incorrect placeholder values

---

scripts/npm/check-owners.js

[BPK-962] check-owners script now checks native packages

---

dangerfile.js

+ [ ] For any new web components I've made sure that the style can be extended by the consumer using a `className` override.
+ [ ] For any new native components I've made sure that the style can be extended by the consumer using a `style` override.

Made Danger even better

---

packages/bpk-docs/package.json
packages/bpk-docs/src/constants/routes.js
packages/bpk-docs/src/layouts/DocsLayout/DocsLayout.js
packages/bpk-docs/src/pages/NativeCardsPage/NativeCardsPage.js
packages/bpk-docs/src/pages/NativeCardsPage/index.js
packages/bpk-docs/src/routes/Routes.js
readme.md

[BPK-879] Add docs for card component

---

packages/bpk-docs/src/pages/FieldsetsPage/FieldsetsPage.js

[BPK-974] Fix fieldset page grammar

---

packages/bpk-docs/src/pages/ResourcesPage/ResourcesPage.js

[BPK-973] Updated link to Craft library

---

contributing.md

[nojira] update contributing.md

---

dangerfile.js

Danger will now check that shrinkwrap changes are intentional.
Also Danger will ensure new files are licensed.

[WIP] [BPK-969] Enhance Dangerfile checks

---

dangerfile.js

+ [ ] For any new web components I've made sure that the style can be extended by the consumer using a `className` override.
+ [ ] For any new native components I've made sure that the style can be extended by the consumer using a `style` override.

[skip ci] Fix a bug in Dangerfile

---

changelog.md
native/packages/react-native-bpk-theming/index.js
native/packages/react-native-bpk-theming/package.json
native/packages/react-native-bpk-theming/readme.md
native/packages/react-native-bpk-theming/src/BpkButton-test.android.js
native/packages/react-native-bpk-theming/src/BpkButton-test.ios.js
native/packages/react-native-bpk-theming/src/BpkThemeProvider-test.common.js
native/packages/react-native-bpk-theming/src/BpkThemeProvider.js
native/packages/react-native-bpk-theming/src/__snapshots__/BpkButton-test.android.js.snap
native/packages/react-native-bpk-theming/src/__snapshots__/BpkButton-test.ios.js.snap
native/packages/react-native-bpk-theming/stories.js
native/storybook/storybook.js

[BPK-952] Theming support

---

native/package.json
native/packages/react-native-bpk-component-icon/package-lock.json
native/packages/react-native-bpk-theming/package-lock.json
package.json
scripts/npm/check-versions.js

I added a node script to check Node & npm versions and print out helpful messaging otherwise.

[BPK-970] Improve npm/node check message

---

changelog.md
packages/bpk-component-progress/src/bpk-progress.scss
packages/bpk-component-ticket/src/bpk-ticket.scss

[BPK-1011] - fix ticket notch safari display issue

---

native/packages/react-native-bpk-component-icon/readme.md

[BPK-1006] - Fix readme formatting

---

changelog.md
native/packages/react-native-bpk-component-button/package-lock.json
native/packages/react-native-bpk-component-button/package.json
native/packages/react-native-bpk-component-button/src/BpkButton-styles.js
native/packages/react-native-bpk-component-button/src/BpkButton-test.common.js
native/packages/react-native-bpk-component-button/src/BpkButton.js
native/packages/react-native-bpk-component-button/src/__snapshots__/BpkButton-test.android.js.snap
native/packages/react-native-bpk-component-button/src/__snapshots__/BpkButton-test.ios.js.snap
native/packages/react-native-bpk-component-button/stories.js
native/packages/react-native-bpk-theming/src/BpkThemeProvider.js
native/packages/react-native-bpk-theming/src/create-theme-listener.js
native/packages/react-native-bpk-theming/src/create-with-theme.js

[BPK-953] Allow BpkButton to be themed

---

native/package-lock.json
native/packages/react-native-bpk-theming/package-lock.json
packages/bpk-component-mobile-scroll-container/package-lock.json

on a fresh install the package locks gets changed, this PR is to commit those changes

[NoJira] package lock update

---

packages/bpk-component-banner-alert/src/BpkBannerAlert.js
packages/bpk-component-banner-alert/src/bpk-banner-alert.scss
packages/bpk-component-banner-alert/stories.js
packages/bpk-docs/src/pages/BannerAlertsPage/BannerAlertsPage.js
packages/bpk-tokens/src/web/base/notifications.json
packages/bpk-tokens/tokens/base.common.js
packages/bpk-tokens/tokens/base.default.scss
packages/bpk-tokens/tokens/base.es6.js
packages/bpk-tokens/tokens/base.raw.json
packages/bpk-tokens/tokens/base.scss

[BPK-1073] Add neutral banner alert configuration (web)

---

native/packages/react-native-bpk-component-button/src/__snapshots__/BpkButton-test.android.js.snap
native/packages/react-native-bpk-component-text/src/BpkText.js
native/packages/react-native-bpk-component-text/src/__snapshots__/BpkText-test.android.js.snap

update emphasize behaviour in android
Before
After

update emphasize behaviour in android

---

changelog.md
native/packages/react-native-bpk-component-button/src/BpkButton-styles.js
native/packages/react-native-bpk-component-button/src/BpkButton-test.android.js
native/packages/react-native-bpk-component-button/src/BpkButton-test.ios.js
native/packages/react-native-bpk-component-button/src/BpkButton.js
native/packages/react-native-bpk-component-button/src/__snapshots__/BpkButton-test.android.js.snap
native/packages/react-native-bpk-component-button/src/__snapshots__/BpkButton-test.ios.js.snap
native/packages/react-native-bpk-component-button/src/layout/BpkButtonContainer.android.js
native/packages/react-native-bpk-component-button/src/layout/BpkButtonContainer.ios.js
native/packages/react-native-bpk-component-button/src/utils.js

I've slayed the beast by creating two components, one for iOS and one for Android for the two containers, I've moved away all the accessory functions in a utils file in order to have some sort of structure in place

[NoJira] refactor RN button component

---

changelog.md
native/packages/react-native-bpk-component-animate-height/src/BpkAnimateHeight.js
native/packages/react-native-bpk-component-button/src/BpkButton.js
native/packages/react-native-bpk-component-button/src/layout/BpkButtonContainer.android.js
native/packages/react-native-bpk-component-button/src/layout/BpkButtonContainer.ios.js
native/packages/react-native-bpk-component-card/src/BpkCard.js

Import prop type to prevent the build to break in the native app
see 
https://github.com/necolas/react-native-web/issues/423

[NoJira] import proptypes from view to prevent broken build

---

native/package-lock.json
native/package.json
native/storybook/TextStyles.js
native/storybook/storybook.js
scripts/npm/check-bpk-dependencies.js

this will prevent the checkDeps to break after every release

[BPK-1074] remove devDeps from native package.json

---

native/package-lock.json
native/package.json
package-lock.json
package.json

This is the first of a few consecutive PR's aimed at upgrading dependencies in the backpack codebase.

[BPK-971] Update low risk storybook deps

---

package-lock.json
package.json
packages/bpk-component-barchart/src/__snapshots__/BpkBarchartBars-test.js.snap
packages/bpk-component-barchart/src/__snapshots__/BpkChartDataTable-test.js.snap
packages/bpk-component-calendar/src/BpkCalendarContainer-test.js
packages/bpk-component-calendar/src/BpkCalendarGridTransition-test.js
packages/bpk-component-image/src/withLazyLoading-test.js
packages/bpk-component-image/src/withLazyLoading.js
packages/bpk-component-star-rating/src/__snapshots__/BpkInteractiveStarRating-test.js.snap
packages/bpk-component-star-rating/src/__snapshots__/BpkStarRating-test.js.snap
scripts/jest/setup.js

This is the last of a few PR's aimed at upgrading dependencies in the backpack monorepo. I focus on updating enzyme in this one.
Please have a read of their upgrade guide: https://github.com/airbnb/enzyme/blob/master/docs/guides/migration-from-2-to-3.md
It details the significant changes of version 3 vs 2. We've had to update some of our tests as a result.

[BPK-971] Upgrade enzyme dependencies

---

contributing.md

Not 100% sure what's going on with the whitespace here but this seems to fix the heading

Fix Sass mixins header in contributing.md

---

changelog.md
native/packages/react-native-bpk-component-spinner/index.js
native/packages/react-native-bpk-component-spinner/package-lock.json
native/packages/react-native-bpk-component-spinner/package.json
native/packages/react-native-bpk-component-spinner/readme.md
native/packages/react-native-bpk-component-spinner/src/BpkSpinner-test.android.js
native/packages/react-native-bpk-component-spinner/src/BpkSpinner-test.common.js
native/packages/react-native-bpk-component-spinner/src/BpkSpinner-test.ios.js
native/packages/react-native-bpk-component-spinner/src/BpkSpinner.js
native/packages/react-native-bpk-component-spinner/src/__snapshots__/BpkSpinner-test.android.js.snap
native/packages/react-native-bpk-component-spinner/src/__snapshots__/BpkSpinner-test.ios.js.snap
native/packages/react-native-bpk-component-spinner/stories.js
native/storybook/storybook.js

Docs and screenshots to be added in a future PR.
Here's some screenshots of the 'all types' story:
The themed one doesn't look very different from the dark one right now because it's using `#2d244c` (same as the themed button), but this may change in future based on feedback from @jamesf3rguson.

[BPK-1083] New spinner component

---

changelog.md
packages/bpk-animate-height/src/AnimateHeight.js
packages/bpk-component-grid/src/BpkGridColumn.js

[NOJIRA] Remove usage of `Number.isNaN` & `Number.isFinite`

---

changelog.md
native/packages/react-native-bpk-component-horizontal-nav/index.js
native/packages/react-native-bpk-component-horizontal-nav/package-lock.json
native/packages/react-native-bpk-component-horizontal-nav/package.json
native/packages/react-native-bpk-component-horizontal-nav/readme.md
native/packages/react-native-bpk-component-horizontal-nav/src/BpkHorizontalNav-test.android.js
native/packages/react-native-bpk-component-horizontal-nav/src/BpkHorizontalNav-test.common.js
native/packages/react-native-bpk-component-horizontal-nav/src/BpkHorizontalNav-test.ios.js
native/packages/react-native-bpk-component-horizontal-nav/src/BpkHorizontalNav.js
native/packages/react-native-bpk-component-horizontal-nav/src/BpkHorizontalNavItem-test.android.js
native/packages/react-native-bpk-component-horizontal-nav/src/BpkHorizontalNavItem-test.common.js
native/packages/react-native-bpk-component-horizontal-nav/src/BpkHorizontalNavItem-test.ios.js
native/packages/react-native-bpk-component-horizontal-nav/src/BpkHorizontalNavItem.js
native/packages/react-native-bpk-component-horizontal-nav/src/__snapshots__/BpkHorizontalNav-test.android.js.snap
native/packages/react-native-bpk-component-horizontal-nav/src/__snapshots__/BpkHorizontalNav-test.ios.js.snap
native/packages/react-native-bpk-component-horizontal-nav/src/__snapshots__/BpkHorizontalNavItem-test.android.js.snap
native/packages/react-native-bpk-component-horizontal-nav/src/__snapshots__/BpkHorizontalNavItem-test.ios.js.snap
native/packages/react-native-bpk-component-horizontal-nav/stories.js
native/storybook/storybook.js

[BPK-1079] HorizontalNav component

---

changelog.md
native/packages/react-native-bpk-component-switch/index.js
native/packages/react-native-bpk-component-switch/package-lock.json
native/packages/react-native-bpk-component-switch/package.json
native/packages/react-native-bpk-component-switch/readme.md
native/packages/react-native-bpk-component-switch/src/BpkSwitch-test.android.js
native/packages/react-native-bpk-component-switch/src/BpkSwitch-test.common.js
native/packages/react-native-bpk-component-switch/src/BpkSwitch-test.ios.js
native/packages/react-native-bpk-component-switch/src/BpkSwitch.js
native/packages/react-native-bpk-component-switch/src/__snapshots__/BpkSwitch-test.android.js.snap
native/packages/react-native-bpk-component-switch/src/__snapshots__/BpkSwitch-test.ios.js.snap
native/packages/react-native-bpk-component-switch/stories.js
native/storybook/storybook.js

[BPK-1039] Add native switch component

---

native/packages/react-native-bpk-component-card/src/BpkCard-test.common.js
native/packages/react-native-bpk-component-card/src/__snapshots__/BpkCard-test.android.js.snap
native/packages/react-native-bpk-component-card/src/__snapshots__/BpkCard-test.ios.js.snap
native/packages/react-native-bpk-component-card/stories.js

Also add card results list example to storybook

[BPK-1025] Refactor card tests

---

native/packages/react-native-bpk-component-button/stories.js
native/packages/react-native-bpk-component-horizontal-nav/stories.js
native/packages/react-native-bpk-component-spinner/stories.js
native/packages/react-native-bpk-component-switch/stories.js
native/storybook/themeAttributes.js

Removes duplication across our stories.
This is a precursor to a future move to make use of the new branding API.

[no jira] Make theming common amongst native stories

---

changelog.md

I removed the ticket changelog entry as it's not getting released anymore.

[NOJIRA] Changelog tweaks

---

changelog.md
packages/bpk-component-banner-alert/readme.md
packages/bpk-component-banner-alert/src/BpkBannerAlert.js

Tiny PR to address https://skyscanner.slack.com/archives/C0JHPDSSU/p1511197541000423?thread_ts=1511197480.000625&cid=C0JHPDSSU

[BPK-509] Fix missing required label prop

---

packages/bpk-component-image/readme.md

Documents the combination of the two HOCs and clarifies SSR support.

[No JIRA] Improve image docs

---

packages/bpk-component-theme-toggle/src/theming.js

amend the blockquote colour in the custom theme

[NoJira] update theme colours

---

contributing.md
decisions/README.md
decisions/TEMPLATE.md
decisions/theme-props-naming.md

Thought I'd get us started with one!

[no jira] Decisions directory

---

changelog.md

Move changelog entry after release

---

.storybook/config.js
packages/bpk-component-definition-list/index.js
packages/bpk-component-definition-list/package-lock.json
packages/bpk-component-definition-list/package.json
packages/bpk-component-definition-list/readme.md
packages/bpk-component-definition-list/src/BpkDefinitionDescription-test.js
packages/bpk-component-definition-list/src/BpkDefinitionDescription.js
packages/bpk-component-definition-list/src/BpkDefinitionList-test.js
packages/bpk-component-definition-list/src/BpkDefinitionList.js
packages/bpk-component-definition-list/src/BpkDefinitionTerm-test.js
packages/bpk-component-definition-list/src/BpkDefinitionTerm.js
packages/bpk-component-definition-list/src/ComponentFactory.js
packages/bpk-component-definition-list/src/__snapshots__/BpkDefinitionDescription-test.js.snap
packages/bpk-component-definition-list/src/__snapshots__/BpkDefinitionList-test.js.snap
packages/bpk-component-definition-list/src/__snapshots__/BpkDefinitionTerm-test.js.snap
packages/bpk-component-definition-list/src/bpk-definition-list.scss
packages/bpk-component-definition-list/stories.js
readme.md

Entirely based on `bpk-component-list`, just a simple wrapper around `dl`, `dt`, and `dd`.

Add bpk-component-definitions-list

---

packages/bpk-component-drawer/src/BpkDrawer.js
packages/bpk-component-drawer/src/bpk-drawer.scss

Temporary workaround for scrolling issue on iphone

Fix scrolling the scrim background on iphone

---

changelog.md
packages/bpk-component-drawer/package.json
packages/bpk-component-drawer/readme.md
packages/bpk-docs/package.json
packages/bpk-docs/src/constants/routes.js
packages/bpk-docs/src/layouts/DocsLayout/DocsLayout.js
packages/bpk-docs/src/pages/DrawerPage/DrawerPage.js
packages/bpk-docs/src/pages/DrawerPage/index.js
packages/bpk-docs/src/pages/ModalsPage/ModalsPage.js
packages/bpk-docs/src/routes/Routes.js

Follow up from #286 
Will rebase once that's merged.

Add sliding drawer docs

---

.storybook/themeableAttributes.js
packages/bpk-component-close-button/readme.md
packages/bpk-component-close-button/src/bpk-close-button.scss
packages/bpk-component-close-button/src/themeAttributes-test.js
packages/bpk-component-close-button/src/themeAttributes.js
packages/bpk-component-modal/readme.md
packages/bpk-component-modal/src/BpkModal-test.js
packages/bpk-component-modal/src/BpkModal.js
packages/bpk-component-modal/src/themeAttributes-test.js
packages/bpk-component-modal/stories.js
packages/bpk-component-theme-toggle/src/BpkThemeToggle.js
packages/bpk-component-theme-toggle/src/__snapshots__/BpkThemeToggle-test.js.snap
packages/bpk-component-theme-toggle/src/theming.js
packages/bpk-docs/src/pages/DrawerPage/DrawerPage.js
packages/bpk-react-utils/readme.md
packages/bpk-react-utils/src/Portal.js
packages/bpk-tokens/src/web/base/modals.json
packages/bpk-tokens/tokens/base.raw.json

I aligned the names of the close buttons theme attributes to our [guidelines](https://github.com/Skyscanner/backpack/blob/BPK-984-fix-close-button-theme-attributes/decisions/theme-props-naming.md).

[BPK-984] Fix close button theme attributes

---

.storybook/themeableAttributes.js
changelog.md
packages/bpk-component-popover/index.js
packages/bpk-component-popover/readme.md
packages/bpk-component-popover/src/BpkPopoverPortal.js
packages/bpk-component-popover/src/themeAttributes-test.js
packages/bpk-component-popover/src/themeAttributes.js
packages/bpk-component-popover/stories.js
packages/bpk-component-popover/stories.scss
packages/bpk-docs/src/pages/PopoversPage/PopoversPage.js
packages/bpk-docs/src/themeableAttributes.js
packages/bpk-react-utils/src/Portal-test.js
packages/bpk-react-utils/src/Portal.js

Themeable popover with docs and storybook

[BPK-987] themeable popover

---

packages/bpk-component-checkbox/readme.md
packages/bpk-component-radio/readme.md
packages/bpk-docs/src/themeableAttributes.js

Forgot the docs for the checkboxes and radio buttons

[BPK-981] Forgotten docs

---

packages/bpk-docs/src/layouts/SideNavLayout/nav-list.scss

[BPK-1136] Add theme support to docs sidenav

---

packages/bpk-docs/src/layouts/DocsLayout/DocsLayout.js
packages/bpk-docs/src/pages/HomePage/HomePage.js

- Updated mission to reflect the squad refresh
- Removed Tickets from side nav for React Native as this is no longer needed

[No-JIRA]: Updating mission and component nav

---

native/packages/react-native-bpk-component-text-input/src/BpkTextInput-test.common.js
native/packages/react-native-bpk-component-text-input/src/BpkTextInput.js
native/packages/react-native-bpk-component-text-input/src/__snapshots__/BpkTextInput-test.android.js.snap
native/packages/react-native-bpk-component-text-input/src/__snapshots__/BpkTextInput-test.ios.js.snap

Part 2 of my PR adventure for floating label text inputs. Snapshot tests!

[BPK-1108] Add snapshot tests

---

packages/bpk-docs/src/pages/ThemingPage/ThemingPage.js

[BPK-1170] Add note about CSS variables support

---

changelog.md
native/packages/react-native-bpk-component-text-input/readme.md
native/packages/react-native-bpk-component-text-input/src/BpkTextInput-test.common.js
native/packages/react-native-bpk-component-text-input/src/BpkTextInput.js
native/packages/react-native-bpk-component-text-input/src/__snapshots__/BpkTextInput-RTL-test.js.snap
native/packages/react-native-bpk-component-text-input/src/__snapshots__/BpkTextInput-test.android.js.snap
native/packages/react-native-bpk-component-text-input/src/__snapshots__/BpkTextInput-test.ios.js.snap

[BPK-1108] Fix placeholders

---

packages/bpk-component-banner-alert/package-lock.json
packages/bpk-component-banner-alert/package.json

Pin an older version of react-transition-group(1.x.x) so that at least
the component works.
cc @matthewdavidson

[No JIRA] Fix banner alert

---

changelog.md
native/packages/react-native-bpk-component-text-input/readme.md
native/packages/react-native-bpk-component-text-input/src/BpkTextInput-test.common.js
native/packages/react-native-bpk-component-text-input/src/BpkTextInput.js
native/packages/react-native-bpk-component-text-input/src/__snapshots__/BpkTextInput-RTL-test.js.snap
native/packages/react-native-bpk-component-text-input/src/__snapshots__/BpkTextInput-test.android.js.snap
native/packages/react-native-bpk-component-text-input/src/__snapshots__/BpkTextInput-test.ios.js.snap
native/packages/react-native-bpk-component-text-input/stories.js

Feel silly we didn't think of this approach before!
CC @tadam313

[no jira] Reinstate placeholder support to native text input

---

packages/bpk-docs/src/components/DocsPageBuilder/DocsPageBuilder.js
packages/bpk-docs/src/components/UsageTable/UsageTable.js
packages/bpk-docs/src/components/UsageTable/index.js
packages/bpk-docs/src/pages/TooltipsPage/TooltipsPage.js

I still need to add in icons, but keen to get eyes on this sooner.

Bpk 1161 tooltips usage table

---

changelog.md
packages/bpk-component-banner-alert/readme.md
packages/bpk-component-banner-alert/src/BpkBannerAlert-test.js
packages/bpk-component-banner-alert/src/BpkBannerAlert.js
packages/bpk-component-banner-alert/src/__snapshots__/BpkBannerAlert-test.js.snap
packages/bpk-docs/src/pages/BannerAlertsPage/BannerAlertsPage.js
packages/bpk-docs/src/pages/BannerAlertsPage/bpk-banner-alerts-page.scss
packages/bpk-react-utils/src/withDefaultProps.js

Think this is good except for changelog entry and maybe a more in-depth explanation in the readme?

[BPK-1156] Fix Web banner alert animation jank

---

native/packages/react-native-bpk-component-horizontal-nav/readme.md
packages/bpk-component-horizontal-nav/readme.md

This is to make it easier for consumers to use the documentation.

[BPK-1110] Add state management examples to horizontal nav readmes

---

changelog.md
native/packages/react-native-bpk-component-banner-alert/readme.md
native/packages/react-native-bpk-component-banner-alert/src/BpkBannerAlert-test.android.js
native/packages/react-native-bpk-component-banner-alert/src/BpkBannerAlert-test.common.js
native/packages/react-native-bpk-component-banner-alert/src/BpkBannerAlert.android.js
native/packages/react-native-bpk-component-banner-alert/src/BpkBannerAlert.ios.js
native/packages/react-native-bpk-component-banner-alert/src/__snapshots__/BpkBannerAlert-test.android.js.snap
native/packages/react-native-bpk-component-banner-alert/src/__snapshots__/BpkBannerAlert-test.ios.js.snap
native/packages/react-native-bpk-component-banner-alert/src/customPropTypes.js
native/packages/react-native-bpk-component-banner-alert/stories.js

This is now splitted in two commits, the fist commit had a bunch of feedback (https://github.com/Skyscanner/backpack/pull/382) the second commit is the latest version

Bpk 1059 android banner alert

---

decisions/TEMPLATE.md
decisions/adding-types.md

**Note:** this cannot be merged until #397 is merged.

[BPK-1151] Add flow types decision

---

.flowconfig

[no jira] Add emojis to flowconfig

---

scripts/npm/check-owners.js

I got a bit carried away but this fixes the issue with `.` files we have during release, and I've added some async/await cause why not? 😄

[NoJira] update check-owners

---

.eslintrc
packages/bpk-component-banner-alert/index.js
packages/bpk-component-banner-alert/src/AnimateAndFade.js
packages/bpk-component-banner-alert/src/BpkBannerAlert.js
packages/bpk-component-banner-alert/src/withBannerAlertState.js
packages/bpk-component-banner-alert/stories.js

I did not do the test because of how complex getting `flow-typed` and `jest` working is. I have concerns around CI etc with that approach so I figured let's discuss it in the new year.

[BPK-1122] Flow type web banner alerts

---

packages/bpk-component-mobile-scroll-container/readme.md
packages/bpk-docs/package.json
packages/bpk-docs/src/constants/routes.js
packages/bpk-docs/src/layouts/DocsLayout/DocsLayout.js
packages/bpk-docs/src/pages/ChipsPage/ChipsPage.js
packages/bpk-docs/src/pages/MobileScrollContainerPage/BlockExample.js
packages/bpk-docs/src/pages/MobileScrollContainerPage/BlockExample.scss
packages/bpk-docs/src/pages/MobileScrollContainerPage/MobileScrollContainerPage.js
packages/bpk-docs/src/pages/MobileScrollContainerPage/index.js
packages/bpk-docs/src/routes/Routes.js

[BPK-1003] Add mobile scroll container docs

---

native/packages/react-native-bpk-component-banner-alert/src/BpkBannerAlert.android.js
native/packages/react-native-bpk-component-banner-alert/src/BpkBannerAlert.ios.js
packages/bpk-component-banner-alert/src/BpkBannerAlert.js

[No JIRA] Remove usage of Object.values

---

package-lock.json
package.json

Originally I bumped us to the latest version (`3.3.3`), but that has [an issue](https://github.com/storybooks/storybook/issues/2602). The issue has been fixed but hasn't yet been released.
So, I've locked us at `3.3.2` for the time being, but as soon as `3.3.4` is out I'll attempt to move us back up to a non-locked version.

[BPK-748] Update Storybook to fix broken storybooks

---

package.json

remember to run 
`nvm install lts/carbon`
to update to the latest

[NoJira] update node version

---

changelog.md
packages/bpk-component-banner-alert/src/AnimateAndFade.js
packages/bpk-component-banner-alert/src/__snapshots__/AnimateAndFade-test.js.snap
packages/bpk-component-banner-alert/src/__snapshots__/BpkBannerAlert-test.js.snap
packages/bpk-docs/src/pages/BannerAlertsPage/BannerAlertsPage.js

https://gojira.skyscanner.net/browse/BPK-1179

[BPK-1179] Fix hidden web banner alert

---

packages/bpk-component-datatable/src/BpkDataTable-test.js
packages/bpk-component-datatable/src/BpkDataTable.js
packages/bpk-component-datatable/src/BpkDataTableColumn-test.js
packages/bpk-component-datatable/src/BpkDataTableColumn.js
packages/bpk-component-datatable/src/__snapshots__/BpkDataTable-test.js.snap
packages/bpk-component-datatable/src/__snapshots__/bpkHeaderRenderer-test.js.snap
packages/bpk-component-datatable/src/bpk-data-table-column.scss
packages/bpk-component-datatable/src/bpk-data-table.scss
packages/bpk-component-datatable/src/bpkHeaderRenderer-test.js
packages/bpk-component-datatable/src/bpkHeaderRenderer.js
packages/bpk-component-datatable/src/utils.js

Addressing [comments from Kartikey](https://gojira.skyscanner.net/browse/BPK-434?focusedCommentId=1174220&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1174220)
- always show sort icons
- change sort icon colour

[BPK-434] always show sort icons

---

native/packages/react-native-bpk-theming/src/types.js

I haven't added typing to the rest of this package yet, as this PR is to facilitate adding flow types to native buttons, so I want to get that done first.

[no jira] Added a Theme type for other modules to use

---

.flowconfig
native/packages/react-native-bpk-component-button/index.js
native/packages/react-native-bpk-component-button/src/BpkButton-styles.js
native/packages/react-native-bpk-component-button/src/BpkButton-test.common.js
native/packages/react-native-bpk-component-button/src/BpkButton.js
native/packages/react-native-bpk-component-button/src/common-types.js
native/packages/react-native-bpk-component-button/src/layout/BpkButtonContainer.android.js
native/packages/react-native-bpk-component-button/src/layout/BpkButtonContainer.ios.js
native/packages/react-native-bpk-component-button/src/utils.js
native/packages/react-native-bpk-component-button/stories.js
native/packages/react-native-bpk-component-icon/src/BpkIcon.js

[no jira] Flow type native buttons

---

packages/bpk-docs/src/components/Header/Header.scss

[BPK-1181] Fix docs logo when RTL

---

changelog.md
packages/bpk-component-button/docs/migrating-from-v1-to-v2.md
packages/bpk-component-button/readme.md
packages/bpk-component-button/src/BpkButton-test.js
packages/bpk-component-button/src/BpkButton.js
packages/bpk-component-button/src/__snapshots__/BpkButton-test.js.snap
packages/bpk-component-button/src/bpk-button.scss
packages/bpk-component-button/stories.js
packages/bpk-component-loading-button/readme.md
packages/bpk-component-loading-button/src/BpkLoadingButton-test.js
packages/bpk-component-loading-button/src/BpkLoadingButton.js
packages/bpk-component-loading-button/src/__snapshots__/BpkLoadingButton-test.js.snap
packages/bpk-component-loading-button/stories.js
packages/bpk-docs/src/pages/ButtonsPage/ButtonsPage.js
packages/bpk-mixins/src/mixins/_buttons.scss

[BPK-1130] Remove selected prop from buttons

---

.travis.yml

Fixes https://github.com/Skyscanner/backpack/issues/455

[BPK-1206] Whitelist greenkeeper branch

---

subshell

Subshell now preserves color and other terminal escape codes.

[No JIRA] Make subshell better

---

subshell

Just as I closed #464 I realised we no longer propagate the exit status 🤦‍♂️

[No JIRA] Propagate subshell exit status

---

changelog.md
packages/bpk-component-fieldset/readme.md
packages/bpk-component-fieldset/src/BpkFieldset-test.js
packages/bpk-component-fieldset/src/BpkFieldset.js
packages/bpk-component-fieldset/src/__snapshots__/BpkFieldset-test.js.snap
packages/bpk-component-fieldset/src/bpk-fieldset.scss
packages/bpk-component-fieldset/stories.js
packages/bpk-docs/src/pages/FieldsetsPage/FieldsetsPage.js

Haven't done docs yet and there's an outstanding question around checkboxes. Because checkbox are inline elements the text ends up on the same line which looks terrible

[BPK-1250] Add description to BpkFieldSet

---

changelog.md
packages/bpk-component-dialog/package.json
packages/bpk-component-dialog/readme.md
packages/bpk-component-dialog/src/BpkDialog.js
packages/bpk-component-dialog/src/BpkDialog.scss
packages/bpk-component-dialog/src/__snapshots__/BpkDialog-test.js.snap
packages/bpk-component-dialog/stories.js
packages/bpk-component-input/package-lock.json
packages/bpk-component-modal/readme.md
packages/bpk-component-modal/src/BpkModal.js
packages/bpk-component-modal/src/BpkModalDialog.js
packages/bpk-component-modal/src/customPropTypes-test.js
packages/bpk-component-modal/src/customPropTypes.js
packages/bpk-docs/src/components/Paragraph/Paragraph.js
packages/bpk-docs/src/components/Paragraph/Paragraph.scss
packages/bpk-docs/src/components/Paragraph/index.js
packages/bpk-docs/src/pages/DialogsPage/DialogsPage.js
packages/bpk-scrim-utils/readme.md
packages/bpk-scrim-utils/src/customPropTypes-test.js
packages/bpk-scrim-utils/src/customPropTypes.js
packages/bpk-scrim-utils/src/withScrim.js

[BPK-1268] Remove title and header from dialogs

---

packages/bpk-docs/src/pages/DialogsPage/DialogExamples.js
packages/bpk-docs/src/pages/DialogsPage/DialogExamples.scss
packages/bpk-docs/src/pages/DialogsPage/DialogsPage.js

As requested by @shaundon in https://github.com/Skyscanner/backpack/pull/475#pullrequestreview-92177323, i've improved the dismissible example in the docs.

[BPK-1268] Improve dialog docs example

---

packages/bpk-docs/src/index.js

See https://github.com/Skyscanner/backpack/issues/390

Fix anchor double click issue

---

packages/bpk-component-grid-toggle/src/BpkGridToggle.js
packages/bpk-component-grid-toggle/src/__snapshots__/BpkGridToggle-test.js.snap
packages/bpk-component-rtl-toggle/src/BpkRtlToggle.js
packages/bpk-component-rtl-toggle/src/__snapshots__/BpkRtlToggle-test.js.snap

This is to facilitate the new docs design.

[BPK-1286] Change copy for RTL and grid toggles

---

changelog.md
packages/bpk-component-banner-alert/src/__snapshots__/BpkBannerAlertInner-test.js.snap
packages/bpk-component-chip/src/BpkChip.js
packages/bpk-component-close-button/src/BpkCloseButton.js
packages/bpk-component-close-button/src/__snapshots__/BpkCloseButton-test.js.snap
packages/bpk-component-dialog/src/__snapshots__/BpkDialog-test.js.snap
packages/bpk-component-drawer/src/__snapshots__/BpkDrawer-test.js.snap
packages/bpk-component-drawer/src/__snapshots__/BpkDrawerContent-test.js.snap
packages/bpk-component-modal/src/__snapshots__/BpkModal-test.js.snap
packages/bpk-component-modal/src/__snapshots__/BpkModalDialog-test.js.snap
packages/bpk-component-popover/src/__snapshots__/BpkPopover-test.js.snap
packages/bpk-docs/src/pages/ChipsPage/ChipsPage.js
packages/bpk-docs/src/pages/ChipsPage/ChipsPage.scss
packages/bpk-mixins/src/mixins/_chips.scss

[BPK-1317] Fix close button alignment issue in chips

---

changelog.md
packages/bpk-component-popover/index.js
packages/bpk-component-popover/readme.md
packages/bpk-component-popover/src/BpkPopoverPortal.js
packages/bpk-component-popover/stories.js
packages/bpk-component-tooltip/index.js
packages/bpk-component-tooltip/readme.md
packages/bpk-component-tooltip/src/BpkTooltip-test.js
packages/bpk-component-tooltip/src/BpkTooltip.js
packages/bpk-component-tooltip/src/BpkTooltipPortal-test.js
packages/bpk-component-tooltip/src/BpkTooltipPortal.js
packages/bpk-component-tooltip/src/constants.js
packages/bpk-component-tooltip/stories.js
packages/bpk-tokens/tokens/base.ios.json
packages/bpk-tokens/tokens/base.raw.android.json
packages/bpk-tokens/tokens/base.raw.ios.json

Also did some flow typing in the same PR because I was feeling rebellious.

[BPK-1300] Add popperModifiers prop to popovers and tooltips

---

package-lock.json
package.json

https://github.com/Skyscanner/backpack/pull/521

Greenkeeper/stylelint 9.1.1

---

native/storybook/constants.js
native/storybook/rtl-addon/register.js
native/storybook/storybook.js

@shaundon came up with this amazin idea, here's a quick demo

Add RTL toggle in the storybook UI

---

native/packages/react-native-bpk-component-banner-alert/src/AlertTypes.js
native/packages/react-native-bpk-component-banner-alert/src/BpkBannerAlert-test.common.js
native/packages/react-native-bpk-component-banner-alert/src/BpkBannerAlert.android.js
native/packages/react-native-bpk-component-banner-alert/src/BpkBannerAlert.ios.js

Not entirely sure if this even merrits a changelog entry?

[BPK-1174] Refactor Alert_types into separate file to avoid duplication

---

native/packages/react-native-bpk-component-button/src/BpkButton-test.android.js
native/packages/react-native-bpk-component-button/src/BpkButton.android.js
native/packages/react-native-bpk-component-button/src/__snapshots__/BpkButton-test.android.js.snap

Only done for BpkButton as a bugfix, probably can check other instances

IMP-3922 Fix crash on pre-Lollipop

---

packages/bpk-docs/src/pages/GettingStartedPage/GettingStartedPage.js

[NoJira] fix broken url

---

changelog.md
packages/bpk-component-badge/BadgeLayout.js
packages/bpk-component-badge/badge-layout.scss
packages/bpk-component-badge/index.js
packages/bpk-component-badge/readme.md
packages/bpk-component-badge/src/BpkBadge-test.js
packages/bpk-component-badge/src/BpkBadge.js
packages/bpk-component-badge/src/__snapshots__/BpkBadge-test.js.snap
packages/bpk-component-badge/stories.js
packages/bpk-docs/src/pages/BadgePage/BadgePage.js
packages/bpk-mixins/src/mixins/_badges.scss

[BPK-1368] web badge styles

---

packages/bpk-docs/src/layouts/DocsLayout/DocsLayout.js

[no jira] Enable link buttons page on docs site

---

packages/bpk-component-badge/BadgeLayout.js
packages/bpk-component-badge/index.js
packages/bpk-component-badge/src/BpkBadge.js
packages/bpk-component-badge/stories.js

I forgot to flow the badge component before I worked on it, so here it is

[NO-JIRA] Flow type Badge component

---

packages/bpk-docs/package.json
packages/bpk-docs/src/constants/routes.js
packages/bpk-docs/src/layouts/DocsLayout/DocsLayout.js
packages/bpk-docs/src/pages/NativePanelsPage/NativePanelsPage.js
packages/bpk-docs/src/pages/NativePanelsPage/index.js
packages/bpk-docs/src/routes/Routes.js

Copy as per web component -> https://backpack.github.io/components/web/panels
Examples are similar to native card component -> 
https://backpack.github.io/components/native/cards

[BPK1334] native panels docs page

---

readme.md

Add some missing packages from the readme

[NoJira] some love for the readme

---

changelog.md
native/packages/react-native-bpk-component-navigation-bar/src/BpkNavigationBar-test.android.js
native/packages/react-native-bpk-component-navigation-bar/src/BpkNavigationBar-test.ios.js
native/packages/react-native-bpk-component-navigation-bar/src/BpkNavigationBar.android.js
native/packages/react-native-bpk-component-navigation-bar/src/BpkNavigationBar.ios.js
native/packages/react-native-bpk-component-navigation-bar/src/__snapshots__/BpkNavigationBar-test.android.js.snap
native/packages/react-native-bpk-component-navigation-bar/src/__snapshots__/BpkNavigationBar-test.ios.js.snap

I stupidly forgot to do this previously 😐.

Add style support for navigation bar.

---

packages/bpk-docs/src/components/DocsPageBuilder/DocsPageBuilder.js
packages/bpk-docs/src/pages/DialogsPage/DialogsPage.js
packages/bpk-docs/src/pages/ModalsPage/ModalsPage.js
packages/bpk-docs/src/pages/PopoversPage/PopoversPage.js

Also, _do's and don'ts_ has been moved nearer to the top of the page.

[BPK-1387] Update do's and don'ts for some components

---

native/packages/react-native-bpk-component-picker/src/BpkPickerMenu.android.js
native/packages/react-native-bpk-component-picker/src/__snapshots__/BpkPicker-test.android.js.snap

Very small PR - I should probably have mixed it in with the Flow one. I added a wrapper components, so that the layout can be more Flexy and less hacky.

[BPK-1432] Refactor BpkPicker

---

changelog.md
native/packages/react-native-bpk-component-navigation-bar/src/BpkNavigationBar.android.js
native/packages/react-native-bpk-component-navigation-bar/src/BpkNavigationBar.ios.js
native/packages/react-native-bpk-component-navigation-bar/src/__snapshots__/BpkNavigationBar-test.android.js.snap
native/packages/react-native-bpk-component-navigation-bar/src/__snapshots__/BpkNavigationBar-test.ios.js.snap

Because we were replacing the style network images didn't work as they
always require their own style.

[No JIRA] Don't botch image styles in nav bar

---

contributing.md
package.json

quick change to the `package.json`
you might have to run `nvm use` once this gets merged
the preinstall check has problems with windows npx should help that

update preinstall, node

---

native/packages/react-native-bpk-component-animate-height/src/BpkAnimateHeight.js
native/packages/react-native-bpk-component-animate-height/src/__snapshots__/BpkAnimateHeight-test.android.js.snap
native/packages/react-native-bpk-component-animate-height/src/__snapshots__/BpkAnimateHeight-test.ios.js.snap
native/packages/react-native-bpk-component-banner-alert/src/__snapshots__/AnimateAndFade-test.android.js.snap
native/packages/react-native-bpk-component-banner-alert/src/__snapshots__/AnimateAndFade-test.ios.js.snap
native/packages/react-native-bpk-component-banner-alert/src/__snapshots__/BpkBannerAlert-test.android.js.snap
native/packages/react-native-bpk-component-banner-alert/src/__snapshots__/BpkBannerAlert-test.ios.js.snap

Banner alerts were broken after merging https://github.com/Skyscanner/backpack/pull/619 so this PR reverts it.

Revert #619

---

packages/bpk-docs/src/components/HomePageCard/HomePageCard.js
packages/bpk-docs/src/pages/NeoHomePage/HomePage.js

Use React Router facitilies to navigate internally from the
homepage.

[BPK-1372] Don't use full nav via home page cards

---

index.html
packages/bpk-docs/src/layouts/DefaultLayout/DefaultLayout.js
packages/bpk-docs/src/layouts/DefaultLayout/default-layout.scss
packages/bpk-docs/src/layouts/SideNavLayout/SideNavLayout.js
packages/bpk-docs/src/layouts/SideNavLayout/side-nav-layout.scss
packages/bpk-docs/src/pages/DatepickerPage/DatepickerPage.js
packages/bpk-docs/src/pages/DialogsPage/DialogExamples.js
packages/bpk-docs/src/pages/DrawerPage/DrawerPage.js
packages/bpk-docs/src/pages/HomePage/HomePage.js
packages/bpk-docs/src/pages/HomePage/home-page.scss
packages/bpk-docs/src/pages/ModalsPage/ModalsPage.js
packages/bpk-docs/src/pages/NeoHomePage/HomePage.js
packages/bpk-docs/src/pages/NeoHomePage/home-page.scss
packages/bpk-docs/src/pages/PopoversPage/PopoversPage.js

Browser compat screenshots:
**Chrome:**
**Chrome on Android:**
**Edge 16:**
**Firefox:**
**IE11:**
**Mobile Safari:**
**Safari:**

[NOJIRA] Get rid of sticky footer

---

packages/bpk-component-modal/readme.md

[#605] Fix modal docs

---

packages/bpk-component-image/src/withLazyLoading.js

I've missed one comment from the previus review osrry about that 😅 
https://github.com/Skyscanner/backpack/pull/656#discussion_r181656117

[BPK-1457] fix missed comment from previous PR

---

packages/bpk-docs/package-lock.json
packages/bpk-docs/package.json
packages/bpk-docs/src/pages/NeoHomePage/UpdatedAt.js

tested on the regular docs, SSR, and SSR with disabled JS

[BPK-1494] "updated at" format fix

---

.storybook/config.js
packages/bpk-component-navigation-bar/index.js
packages/bpk-component-navigation-bar/package-lock.json
packages/bpk-component-navigation-bar/package.json
packages/bpk-component-navigation-bar/readme.md
packages/bpk-component-navigation-bar/src/BpkNavigationBar-test.js
packages/bpk-component-navigation-bar/src/BpkNavigationBar.js
packages/bpk-component-navigation-bar/src/BpkNavigationBar.scss
packages/bpk-component-navigation-bar/src/BpkNavigationBarIconButton-test.js
packages/bpk-component-navigation-bar/src/BpkNavigationBarIconButton.js
packages/bpk-component-navigation-bar/src/__snapshots__/BpkNavigationBar-test.js.snap
packages/bpk-component-navigation-bar/src/__snapshots__/BpkNavigationBarIconButton-test.js.snap
packages/bpk-component-navigation-bar/stories.js
packages/bpk-component-navigation-bar/stories.scss
packages/bpk-react-utils/src/cssModules-test.js
unreleased.md

[BPK-1532] Add navigation bar component

---

packages/bpk-docs/package.json
packages/bpk-docs/src/constants/routes.js
packages/bpk-docs/src/layouts/links.js
packages/bpk-docs/src/pages/NativeNavigationBarPage/NativeNavigationBarPage.js
packages/bpk-docs/src/pages/NavigationBarPage/NavigationBarPage.js
packages/bpk-docs/src/pages/NavigationBarPage/NavigationBarPage.scss
packages/bpk-docs/src/pages/NavigationBarPage/index.js
packages/bpk-docs/src/pages/NeoNavigationBarPage/NavigationBarPage.js
packages/bpk-docs/src/pages/NeoNavigationBarPage/index.js
packages/bpk-docs/src/routes/Routes.js

[BPK-1532] Add navigation bar docs

---

packages/bpk-docs/src/layouts/links.js
packages/bpk-docs/src/pages/AccordionsPage/AccordionsPage.js
packages/bpk-docs/src/pages/AlignmentPage/AlignmentPage.js
packages/bpk-docs/src/pages/AutosuggestPage/AutosuggestPage.js
packages/bpk-docs/src/pages/BadgePage/BadgePage.js
packages/bpk-docs/src/pages/BannerAlertsPage/BannerAlertsPage.js
packages/bpk-docs/src/pages/BarchartsPage/BarchartsPage.js
packages/bpk-docs/src/pages/BlockquotesPage/BlockquotesPage.js
packages/bpk-docs/src/pages/BreakpointsPage/BreakpointsPage.js
packages/bpk-docs/src/pages/ButtonsPage/ButtonsPage.js
packages/bpk-docs/src/pages/CalendarPage/CalendarPage.js
packages/bpk-docs/src/pages/CardsPage/CardsPage.js
packages/bpk-docs/src/pages/CodePage/CodePage.js
packages/bpk-docs/src/pages/DatepickerPage/DatepickerPage.js
packages/bpk-docs/src/pages/DescriptionListsPage/DescriptionListsPage.js
packages/bpk-docs/src/pages/FormsPage/FormsPage.js
packages/bpk-docs/src/pages/NativeBadgePage/NativeBadgePage.js
packages/bpk-docs/src/pages/NativeBannerAlertPage/NativeBannerAlertPage.js
packages/bpk-docs/src/pages/NativeButtonPage/NativeButtonPage.js
packages/bpk-docs/src/pages/NativeCardsPage/NativeCardsPage.js
packages/bpk-docs/src/pages/NeoBadgePage/BadgePage.js
packages/bpk-docs/src/pages/NeoBannerAlertPage/BannerAlertPage.js
packages/bpk-docs/src/pages/NeoButtonPage/ButtonPage.js
packages/bpk-docs/src/pages/NeoCardPage/CardPage.js

The following component pages are affected: Accordion, Alignment, Autosuggest, Badge, Banner alert, Bar chart, Blockquote, Breakpoint, Button, Calendar, Card, Chip, Code, Datepicker, and Description List

[BPK-1557]: Amend the docs for the first batch of components

---

.storybook/themeableAttributes.js
packages/bpk-component-navigation-bar/package.json
packages/bpk-component-navigation-bar/readme.md
packages/bpk-component-navigation-bar/src/BpkNavigationBar.scss
packages/bpk-component-navigation-bar/src/BpkNavigationBarButtonLink-test.js
packages/bpk-component-navigation-bar/src/BpkNavigationBarButtonLink.js
packages/bpk-component-navigation-bar/src/BpkNavigationBarButtonLink.scss
packages/bpk-component-navigation-bar/src/BpkNavigationBarIconButton.scss
packages/bpk-component-navigation-bar/src/__snapshots__/BpkNavigationBar-test.js.snap
packages/bpk-component-navigation-bar/src/__snapshots__/BpkNavigationBarButtonLink-test.js.snap
packages/bpk-component-navigation-bar/src/__snapshots__/BpkNavigationBarIconButton-test.js.snap
packages/bpk-component-navigation-bar/src/themeAttributes.js
packages/bpk-component-navigation-bar/stories.js
packages/bpk-component-theme-toggle/src/theming.js
unreleased.md

[BPK-1552] Make navigation bar themable

---

packages/bpk-docs/src/pages/DialogsPage/DialogsPage.js
packages/bpk-docs/src/pages/DrawerPage/DrawerPage.js
packages/bpk-docs/src/pages/FieldsetsPage/FieldsetsPage.js
packages/bpk-docs/src/pages/FormsPage/FormsPage.js
packages/bpk-docs/src/pages/HorizontalGridPage/HorizontalGridPage.js
packages/bpk-docs/src/pages/HorizontalNavPage/HorizontalNavPage.js
packages/bpk-docs/src/pages/NativeFlatListPage/NativeFlatListPage.js
packages/bpk-docs/src/pages/NativeHorizontalNavPage/NativeHorizontalNavPage.js
packages/bpk-docs/src/pages/NeoHorizontalNavPage/HorizontalNavPage.js

The following component pages are affected:  Dialog, Drawer, Fieldset, Flat list, Form elements, Horizontal grid, Horizontal navigation

[BPK-1562]: Amend the docs for the second batch of components

---

packages/bpk-component-navigation-bar/index.js
packages/bpk-component-navigation-bar/stories.js
packages/bpk-docs/src/pages/NavigationBarPage/NavigationBarPage.js
packages/bpk-docs/src/themeableAttributes.js
unreleased.md

I forgot to export the BpkNavigationBarButtonLink in the previous PR 🤦‍♂️ 
I'm also updating the docs page to apply the correct theme.

[BPK-1552] Fix BpkNavigationBarButtonLink export and update docs

---

packages/bpk-component-theme-toggle/src/theming.js
packages/bpk-docs/src/layouts/NeoSideNavLayout/NavList.scss
packages/bpk-docs/src/layouts/NeoSideNavLayout/Sidebar.scss
packages/bpk-docs/src/layouts/NeoSideNavLayout/_common.scss
packages/bpk-docs/src/themeableAttributes.js

This is what the London theme looks like with those changes

[BPK-1554] New theme for neo docs

---

packages/bpk-docs/src/pages/IconsPage/IconsPage.js
packages/bpk-docs/src/pages/ImagesPage/ImagesPage.js
packages/bpk-docs/src/pages/LinksPage/LinksPage.js
packages/bpk-docs/src/pages/ListsPage/ListsPage.js
packages/bpk-docs/src/pages/MobileScrollContainerPage/MobileScrollContainerPage.js
packages/bpk-docs/src/pages/ModalsPage/ModalsPage.js
packages/bpk-docs/src/pages/NativeButtonLinkPage/NativeButtonLinkPage.js
packages/bpk-docs/src/pages/NativeIconsPage/NativeIconsPage.js
packages/bpk-docs/src/pages/NativeNavigationBarPage/NativeNavigationBarPage.js
packages/bpk-docs/src/pages/NativeNudgerPage/NativeNudgerPage.js
packages/bpk-docs/src/pages/NativePanelsPage/NativePanelsPage.js
packages/bpk-docs/src/pages/NativePhoneInputPage/NativePhoneInputPage.js
packages/bpk-docs/src/pages/NativePickerPage/NativePickerPage.js
packages/bpk-docs/src/pages/NativeProgressPage/NativeProgressPage.js
packages/bpk-docs/src/pages/NavigationBarPage/NavigationBarPage.js
packages/bpk-docs/src/pages/NeoIconPage/IconPage.js
packages/bpk-docs/src/pages/NeoLinkPage/LinkPage.js
packages/bpk-docs/src/pages/NeoNavigationBarPage/NavigationBarPage.js
packages/bpk-docs/src/pages/NeoNudgerPage/NudgerPage.js
packages/bpk-docs/src/pages/NeoPanelPage/PanelPage.js
packages/bpk-docs/src/pages/NudgersPage/NudgersPage.js
packages/bpk-docs/src/pages/PaginationPage/PaginationPage.js
packages/bpk-docs/src/pages/PanelsPage/PanelsPage.js
packages/bpk-docs/src/pages/PopoversPage/PopoversPage.js
packages/bpk-docs/src/pages/ProgressPage/ProgressPage.js

The following component pages are affected: Icon, Image, Link, List, Mobile scroll container, Modal, Navigation bar, Nudger, Pagination, Panel, Phone number input, Picker, Popover and Progress bar

[BPK-1565]: Amend the docs for the third batch of components

---

packages/bpk-docs/src/pages/NativeSectionListPage/NativeSectionListPage.js
packages/bpk-docs/src/pages/NativeSpinnerPage/NativeSpinnerPage.js
packages/bpk-docs/src/pages/NativeStarRatingPage/NativeStarRatingPage.js
packages/bpk-docs/src/pages/NativeSwitchPage/NativeSwitchPage.js
packages/bpk-docs/src/pages/NativeTextInputPage/NativeTextInputPage.js
packages/bpk-docs/src/pages/NativeTextPage/NativeTextPage.js
packages/bpk-docs/src/pages/NativeTouchableOverlayPage/NativeTouchableOverlayPage.js
packages/bpk-docs/src/pages/NeoSpinnerPage/SpinnerPage.js
packages/bpk-docs/src/pages/NeoStarRatingPage/StarRatingPage.js
packages/bpk-docs/src/pages/NeoTextPage/TextPage.js
packages/bpk-docs/src/pages/SlidersPage/SlidersPage.js
packages/bpk-docs/src/pages/SpinnersPage/SpinnersPage.js
packages/bpk-docs/src/pages/StarRatingPage/StarRatingPage.js
packages/bpk-docs/src/pages/TablesPage/TablesPage.js
packages/bpk-docs/src/pages/TextPage/TextPage.js
packages/bpk-docs/src/pages/ThemingPage/ThemingPage.js
packages/bpk-docs/src/pages/TooltipsPage/TooltipsPage.js

The following component pages are affected: ISection list, Slider, Spinner, Star rating, Switch, Table, Text, Text input, Theming, Tooltip and Touchable overlay.

[BPK-1565]: Amend the docs for the fourth batch of components

---

packages/bpk-docs/package.json
packages/bpk-docs/src/constants/redirect-routes.js
packages/bpk-docs/src/constants/routes.js
packages/bpk-docs/src/layouts/links.js
packages/bpk-docs/src/pages/NativeSectionListPage/NativeSectionListPage.js
packages/bpk-docs/src/pages/NeoSectionListPage/SectionListPage.js
packages/bpk-docs/src/pages/NeoSectionListPage/index.js
packages/bpk-docs/src/pages/SectionListPage/SectionListPage.js
packages/bpk-docs/src/pages/SectionListPage/index.js
packages/bpk-docs/src/routes/Routes.js

The attached screenshot is from the neo site, but I did test it on both.

[BPK-1546] Web section list docs

---

packages/bpk-docs/package.json
packages/bpk-docs/src/constants/routes.js
packages/bpk-docs/src/layouts/links.js
packages/bpk-docs/src/pages/NavigationStackPage/NavigationStackPage.js
packages/bpk-docs/src/pages/NavigationStackPage/NavigationStackPage.scss
packages/bpk-docs/src/pages/NavigationStackPage/index.js
packages/bpk-docs/src/pages/NavigationStackPage/page-components.js
packages/bpk-docs/src/routes/Routes.js

[BPK-1533] Add navigation stack docs page

---

packages/bpk-docs/src/layouts/NeoSideNavLayout/NavList.scss
packages/bpk-docs/src/layouts/NeoSideNavLayout/Sidebar.scss
packages/bpk-docs/src/layouts/NeoSideNavLayout/_common.scss

[No JIRA] Add theming fallbacks for IE

---

.travis.yml

This makes neo the new artifact for deployment🎉🎉🎉
a quick reminder, this can be tested locally by runnig
```
npm run docs:neo:dist && http-server ./dist
```
if you don't have `http-server installed, just run 
```
npm i -g http-server
```

[BPK-1593] Release the beast

---

packages/bpk-docs/src/pages/NavigationBarPage/NavigationBarPage.js

@jamesf3rguson asked for a more generic title for the new example.

[NO-JIRA] Update navigation bar docs

---

native/packages/react-native-bpk-component-carousel/index.js
native/packages/react-native-bpk-component-carousel/package-lock.json
native/packages/react-native-bpk-component-carousel/package.json
native/packages/react-native-bpk-component-carousel/readme.md
native/packages/react-native-bpk-component-carousel/src/BpkCarousel-test.android.js
native/packages/react-native-bpk-component-carousel/src/BpkCarousel-test.common.js
native/packages/react-native-bpk-component-carousel/src/BpkCarousel-test.ios.js
native/packages/react-native-bpk-component-carousel/src/BpkCarousel.js
native/packages/react-native-bpk-component-carousel/src/BpkCarouselItem-test.android.js
native/packages/react-native-bpk-component-carousel/src/BpkCarouselItem-test.common.js
native/packages/react-native-bpk-component-carousel/src/BpkCarouselItem-test.ios.js
native/packages/react-native-bpk-component-carousel/src/BpkCarouselItem.js
native/packages/react-native-bpk-component-carousel/src/__snapshots__/BpkCarousel-test.android.js.snap
native/packages/react-native-bpk-component-carousel/src/__snapshots__/BpkCarousel-test.ios.js.snap
native/packages/react-native-bpk-component-carousel/src/__snapshots__/BpkCarouselItem-test.android.js.snap
native/packages/react-native-bpk-component-carousel/src/__snapshots__/BpkCarouselItem-test.ios.js.snap
native/packages/react-native-bpk-component-carousel/stories.js
native/storybook/storybook.js
unreleased.md

[BPK-1530] Introduce native carousel component

---

scripts/npm/check-owners.js

Only the best search and replace tools for Backpack!

[NoJira] update endpoint and package to use https

---

packages/bpk-docs/src/components/DocsPageBuilder/NeoDocsPageBuilder.js
packages/bpk-docs/src/components/neo/PresentationBlock/PresentationBlock.js
packages/bpk-docs/src/components/neo/PresentationBlock/PresentationBlock.scss

Question for design: Should the background be themed? Or always be the same dark color?

[No-Jira] POC dark docs examples

---

native/packages/react-native-bpk-component-alert/readme.md

Remove action function from the readme file

[No JIRA] Update readme to remove action function

---

packages/bpk-docs/src/pages/ButtonsPage/ButtonsPage.js
packages/bpk-docs/src/pages/ButtonsPage/buttons-page.scss

[BPK-1596] Fix buttons page on narrow devices

---

.storybook/config.js
packages/bpk-component-phone-input/index.js
packages/bpk-component-phone-input/package.json
packages/bpk-component-phone-input/readme.md
packages/bpk-component-phone-input/src/BpkNavigationBar-test.js
packages/bpk-component-phone-input/src/BpkPhoneInput.js
packages/bpk-component-phone-input/src/BpkPhoneInput.scss
packages/bpk-component-phone-input/src/__snapshots__/BpkNavigationBar-test.js.snap
packages/bpk-component-phone-input/stories.js
unreleased.md

Docs and integration with the @matteo-hertel's work in a different PR

[BPK-1611] Add web phone input

---

contributing.md
packages/bpk-docs/src/pages/MapPage/MapPage.js

I've added the key to Travis too.

[BPK-1627] Read Google Maps API key from environment variable

---

packages/bpk-component-select/src/bpk-select.scss

While implementing the select component @tiagoengel found a problem with RTL, this fixes it

[NoJira] update select RTL

---

native/packages/react-native-bpk-component-alert/index.js
native/packages/react-native-bpk-component-alert/package.json
native/packages/react-native-bpk-component-alert/stories.js

[NOJIRA] Prevent alert from automatically triggering on storybook startup

---

packages/bpk-docs/package.json
packages/bpk-docs/src/layouts/links.js
packages/bpk-docs/src/pages/NativePhoneInputPage/NativePhoneInputPage.js
packages/bpk-docs/src/pages/PhoneInputPage/PhoneInputPage.js
packages/bpk-docs/src/pages/PhoneInputPage/index.js
packages/bpk-docs/src/routes/Routes.js

[BPK 1611] Web phone input docs

---

packages/bpk-component-phone-input/readme.md
packages/bpk-component-phone-input/src/BpkPhoneInput.scss
packages/bpk-component-phone-input/src/__snapshots__/BpkPhoneInput-test.js.snap
packages/bpk-component-phone-input/stories.js
packages/bpk-component-select/readme.md
packages/bpk-component-select/src/BpkSelect-test.js
packages/bpk-component-select/src/BpkSelect.js
packages/bpk-component-select/src/__snapshots__/BpkSelect-test.js.snap
packages/bpk-component-select/src/bpk-select.scss
packages/bpk-component-select/stories.js
packages/bpk-docs/src/pages/PhoneInputPage/PhoneInputPage.js

[BPK-1611] Focus displays correctly on selects with image

---

native/android/build.gradle

On a clean machine, following the instructions in contributing.md leads to a number of build errors in the Android project. Making the changes in this PR makes the instructions work flawlessly. I think that we should merge these changes in so as to align the gradle project with the contributing.md file.

[NO-JIRA] Android - Fix unresolved dependency on common.jar

---

.storybook/config.js
packages/bpk-component-breadcrumb/index.js
packages/bpk-component-breadcrumb/package.json
packages/bpk-component-breadcrumb/readme.md
packages/bpk-component-breadcrumb/src/BpkBreadcrumb-test.js
packages/bpk-component-breadcrumb/src/BpkBreadcrumb.js
packages/bpk-component-breadcrumb/src/BpkBreadcrumb.scss
packages/bpk-component-breadcrumb/src/BpkBreadcrumbItem-test.js
packages/bpk-component-breadcrumb/src/BpkBreadcrumbItem.js
packages/bpk-component-breadcrumb/src/BpkBreadcrumbItem.scss
packages/bpk-component-breadcrumb/src/__snapshots__/BpkBreadcrumb-test.js.snap
packages/bpk-component-breadcrumb/src/__snapshots__/BpkBreadcrumbItem-test.js.snap
packages/bpk-component-breadcrumb/stories.js

[BPK-1527] Breadcrumbs

---

packages/bpk-docs/src/components/DocsPageBuilder/DocsPageBuilder.js
packages/bpk-docs/src/components/DocsPageBuilder/DocsPageBuilder.scss
packages/bpk-docs/src/components/DocsPageBuilder/TokenSwitcher.js
packages/bpk-docs/src/components/DocsPageBuilder/TokenTable.js
packages/bpk-docs/src/components/PageHead/PageHead.js

[BPK-1591] Move tokens platform switcher to the first section

---

contributing.md
packages/bpk-component-datepicker/readme.md
packages/bpk-component-pagination/readme.md
packages/bpk-component-select/readme.md
packages/bpk-docs/src/pages/AlignmentPage/AlignmentPage.js

- datepicker
- pagination
- select
- alignment

small tweaks in documentation

---

packages/bpk-component-navigation-bar/src/BpkNavigationBar.js
packages/bpk-docs/src/pages/BreadcrumbPage/BreadcrumbPage.js

I also found another error on the docs site when testing this fix, I've bundled that in too.

[BPK-1635] Accept string for BpkNavigationBar title

---

native/android/app/build.gradle
native/android/app/src/main/java/com/native/MainApplication.java
native/android/settings.gradle
native/ios/Podfile
native/ios/Podfile.lock
native/ios/native.xcodeproj/xcshareddata/xcschemes/native.xcscheme
native/ios/native/Info.plist
native/package-lock.json
native/package.json
native/packages/react-native-bpk-component-button/package.json
native/packages/react-native-bpk-component-nudger/src/__snapshots__/BpkNudger-test.ios.js.snap
native/packages/react-native-bpk-styles/index.js
native/packages/react-native-bpk-styles/package-lock.json
native/packages/react-native-bpk-styles/package.json
native/packages/react-native-bpk-styles/readme.md
native/packages/react-native-bpk-styles/src/gradients-test.js
native/packages/react-native-bpk-styles/src/gradients.js
native/packages/react-native-bpk-styles/stories.js
native/storybook/storybook.js
unreleased.md

Include definition for the Skyscanner primary gradient in
`react-native-bpk-styles`.

[BPK-1683] Add gradient to react-native-bpk-styles

---

native/packages/react-native-bpk-component-carousel/stories.js

You can imagine how tedious it was to add all these URLs..

[No JIRA] Change BpkCarousel stories to use more images

---

packages/bpk-scrim-utils/readme.md
packages/bpk-scrim-utils/src/BpkScrim-test.js
packages/bpk-scrim-utils/src/BpkScrim.js
packages/bpk-scrim-utils/src/__snapshots__/BpkScrim-test.js.snap
packages/bpk-scrim-utils/src/bpk-scrim.scss
packages/bpk-scrim-utils/src/withScrim.js
packages/bpk-tokens/src/web/base/scrims.json
packages/bpk-tokens/tokens/base.common.js
packages/bpk-tokens/tokens/base.default.scss
packages/bpk-tokens/tokens/base.es6.js
packages/bpk-tokens/tokens/base.raw.json
packages/bpk-tokens/tokens/base.scss
unreleased.md

[BPK-1679] Add dark version of scrim

---

packages/bpk-svgs/tasks/getIconFontMetadataProvider.js

To test this you can:
1. add a test icon (duplicate existing file)
2. run `npm run build`
3. run git add (do NOT commit)
4. run `npm run build` again
5. check there are no new changes to be committed.

[BPK-1623] Fix icon mapping generation

---

native/package-lock.json

It keeps causing CI to fail as it's changed.

[No JIRA] Update native lockfile

---

contributing.md

The website and repo for Storybook have moved
(https://github.com/storybooks/storybook)
Let me know if you'd prefer to leave out the trailing whitespace changes.

Update URL for Storybook

---

packages/bpk-component-calendar/src/BpkCalendarGridTransition-test.js
packages/bpk-component-calendar/src/BpkCalendarGridTransition.js
packages/bpk-component-calendar/src/__snapshots__/BpkCalendarContainer-test.js.snap
packages/bpk-component-calendar/src/__snapshots__/BpkCalendarGridTransition-test.js.snap
packages/bpk-component-calendar/src/utils.js
unreleased.md

Tested on Safari, FF, Chrome and IE11.

[BPK-1685] Fix calendar transition for custom font size

---

packages/bpk-component-map/src/BpkMap.js
unreleased.md

So we can change the center and the zoom changing the props.

Make "center" and "zoom" controlled in BpkMap

---

packages/bpk-docs/src/pages/GettingStartedPage/GettingStartedPage.js

[BPK-1695] Link to the sketch folder and not individual files

---

native/packages/react-native-bpk-component-image/index.js
native/packages/react-native-bpk-component-image/package-lock.json
native/packages/react-native-bpk-component-image/package.json
native/packages/react-native-bpk-component-image/readme.md
native/packages/react-native-bpk-component-image/src/BpkImage-test.android.js
native/packages/react-native-bpk-component-image/src/BpkImage-test.common.js
native/packages/react-native-bpk-component-image/src/BpkImage-test.ios.js
native/packages/react-native-bpk-component-image/src/BpkImage.js
native/packages/react-native-bpk-component-image/src/__snapshots__/BpkImage-test.android.js.snap
native/packages/react-native-bpk-component-image/src/__snapshots__/BpkImage-test.ios.js.snap
native/packages/react-native-bpk-component-image/stories.js
native/storybook/storybook.js
unreleased.md

[BPK-1489] Add RN Image component

---

native/packages/react-native-bpk-component-image/index.js
native/packages/react-native-bpk-component-image/package-lock.json
native/packages/react-native-bpk-component-image/package.json
native/packages/react-native-bpk-component-image/readme.md
native/packages/react-native-bpk-component-image/src/withLoadingBehaviour.js
native/packages/react-native-bpk-component-image/stories.js
package-lock.json

[BPK-1489] Add loading state HOC

---

packages/bpk-docs/src/layouts/SideNavLayout/Sidebar.js
packages/bpk-docs/src/pages/HomePage/HomePage.js

James asked me to do this at an appropriate time.

[No JIRA] Remove rainbow logo

---

.travis.yml

Reverts Skyscanner/backpack#889
Of course, it didn't work when merging on master 😭

Revert "[NoJira] testing parallel builds"

---

decisions/README.md
decisions/parallel-builds.md

The decision about the parallel builds

[BPK-1736] add decision on parallel builds

---

packages/bpk-component-infinite-scroll/src/withInfiniteScroll.js
unreleased.md

This covers when the ratio is over 1 (almost 1)

Change ratio comparison from equal to greater than.

---

native/packages/react-native-bpk-component-horizontal-nav/src/BpkHorizontalNav.js
unreleased.md

I had to add a wrapper view to the selected indicator so that it aligns correctly when using RTL.
It took me far too long to figure this out 🤦‍♂️

[BPK-1707] Fix RTL in native horizontal nav

---

packages/bpk-component-ticket/src/bpk-ticket.scss
unreleased.md

I haven't made a story for this as it's pretty trivial, but here's the one I tested it with in development to prove this works:

[BPK-1733] Ticket images

---

native/packages/react-native-bpk-component-icon/src/BpkIcon-test.common.js
native/packages/react-native-bpk-component-icon/src/__snapshots__/BpkIcon-test.android.js.snap
native/packages/react-native-bpk-component-icon/src/__snapshots__/BpkIcon-test.ios.js.snap
native/packages/react-native-bpk-component-progress/src/BpkProgress-test.common.js
native/packages/react-native-bpk-component-progress/src/__snapshots__/BpkProgress-test.android.js.snap
native/packages/react-native-bpk-component-progress/src/__snapshots__/BpkProgress-test.ios.js.snap
native/packages/react-native-bpk-component-text/src/BpkText-test.common.js
native/packages/react-native-bpk-component-text/src/__snapshots__/BpkText-test.android.js.snap
native/packages/react-native-bpk-component-text/src/__snapshots__/BpkText-test.ios.js.snap
native/packages/react-native-bpk-component-touchable-overlay/src/BpkTouchableOverlay-test.js
native/packages/react-native-bpk-component-touchable-overlay/src/__snapshots__/BpkTouchableOverlay-test.js.snap
native/packages/react-native-bpk-theming/src/util-test.js
package-lock.json
package.json
packages/bpk-component-mobile-scroll-container/src/BpkMobileScrollContainer-test.js
packages/bpk-component-mobile-scroll-container/src/__snapshots__/BpkMobileScrollContainer-test.js.snap
packages/bpk-component-popover/src/BpkPopoverPortal-test.js
packages/bpk-component-text/src/BpkText-test.js
packages/bpk-component-tooltip/src/BpkTooltipPortal-test.js
packages/bpk-component-tooltip/src/__snapshots__/BpkTooltipPortal-test.js.snap
packages/bpk-react-utils/src/Portal-test.js

[BPK-1726] update eslint-config-skyscanner-with-prettier

---

native/android/app/BUCK
native/android/app/build.gradle
native/android/app/src/androidTest/java/net/skyscanner/backpack/DetoxTest.java
native/android/app/src/main/AndroidManifest.xml
native/android/app/src/main/java/net/skyscanner/backpack/MainActivity.java
native/android/app/src/main/java/net/skyscanner/backpack/MainApplication.java

Change package name from `com.backpack` to `net.skyscanner.backpack`

[no-jira] Fix package-name for android app

---

native/ios/Main.storyboard
native/ios/Podfile.lock
native/ios/native.xcodeproj/project.pbxproj
native/ios/native/View Controllers/BadgeViewController.h
native/ios/native/View Controllers/BadgeViewController.m
native/packages/react-native-backpack/Backpack2.podspec
native/packages/react-native-backpack/libraries/Badge/ios/native/classes/BPKBadge.h
native/packages/react-native-backpack/libraries/Badge/ios/native/classes/BPKBadge.m
native/packages/react-native-backpack/libraries/Badge/ios/native/classes/Badge.h

Does not yet support docked variant. Will follow up with that in a later PR.
**Native implementation:**
**Existing React Native version:**

[BPK-1776] Implement iOS native badge

---

UNRELEASED.md
packages/bpk-component-breadcrumb/src/BpkBreadcrumb.scss

[BPK-1823] fix breadcrumb responsiveness

---

UNRELEASED.md
packages/bpk-component-banner-alert/package-lock.json
packages/bpk-component-banner-alert/package.json
packages/bpk-stylesheets/base.css
packages/bpk-stylesheets/package-lock.json
packages/bpk-stylesheets/package.json

It breaks `bpk-component-banner-alert` and causes a breaking change the `bpk-stylesheets`.

[BPK-1864] Revert #1009

---

.eslintrc
native/.eslintrc
package-lock.json
package.json
packages/bpk-component-checkbox/src/BpkCheckbox.js
packages/bpk-component-label/src/BpkLabel.js
packages/bpk-component-radio/src/BpkRadio.js
packages/bpk-docs/src/pages/.eslintrc
packages/bpk-tether/.eslintrc

Off the back of https://github.com/Skyscanner/eslint-config-skyscanner-with-prettier/pull/11

[NOJIRA] Upgrade eslint-config-skyscanner-with-prettier

---

.travis.yml

[nojira] Small tweaks to travis config

---

packages/bpk-docs/src/components/DocsPageWrapper/DocsPageWrapper.js

Preference order for the default platform to display goes:
1. Android
2. iOS
3. React Native
4. Web
We don't have any Android or iOS pages yet, but here's some screenshots to demonstrate how it would look with various states:
**What does this PR not contain?**
- The side nav filter is still just 'web' and 'native' right now (out of scope and we can still use 'native' filter for iOS and Android for the moment)
- I've not renamed `nativeSubpage` to `reactNativeSubpage` - YAGNI?

[BPK-1833] Add Android and iOS tabs to platform switcher in docs

---

UNRELEASED.md
packages/bpk-tokens/src/android/base/aliases.json
packages/bpk-tokens/src/android/base/spacing.json
packages/bpk-tokens/src/ios/base/aliases.json
packages/bpk-tokens/src/ios/base/spacing.json
packages/bpk-tokens/src/web/base/aliases.json
packages/bpk-tokens/src/web/base/spacing.json
packages/bpk-tokens/tokens/android/base.react.native.common.js
packages/bpk-tokens/tokens/android/base.react.native.es6.js
packages/bpk-tokens/tokens/base.android.xml
packages/bpk-tokens/tokens/base.common.js
packages/bpk-tokens/tokens/base.default.scss
packages/bpk-tokens/tokens/base.es6.js
packages/bpk-tokens/tokens/base.ios.json
packages/bpk-tokens/tokens/base.raw.android.json
packages/bpk-tokens/tokens/base.raw.ios.json
packages/bpk-tokens/tokens/base.raw.json
packages/bpk-tokens/tokens/base.react.native.android.js
packages/bpk-tokens/tokens/base.react.native.ios.js
packages/bpk-tokens/tokens/base.scss
packages/bpk-tokens/tokens/breakpoints.raw.json
packages/bpk-tokens/tokens/ios/base.react.native.common.js
packages/bpk-tokens/tokens/ios/base.react.native.es6.js
packages/bpk-tokens/tokens/travelpro.raw.json

None as a value
Needed for https://github.com/Skyscanner/backpack-ios/pull/51

Adding no spacing property

---

native/android/app/src/main/AndroidManifest.xml
native/android/app/src/main/res/values/strings.xml
native/android/build.gradle
native/android/gradle/wrapper/gradle-wrapper.properties

Update build tools version
Edit: Had to add the `@string/app_name` because the manifest merge was failing.

[BPK-2004] Update build tools and gradle version

---

UNRELEASED.md
native/packages/react-native-bpk-component-button/src/BpkButton.android.js
native/packages/react-native-bpk-component-button/src/__snapshots__/BpkButton-test.android.js.snap
native/packages/react-native-bpk-component-nudger/src/__snapshots__/BpkNudger-test.android.js.snap

Problem only happens with react 0.57.x. I'm not sure exactly why this fixes the problem but it does and is not causing any other visual diffs.

[BPK-2021] Fix android button ripple

---

native/android/build.gradle

[No JIRA] Fix Android build issue

---

meta.json

[No JIRA] Remove James :sob:

---

packages/bpk-component-popover/README.md
packages/bpk-component-popover/src/BpkPopover.js

Not actually changing anything here, just reordering the props!

[NO-JIRA] Alphabeticalise BpkPopover API

---

UNRELEASED.md
packages/bpk-component-popover/README.md
packages/bpk-component-popover/src/BpkPopover-test.js
packages/bpk-component-popover/src/BpkPopover.js
packages/bpk-component-popover/src/__snapshots__/BpkPopover-test.js.snap
packages/bpk-component-popover/src/__snapshots__/BpkPopoverPortal-test.js.snap

[TER-140] Add close button props

---

UNRELEASED.md
packages/bpk-component-image/index.js
packages/bpk-component-image/src/BpkBackgroundImage-test.js
packages/bpk-component-image/src/BpkBackgroundImage.js
packages/bpk-component-image/src/BpkImage.js
packages/bpk-component-image/src/__snapshots__/BpkBackgroundImage-test.js.snap
packages/bpk-component-image/src/bpk-background-image.scss
packages/bpk-component-image/src/bpk-image.scss
packages/bpk-component-image/stories.js

* Implemented BpkBackgroundImage to match BpkImage interface
* Moved some reusable scss into mixins to be shared between BpkImage and BpkBackgroundImage
* Fixed up the old tests that were lying around
* Added storybook entries for BpkBackgroundImage

Implement BpkBackgroundImage in bpk-component-image

---

packages/bpk-component-image/README.md
packages/bpk-docs/src/pages/WebImagesPage/WebImagesPage.js

[No JIRA] Add docs for BpkBackgroundImage

---

package-lock.json
package.json

[NOJIRA] Upgrade flow

---

packages/bpk-component-map/README.md

Fix missing closing tag for BpkMap documentation

---

.babelrc
package-lock.json
package.json

This is the result of attempting to upgrade to Babel 7. That wasn't successful, but I was able to replace this one deprecated dependency and I think it has some value on its own.
This also adds Danger to the Greenkeeper ignored packages as we can't upgrade it without upgrading Babel.

[BPK-2144] Replace babel-preset-es2015 with babel-preset-env

---

packages/bpk-docs/src/pages/BackpackReactScriptsPage/BackpackReactScriptsPage.js

Some small tweaks to the BRS docs page. Hopefully they are self explanatory 😅.

[BPK-1801] Update BRS docs

---

packages/bpk-docs/src/pages/WebTextPage/TextPage.js

We should merge this last, and then the docs will be redeployed with all the new screenshots from git submodules 🎉

[BPK-2183] Align Text examples between platforms

---

UNRELEASED.md
packages/bpk-component-banner-alert/package.json
packages/bpk-component-banner-alert/src/AnimateAndFade-test.js
packages/bpk-component-banner-alert/src/AnimateAndFade.js
packages/bpk-component-banner-alert/src/BpkBannerAlertInner-test.js
packages/bpk-component-banner-alert/src/__snapshots__/AnimateAndFade-test.js.snap
packages/bpk-component-banner-alert/src/__snapshots__/BpkBannerAlertInner-test.js.snap

[Migration guide](https://github.com/reactjs/react-transition-group/blob/HEAD/Migration.md)

[NO-JIRA] Upgrade react-transition-group

---

packages/bpk-docs/src/pages/CalendarPage/CalendarPage.js
packages/bpk-docs/src/pages/NativeCalendarPage/NativeCalendarPage.js
packages/bpk-docs/src/pages/NativeCalendarPage/index.js

Needs https://github.com/Skyscanner/backpack-react-native/pull/41 to be merged first!

[BPK-2221] Document RN calendar

---

packages/bpk-docs/src/components/HomePageCard/HomePageCard.js
packages/bpk-docs/src/components/HomePageCard/HomePageCard.scss
packages/bpk-docs/src/pages/HomePage/HomePage.js
packages/bpk-docs/src/pages/HomePage/home-page.scss

Before | Order breaking change | After
-- | -- | --

[NOJIRA] Fix homepage full width block

---

UNRELEASED.md
packages/bpk-component-barchart/src/__snapshots__/BpkBarchart-test.js.snap
packages/bpk-component-horizontal-nav/README.md
packages/bpk-component-horizontal-nav/src/BpkHorizontalNav.js
packages/bpk-component-horizontal-nav/src/BpkHorizontalNavItem.js
packages/bpk-component-horizontal-nav/stories.js
packages/bpk-component-horizontal-nav/stories.scss
packages/bpk-component-mobile-scroll-container/README.md
packages/bpk-component-mobile-scroll-container/src/BpkMobileScrollContainer.js
packages/bpk-docs/src/components/DocsPageWrapper/DocsPageWrapper.js

[Archive_7.zip](https://github.com/Skyscanner/backpack/files/2840067/Archive_7.zip)

[BPK-2225] Autoscroll to selected horizontal nav item

---

package-lock.json
packages/bpk-component-map/README.md
packages/bpk-component-map/package.json

Meant to do this in the original PR.

[No JIRA] Tweak docs and package.json

---

packages/bpk-docs/src/pages/NativeNavigationBarPage/NativeNavigationBarPage.js

[BPK-2250] Document primary text buttons for nav bar

---

UNRELEASED.md
packages/bpk-theming/README.md
packages/bpk-theming/src/BpkThemeProvider-test.js
packages/bpk-theming/src/BpkThemeProvider.js
packages/bpk-theming/src/__snapshots__/BpkThemeProvider-test.js.snap

+ [ ] Check this if you have read and followed the [contributing guidelines](https://github.com/Skyscanner/backpack/blob/master/CONTRIBUTING.md)

[NO-JIRA] Add component prop to BpkThemingProvider

---

UNRELEASED.md
package-lock.json
packages/bpk-theming/src/BpkThemeProvider-test.js
packages/bpk-theming/src/BpkThemeProvider.js
packages/bpk-theming/src/__snapshots__/BpkThemeProvider-test.js.snap

The `style` prop is now correctly applied in `BpkThemeProvider` e.g:
```
<BpkThemeProvider
theme={{ color: colorWhite }}
themeAttributes={['color']}
style={{ /* user defined style goes here */ }}
>
<p>Lorem Ipsum</p>
</BpkThemeProvider>
```

[BPK-2287] Theme provider now works with user defined style

---

UNRELEASED.md
packages/bpk-theming/src/BpkThemeProvider.js
packages/bpk-theming/src/__snapshots__/BpkThemeProvider-test.js.snap

[BPK-2287] Fix theme provider style spreading

---

packages/bpk-docs/src/pages/AndroidThemingPage/AndroidThemingPage.js
packages/bpk-docs/src/pages/AndroidThemingPage/index.js
packages/bpk-docs/src/pages/IOSThemingPage/IOSThemingPage.js
packages/bpk-docs/src/pages/IOSThemingPage/index.js
packages/bpk-docs/src/pages/ThemingPage/ThemingPage.js

[NO-JIRA] Add theming pages for iOS and Android

---

package-lock.json
package.json
packages/bpk-component-router-link/package.json

Upgrading `react-router-dom` to `v5.0.0` led to links breaking inside the mobile sidebar modal.

[NO-JIRA] Fix docs button

---

package-lock.json
packages/bpk-docs/src/pages/NativeCalendarPage/NativeCalendarPage.js

[NO-JIRA] Add single selection screenshot for Android

---

CODE_REVIEW_GUIDELINES.md

[No JIRA] Add RTL to code review guidelines

---

packages/bpk-docs/src/pages/MobileScrollContainerPage/MobileScrollContainerPage.js

[NO-JIRA] Fix typo

---

packages/bpk-docs/src/components/DocsPageBuilder/BpkMarkdownRenderer.js
packages/bpk-docs/src/components/DocsPageBuilder/BpkMarkdownRenderer.scss

Just adding a bit of spacing below tables in MD.

[NO-JIRA] Add spacing to readme tables

---

UNRELEASED.md
packages/bpk-component-select/src/BpkSelect.js
packages/bpk-component-select/src/__snapshots__/BpkSelect-test.js.snap
packages/bpk-component-select/src/bpk-select.scss
packages/bpk-mixins/src/mixins/_forms.scss

[BPK-2378]: Updated select component for invalid input

---

packages/bpk-docs/src/pages/IOSThemingPage/IOSThemingPage.js

[BPK-2321] iOS - Add primary button theming support

---

CONTRIBUTING.md

[NO-JIRA] Add cloning section to contributing guide

---

UNRELEASED.md
packages/bpk-component-textarea/README.md
packages/bpk-component-textarea/src/BpkTextarea.js
packages/bpk-component-textarea/src/BpkTextarea.scss
packages/bpk-component-textarea/src/__snapshots__/BpkTextarea-test.js.snap
packages/bpk-docs/src/pages/FieldsetsPage/FieldsetsPage.js
packages/bpk-docs/src/pages/FormsPage/FormsPage.js
packages/bpk-mixins/src/mixins/_forms.scss

Added validation to textarea field and updated docs to show invalid input with state toggle

[BPK-2395]: Textarea Validation

---

packages/bpk-docs/src/components/DocsPageBuilder/TokenSwitcher.js

[NO-JIRA] Fix docs tokens pages platform selection

---

UNRELEASED.md
packages/bpk-component-fieldset/src/BpkFieldset-test.js
packages/bpk-component-fieldset/src/BpkFieldset.js
packages/bpk-component-fieldset/src/__snapshots__/BpkFieldset-test.js.snap
packages/bpk-mixins/src/mixins/_forms.scss

[NO-JIRA] Invalid disabled fields

---

CONTRIBUTING.md
UNRELEASED.md

[No JIRA] Update instructions in unreleased.md

---

decisions/versioning-rules.md

[NO-JIRA]: Decision for versioning

---

packages/bpk-docs/src/pages/IOSThemingPage/IOSThemingPage.js

Should be merged once this is released:
https://github.com/Skyscanner/backpack-ios/pull/275

[BPK-2348] Update iOS theming page to reflect latest state

---

packages/bpk-component-image/README.md

- remove `altText` from BpkBackgroundImage
- add `style`
- remove deprecated/old props (`srcSet`, `sizes`) from examples

Update image component docs

---

UNRELEASED.md
packages/bpk-component-map/README.md
packages/bpk-component-map/src/BpkMapMarker-test.js
packages/bpk-component-map/src/BpkMapMarker.js
packages/bpk-component-map/src/BpkMapMarker.scss
packages/bpk-component-map/src/__snapshots__/BpkMapMarker-test.js.snap
packages/bpk-docs/src/pages/MapPage/MapPage.js

This was already being done by consumers so this pulls it into Backpack. I've also updated the docs page to be stateful so it works as an example (see GIF above).

[No JIRA] Add 'selected' prop to BpkMapMarker

---

UNRELEASED.md
packages/bpk-component-map/README.md
packages/bpk-component-map/src/BpkMapMarker.js
packages/bpk-component-map/src/BpkMapMarker.scss
packages/bpk-docs/src/pages/MapPage/MapPage.js

Looks like this:
(selected)
(not selected)

[No JIRA] Add new marker type

---

packages/bpk-component-text/index.js

Follow up from this PR: https://github.com/Skyscanner/backpack/pull/1444
Accidentally forgot to add the flow strict comment to the index file. 

[NoJira]: Add flow strict comment to index

---

.gitignore
.travis.yml
package.json

Sassdoc should be deployed by `backpack` instead of `backpack-docs`

[NO-JIRA] Add sassdoc to deployment

---

packages/bpk-component-datepicker/src/BpkDatepicker-test.js

[No JIRA] Fix test warnings

---

package-lock.json
package.json
packages/bpk-mixins/src/mixins/_typography.scss
packages/bpk-stylesheets/base.css

Closes #1403.
Upgrading caused some new errors because a false negative was fixed (https://github.com/stylelint/stylelint/pull/3959).
```
> stylelint 'packages/**/*.scss' --syntax scss
packages/bpk-mixins/src/mixins/_typography.scss
804:3  ⚠  Expected "h1" to have no more than 0 type selectors           selector-max-type
815:3  ⚠  Expected "h2" to have no more than 0 type selectors           selector-max-type
826:3  ⚠  Expected "h3" to have no more than 0 type selectors           selector-max-type
838:3  ⚠  Expected "h4" to have no more than 0 type selectors           selector-max-type
850:3  ⚠  Expected "h5" to have no more than 0 type selectors           selector-max-type
862:3  ⚠  Expected "h6" to have no more than 0 type selectors           selector-max-type
874:3  ⚠  Expected "a" to …
```

[No JIRA] Update Stylelint

---

CONTRIBUTING.md
package.json
scripts/npm/add-svgs.js

Just a cheeky script to make adding SVGs a breeze!
To try it:
```
npm run add-svgs
```
The prompts should then give you all the info you need!

[NO-JIRA] Add SVG script

---

CONTRIBUTING.md

[NO JIRA]: Updating documentation

---

packages/bpk-component-modal/stories.js

[NO-JIRA] Add nested modals example to storybook

---

UNRELEASED.md
packages/bpk-component-phone-input/src/BpkPhoneInput-test.js
packages/bpk-component-phone-input/src/BpkPhoneInput.js
packages/bpk-component-phone-input/src/__snapshots__/BpkPhoneInput-test.js.snap
packages/bpk-component-phone-input/stories.js
packages/bpk-component-select/src/BpkSelect.js
packages/bpk-component-select/src/BpkSelect.scss

No jira rollback phone input

---

.storybook/addons.js
.storybook/config.js
package-lock.json
package.json

More info here
https://storybook.js.org/addons/

Add a11y and viewport addons to storybook

---

packages/bpk-component-text/README.md

[NO JIRA]: Minor update to include new tag name

---

package-lock.json
package.json
scripts/npm/check-owners.js

[NO-JIRA] Add check-owners error catch

---

.spelling
UNRELEASED.md
packages/bpk-component-radio/README.md
packages/bpk-component-radio/src/BpkRadio-test.js
packages/bpk-component-radio/src/BpkRadio.js
packages/bpk-component-radio/src/__snapshots__/BpkRadio-test.js.snap

[No JIRA] Add ariaLabel prop to BpkRadio

---

scripts/npm/check-owners.js

Same as the change here: https://github.com/Skyscanner/backpack-react-native/pull/157

[NO-JIRA] Improve check-owners output

---

packages/bpk-component-chip/stories.js
packages/bpk-component-infinite-scroll/stories.js

Fixed some small issues with the storybook, diff should be self evident.

[BPK-2642] Infinite scroll story bugs

---

packages/bpk-component-phone-input/src/__snapshots__/BpkPhoneInput-test.js.snap

WOM-119 - Update snapshots

---

UNRELEASED.yaml
packages/bpk-component-button/README.md
packages/bpk-component-button/src/BpkButton.scss

[BPK-2606]: iconOnly buttons should stay circular

---

packages/bpk-component-autosuggest/README.md

[NO-JIRA] Add input props name to README example

---

UNRELEASED.yaml
packages/bpk-component-select/src/BpkSelect.scss

+ [x] ~`README.md`~
+ [x] ~Tests~
+ [x] ~Docs~

[BPK-2688] Fix phone input flag click

---

UNRELEASED.yaml
packages/bpk-component-infinite-scroll/src/__snapshots__/withInfiniteScroll-test.js.snap
packages/bpk-component-infinite-scroll/src/withInfiniteScroll-test.js
packages/bpk-component-infinite-scroll/src/withInfiniteScroll.js
packages/bpk-component-infinite-scroll/stories.js

[BPK-2668] Fix behaviour when data is changed to an empty array

---

.spelling
UNRELEASED.yaml
packages/bpk-component-nudger/BpkNudgerStory.scss
packages/bpk-component-nudger/README.md
packages/bpk-component-nudger/src/BpkNudger-test.js
packages/bpk-component-nudger/src/BpkNudger.js
packages/bpk-component-nudger/src/BpkNudger.scss
packages/bpk-component-nudger/src/__snapshots__/BpkNudger-test.js.snap
packages/bpk-component-nudger/stories.js

[BPK-2732]: BpkNudger to support outline buttons

---

package.json

[No JIRA] Rename npm script to make it safer

---

UNRELEASED.yaml
packages/bpk-component-ticket/src/BpkTicket.scss

[BPK-2735] Update ticket line style

---

decisions/sizing-in-rem.md

[BPK-2768] Document decision to use REM

---

UNRELEASED.yaml
packages/bpk-component-input/src/BpkInput.js
packages/bpk-component-input/src/BpkInput.scss

[BPK-2776] Properly hide clear button when hidden

---

.spelling
UNRELEASED.yaml
packages/bpk-component-image/README.md
packages/bpk-component-image/index.js
packages/bpk-component-image/src/BpkImage-test.js
packages/bpk-component-image/src/BpkImage.js
packages/bpk-component-image/src/BpkImage.scss
packages/bpk-component-image/src/BpkImageBorderRadiusStyles.js
packages/bpk-component-image/src/BpkImageCornerStyles.js
packages/bpk-component-image/src/__snapshots__/BpkImage-test.js.snap
packages/bpk-component-image/stories.js

[BPK-2781]: Added ability to apply borderRadius to BpkImage

---

.eslintignore

[NO JIRA]: Added `dist-storybook` and `dist-sassdoc` to be ignored in linting

---

packages/bpk-component-rating/package.json

[NO JIRA]: Making rating public

---

UNRELEASED.yaml
package-lock.json
packages/bpk-tokens/src/android/base/typography.json
packages/bpk-tokens/src/ios/base/typography.json
packages/bpk-tokens/src/web/base/typography.json
packages/bpk-tokens/tokens/android/base.react.native.common.js
packages/bpk-tokens/tokens/android/base.react.native.es6.js
packages/bpk-tokens/tokens/base.android.xml
packages/bpk-tokens/tokens/base.common.js
packages/bpk-tokens/tokens/base.default.scss
packages/bpk-tokens/tokens/base.es6.js
packages/bpk-tokens/tokens/base.ios.json
packages/bpk-tokens/tokens/base.raw.android.json
packages/bpk-tokens/tokens/base.raw.ios.json
packages/bpk-tokens/tokens/base.raw.json
packages/bpk-tokens/tokens/base.react.native.android.js
packages/bpk-tokens/tokens/base.react.native.ios.js
packages/bpk-tokens/tokens/base.scss
packages/bpk-tokens/tokens/ios/base.react.native.common.js
packages/bpk-tokens/tokens/ios/base.react.native.es6.js

[No JIRA] Add tokens for text color in light mode

---

UNRELEASED.yaml
packages/bpk-tokens/src/android/base/typography.json
packages/bpk-tokens/src/ios/base/typography.json
packages/bpk-tokens/src/web/base/typography.json
packages/bpk-tokens/tokens/android/base.react.native.common.js
packages/bpk-tokens/tokens/android/base.react.native.es6.js
packages/bpk-tokens/tokens/base.android.xml
packages/bpk-tokens/tokens/base.common.js
packages/bpk-tokens/tokens/base.default.scss
packages/bpk-tokens/tokens/base.es6.js
packages/bpk-tokens/tokens/base.ios.json
packages/bpk-tokens/tokens/base.raw.android.json
packages/bpk-tokens/tokens/base.raw.ios.json
packages/bpk-tokens/tokens/base.raw.json
packages/bpk-tokens/tokens/base.react.native.android.js
packages/bpk-tokens/tokens/base.react.native.ios.js
packages/bpk-tokens/tokens/base.scss
packages/bpk-tokens/tokens/ios/base.react.native.common.js
packages/bpk-tokens/tokens/ios/base.react.native.es6.js

I messed up the names in the last PRs. Didn't follow the naming
convention properly.
+ [x] Tests

[No JIRA] Fix semantic text names

---

CHANGELOG.md
packages/bpk-tokens/src/android/base/typography.json
packages/bpk-tokens/src/ios/base/typography.json
packages/bpk-tokens/tokens/android/base.react.native.common.js
packages/bpk-tokens/tokens/android/base.react.native.es6.js
packages/bpk-tokens/tokens/base.android.xml
packages/bpk-tokens/tokens/base.ios.json
packages/bpk-tokens/tokens/base.raw.android.json
packages/bpk-tokens/tokens/base.raw.ios.json
packages/bpk-tokens/tokens/base.react.native.android.js
packages/bpk-tokens/tokens/base.react.native.ios.js
packages/bpk-tokens/tokens/ios/base.react.native.common.js
packages/bpk-tokens/tokens/ios/base.react.native.es6.js

Remove unreleased deprected tokens

---

.storybook/themeableAttributes.js
UNRELEASED.yaml
packages/bpk-component-star-rating/README.md
packages/bpk-component-star-rating/src/BpkStar.scss
packages/bpk-component-star-rating/src/themeAttributes-test.js
packages/bpk-component-star-rating/src/themeAttributes.js
packages/bpk-component-theme-toggle/src/theming.js

[BPK-2888]: Added theming support to BpkStarRating

---

UNRELEASED.yaml
packages/bpk-component-pagination/src/BpkPaginationPage.scss

Bpk 2900 pagination to always be circular

---

.storybook/themeableAttributes.js
UNRELEASED.yaml
packages/bpk-component-fieldset/index.js
packages/bpk-component-fieldset/src/BpkFieldset.scss
packages/bpk-component-fieldset/src/themeAttributes.js
packages/bpk-component-form-validation/index.js
packages/bpk-component-form-validation/src/BpkFormValidation.scss
packages/bpk-component-form-validation/src/themeAttributes-test.js
packages/bpk-component-form-validation/src/themeAttributes.js
packages/bpk-component-input/README.md
packages/bpk-component-input/index.js
packages/bpk-component-input/src/BpkInput.scss
packages/bpk-component-input/src/themeAttributes-test.js
packages/bpk-component-input/src/themeAttributes.js
packages/bpk-component-select/src/themeAttributes-test.js
packages/bpk-component-select/src/themeAttributes.js
packages/bpk-component-textarea/index.js
packages/bpk-component-textarea/src/themeAttributes-test.js
packages/bpk-component-textarea/src/themeAttributes.js
packages/bpk-component-theme-toggle/src/theming.js
packages/bpk-mixins/src/mixins/_forms.scss

Bpk 2889 theming for inputs

---

.storybook/themeableAttributes.js
UNRELEASED.yaml
packages/bpk-component-banner-alert/README.md
packages/bpk-component-banner-alert/src/BpkBannerAlert.scss
packages/bpk-component-banner-alert/src/themeAttributes-test.js
packages/bpk-component-banner-alert/src/themeAttributes.js
packages/bpk-component-theme-toggle/src/theming.js

[BPK-2901]: Added theming support to BpkBannerAlert

---

.storybook/themeableAttributes.js
UNRELEASED.yaml
packages/bpk-component-badge/README.md
packages/bpk-component-badge/src/themeAttributes-test.js
packages/bpk-component-badge/src/themeAttributes.js
packages/bpk-component-theme-toggle/src/theming.js
packages/bpk-mixins/src/mixins/_badges.scss

[BPK-2902]: Added theming support to BpkBadge

---

packages/bpk-component-boilerplate/package-lock.json
packages/bpk-component-boilerplate/package.json

The example code within the boilerplate component package tries to import from `bpk-mixins` (which seems reasonable given that every component uses mixins). However `bpk-mixins` is not present in the package.json dependencies
+ [ ] `UNRELEASED.md` (NA)
+ [ ] `README.md` (NA)
+ [ ] Tests (NA)
+ [ ] Docs (NA)

[BPK-2653] Fix boilerplate package dependencies

---

scripts/publish-process/util.js

[NO-JIRA] Speed up beta publish script

---

UNRELEASED.yaml
packages/bpk-component-rating/index.js
packages/bpk-component-rating/stories.js

Exported RATING_SIZES

---

scripts/publish-process/util.js

[NO-JIRA] Add progress bar to release script

---

UNRELEASED.yaml
packages/bpk-component-mobile-scroll-container/src/BpkMobileScrollContainer.js

[BPK-2399] Mobile scroll container RTL fix

---

UNRELEASED.yaml
packages/bpk-component-rating/README.md
packages/bpk-component-rating/src/BpkRating-test.js
packages/bpk-component-rating/src/BpkRating.js
packages/bpk-component-rating/src/BpkRating.scss
packages/bpk-component-rating/src/__snapshots__/BpkRating-test.js.snap
packages/bpk-component-rating/stories.js
packages/bpk-component-rating/stories.scss

[BPK-2812]: Support vertical layout for rating component

---

UNRELEASED.yaml
packages/bpk-component-button/src/BpkButton.scss
packages/bpk-mixins/src/mixins/_buttons.scss

[NO JIRA]: Fixed `icon-only` border radius

---

UNRELEASED.yaml
packages/bpk-component-popover/src/BpkPopoverPortal.js
packages/bpk-component-tooltip/src/BpkTooltipPortal.js

[NO-JIRA] Fix GPU acceleration of BPKPopover

---

package-lock.json
packages/bpk-component-theme-toggle/src/BpkThemeToggle.js
packages/bpk-component-theme-toggle/src/__snapshots__/BpkThemeToggle-test.js.snap
packages/bpk-component-theme-toggle/src/azureTheme.js
packages/bpk-component-theme-toggle/src/theming.js

[NO-JIRA] Add azure to theme toggle

---

packages/bpk-component-theme-toggle/src/theming.js

[NO-JIRA] Remove extraneous theme attribute

---

packages/bpk-component-barchart/stories.scss
packages/bpk-component-datatable/src/BpkDataTable.scss
packages/bpk-component-datatable/src/BpkDataTableColumn.scss
packages/bpk-component-grid-toggle/src/BpkGridToggle.scss
packages/bpk-component-horizontal-nav/stories.scss
packages/bpk-component-icon/README.md
packages/bpk-component-mobile-scroll-container/stories.scss
packages/bpk-component-nudger/BpkNudgerStory.scss
packages/bpk-component-text/stories.scss
packages/bpk-mixins/src/mixins/_typography.scss
packages/bpk-mixins/stories.scss

[BPK-3002] Update remaining old colour usages

---

packages/bpk-mixins/src/mixins/_typography.scss

[NO-JIRA] Fix code alternate background color

---

UNRELEASED.yaml

[BPK-3002]: Update UNRELEASED

---

UNRELEASED.yaml
packages/bpk-component-pagination/src/BpkPaginationPage.scss

[NO JIRA]: Fixed pagination issue

---

.storybook/themeableAttributes.js
packages/bpk-component-theme-toggle/src/theming.js

[NO-JIRA] Reinstate logofillColor

---

UNRELEASED.yaml
packages/bpk-component-accordion/src/BpkAccordionItem.js
packages/bpk-component-accordion/src/__snapshots__/BpkAccordionItem-test.js.snap
packages/bpk-component-accordion/src/__snapshots__/withAccordionItemState-test.js.snap

[NO-JIRA] Fix typo in textStyle default value

---

UNRELEASED.yaml
packages/bpk-component-horizontal-nav/package.json
packages/bpk-component-horizontal-nav/src/BpkHorizontalNav.js
packages/bpk-component-horizontal-nav/stories.js

+ [x] Tests
Best way to test is in the docs:
```
rm -rf node_modules/bpk-component-horizontal-nav/* && cp -R ../backpack/packages/bpk-component-horizontal-nav/* ./node_modules/bpk-component-horizontal-nav/ && npx webpack-dev-server --open
```

[BPK-3091] nav bar scroll to selected

---

UNRELEASED.yaml
package-lock.json
package.json
packages/bpk-tokens/gulpfile.babel.js
packages/bpk-tokens/src/transformDarkValues.js
packages/bpk-tokens/tokens/base.ios.json
packages/bpk-tokens/tokens/base.raw.android.json
packages/bpk-tokens/tokens/base.raw.ios.json

[BPK-3098] Enable dynamic color output

---

packages/bpk-tokens/src/android/base/colors.json
packages/bpk-tokens/src/ios/base/colors.json
packages/bpk-tokens/tokens/android/base.react.native.common.js
packages/bpk-tokens/tokens/android/base.react.native.es6.js
packages/bpk-tokens/tokens/base.android.xml
packages/bpk-tokens/tokens/base.ios.json
packages/bpk-tokens/tokens/base.raw.android.json
packages/bpk-tokens/tokens/base.raw.ios.json
packages/bpk-tokens/tokens/base.react.native.android.js
packages/bpk-tokens/tokens/base.react.native.ios.js
packages/bpk-tokens/tokens/ios/base.react.native.common.js
packages/bpk-tokens/tokens/ios/base.react.native.es6.js

[NO-JIRA] Add primary color dynamic tokens

---

UNRELEASED.yaml
packages/bpk-tokens/src/transformDarkValues.js
packages/bpk-tokens/tokens/base.raw.android.json
packages/bpk-tokens/tokens/base.raw.ios.json

[BPK-3098] Fix dynamic tokens

---

packages/bpk-tokens/src/android/base/colors.json
packages/bpk-tokens/src/ios/base/colors.json
packages/bpk-tokens/tokens/android/base.react.native.common.js
packages/bpk-tokens/tokens/android/base.react.native.es6.js
packages/bpk-tokens/tokens/base.android.xml
packages/bpk-tokens/tokens/base.ios.json
packages/bpk-tokens/tokens/base.raw.android.json
packages/bpk-tokens/tokens/base.raw.ios.json
packages/bpk-tokens/tokens/base.react.native.android.js
packages/bpk-tokens/tokens/base.react.native.ios.js
packages/bpk-tokens/tokens/ios/base.react.native.common.js
packages/bpk-tokens/tokens/ios/base.react.native.es6.js

[NO-JIRA] Fix primary dynamic color

---

UNRELEASED.yaml
package-lock.json
packages/bpk-component-slider/package-lock.json
packages/bpk-component-slider/package.json
packages/bpk-component-slider/src/BpkSlider.js
packages/bpk-component-slider/src/__snapshots__/BpkSlider-test.js.snap

[NO JIRA]: Updating to latest dep version

---

UNRELEASED.yaml
packages/bpk-tokens/formatters/bpk.react.native.es6.js.js
packages/bpk-tokens/formatters/react-native-value-template.js
packages/bpk-tokens/tokens/android/base.react.native.es6.js
packages/bpk-tokens/tokens/base.react.native.android.js
packages/bpk-tokens/tokens/base.react.native.ios.js
packages/bpk-tokens/tokens/ios/base.react.native.es6.js

[BPK-3176] add rn semantic tokens

---

UNRELEASED.yaml
packages/bpk-component-datepicker/src/BpkDatepicker.js

[NO JIRA]: Added missing prop

---

.spelling
UNRELEASED.yaml
packages/bpk-component-phone-input/README.md
packages/bpk-component-phone-input/src/BpkPhoneInput-test.js
packages/bpk-component-phone-input/src/BpkPhoneInput.js
packages/bpk-component-phone-input/src/__snapshots__/BpkPhoneInput-test.js.snap
packages/bpk-component-phone-input/stories.js

+ [x] Tests
+ [x] Docs - Follow up PR required to showcase this option

[BPK-3168] Support phone-input masking

---

decisions/logos.md

[NO-JIRA] Add logo decision

---

packages/bpk-mixins/package.json

Ensures compatibility with Node 12

Bump node-sass version

---

packages/bpk-component-theme-toggle/src/BpkThemeToggle.js

[NO-JIRA] Theme toggle tweaks

---

packages/bpk-component-theme-toggle/package-lock.json
packages/bpk-component-theme-toggle/package.json
packages/bpk-component-theme-toggle/src/BpkThemeToggle.js

[NO-JIRA] Simplify konami logic

---

.eslintignore
packages/bpk-component-icon/src/classNameModifierHOCFactory-test.js
packages/bpk-component-icon/src/classNameModifierHOCFactory.js
packages/bpk-component-icon/src/withAlignment-test.js
packages/bpk-component-icon/src/withAlignment.js
packages/bpk-component-icon/src/withDescription-test.js
packages/bpk-component-icon/src/withDescription.js

[NO-JIRA] Fix icon linting errors

---

UNRELEASED.yaml
packages/bpk-component-accordion/README.md
packages/bpk-component-accordion/src/BpkAccordionItem-test.js
packages/bpk-component-accordion/src/BpkAccordionItem.js
packages/bpk-component-accordion/src/__snapshots__/BpkAccordionItem-test.js.snap
packages/bpk-component-accordion/stories.js

[NO-JIRA] Fix accordion README

---

decisions/backpack-bot-api-token-for-danger.md

[NO-JIRA] Update backpackbot token decision

---

decisions/backpack-bot-api-token-for-danger.md

[NO-JIRA] Clarify danger token scope

---

UNRELEASED.yaml
package-lock.json
packages/bpk-component-carousel/package-lock.json
packages/bpk-component-carousel/package.json
packages/bpk-component-carousel/src/BpkCarousel.js

I don't have access to an Android device right now so could whoever reviews this (cough Ollie) please check it on Android?
Here it is in Safari for iOS:

[BPK-3397] Add swipe support to carousel

---

UNRELEASED.yaml
packages/bpk-react-utils/src/__snapshots__/withDefaultProps-test.js.snap
packages/bpk-react-utils/src/withDefaultProps-test.js
packages/bpk-react-utils/src/withDefaultProps.js

[BPK-2118] Flow type withDefaultProps

---

UNRELEASED.yaml
packages/bpk-react-utils/src/cssModules-test.js
packages/bpk-react-utils/src/cssModules.js

[BPK-2118] Flow type cssModules

---

packages/bpk-react-utils/src/isRTL-test.js

[BPK-2118] Flow type isRTL script

---

UNRELEASED.yaml
packages/bpk-component-input/src/BpkClearButton.js
packages/bpk-component-input/src/__snapshots__/BpkClearButton-test.js.snap

[BPK-2742] Fix clearable input tab for IE11

---

package-lock.json
package.json

[No JIRA] Remove redundant dependency

---

dangerfile.js
packages/bpk-component-navigation-bar/README.md
packages/bpk-component-navigation-stack/README.md

* Add missing import for `withNavigationStackState`
* Use `BpkNavigationBarButtonLink` instead of `BpkButtonLink`

Modify a couple of "import" in readme.md

---

packages/bpk-component-infinite-scroll/README.md

[NO-JIRA] Fix README heading

---

packages/bpk-component-datepicker/README.md

See https://github.com/Skyscanner/backpack-docs/pull/362

[BPK-3605] Fix typo

---

decisions/writing-docs.md

[No JIRA] Clarify US English use in code

---

packages/bpk-component-calendar/DOCS.md

This PR adds additonal documentation on how the calendar component is constructed to help add clarity on the component

Improve calendar documentation

---

scripts/npm/check-owners.js

[NO-JIRA] Ignore mattface from check-owners

---

.spelling
packages/bpk-component-flare/README.md

[NO-JIRA] Add flareProps to README

---

package-lock.json

Reverts Skyscanner/backpack#1845

Revert "[Security] Bump tar from 2.2.1 to 2.2.2"

---

package-lock.json

Reverts Skyscanner/backpack#1833

Revert "[Security] Bump acorn from 5.7.3 to 5.7.4"

---

package-lock.json
packages/bpk-component-datatable/package-lock.json

Reverts Skyscanner/backpack#1843

Revert "[Security] Bump lodash from 4.17.11 to 4.17.13"

---

scripts/npm/check-owners.js

Part of my new thing about automating cultural knowledge.

[No JIRA] Add warning to check owners to help release process

---

CHANGELOG.md

[NO-JIRA] Add missing changelog versions

---

UNRELEASED.yaml
packages/bpk-component-star-rating/index.js
packages/bpk-component-star-rating/src/BpkInteractiveStar.js
packages/bpk-component-star-rating/src/BpkStar.js
packages/bpk-component-star-rating/src/__snapshots__/BpkInteractiveStar-test.js.snap

[BPK-3765] Fix star rating RTL animation

---

UNRELEASED.yaml
packages/bpk-animate-height/src/AnimateHeight.js
packages/bpk-component-grid/src/BpkGridColumn.js
packages/bpk-tokens/src/setOpacity-test.js
packages/bpk-tokens/src/setOpacity.js

Those damn falsy checks and zero!

[BPK-3447] Fix bug in setOpacity

---

UNRELEASED.yaml
packages/bpk-component-autosuggest/package-lock.json
packages/bpk-component-autosuggest/package.json

Minor bump of `react-autosuggest` to keep it up to date: https://github.com/moroshko/react-autosuggest/releases/tag/v10.0.2

Upgrade "react-autosuggest" to v10.0.2

---

UNRELEASED.yaml
packages/bpk-component-switch/src/BpkSwitch.js
packages/bpk-component-switch/src/__snapshots__/BpkSwitch-test.js.snap

[NO-JIRA] Switch fix aria-labels

---

UNRELEASED.yaml
packages/bpk-component-loading-button/src/BpkLoadingButton.js

Minor issue, but I hate warnings :-P

Fix BpkLoadingButton "unique key" warning

---

packages/bpk-svgs/gulpfile.babel.js

Just a bit of code refactoring. The output is unchanged.
+ [x] Tests

[BPK-4041] Cleanup gulpfile duplication

---

.spelling
UNRELEASED.yaml
packages/bpk-component-horizontal-nav/README.md
packages/bpk-component-horizontal-nav/src/BpkHorizontalNav-test.js
packages/bpk-component-horizontal-nav/src/BpkHorizontalNav.css
packages/bpk-component-horizontal-nav/src/BpkHorizontalNav.js
packages/bpk-component-horizontal-nav/src/BpkHorizontalNav.scss
packages/bpk-component-horizontal-nav/src/__snapshots__/BpkHorizontalNav-test.js.snap
packages/bpk-component-horizontal-nav/stories.js

[BPK-4042] Add showUnderline prop to BpkHorizonalNav

---

packages/bpk-component-text/src/BpkText.js

[wip] Change BpkText "bold" prop default value

---

decisions/dependencies-with-a-native-component.md

[BPK-4137] Add native-dependency decision

---

package.json

I can't figure out why just doing this won't work. Talked to George and we decided to just put this in and then we can see how it goes next time we have a release. Then we can hopefully see the problem and come up with another method to fix it.

[BPK-4138] Fix release process css publish

---

UNRELEASED.yaml
packages/bpk-component-breakpoint/src/BpkBreakpoint.js
packages/bpk-component-checkbox/src/BpkCheckbox.js

[BPK-4197]: Flow fixes

---

UNRELEASED.yaml
packages/bpk-component-chip/README.md

[BPK-4213]: Updated README

---

UNRELEASED.yaml
packages/bpk-component-horizontal-nav/src/BpkHorizontalNav.js

[No JIRA] Fix flow ignores in horizontal nav

---

UNRELEASED.md
packages/bpk-component-phone-input/src/__snapshots__/BpkPhoneInput-test.js.snap
packages/bpk-component-select/src/BpkSelect.js
packages/bpk-component-select/src/__snapshots__/BpkSelect-test.js.snap

Tested it on my phone, all good.

[BPK-4102] Make select images hidden from screen readers

---

.spelling
.storybook/config.js
UNRELEASED.md
packages/bpk-component-overlay/README.md
packages/bpk-component-overlay/index.js
packages/bpk-component-overlay/package-lock.json
packages/bpk-component-overlay/package.json
packages/bpk-component-overlay/src/BpkOverlay-test.js
packages/bpk-component-overlay/src/BpkOverlay.css
packages/bpk-component-overlay/src/BpkOverlay.js
packages/bpk-component-overlay/src/BpkOverlay.scss
packages/bpk-component-overlay/src/__snapshots__/BpkOverlay-test.js.snap
packages/bpk-component-overlay/stories.css
packages/bpk-component-overlay/stories.js
packages/bpk-component-overlay/stories.scss
scripts/npm/create-component.js

This PR is going to party like it's #1999 🎉 
I've done a self review to explain any things that aren't obvious, but I think for the most part it's all quite self explanatory. I've tested it in IE11 too and it's all good.

[BPK-4227] Add BpkOverlay component

---

package.json

Just committing this so that I can do a release without stuff changing!

[skip ci] Format package.json correctly

---

UNRELEASED.md
packages/bpk-component-image/src/withLoadingBehavior.js

[No JIRA] Add flow types to `WithLoadingBehavior`

---

.travis.yml

Temporarily to unblock other PRs

[No Jira] Disable Danger

---

decisions/backpack-bot-api-token-for-danger.md

[BPK-3625] Update danger token decision

---

.github/workflows/ci.yml

[NO-JIRA] Fix CI Node version

---

.github/workflows/ci.yml

[NO-JIRA] Neaten up CI workflow

---

.spelling
UNRELEASED.md
packages/bpk-component-image/README.md
packages/bpk-component-image/src/BpkBackgroundImage-test.js
packages/bpk-component-image/src/BpkBackgroundImage.js
packages/bpk-component-image/src/BpkImage-test.js
packages/bpk-component-image/src/BpkImage.js
packages/bpk-component-image/src/__snapshots__/BpkBackgroundImage-test.js.snap
packages/bpk-component-image/src/__snapshots__/BpkImage-test.js.snap
packages/bpk-component-image/src/customPropTypes-test.js
packages/bpk-component-image/src/customPropTypes.js
packages/bpk-component-image/stories.js

[BPK-2506] Clearer image aspect ratio API

---

.github/workflows/ci.yml

Seems to have done the trick:
https://github.com/backpack/storybook/commits/master

[NO-JIRA] Fix build

---

.spelling
.storybook/config.js
UNRELEASED.md
packages/bpk-component-aria-live/README.md
packages/bpk-component-aria-live/index.js
packages/bpk-component-aria-live/package-lock.json
packages/bpk-component-aria-live/package.json
packages/bpk-component-aria-live/src/BpkAriaLive-test.js
packages/bpk-component-aria-live/src/BpkAriaLive.css
packages/bpk-component-aria-live/src/BpkAriaLive.js
packages/bpk-component-aria-live/src/BpkAriaLive.scss
packages/bpk-component-aria-live/src/__snapshots__/BpkAriaLive-test.js.snap
packages/bpk-component-aria-live/stories.js

[BPK-4299] Add BpkAriaLive component

---

packages/bpk-component-aria-live/README.md
packages/bpk-component-aria-live/stories.js

[BPK-4299] Aria-live example tweaks

---

.github/workflows/ci.yml

I want to try and use simpler language as much as possible, to lower the barrier to entry for understanding what's going on. This doesn't just affect newcomers, it also affects us, because if we don't look at something for a while, we might forget what it's doing or how it works.
To that end, I simplified the language we use in our CI steps to be more descriptive of what's happening at each stage:
**Before**
**After**
_Note: there's a typo in this screenshot, but I've fixed it in the code._

[No Jira] Use more descriptive names for the CI process

---

UNRELEASED.md
packages/bpk-component-datatable/src/BpkDataTable-test.js
packages/bpk-component-datatable/src/BpkDataTable.js
packages/bpk-component-datatable/src/__snapshots__/BpkDataTable-test.js.snap

[NO-JIRA] Fix consumer rowClassName

---

UNRELEASED.md
packages/bpk-component-image/src/BpkBackgroundImage.js
packages/bpk-component-image/src/withLazyLoading.js

[NO-JIRA] Fix static defaultProps

---

UNRELEASED.md
packages/bpk-component-popover/src/BpkPopoverPortal-test.js
packages/bpk-component-popover/src/BpkPopoverPortal.js
packages/bpk-component-popover/src/keyboardFocusScope.js
packages/bpk-component-popover/stories.js
packages/bpk-react-utils/src/Portal.js

[BPK-4333] Fix popover input focus

---

UNRELEASED.md
packages/bpk-component-datatable/src/BpkDataTable.js
packages/bpk-component-datatable/src/BpkDataTableColumn.js
packages/bpk-component-datatable/src/bpkHeaderRenderer.js
packages/bpk-component-datatable/src/common-types.js
packages/bpk-component-datatable/src/hasChildrenOfType.js
packages/bpk-component-datatable/src/sort-types.js
packages/bpk-component-datatable/src/sorter.js

[No JIRA] Flow type bpk-component-datatable

---

packages/bpk-component-slider/README.md
packages/bpk-component-slider/stories.js

[BPK-3973] Add time slider example

---

packages/bpk-component-slider/examples.js
packages/bpk-component-slider/stories.js

[BPK-3973] Migrate slider examples to new format

---

.github/workflows/ci.yml
.jirabot.yml
CHANGELOG.md
dangerfile.js
decisions/parallel-builds.md
lerna.json
packages/bpk-component-datatable/README.md

CI is expected to fail right now because of the following tasks still outstanding:

[BPK-4401]: Migrate to main branch

---

packages/bpk-component-aria-live/examples.js

[NO-JIRA] Expose aria-live demo for docs site

---

packages/bpk-component-breakpoint/examples.css
packages/bpk-component-breakpoint/examples.js
packages/bpk-component-breakpoint/examples.scss
packages/bpk-component-breakpoint/package.json

[NO-JIRA] Update breakpoint demo styling

---

packages/bpk-component-badge/BadgeLayout.js
packages/bpk-component-badge/BpkBadgeLayout.css
packages/bpk-component-badge/BpkBadgeLayout.scss
packages/bpk-component-badge/examples.js
packages/bpk-component-badge/package.json
packages/bpk-component-button/BpkButtonStory.css
packages/bpk-component-button/BpkButtonStory.scss
packages/bpk-component-button/examples.js
packages/bpk-component-button/stories.js
packages/bpk-storybook-utils/package.json
packages/bpk-storybook-utils/src/BpkDarkExampleWrapper.css
packages/bpk-storybook-utils/src/BpkDarkExampleWrapper.js
packages/bpk-storybook-utils/src/BpkDarkExampleWrapper.scss

[BPK-4379] Add dark component wrapper

---

packages/bpk-component-badge/package.json
packages/bpk-component-banner-alert/examples.css
packages/bpk-component-banner-alert/examples.js
packages/bpk-component-banner-alert/examples.scss
packages/bpk-component-banner-alert/package.json
packages/bpk-component-banner-alert/stories.js

[BPK-4379] Migrate banner-alert stories

---

packages/bpk-component-grid-toggle/examples.js
packages/bpk-component-grid-toggle/stories.js
packages/bpk-component-grid/examples.js

Migrate Grid and Grid Toggle components

[BPK-4388]: Migrate two components to new stories

---

UNRELEASED.md
packages/bpk-component-chip/examples.js
packages/bpk-component-chip/src/BpkSelectableChip.js
packages/bpk-component-chip/src/__snapshots__/BpkDismissibleChip-test.js.snap

[BPK-4306]: Fixing A11y issue for dismissible chip

---

UNRELEASED.md
package.json
packages/bpk-component-calendar/src/BpkCalendarNav.js
packages/bpk-component-calendar/src/__snapshots__/BpkCalendarContainer-test.js.snap
packages/bpk-component-calendar/src/__snapshots__/BpkCalendarNav-test.js.snap
packages/bpk-component-calendar/src/accessibility-test.js

Also added a quick way to just run a11y tests.

[No Jira] Fix a broken a11y test

---

scripts/npm/check-owners.js

As we don't actually publish `bpk-component-boilerplate` and is used for automated component creation in our project, adding it as a project to be ignored when checking owners

[NO JIRA]: Updating check owners script to ignore non published folders

---

UNRELEASED.md
packages/bpk-component-card/README.md
packages/bpk-component-card/examples.js
packages/bpk-component-card/package.json
packages/bpk-component-card/src/BpkCard-test.js
packages/bpk-component-card/src/BpkCard.js
packages/bpk-component-card/src/__snapshots__/BpkCard-test.js.snap
packages/bpk-component-card/stories.js

[KOA-4473] Add non-atomic option for cards

---

UNRELEASED.md
packages/bpk-component-card/src/BpkCard.js
packages/bpk-component-card/src/__snapshots__/BpkCard-test.js.snap

[KOA-4473] Fix non-atomic card role

---

packages/bpk-component-datatable/package.json
packages/bpk-component-datatable/src/__snapshots__/BpkDataTable-test.js.snap
packages/bpk-component-scrollable-calendar/package.json
packages/bpk-component-scrollable-calendar/src/__snapshots__/BpkScrollableCalendarGridList-test.js.snap
packages/bpk-component-slider/package.json
packages/bpk-tokens/package.json

I ran them all locally and everything seems to work fine.
One that I **didn't** upgrade is `intersection-observer`. They have no release notes / changelog of any sort, so I felt it was better to just leave it on the version we know is fine.

[KOA-4561] Upgrade minor dependencies

---

dangerfile.js
meta.json

Updating the web repository with the latest danger checks

KOA-4571 Update dangerfile to improve licensing and org membership checks

---

UNRELEASED.md
packages/bpk-component-calendar/README.md
packages/bpk-component-calendar/examples-components.js
packages/bpk-component-calendar/examples.js
packages/bpk-component-calendar/package.json
packages/bpk-component-calendar/src/BpkCalendarGrid-test.js
packages/bpk-component-calendar/src/BpkCalendarGridTransition.js
packages/bpk-component-calendar/src/BpkCalendarNav-test.js
packages/bpk-component-calendar/src/BpkCalendarNav.js
packages/bpk-component-calendar/src/Week-test.js
packages/bpk-component-calendar/src/Week.js
packages/bpk-component-calendar/src/date-utils.js
packages/bpk-component-calendar/test-utils.js
packages/bpk-component-datepicker/README.md
packages/bpk-component-datepicker/examples.js
packages/bpk-component-datepicker/src/BpkDatepicker-test.js
packages/bpk-component-datepicker/src/accessibility-test.js
packages/bpk-component-fieldset/examples.js
packages/bpk-component-scrollable-calendar/README.md
packages/bpk-component-scrollable-calendar/examples.js
packages/bpk-component-scrollable-calendar/package.json
packages/bpk-component-scrollable-calendar/src/BpkScrollableCalendarGrid-test.js
packages/bpk-component-scrollable-calendar/src/BpkScrollableCalendarGridList-test.js
packages/bpk-component-scrollable-calendar/src/__snapshots__/BpkScrollableCalendarGridList-test.js.snap
packages/bpk-component-scrollable-calendar/stories.js
packages/bpk-component-scrollable-calendar/test-utils.js

The changes were quite substantial so I had to update a lot to get it all working. I'll add inline comments for context where needed.

[KOA-4563] Upgrade `date-fns`

---

UNRELEASED.md
package-lock.json
package.json
packages/bpk-component-router-link/package.json
packages/bpk-component-router-link/stories.js

After this PR, I will release the changes, pull them into the docs site and then complete the upgrade there, as according to [the ticket](https://gojira.skyscanner.net/browse/KOA-2783) that's where issues have arisen.

[KOA-2783] Upgrade react-router-dom

---

.spelling
UNRELEASED.md
packages/bpk-component-rating/README.md
packages/bpk-component-rating/examples.js
packages/bpk-component-rating/index.js
packages/bpk-component-rating/src/BpkRating-test.js
packages/bpk-component-rating/src/BpkRating.js
packages/bpk-component-rating/src/__snapshots__/BpkRating-test.js.snap
packages/bpk-component-rating/src/common-types.js
packages/bpk-component-rating/stories.js

[KOA-4594] Add ratingScale prop to rating component

---

.spelling
packages/bpk-component-calendar/README.md

These props are required in [BpkCalendarNav](https://github.com/Skyscanner/backpack/blob/0f574b3b10472aeab14e70f03ea201409c997008/packages/bpk-component-calendar/src/BpkCalendarNav.js#L157-L158) and in [BpkCalendar](https://github.com/Skyscanner/backpack/blob/0f574b3b10472aeab14e70f03ea201409c997008/packages/bpk-component-calendar/src/composeCalendar.js#L150-L151)

Update `bpk-component-calendar` README.md

---

UNRELEASED.md
packages/bpk-component-slider/package-lock.json
packages/bpk-component-slider/package.json
packages/bpk-component-slider/src/accessibility-test.js

Updated to the latest `react-slider` library that includes new A11y fixes and support for `ariaLabelledBy`.

[KOA-4472]: Enhance slider accessibility

---

meta.json

[No Jira] Remove Shaun from maintainers

---

packages/bpk-component-chip/examples.js
packages/bpk-component-chip/stories.js

[No JIRA] Create chip radiogroup example

---

.storybook/babel.config.js
babel.config.js

[no jira]: Fix babel config for storybook to fix rendering issues on browsers

---

packages/bpk-component-image/README.md

Fix BackgroundImage docs

---

meta.json

[KOA-4661] Add Ana as maintainer

---

CONTRIBUTING.md
README.md

[no-jira] Fix a few broken links in README.md and CONTRIBUTING.md

---

packages/bpk-component-autosuggest/examples.js
packages/bpk-component-autosuggest/stories.js

[NO-JIRA] Add autosuggest hanzi example

---

.github/workflows/ci.yml
packages/bpk-component-datepicker/package.json
packages/bpk-component-form-validation/package.json
packages/bpk-component-phone-input/package.json
packages/bpk-component-popover/package.json

This PR allows CI to run on both PRs to main but also on pull requests to open pull requests.

[no jira]: Allow CI to run on PRs to PRs

---

meta.json

Adding maria to list of maintainers after being added to npm

[no jira]: Add maria to npm

---

UNRELEASED.md
packages/bpk-component-image/src/BpkBackgroundImage-test.js
packages/bpk-component-image/src/BpkBackgroundImage.js
packages/bpk-component-image/src/__snapshots__/BpkBackgroundImage-test.js.snap

[NO-JIRA] Background image fixes - to discuss

---

UNRELEASED.md
package.json
packages/bpk-component-barchart/package-lock.json
packages/bpk-component-barchart/package.json

[KOA-4796] Upgrade d3-scale library

---

meta.json

Adding myself to the list of owners.

Add zgeor to the meta.json

---

.husky/pre-commit
package-lock.json
package.json

Upgrading dependencies to latest
Updating to follow new husky format

Updating husky and lint-staged to latest

---

CHANGELOG.md
UNRELEASED.md
packages/bpk-component-banner-alert/package.json
packages/bpk-component-chip/package.json

- update changelog post publish
- fix cross dependencies

[NO-JIRA] Update changelog and fix dependencies

---

.github/workflows/ci.yml

Disable dependabot on the following steps
- Prepare to deploy Storybook (pull request build)
- Deploy Storybook to backpack.github.io/storybook-prs, if a pull request
- Link to the pull request build
Disable running on forks in addition to dependabot[bot]
- Post a comment about the visual tests (if they fail)
- Post a comment about the visual tests (if they pass)

Disable dependabot[bot] steps requiring a token (Comments)

---

UNRELEASED.md
packages/bpk-mixins/src/mixins/_forms.scss

[NO-JIRA] Fix radio variable bug

---

packages/bpk-mixins/src/mixins/_utils.scss

Fix a typo

---

UNRELEASED.md
packages/bpk-mixins/src/mixins/_typography.scss

[KOA-4812]: Adding new text styles

---

CHANGELOG.md

[NO-JIRA] Update changelog

---

UNRELEASED.md
packages/bpk-component-accordion/README.md
packages/bpk-component-accordion/examples.js
packages/bpk-component-accordion/src/BpkAccordionItem.js

[KOA-4939] Deprecate weight from accordion

---

package-lock.json

Update mixin-deep in package-lock.json

---

UNRELEASED.md
packages/package-lock.json
packages/package.json

There were some dependencies that were not added to the single package during the migration, so this PR adds them in to ensure all dependencies are available.

[NO JIRA]: Install missing dependencies

---

UNRELEASED.md
packages/bpk-component-image/package-lock.json
packages/bpk-component-image/package.json

[NO-JIRA] Fix image component dependency

---

UNRELEASED.md
packages/bpk-component-modal/src/BpkModal.js

[NO JIRA] Fix datepicker input fields bug

---

packages/bpk-component-split-input/package-lock.json
packages/bpk-component-split-input/package.json

[NO JIRA] Fix split input component dependencies

---

examples/bpk-component-fieldset/examples.js

[NO JIRA] Fix action import in fieldset component example

---

UNRELEASED.md
packages/bpk-component-split-input/src/BpkInputField.js
packages/bpk-component-split-input/src/BpkInputField.module.scss
packages/bpk-component-split-input/src/BpkSplitInput.js
packages/bpk-component-split-input/src/BpkSplitInput.module.scss
packages/bpk-component-split-input/src/__snapshots__/BpkSplitInput-test.js.snap

[NO JIRA] remove deprecated spacing tokens

---

UNRELEASED.md
packages/bpk-component-graphic-promotion/src/BpkGraphicPromo.module.scss

[ST-4506] Set a maximum height in the Sponsor Logo.

---

package-lock.json
packages/bpk-component-banner-alert/package.json
packages/bpk-component-chip/package.json
packages/bpk-component-floating-notification/package.json

[NO JIRA] Update dependecies

---

UNRELEASED.md
packages/bpk-component-graphic-promotion/src/BpkGraphicPromo.module.scss

[ST-4504] Correct the Graphic Promo max width.

---

UNRELEASED.md
packages/bpk-component-breakpoint/package-lock.json
packages/bpk-component-breakpoint/package.json

[KOA-4996] Bump react-responsive in breakpoint component

---

UNRELEASED.md
packages/bpk-component-graphic-promotion/src/BpkGraphicPromo-test.js
packages/bpk-component-graphic-promotion/src/BpkGraphicPromo.js
packages/bpk-component-graphic-promotion/src/__snapshots__/BpkGraphicPromo-test.js.snap

The ID was added to the wrong element before. This PR fixes that problem.

[ST-4451] Add the ID to the element with the background image in Graphic Promo.

---

.eslintrc
.storybook/webpack.config.js
tsconfig.json

This PR extracts the typescript specific changes from #2527 to a separate PR so that it can be merged ahead of the PR and would also unblock #2535 from waiting on the first PR

[NO JIRA]: Extract TS updates to separate PR

---

UNRELEASED.md
packages/bpk-component-scrollable-calendar/package-lock.json
packages/bpk-component-scrollable-calendar/package.json
packages/bpk-component-scrollable-calendar/src/BpkScrollableCalendarGridList.js
packages/bpk-component-scrollable-calendar/src/__snapshots__/BpkScrollableCalendar-test.js.snap
packages/bpk-component-scrollable-calendar/src/__snapshots__/BpkScrollableCalendarGridList-test.js.snap
packages/bpk-component-scrollable-calendar/src/utils-test.js
packages/bpk-component-scrollable-calendar/src/utils.js
packages/package-lock.json
packages/package.json

Migrated the scrollable calendar from previously heavy react-virtualized library to much more lightweight library to aid in React 17 support and also reduce bundlesizes

[KOA-5027]: Migrate calendar from react-virtualized

---

UNRELEASED.md
examples/bpk-component-calendar/examples.js
packages/bpk-component-calendar/src/BpkCalendarGrid-test.js
packages/bpk-component-calendar/src/BpkCalendarGrid.js
packages/bpk-component-scrollable-calendar/src/BpkScrollableCalendarGrid-test.js

[NO JIRA] Set default values for minDate and maxDate in calendar

---

UNRELEASED.md
packages/bpk-component-breadcrumb/src/BpkBreadcrumbItem.module.scss

[KOA-5477]: Breadcrumb to use semantic tokens

---

UNRELEASED.md
packages/bpk-component-navigation-bar/src/BpkNavigationBar.module.scss

[NO JIRA] Add missing nav bar bottom border

---

UNRELEASED.md
packages/bpk-component-switch/src/BpkSwitch.js

PropType should be `bool` instead of `boolean`.

Fix BpkSwitch proptype

---

UNRELEASED.md
packages/bpk-component-price/src/BpkPrice.module.scss

[KOA-5551] Update price component to use semantic colour tokens

---

UNRELEASED.md
packages/bpk-component-section-list/src/BpkSectionListItem.module.scss
packages/bpk-component-section-list/src/BpkSectionListSection.module.scss

[KOA-5594]: Section list semantic token update

---

UNRELEASED.md
packages/bpk-component-popover/src/BpkPopover.module.scss
packages/bpk-component-tooltip/src/BpkTooltip.module.scss

[KOA-5595] Update popover and tooltip to semantic colours

---

UNRELEASED.md
packages/bpk-component-close-button/src/BpkCloseButton.module.scss
packages/bpk-component-content-cards/src/BpkContentCard.module.scss
packages/bpk-component-nudger/src/BpkNudger.module.scss
packages/bpk-component-spinner/src/BpkSpinner.module.scss
packages/bpk-component-star-rating/src/BpkStar.module.scss
packages/bpk-component-ticket/src/BpkTicket.module.scss

- bpk-component-close-button<br />
- bpk-component-content-cards<br />
- bpk-component-nudger<br />
- bpk-component-spinner<br />
- bpk-component-star-rating<br />
- bpk-component-ticket<br />
- Migrated components to use semantic tokens

[KOA-5588]: Group semantic token update

---

UNRELEASED.md
packages/bpk-component-dialog/src/BpkDialog.module.scss
packages/bpk-component-dialog/src/BpkDialogInner.module.scss
packages/bpk-component-drawer/src/BpkDrawerContent.module.scss
packages/bpk-component-modal/src/BpkModalInner.module.scss

[KOA-5593]: Dialogs semantic update

---

UNRELEASED.md
packages/bpk-component-pagination/src/BpkPaginationList.module.scss
packages/bpk-component-pagination/src/BpkPaginationNudger.module.scss

| -- | -- |
| ![Pagination Before](https://user-images.githubusercontent.com/8831547/204833175-d580e337-5b0b-4cf4-9cce-0428d52f0232.png) | ![Pagination After](https://user-images.githubusercontent.com/8831547/204834038-232ec988-25ea-42cb-87f3-435215f5610f.png) |

[NO JIRA]: Fix pagination alignment

---

examples/bpk-component-content-cards/examples.tsx

Updates examples to follow more realistic example as per the Figma and Design guidence see below what it looks like now with better content example

[NO JIRA]: Update content cards examples

---

.spelling
packages/bpk-component-page-indicator/README.md

Added `VARIANT` descriptions to make user use more concise and clear.

[NO-JIRA]Update page indicator doc

---

UNRELEASED.md
examples/bpk-component-pagination/examples.js
examples/bpk-component-pagination/stories.js
packages/bpk-component-pagination/src/BpkPaginationList.module.scss
packages/bpk-component-pagination/src/BpkPaginationNudger.js
packages/bpk-component-pagination/src/BpkPaginationNudger.module.scss
packages/bpk-component-pagination/src/BpkPaginationPage.module.scss
packages/bpk-component-pagination/src/__snapshots__/BpkPaginationNudger-test.js.snap

Updates to the new pagination style as per figma
| -- | -- |
| ![Screenshot 2023-01-05 at 17 21 13](https://user-images.githubusercontent.com/8831547/210841947-03420fbd-507e-47d5-af6f-9539bae2fe5b.png) | ![Screenshot 2023-01-05 at 17 20 26](https://user-images.githubusercontent.com/8831547/210841976-70ded3b4-f318-4af5-94a8-926a53899fef.png) |

[NO JIRA]: Update Pagination to new design

---

package-lock.json
package.json
scripts/webpack/postCssPlugins.js

PR to fix the autoprefixer warnings when running storybook and reduce dependencies

[NO JIRA]: Removed autoprefixer and fixed browserlist warnings

---

UNRELEASED.md
packages/bpk-component-tooltip/src/BpkTooltip.module.scss

[KOA-5787] Update tooltip padding

---

packages/bpk-component-grid/README.md

This component has been deprecated for a long time. Update the README to reflect that

Update grid README

---

examples/bpk-component-badge/examples.js

[KOA-5853]: Update BpkBadge examples

---

examples/bpk-component-badge/BadgeLayout.js
examples/bpk-component-badge/examples.js

Removed the examples to show trailing icon badges in order to discourage their use

[KOA-5851]: Remove trailing badges

---

CHANGELOG_FORMAT.md
CONTRIBUTING.md
README.md
packages/README.md
packages/bpk-component-accordion/README.md
packages/bpk-component-autosuggest/README.md
packages/bpk-component-breadcrumb/src/BpkBreadcrumbItem-test.js
packages/bpk-component-breadcrumb/src/__snapshots__/BpkBreadcrumbItem-test.js.snap
packages/bpk-component-scrollable-calendar/README.md

[KOA-5639] Remove references to backpack.github.io

---

CONTRIBUTING.md

[skip ci] update contribution guidelines

---

CHANGELOG_FORMAT.md
README.md
packages/README.md

[NO JIRA] Fix broken docs links

---

UNRELEASED.md
packages/bpk-component-popover/src/BpkPopoverPortal.js
packages/bpk-component-tooltip/src/BpkTooltipPortal.js

[NO JIRA] Fix popperModifiers prop type

---

UNRELEASED.md
packages/bpk-component-link/src/BpkButtonLink-test.js
packages/bpk-component-link/src/BpkButtonLink.js
packages/bpk-component-link/src/BpkLink-test.js
packages/bpk-component-link/src/BpkLink.js
packages/bpk-component-link/src/__snapshots__/BpkButtonLink-test.js.snap
packages/bpk-component-link/src/__snapshots__/BpkLink-test.js.snap

[KOA-5056]: Remove deprecated `white` property

---

packages/bpk-component-switch/src/BpkSwitch.module.scss

There is a rtl issue on the switch component, this PR is to fix it.
Before:
After:

Fix rtl issue for switch component

---

UNRELEASED.md
packages/bpk-component-banner-alert/README.md

- Updated docs for `bpk-component-banner-alert` to correctly reflect the required props.

[DTO-4059] Fix BackpackBannerAlert Docs for Required Props

---

UNRELEASED.md
packages/bpk-component-theme-toggle/src/theming.js

[NO JIRA] Fix theming

---

.github/dependabot.yml
.github/workflows/pr.yml

Updates the config for running dependabot changes to ensure the right labels get added for the new process, removes setting specific labels and lets the default config of `dependencies` label be applied to PRs
Removes the dependabot step from the PR workflow as if we bump Backpack dependencies or JS dependencies we want to include these in the release

[NO JIRA]: Update config for running dependabot changes

---

package-lock.json
package.json

Adds the supernova dependency so that when the docs publish goes through it will be able to run it.

[KOA-5931]: Add missing supernova dependency

---

.github/workflows/_build.yml
.github/workflows/main.yml
.github/workflows/pr.yml
.storybook/preview.js
package-lock.json
package.json

**Description:**
Adding the Percy Storybook snapshots integrated with Github Actions as a new visual testing platform.
- [-] `UNRELEASED.md` (See [How to write a good changelog entry](https://github.com/Skyscanner/backpack/blob/main/CHANGELOG_FORMAT.md))
- [-] `README.md`
- [-] Tests
- [-] Storybook examples created/updated

[LOOM-640] - setting up Percy for Backpack GitHub actions

---

packages/bpk-component-chip/src/commonTypes.js

[NO-JIRA] Fix chip prop type warning

---

.github/workflows/release.yml

This PR updates the release scripts in order to publish the compiled version of Backpack

[NO JIRA]: Update release process to ship transpiled

---

packages/bpk-component-floating-notification/src/BpkFloatingNotification.module.scss

[KOA-5987] Fix floating notification alignment

---

examples/bpk-component-calendar/examples.js
examples/bpk-component-input/examples.js
examples/bpk-component-scrollable-calendar/examples.js
package-lock.json
packages/bpk-component-calendar/README.md

[NO JIRA] Change date in calendar tests

---

babel.config.js
package-lock.json
package.json
scripts/transpilation/copy-types.js

This PR ensures that the typescript types files that we create as part of moving to TS are included in the transpiled package bundle.

[NO JIRA]: Ensure TS is included in transpiled package

---

CONTRIBUTING.md

[NO JIRA] Update contribution guide to make TS the default

---

CONTRIBUTING.md

[NO JIRA] Update experimentation guidelines

---

dangerfile.js

[NO JIRA] Add danger step for type files

---

packages/bpk-component-modal/README.md
packages/bpk-component-modal/src/BpkModal.d.ts
packages/bpk-component-modal/src/BpkModal.tsx
packages/bpk-component-modal/src/BpkModalInner.d.ts
packages/bpk-component-modal/src/BpkModalInner.tsx
packages/bpk-component-modal/src/__snapshots__/BpkModal-test.tsx.snap
packages/bpk-scrim-utils/index.d.ts
packages/bpk-scrim-utils/src/withScrim.d.ts
packages/bpk-scrim-utils/src/withScrim.tsx

[NO JIRA] Fix modal props

---

.naverc
.nvmrc
CONTRIBUTING.md
package-lock.json
package.json

[KOA-6076] Upgrade Backpack to Node 18

---

.github/pull_request_template.md

[NO JIRA] Update PR template

---

packages/bpk-component-breakpoint/src/BpkBreakpoint.tsx
packages/package-lock.json
packages/package.json

[KOA-6134] Update react-responsive

---

packages/bpk-component-dialog/src/BpkDialogInner.d.ts
packages/bpk-component-dialog/src/common-types.d.ts
packages/bpk-component-dialog/src/common-types.ts

[NO JIRA] Fix dialog types

---

package-lock.json
package.json

Tested with https://github.com/Skyscanner/backpack/pull/2908 too and all runs fine

[KOA-6040] Bump autoprefixer

---

.storybook/main.js
package-lock.json
package.json

[KOA-6041] Bump webpack to v5

---

examples/bpk-component-card/examples.js

[KOA-6212] Update card wrapper example to match Figma

---

package-lock.json
package.json

When dependabot bumped #2955 it introduced a bug which causes build to hang due to an error in that package version. This PR reverts it so we can continue with Backpack delivery until the issue is resolved

[NO JIRA]: Revert @storybook/addon-docs

---

package-lock.json
package.json
packages/package-lock.json
packages/package.json

Bumps `bpk-svgs` to the latest to adopt the updated Explore icon!

[KOA-6262]: Updated explore icon

---

packages/bpk-component-icon/src/classNameModifierHOCFactory.d.ts
packages/bpk-component-icon/src/classNameModifierHOCFactory.tsx
packages/bpk-component-icon/src/withAlignment.d.ts
packages/bpk-component-icon/src/withAlignment.tsx
packages/bpk-component-icon/src/withDescription.d.ts
packages/bpk-component-icon/src/withDescription.tsx
packages/bpk-component-icon/src/withRtlSupport.d.ts

Corrects the icon HOCs to allow the correct types of either a Component or a String to compose the outputted component

[NO JIRA]: Correct icon type props

---

packages/bpk-component-popover/src/BpkPopoverPortal.js

[NO JIRA] Fix popover type export

---

packages/bpk-component-button/src/BpkButtonV2/common-types.d.ts
packages/bpk-component-button/src/BpkButtonV2/common-types.tsx

[NO JIRA] Fix button onClick handler type

---

packages/bpk-component-floating-notification/src/BpkFloatingNotification.js
packages/bpk-component-floating-notification/src/__snapshots__/BpkFloatingNotification-test.js.snap
packages/bpk-component-page-indicator/src/NavButton.js
packages/bpk-component-pagination/src/BpkPaginationNudger.js
packages/bpk-component-pagination/src/BpkPaginationPage.js

This PR changes internal use of BpkButton to use the new BpkButtonV2 which should mean that bundlesizes are reduced as the old buttons will not be imported

[NO JIRA]: Upgrade internally to BpkButtonV2

---

packages/bpk-component-floating-notification/src/BpkFloatingNotification.js
packages/package-lock.json
packages/package.json

- updates react-transition-group from v2 to v4
<details>
<summary>React transition group change log:</summary>
-    use stable context API (React 16)
-    support esm via package.json routes
</details>
**Breaking change**
- moves react-transition-group to a peer-dep

[LUNA-874] Update react-transition-group

---

examples/bpk-component-map/stories.js

This PR temporarily removes the Map component visual tests, as they keep failing on PRs and require manual approval to change the root screenshot due to rendering issues in the percy testing environment and not loading in time or correctly.
Following this removal there will be a follow up investigation ticket to reinstate this test but using appropriate loading/waiting methods to ensure the map renders correctly in the percy environment.

Remove Map visual test due to rendering issues

---

package-lock.json
package.json

`babel-plugin-react-docgen` was previously installed due to it being a nested dependency (2 levels deep) of a dependency. A [minor bump](https://github.com/Skyscanner/backpack/pull/3106) in `@storybook/react-webpack5` removed this dependency and hence it was never installed anymore making Storybook build fail as we were using it directly.

[NO JIRA] Add babel-plugin-react-docgen as a dependency

---

packages/bpk-component-bottom-sheet/src/BpkBottomSheet.d.ts
packages/bpk-component-bottom-sheet/src/BpkBottomSheet.tsx

Following BpkModal precedent of allowing onClose function to receive information about the event that triggered it.
_Tested by locally adding logging to storybook examples and confirming the logging is triggered on closing the component._

[BpkBottomSheet] add event tracking option to close

---

.github/dependabot.yml

Dependabot seems to not update the `package.json` file for minor, patch bumps. Adjusting the `versioning-strategy` should resovle this.

[NoJira] - set versioning-strategy to update package.json as well in dependabot

---

CONTRIBUTING.md
dangerfile.ts
packages/bpk-component-boilerplate/src/BpkBoilerplate-test.tsx
packages/bpk-component-boilerplate/src/BpkBoilerplate.d.ts
packages/bpk-component-boilerplate/src/BpkBoilerplate.tsx
packages/bpk-component-boilerplate/src/__snapshots__/BpkBoilerplate-test.tsx.snap

Update boilerplate to remove className, update contribution and add danger check

---

packages/bpk-component-swap-button/README.md
packages/bpk-component-swap-button/src/BpkSwapButton-test.tsx
packages/bpk-component-swap-button/src/BpkSwapButton.tsx
packages/bpk-component-swap-button/src/__snapshots__/BpkSwapButton-test.tsx.snap
packages/bpk-component-swap-button/src/accessibility-test.tsx

[Luna 1092] - BpkSwapButton Fix Aria Props

---

examples/bpk-component-swap-button/examples.js
packages/bpk-component-swap-button/index.d.ts
packages/bpk-component-swap-button/index.ts
packages/bpk-component-swap-button/src/BpkSwapButton.d.ts

Updates the TS declaration files for exports to be reflective of current API, also exports `SWAPBUTTON_TYPES` so it can be used outside of the component for types

[BpkSwapButton]: Updating exported typescript declarations for docs and usage

---

packages/bpk-component-section-header/src/BpkSectionHeader.module.scss
packages/bpk-component-section-header/src/BpkSectionHeader.tsx
packages/bpk-component-section-header/src/__snapshots__/BpkSectionHeader-test.tsx.snap

[ARGG-1036] [BpkSectionHeader] Fix section header vertical padding

---

babel.config.js
package-lock.json
package.json
packages/bpk-component-breakpoint/index.ts
packages/bpk-component-breakpoint/src/BpkBreakpoint-test.tsx
packages/bpk-component-breakpoint/src/BpkBreakpoint.d.ts
packages/bpk-component-breakpoint/src/BpkBreakpoint.tsx
packages/bpk-component-breakpoint/src/__snapshots__/BpkBreakpoint-test.tsx.snap
packages/bpk-component-breakpoint/src/useMediaQuery-test.ts
packages/bpk-component-breakpoint/src/useMediaQuery.ts
packages/package-lock.json
packages/package.json

[ST-5579][BpkBreakpoint] Remove react-responsive

---

packages/bpk-component-breakpoint/src/useMediaQuery-test.tsx

This fixes the linting failure in main.

Fix linting

---

packages/bpk-component-skeleton/src/BpkBaseSkeleton-test.tsx
packages/bpk-component-skeleton/src/BpkBodyTextSkeleton-test.tsx
packages/bpk-component-skeleton/src/BpkCircleSkeleton-test.tsx
packages/bpk-component-skeleton/src/BpkHeadlineSkeleton-test.tsx
packages/bpk-component-skeleton/src/BpkImageSkeleton-test.tsx
packages/bpk-component-skeleton/src/accessibility-test.tsx
packages/bpk-component-skeleton/src/utils-test.ts

[MAT-1241] add test files

---

README.md
packages/bpk-component-skeleton/README.md

[MAT-1207] update readme file

---

packages/bpk-component-map/src/BpkPriceMarker.js
packages/bpk-component-map/src/__snapshots__/BpkPriceMarker-test.js.snap

**Class 2 Overrides:**
1. Move style override to wrapper.

LOOM-1298 BpkPriceMarker Class 2 Overrides

---

package-lock.json
package.json

Bump to SVGs. 
- Modified ai svg
- Added dot svg

[BDES-144]: update svgs to include modified ai logo & new dot logo

---

packages/bpk-component-theme-toggle/src/BpkThemeToggle.js
packages/bpk-component-theme-toggle/src/__snapshots__/BpkThemeToggle-test.js.snap

[LOOM-1318] [BpkThemeToggle] classname prop update

---

.stylelintrc.json
packages/bpk-component-banner-alert/src/__snapshots__/BpkBannerAlertDismissable-test.tsx.snap
packages/bpk-component-banner-alert/src/__snapshots__/BpkBannerAlertInner-test.tsx.snap
packages/bpk-component-banner-alert/src/__snapshots__/withBannerAlertState-test.tsx.snap
packages/bpk-component-bottom-sheet/src/__snapshots__/BpkBottomSheet-test.tsx.snap
packages/bpk-component-close-button/src/BpkCloseButton.js
packages/bpk-component-close-button/src/BpkCloseButton.module.scss
packages/bpk-component-close-button/src/__snapshots__/BpkCloseButton-test.js.snap
packages/bpk-component-dialog/src/__snapshots__/BpkDialog-test.tsx.snap
packages/bpk-component-drawer/src/__snapshots__/BpkDrawer-test.js.snap
packages/bpk-component-drawer/src/__snapshots__/BpkDrawerContent-test.js.snap
packages/bpk-component-info-banner/src/__snapshots__/BpkInfoBannerDismissable-test.tsx.snap
packages/bpk-component-info-banner/src/__snapshots__/BpkInfoBannerInner-test.tsx.snap
packages/bpk-component-info-banner/src/__snapshots__/withBannerAlertState-test.tsx.snap
packages/bpk-component-modal/src/BpkModalV2/__snapshots__/BpKModal-test.tsx.snap
packages/bpk-component-modal/src/__snapshots__/BpkModal-test.tsx.snap
packages/bpk-component-modal/src/__snapshots__/BpkModalInner-test.tsx.snap
packages/bpk-component-navigation-bar/src/BpkNavigationBarIconButton.tsx
packages/bpk-component-navigation-bar/src/__snapshots__/BpkNavigationBar-test.tsx.snap
packages/bpk-component-navigation-bar/src/__snapshots__/BpkNavigationBarIconButton-test.tsx.snap
packages/bpk-component-popover/src/__snapshots__/BpkPopover-test.js.snap
packages/bpk-component-theme-toggle/src/BpkThemeToggle.js
packages/bpk-component-theme-toggle/src/__snapshots__/BpkThemeToggle-test.js.snap

Update the BpkCloseButton to use correct colour and add onDark prop.

[LOOM-1318][BpkCloseButton] Update Style and add onDark prop

---

.eslintrc
packages/bpk-component-mobile-scroll-container/src/BpkMobileScrollContainer.js

[LOOM-1376][BpkMobileScrollContainer] Comment to declare the className as an accepted

---

.eslintrc
packages/bpk-component-slider/src/BpkSlider.tsx

[LOOM-1373][BpkSlider] Comment to declare the className as an accepted prop

---

.eslintrc
packages/bpk-component-modal/src/BpkModal.tsx
packages/bpk-component-slider/src/BpkSlider.tsx

[LOOM-1368][BpkModal] Comment to declare the className as an accepted prop

---

.eslintrc
packages/bpk-component-list/src/BpkList.js

**Class 2 Overrides**:
1. Conditional Ordered/Unordered list elements within <BpkList> added to classname allowed list.

LOOM-1367 BpkList Class 2 Overrides

---

packages/bpk-component-barchart/src/BpkBarchart-test.js
packages/bpk-component-barchart/src/BpkBarchart.js
packages/bpk-component-barchart/src/__snapshots__/BpkBarchart-test.js.snap

Reverts Skyscanner/backpack#3382 We need to pull out of making this breaking change at the moment.

Revert "[LOOM-1278][BpkBarChart] Class 2 Fix Remove unused classname prop"

---

.eslintrc
packages/bpk-component-calendar/src/BpkCalendarGridTransition.tsx
packages/bpk-component-calendar/src/BpkCalendarNav.tsx
packages/bpk-component-calendar/src/BpkCalendarWeek.tsx

[LOOM-1393][BpkCalendar] Accepted class 2 rules

---

examples/bpk-component-chip-group/examples.tsx
packages/bpk-component-chip-group/src/BpkChipGroup.module.scss
packages/bpk-component-chip-group/src/BpkChipGroup.tsx
packages/bpk-component-chip-group/src/BpkChipGroupSingleSelect.tsx

Collab sub-PR
Remove label padding after discussion with design - now crops at page margin

ChipGroup - Remove label padding

---

packages/bpk-component-chip-group/src/BpkChipGroup.d.ts

Collab sub-PR
Make typedef consistent with previous changes

ChipGroup Update typedefs for nudger labels

---

packages/bpk-component-nudger/src/BpkConfigurableNudger.tsx
packages/bpk-component-nudger/src/BpkNudger.module.scss
packages/bpk-component-nudger/src/__snapshots__/BpkNudger-test.tsx.snap

[LOOM-1305][BpkConfigurableNudger] Remove unused styling

---

gulpfile.js/bpk-component-icon/gulpfile.babel.js
package-lock.json
package.json

This change is designed to make it easier to adopt new `svg` icon changes.

[NOJIRA][chore]: ensure that icon dir is clean before copy

---

packages/bpk-component-pagination/src/BpkPaginationNudger.js
packages/bpk-component-pagination/src/BpkPaginationNudger.module.scss
packages/bpk-component-pagination/src/__snapshots__/BpkPaginationNudger-test.js.snap

[LOOM-1306][BpkPaginationNudget]: Remove customised padding values

---

packages/bpk-mixins/_forms.scss

Fixes style bug introduced in https://github.com/Skyscanner/backpack/pull/3403

[NoJira] fix the mixins vars

---

packages/bpk-component-scrollable-calendar/src/BpkScrollableCalendarGrid.module.scss
packages/bpk-component-scrollable-calendar/src/BpkScrollableCalendarGrid.tsx
packages/bpk-component-scrollable-calendar/src/__snapshots__/BpkScrollableCalendar-test.tsx.snap
packages/bpk-component-scrollable-calendar/src/__snapshots__/BpkScrollableCalendarGrid-test.tsx.snap
packages/bpk-component-scrollable-calendar/src/__snapshots__/BpkScrollableCalendarGridList-test.tsx.snap

[Loom-1311][BpkScrollableCalendar] Class2 style fix

---

examples/bpk-component-popover/examples.js
examples/bpk-component-popover/stories.js
packages/bpk-component-popover/README.md
packages/bpk-component-popover/src/BpkPopover-test.tsx
packages/bpk-component-popover/src/BpkPopover.module.scss
packages/bpk-component-popover/src/BpkPopover.tsx

[ARGG-1085][BpkPopover] Update popover design

---

examples/bpk-component-modal-v2/examples.tsx
examples/bpk-component-modal-v2/stories.tsx

[maintainence][BpkModalV2] Add Visual Snapshots

---

packages/bpk-component-pagination/src/BpkPaginationPage.js
packages/bpk-component-pagination/src/BpkPaginationPage.module.scss

[LOOM-1370][BpkPaginationPage] Replace BpkButton in BpkPaginationPage

---

.eslintrc
packages/bpk-component-icon/src/classNameModifierHOCFactory.tsx

[LOOM-1375][BpkIcon] eslint Override for ComposedComponent in BpkIcon

---

package-lock.json
package.json

Testing Reverts Skyscanner/backpack#3437

Revert "Bump css-loader from 6.10.0 to 7.1.1"

---

packages/bpk-component-drawer/README.md

Class based components aren't the recommended way to build components anymore

Updates the BpkDrawer component README to useState

---

examples/bpk-component-slider/stories.js

A change to the base library has also brought about a change to the way minDistance works which we recently discovered in prod. Updating our docs to make this relationship clear.
https://github.com/radix-ui/primitives/blob/main/packages/react/slider/src/Slider.tsx#L133

NO-JIRA: BpkSlider docs- add note on min distance

---

packages/bpk-component-price/src/BpkPrice.module.scss

Updates the previousPrice colour to be Red instead of the regular black colour. The only place this is used is with the folks that are requesting this colour change so the impact to consumer in minor.

[BDES-163][BpkPrice]: Update BpkPrice previousPrice colour

---

examples/bpk-component-segmented-control/examples.tsx
examples/bpk-component-segmented-control/stories.tsx

Updates `visual-tests` to include all variants
Adds `complex-contast` examples for use on the Backpack docs site

[NO JIRA]: Update Segmented control examples as per design request and docs

---

packages/bpk-component-map/src/BpkIconMarker.module.scss

[BD-7461][BpkIconMarker] Make the icon to support RTL

---

packages/bpk-component-segmented-control/src/BpkSegmentedControl.module.scss

**Before**
https://github.com/user-attachments/assets/c11ad7ab-0a07-4044-88bf-a72493cfc8da
**After**
https://github.com/user-attachments/assets/ef13c175-2b6a-4dcc-8ede-3b43a574c186

[LUNA-1675]: [BpkSegmentedControls] fixes focus styling

---

packages/bpk-component-image/src/BpkImage.module.scss

There is a design requirement to move the BpkImage border radius to be 12px instead of 8px. This change got raised as part of the #3531 where it was found that the current BpkImage design is not aligned to the Figma component version.
So this PR changes this to align to Figma and be able to support the BpkSnippet contribution. This has been signed off by design as needing to be done!

[NO JIRA][BpkImage]: Update image radius to 12px

---

packages/bpk-component-floating-notification/src/BpkFloatingNotification.module.scss

[LUNA-1725][BpkFloatingNotification] Fixing FloatingNotification to viewport

---

packages/package-lock.json
packages/package.json

This PR corrects the semver range for the react dependencies. As it turns out `^x.x.x - x.x.x` is not correct syntax for the range and we need to drop the `^` when using a `-` range 
More detail here: https://semver.npmjs.com/#syntax-examples
Without it it causes the following errors on install: 
```
While resolving: <dependency-name-here>@0.0.0
Found: react@18.3.1
node_modules/react
dev react@"18.3.1" from the root project
Could not resolve dependency:
peer react@"^17.0.2 - 18.3.1" from @skyscanner/backpack-web@35.0.0
node_modules/@skyscanner/backpack-web
dev @skyscanner/backpack-web@"^35.0.0" from the root project
```

[NO JIRA]: Correct React semver range

---

packages/bpk-component-card-button/src/BpkSaveButton.tsx

We want to add two props which MBD event needs for [hotel saving button](https://skyscanner.atlassian.net/browse/BD-8797), but `BpkSaveButton` doesn't support extension props, so adjust it to support extension props.

[BD-8797][BpkSaveButton]Update it to support extension props

---

examples/bpk-component-card-list/examples.tsx
examples/bpk-component-card-list/stories.js
examples/bpk-component-card-list/stories.ts
packages/bpk-component-card-list/README.md
packages/bpk-component-card-list/index.ts
packages/bpk-component-card-list/src/BpkCardList-test.tsx
packages/bpk-component-card-list/src/BpkCardList.module.scss
packages/bpk-component-card-list/src/BpkCardList.tsx
packages/bpk-component-card-list/src/accessibility-test.tsx
packages/bpk-component-card-list/src/common-types.ts

[BDES-96] [BpkCardList] Base Component

---

packages/bpk-component-ticket/README.md
packages/bpk-component-ticket/src/BpkTicket.js

Deprecate BpkTicket - the JSDoc will make its usage look like this:

[NoJira][BpkTicket] Deprecate BpkTicket component

---

packages/bpk-component-segmented-control/src/BpkSegmentedControl.module.scss

https://github.com/user-attachments/assets/111fcca9-49d5-4914-b73c-83823af8dfe3
As part of the guidance around [focus](https://www.skyscanner.design/latest/foundations/focus-indicator-hluOwQ8H)  we should omit the focus indicator in this instance.

[WEAV-2560][BpkSegmentedControl] Focus Border fix

---

examples/bpk-component-card/examples.js
packages/bpk-component-card/src/BpkDividedCard.module.scss

Reverts Skyscanner/backpack#3659
Re-attempt of https://github.com/Skyscanner/backpack/pull/3658 by @toveadamsson after accidental release of this breaking change in minor release

[CAPY-909][BpkDividedCard] Remove min width & height on BpkDividedCard - Redo

---

.eslintignore
.gitignore
gulpfile.js/bpk-component-spinner/gulpfile.babel.js
gulpfile.js/bpk-component-spinner/gulpfile.js
gulpfile.js/index.js
packages/bpk-component-spinner/src/BpkExtraLargeSpinner.tsx
packages/bpk-component-spinner/src/BpkLargeSpinner.tsx
packages/bpk-component-spinner/src/BpkSpinner.tsx
packages/bpk-component-spinner/src/themeAttributes-test.tsx

[NO JIRA]: Fix Spinner removing aria-hidden from element

---

packages/bpk-component-price/src/BpkPrice.module.scss

Fixes the layout of the leading text of the BpkPrice component. It was incorrectly laid out where when right aligned the previous price was swapped with the subtext, as if it was RTL instead of just right aligned.
| -- | -- |
| ![Screenshot 2024-11-22 at 16 30 13](https://github.com/user-attachments/assets/ea01e008-48f9-41e1-a4c2-9eb8277c198d) | ![Screenshot 2024-11-22 at 16 30 52](https://github.com/user-attachments/assets/9dd6d6b8-7350-4c54-8e3f-ad6a8ce35e69) |

[LOOM-1942][BpkPrice]: Fix right aligned price layout

---

package-lock.json
package.json
packages/package-lock.json
packages/package.json

Upgrading `bpk-svgs` to the latest version. The version bump is to v20 but this is being marked as lower than a major version release for Backpack as the major change only affects apps in terms of the change so change is not impacting Web

[NO JIRA][maintenance]: Bump bpk-svgs to latest for up to date icons

---

package-lock.json
package.json
packages/bpk-mixins/_forms.scss
packages/package-lock.json
packages/package.json

- Updates `@skyscanner/bpk-foundations-web` to the latest version
- Updates large form elements to use the large border radius tokens

[LOOM-2014]: Update form element corner radii

---

packages/bpk-component-popover/src/BpkPopover.tsx

The BpkPopover have use the `rest` parameter in [here](https://github.com/Skyscanner/backpack/blob/07c7ac24ea17e6b9f9bce817e81befdd7851a391/packages/bpk-component-popover/src/BpkPopover.tsx#L136), so the `rest` parameter should also be add in the props type

[Nojira] Support the rest type for BpkPopover

---

packages/package-lock.json
packages/package.json

[NoJira] [BpkSlider] Update the radix deps

---

.github/workflows/_build.yml
.github/workflows/label-check.yml
.github/workflows/main.yml
.github/workflows/pr.yml
.github/workflows/release.yml

Applying the same changes as https://github.com/Skyscanner/backpack-android/pull/2195 provided by Catalyst to use the Github App for CI

SDPLAT-26630: use GH_APP in workflows

---

package-lock.json
package.json
packages/package-lock.json
packages/package.json

[THES-687] update bpk-svgs version

---

.github/pull_request_template.md
CONTRIBUTING.md

[NO-JIRA]Update support team

---

.eslintignore
.prettierignore
examples/bpk-component-icon/examples.js
examples/bpk-component-icon/stories.js
package-lock.json
package.json
packages/bpk-component-icon/all.tsx
packages/package-lock.json
packages/package.json

In this PR there are 3 things updated:
1. Bump bpk-svgs from 20.1.1 to 20.4.1 so as to include extra large icons
2. Bump bpk-foundation-web from 19.3.0 to 19.4.1 so as to include the size variable for extra large icons
3. Add new storybook examples for extra large icons:

[No Jira][BpkIcon]Bump bpk-svgs from 20.1.1 to 20.4.1 & bump bpk-foundations-web from 19.3.0 to 19.4.1

---

packages/bpk-mixins/_typography.scss

[NoJira][BpkLink] Remove wrong tokens use.

---

packages/bpk-mixins/_typography.scss

Remove the unintended underline when bpklink-implicit is clicked.

[NoJira][BpkLink] Remove the underline when bpklink-implicit is clicked.

---

examples/bpk-component-link/examples.js
examples/bpk-component-link/stories.js
packages/bpk-component-breadcrumb/src/__snapshots__/BpkBreadcrumbItem-test.js.snap
packages/bpk-component-grid-toggle/src/__snapshots__/BpkGridToggle-test.js.snap
packages/bpk-component-link/src/BpkButtonLink.js
packages/bpk-component-link/src/BpkLink.js
packages/bpk-component-link/src/BpkLink.module.scss
packages/bpk-component-link/src/__snapshots__/BpkButtonLink-test.js.snap
packages/bpk-component-link/src/__snapshots__/BpkLink-test.js.snap
packages/bpk-component-modal/src/__snapshots__/BpkModalInner-test.tsx.snap
packages/bpk-component-navigation-bar/src/__snapshots__/BpkNavigationBarButtonLink-test.tsx.snap
packages/bpk-component-rtl-toggle/src/__snapshots__/BpkRtlToggle-test.tsx.snap
packages/bpk-mixins/_typography.scss

Reimplement bpklink using gradient background instead of `::after`.
https://www.figma.com/design/OplP0YPdKEpf3zsyztsW7j/Bpk-Inline-Link?node-id=933-5618&p=f&t=jtDebc5xDIMYoigl-0

[BpkLink] Reimplement bpklink using gradient background.

---

packages/bpk-mixins/_typography.scss

[NoJira][BpkLink] change underline offset to 1px

---

packages/bpk-component-tooltip/src/BpkTooltip.tsx

Fix the arrow alignment of tooltip
|before|after|
|---|---|
|  <img src='https://github.com/user-attachments/assets/21e06637-3cd6-4ac3-9b59-d865f73e498e' width=300 >| <img src='https://github.com/user-attachments/assets/a3705fa9-5010-4d13-97ee-3c033bf4d4be' width=300 >|

[CLOV-230][BpkTooltip]Fix arrow alignment

---

packages/bpk-component-mobile-scroll-container/src/BpkMobileScrollContainer-test.tsx
packages/bpk-component-mobile-scroll-container/src/BpkMobileScrollContainer.tsx

We got a feedback that people can not listen to the scroll event when using the `BpkMobileScrollContainer`, so it would be better to add an optional parameter `onScroll` to handle that https://skyscanner.slack.com/archives/C0JHPDSSU/p1747148463500709

[NOJIRA][BpkMobileScrollContainer]expose onScroll

---

examples/bpk-component-icon/examples.js
examples/bpk-component-icon/stories.js

The stars with xxxl design should be inside a group named 'Triple Extra Large'
**Related Slack Discussion:** https://skyscanner.slack.com/archives/CUQ587E5D/p1747818123032859?thread_ts=1747644162.037239&cid=CUQ587E5D

[NO JIRA]Tribble ExtraLarge Rename

---

package-lock.json
package.json

This PR is to fix a known security vulnerability in the braces package, which was introduced via transitive dependencies (e.g. through micromatch used by ts-migrate). [Issue](https://github.com/Skyscanner/backpack/security/dependabot/360)
Vulnerability: Uncontrolled resource consumption 
Affected package: braces < 3.0.3
Patched version: braces@^3.0.3
This fix is temporary until [ts-migrate](https://github.com/airbnb/ts-migrate) upgrade their own dependencies
Before:
After:

[Clover-199]Fix the vulnerability alert: Uncontrolled resource consumption in braces 

---

package-lock.json
package.json
packages/package-lock.json
packages/package.json

[Clov-362]Update bpk-svg new version

---

packages/bpk-component-card-list/README.md
packages/bpk-component-card-list/src/BpkCardListRowRail/BpkCardListCarousel.tsx
packages/bpk-component-card-list/src/BpkCardListRowRail/utils.tsx

[NO JIRA][BpkCardList]Add Comments and modify README

---

examples/bpk-component-card-list/examples.tsx
packages/bpk-component-card-list/src/BpkCardList.tsx
packages/bpk-component-card-list/src/BpkCardListRowRail/BpkCardListCarousel.tsx
packages/bpk-component-card-list/src/BpkCardListRowRail/BpkCardListRowRailContainer.tsx
packages/bpk-component-card-list/src/common-types.ts

Fix an A11y issue, remove hardcoded aria-label: https://skyscanner.slack.com/archives/C04FCMBSZLK/p1750931849361789

[NO JIRA][BpkCardList]Fix A11y translation issues

---

.storybook/main.ts
package-lock.json
package.json

As requested by design adding the [storybook essentials addon](https://storybook.js.org/docs/8/essentials)
Which includes some useful features when both developing and design reviewing. Particularly the measure feature which allows for checking of spacing between elements

Add storybook essentials addon for extra useful features

---

.nvmrc
package-lock.json
package.json

[maintainence] upgrade node to 22.x

---

examples/bpk-component-popover/examples.js
examples/bpk-component-popover/stories.js
packages/bpk-component-popover/src/BpkPopover-test.tsx
packages/bpk-component-popover/src/BpkPopover.module.scss
packages/bpk-component-popover/src/BpkPopover.tsx

Reverts Skyscanner/backpack#3883

Revert "[BD-9759][BpkPopover] Add close button beside body"

---

packages/bpk-animate-height/src/AnimateHeight.js

Using `UNSAFE_componentWillReceiveProps` in strict mode is not recommended and may indicate bugs in your code. See https://reactjs.org/link/unsafe-component-lifecycles for details.
Remove UNSAFE_componentWillReceiveProps usage

[CLOVER-701][AnimateHeight] Remove UNSAFE_componentWillReceiveProps usage

---

packages/bpk-component-skip-link/src/BpkSkipLink.js
packages/bpk-theming/src/BpkThemeProvider.js

[WOODPECKER-3717][BpkSkipLink][BpkThemeProvider]remove defaultProps

---

packages/bpk-component-card/src/BpkCard.figma.tsx
packages/bpk-component-card/src/BpkCardWrapper.figma.tsx
packages/bpk-component-card/src/BpkDividedCard.figma.tsx

This pull request introduces a new integration file to connect the `BpkCard ` component with Figma using Code Connect. This enables designers and developers to preview and configure the component directly in Figma with mapped props.
Figma integration:
* Added a new file `BpkCard.figma.tsx` and `BpkCardWrapper.figma.tsx`  that connects the `BpkHorizontalNav` and `BpkDividedCard` component to Figma using the Code Connect API, mapping component props to Figma controls and providing a usage example for visualisation.

[BpkCard][CLOV-723] Code connect to Figma
