- .travis.yml
We need to enable builds triggered by both pushes and
pull request events. This should reduce the duplication
of pull request builds while still building merges and
direct pushes to master.
See: https://stackoverflow.com/questions/31882306/how-to-configure-travis-ci-to-build-pull-requests-merges-to-master-w-o-redunda
> [BPK-551] Reduce number of travis builds

- changelog.md
- npm-shrinkwrap.json
- package.json
- packages/bpk-tokens/tokens/b2b-widgets.android.xml
- packages/bpk-tokens/tokens/base.android.xml
- packages/bpk-tokens/tokens/base.ios.json
- packages/bpk-tokens/tokens/base.raw.json
- packages/bpk-tokens/tokens/breakpoints.ios.json
- packages/bpk-tokens/tokens/breakpoints.raw.json
- packages/bpk-tokens/tokens/travelpro.android.xml
- packages/bpk-tokens/tokens/travelpro.ios.json
- packages/bpk-tokens/tokens/travelpro.raw.json
Breaking changes from `theo@^4.0.0` => `theo@^5.0.0`:
- Breaking change: removed the color/hex8 transform. Instead, use color/hex8argb in Android, and color/hex8rgba in, for example, CSS level 4 values
- Breaking change: Node.js 6 and up is required
- Dropped support for Node.js v4
- Theo v5 is now compatible with Node.js v6.3 and up, dropping support for Node.js v4.
- Pointing to a non-existing alias now throws an error instead of failing silently.
- Lodash's implementation of kebabCase was dropped because it separated numbers as words:
-- Lodash: A1 -> a-1
-- Theo: A1 -> a1
(See https://github.com/salesforce-ux/theo/blob/master/CHANGELOG.md).
> [WIP] [BPK-558] Upgrade theo

- packages/bpk-docs/src/components/Heading/Heading.js
- packages/bpk-docs/src/components/Heading/Heading.scss
BpkBreakpoint uses `window.matchMedia` based mechanism to render "media queries" declaratively. We use SSR on the docs site an thus we need to media queries to work on first paint.
> [BPK-817] Opt for css media queries over BpkBreakpoint

- .storybook/webpack.config.js
- packages/bpk-stylesheets/webpack.config.babel.js
- scripts/webpack/postCssPlugins.js
- webpack.config.babel.js
Configs exist for docs site, storybook and base stylesheet.
Removed the `*.css` loader in the storybook config as this appears unused.
> [BPK-784] Align postcss config across webpack configs

- changelog.md
- packages/bpk-component-banner-alert/readme.md
- packages/bpk-component-banner-alert/src/BpkBannerAlert-test.js
- packages/bpk-component-banner-alert/src/BpkBannerAlert.js
- packages/bpk-component-banner-alert/src/__snapshots__/BpkBannerAlert-test.js.snap
> [No Jira] Allow custom className and other arbitrary props for bpk-component-banner-alert

- packages/bpk-component-blockquote/readme.md
- packages/bpk-component-blockquote/src/BpkBlockquote-test.js
- packages/bpk-component-blockquote/src/BpkBlockquote.js
- packages/bpk-component-blockquote/src/__snapshots__/BpkBlockquote-test.js.snap
- packages/bpk-component-blockquote/src/bpk-blockquote.scss
- packages/bpk-component-blockquote/stories.js
- packages/bpk-docs/src/pages/BaseStylesheetPage/BaseStylesheetPage.js
- packages/bpk-docs/src/pages/GettingStartedPage/GettingStartedPage.js
- packages/bpk-docs/src/pages/LayoutPage/LayoutPage.js
- packages/bpk-docs/src/pages/TypographyPage/TypographyPage.js
- packages/bpk-mixins/src/mixins/_typography.scss
> [BPK-788] Updated block-quote scss to match Jon Hicks' design

- changelog.md
- packages/bpk-component-table/src/BpkTableRow-test.js
- packages/bpk-component-table/src/BpkTableRow.js
- packages/bpk-component-table/src/__snapshots__/BpkTableRow-test.js.snap
+ [X] For any new components I've made sure that the style can be extended by the consumer using a `className` override.
+ [X] For any new files I've included the [Apache 2.0 License header](https://github.com/Skyscanner/backpack/blob/master/packages/bpk-tokens/formatters/license-header.js#L2-L16) at the top of the file.
+ [X] I've updated `changelog.md` for any changes that need to be highlighted in the changelog.
+ [X] If I've updated `npm-shrinkwrap.json` those changes are intentional.
> Ability to pass custom props to BpkTableRow component

- changelog.md
- npm-shrinkwrap.json
- package.json
- packages/bpk-component-accordion/src/withAccordionItemState.js
- packages/bpk-component-accordion/src/withSingleItemAccordionState.js
- packages/bpk-component-barchart/hocs.js
- packages/bpk-component-icon/src/__snapshots__/withAlignment-test.js.snap
- packages/bpk-component-icon/src/classNameModifierHOCFactory.js
- packages/bpk-component-icon/src/withAlignment-test.js
- packages/bpk-component-icon/src/withAlignment.js
- packages/bpk-component-input/src/withOpenEvents.js
- packages/bpk-component-rtl-toggle/src/updateOnDirectionChange.js
- packages/bpk-component-star-rating/src/withInteractiveStarRatingState.js
- packages/bpk-react-utils/src/withDefaultProps.js
- Set the displayName of the `withAlignment` HOC to "withAlignment". This still breaks from the old `withLargeButtonAlignment` etc., but I think it's the correct thing to do since we've overhauled these HOCs.
- Added **recompose** and used the `wrapDisplayName` function across the board
> [BPK-863] Set displayName of alignment HOC

- npm-shrinkwrap.json
- package.json
- packages/bpk-component-accordion/src/withAccordionItemState.js
- packages/bpk-component-accordion/src/withSingleItemAccordionState.js
- packages/bpk-component-barchart/hocs.js
- packages/bpk-component-icon/src/classNameModifierHOCFactory.js
- packages/bpk-component-icon/src/withAlignment.js
- packages/bpk-component-input/src/withOpenEvents.js
- packages/bpk-component-rtl-toggle/package.json
- packages/bpk-component-rtl-toggle/src/updateOnDirectionChange.js
- packages/bpk-component-star-rating/src/withInteractiveStarRatingState.js
- packages/bpk-react-utils/index.js
- packages/bpk-react-utils/package.json
> [No jira] Expose recompose's wrapDisplayName in bpk-react-utils

- changelog.md
- packages/bpk-component-button/src/BpkButton.js
Came across this while trying to stop event propagation. The `...arguments` parameter is actually that of the `BpkButton` class rather the function, so the onClick handler being passed was receiving garbage. This fixes it. Not sure the best method of testing it, I wasn't able to import a SyntheticEvent from react to assert the type. Open to suggestions.
+ [x] If I've updated …
> pass correct arguments to onClick in BpkButton

- packages/bpk-component-image/readme.md
- packages/bpk-component-image/src/BpkBackgroundImage.js
- packages/bpk-component-image/src/BpkImage.js
- packages/bpk-component-image/src/__snapshots__/BpkImage-test.js.snap
- packages/bpk-component-image/src/withLazyLoading.js
- packages/bpk-docs/src/pages/ImagesPage/ImagesPage.js
- packages/bpk-mixins/src/mixins/_images.scss
> [BPK-231] Fix for lazy loading with SSR

- packages/bpk-component-image/src/BpkImage.js
> [BPK-231] Fix for lazy loading with SSR 2

- packages/bpk-component-image/src/BpkImage.js
- packages/bpk-component-image/src/__snapshots__/BpkImage-test.js.snap
> [BPK-231] Fix for lazy loading with SSR 3

- packages/bpk-component-calendar/readme.md
- packages/bpk-component-datepicker/readme.md
~The order of the `daysOfWeek` array matters, Sunday should be at index 0 - our docs suggested otherwise.~
**Update:** The order of the `daysOfWeek` *does not* matter, however Sunday should have and `index` prop value of 0 - our docs confuse things by showing monday at index zero in the array. This change makes it clearer.
+ [x] If I've updated `npm-shrinkwrap.json` those …
> [NOJIRA] Fix daysOfWeek example

- changelog.md
- packages/bpk-component-image/package.json
- packages/bpk-component-image/src/BpkImage.js
- packages/bpk-component-image/src/__snapshots__/BpkImage-test.js.snap
- packages/bpk-component-image/src/bpk-image.scss
- packages/bpk-component-image/src/withLazyLoading-test.js
- packages/bpk-component-image/src/withLazyLoading.js
- packages/bpk-component-image/stories.js
- packages/bpk-mixins/src/mixins/_images.scss
> [BPK-908] Fix lazy loading HOC not responding to div scroll events

- packages/bpk-docs/src/pages/NativeButtonPage/NativeButtonPage.js
- packages/bpk-docs/src/pages/NativeTextInputPage/NativeTextInputPage.js
- packages/bpk-docs/src/pages/NativeTextPage/NativeTextPage.js
> [skip-ci] [no-jira] Rename iPhone 7 to 8 in screenshot captions

- contributing.md
> [skip ci] [no-jira] Added missing link to APLv2 licence

- packages/bpk-docs/src/constants/routes.js
- packages/bpk-docs/src/layouts/DocsLayout/DocsLayout.js
- packages/bpk-docs/src/pages/BreakpointsPage/BreakpointsPage.js
- packages/bpk-docs/src/pages/BreakpointsPage/breakpoints-page.scss
- packages/bpk-docs/src/pages/BreakpointsPage/index.js
- packages/bpk-docs/src/pages/HorizontalGridPage/HorizontalGridPage.js
- packages/bpk-docs/src/pages/HorizontalGridPage/index.js
- packages/bpk-docs/src/pages/LayoutPage/LayoutPage.js
- packages/bpk-docs/src/routes/Routes.js
> [BPK-906] Separate layout docs into 3 pages

- .github/PULL_REQUEST_TEMPLATE.md
> [NOJIRA] Make sure RN styles can be extended in userland

- contributing.md
@k0nserv I merged the previous PR around this before I saw your comment about using a relative link - this fixes that.
> [skip ci] Licence link now points to one in repo

- packages/bpk-docs/src/components/Header/Header.js
- packages/bpk-docs/src/constants/redirect-routes.js
- packages/bpk-docs/src/constants/routes.js
- packages/bpk-docs/src/layouts/DocsLayout/DocsLayout.js
- packages/bpk-docs/src/layouts/TokensLayout/TokensLayout.js
- packages/bpk-docs/src/layouts/TokensLayout/index.js
- packages/bpk-docs/src/routes/Routes.js
This is the first PR for moving the tokens pages to their own section. I will follow up with the restructure of the actual pages themselves in separate PR's
> [BPK-903] Move bonds to tokens section

- .travis.yml
- dangerfile.js
Danger will now run at the beginning of a build, before tests run.
If a package source files have changed but snapshots haven't, Danger
will post a warning.
> [BPK-966] Make Dangerfile more opinionated

- changelog.md
- package.json
- packages/bpk-tokens/index.js
- packages/bpk-tokens/package.json
- packages/bpk-tokens/readme.md
- packages/bpk-tokens/src/setOpacity-test.js
- packages/bpk-tokens/src/setOpacity.js
> [BPK-925] Add API for setting opacity of colour tokens

- native/packages/react-native-bpk-component-button/src/BpkButton.js
- native/packages/react-native-bpk-component-button/src/__snapshots__/BpkButton-test.android.js.snap
- native/packages/react-native-bpk-component-button/src/__snapshots__/BpkButton-test.ios.js.snap
- native/packages/react-native-bpk-component-button/stories.js
Previously it used a strange object format, now it behaves normally.
> [BPK-967] Make BpkButton work properly with user styles

- changelog.md
- packages/bpk-component-ticket/readme.md
- packages/bpk-component-ticket/src/BpkTicket-test.js
- packages/bpk-component-ticket/src/BpkTicket.js
- packages/bpk-component-ticket/src/__snapshots__/BpkTicket-test.js.snap
> Allow bpk ticket stub to take custom props

- native/.gitignore
- native/package.json
- native/packages/react-native-bpk-component-button/src/BpkButton-test.common.js
- native/packages/react-native-bpk-component-button/src/__snapshots__/BpkButton-test.android.js.snap
- native/packages/react-native-bpk-component-button/src/__snapshots__/BpkButton-test.ios.js.snap
- native/packages/react-native-bpk-component-card/src/BpkCard-test.common.js
- native/packages/react-native-bpk-component-text/src/BpkText-test.common.js
This brings the code coverage flag in and I've improved the coverage to 100% on RN components, the super annoying thing is: when testing errors, those are going to …
> Rn code coverage

- dangerfile.js
- Fixes grammatical error.
- Standardises by using String.includes everywhere.
- Check for unlicensed files excludes ones in a dist folder.
> [no jira] Further enhance Dangerfile

- changelog.md
- packages/bpk-docs/src/components/DocsPageBuilder/TokenSwitcher.js
- packages/bpk-docs/src/helpers/tokens-helper.js
- packages/bpk-docs/src/helpers/tokens.helper-test.js
- packages/bpk-tokens/src/android/base/typography.json
- packages/bpk-tokens/src/ios/base/typography.json
- packages/bpk-tokens/src/web/base/typography.json
- packages/bpk-tokens/tokens/android/base.android.xml
- packages/bpk-tokens/tokens/android/base.raw.json
- packages/bpk-tokens/tokens/base.raw.json
- packages/bpk-tokens/tokens/ios/base.ios.json
- packages/bpk-tokens/tokens/ios/base.raw.json
We now rely on token meta data to apply correct formatting on the docs site. This requires that the token `type` is actually correct. Some were not, so i fixed them.
+ [ ] For any new web components I've made sure that the style can be extended by the consumer using a `className` override.
+ [ ] For any new native components I've made sure that the style can be extended by the consumer using a `style` override.
> [BPK-903] Add correct unit formatting

- native/package.json
- native/packages/react-native-bpk-component-button/package.json
- native/packages/react-native-bpk-component-card/package.json
- native/packages/react-native-bpk-component-text-input/package.json
I noticed that our `native/package.json` had extraneous dependencies (which are otherwise provided by our top level `package.json`). So i removed them.
I also noticed that `bpk-tokens` was a a few major versions behind in some of the native components - perhaps leading to some of the token issues we've been having.
> [BPK-970] Tidy up native dependencies

- changelog.md
- native/packages/react-native-bpk-component-button/src/BpkButton-styles.js
- native/packages/react-native-bpk-component-text-input/src/BpkTextInput.js
- packages/bpk-tokens/src/android/base.json
- packages/bpk-tokens/src/android/base/aliases.json
- packages/bpk-tokens/src/android/base/borders.json
- packages/bpk-tokens/src/ios/base.json
- packages/bpk-tokens/src/ios/base/aliases.json
- packages/bpk-tokens/src/ios/base/borders.json
- packages/bpk-tokens/tokens/android/base.android.xml
- packages/bpk-tokens/tokens/android/base.raw.json
- packages/bpk-tokens/tokens/android/base.react.native.common.js
- packages/bpk-tokens/tokens/android/base.react.native.es6.js
- packages/bpk-tokens/tokens/ios/base.ios.json
- packages/bpk-tokens/tokens/ios/base.raw.json
- packages/bpk-tokens/tokens/ios/base.react.native.common.js
- packages/bpk-tokens/tokens/ios/base.react.native.es6.js
Added `BORDER_SIZE_SM`, `BORDER_SIZE_LG` & `BORDER_SIZE_XL` tokens and consumed them in places where `borderWidth` was set to a hard coded value (only two places, button and text input).
The names are important here - they match web and therefore show up on the docs page.
> [BPK-937] Add ios & android border tokens

- changelog.md
- native/package.json
- native/packages/react-native-bpk-component-button/src/BpkButton-styles.js
- native/packages/react-native-bpk-component-button/src/BpkButton-test.common.js
- native/packages/react-native-bpk-theming/src/BpkThemeProvider-test.common.js
- packages/bpk-tokens/package.json
- packages/bpk-tokens/src/ios/base.json
- packages/bpk-tokens/src/ios/base/touchables.json
- packages/bpk-tokens/src/react-native-output-test.js
- packages/bpk-tokens/tokens/ios/base.ios.json
- packages/bpk-tokens/tokens/ios/base.raw.json
- packages/bpk-tokens/tokens/ios/base.react.native.common.js
- packages/bpk-tokens/tokens/ios/base.react.native.es6.js
Added iOS only `UNDERLAY_COLOR` & `UNDERLAY_OPACITY` tokens and consumed them in the button component.
> Bpk 937 touchable highlight

- changelog.md
- native/packages/react-native-bpk-component-button/src/BpkButton-styles.js
- native/packages/react-native-bpk-component-button/src/BpkButton-test.common.js
- native/packages/react-native-bpk-component-button/src/BpkButton.js
- native/packages/react-native-bpk-component-button/src/__snapshots__/BpkButton-test.android.js.snap
- native/packages/react-native-bpk-component-button/src/__snapshots__/BpkButton-test.ios.js.snap
- native/packages/react-native-bpk-component-button/stories.js
In addition to secondary theming, this PR also includes better propTypes validation, so that a warning will be printed if:
a) The user is trying to theme an unthemeable button type
b) The user hasn't included all the necessary theme attributes for the type of button they're trying to theme.
> [BPK-1019] Add theming support for secondary button

- native/packages/react-native-bpk-component-button/readme.md
- native/packages/react-native-bpk-theming/readme.md
- packages/bpk-docs/package.json
- packages/bpk-docs/src/constants/routes.js
- packages/bpk-docs/src/layouts/DocsLayout/DocsLayout.js
- packages/bpk-docs/src/pages/NativeButtonPage/NativeButtonPage.js
- packages/bpk-docs/src/pages/ThemingPage/ThemingPage.js
- packages/bpk-docs/src/pages/ThemingPage/index.js
- packages/bpk-docs/src/routes/Routes.js
Adds theming info to native button, as well as a new theming page to the sidebar.
New page:
Button page:
> [BPK-954] Add theming documentation

- native/packages/react-native-bpk-theming/package-lock.json
- native/packages/react-native-bpk-theming/package.json
- native/packages/react-native-bpk-theming/stories.js
Previously the example used `BpkThemeableText`, which is something that was created especially for the storybook. Now that buttons are themeable, I've changed the storybook to use that instead.
I also changed the green example to yellow, as our standard button is green and the difference wasn't so apparent.
> [no jira] Change theme story to use BpkButton

- changelog.md
- packages/bpk-react-utils/package-lock.json
- packages/bpk-react-utils/package.json
This is so it'll work with React 16.x.
I'm not certain of what needed to be done here, so here's a summary of what I did:
- Searched for all `package.json` files that mention recompose. The only result was `bpk-react-utils'.
- Upgraded from 0.24.x to 0.26.x in `bpk-react-utils`.
- `npm run clean`
- `npm install`
- `npm run build`
- `npm test`
> [BPK-999] Upgrade recompose to 0.26.x

- changelog.md
- packages/bpk-component-badge/readme.md
- packages/bpk-component-list/readme.md
- packages/bpk-component-list/src/BpkList-test.js
- packages/bpk-component-list/src/BpkList.js
- packages/bpk-component-list/src/BpkListItem-test.js
- packages/bpk-component-list/src/BpkListItem.js
- packages/bpk-component-list/src/__snapshots__/BpkList-test.js.snap
- packages/bpk-component-list/src/__snapshots__/BpkListItem-test.js.snap
Prop contains same functionality as it does elsewhere, using BpkText as an example of how to implement. Has no effect on tests. Has been linted.
Pull Request also contains update to the docs for List and Badge to include className prop, since I noticed it was missing from Badge last week.
> [EXPS-614]: Add className prop to BpkList and BpkListItem

- changelog.md
- packages/bpk-component-breakpoint/package-lock.json
- packages/bpk-component-breakpoint/package.json
the browser warning above was fixed in the latest version of react-responsive. https://github.com/contra/react-responsive/commit/49919d09b7a4e984873b570132ada5554300f071
> Fixed propType warning by updating react-responsive to the latest version

- changelog.md
- packages/bpk-component-horizontal-nav/src/bpk-horizontal-nav-item.scss
For BpkHorizontalNavItem we weren't explicitlly setting the border
radius to 0. In Chrome 62 changes to the default button style was
leaking through and causing visual glitches due to this.
> [No JIRA] Remove border-radius for nav items

- .eslintrc
- package-lock.json
- package.json
Upgrade `eslint-config-skyscanner` and remove rule opt-outs as they're in there now.
> [BPK-964] Upgrade eslint-config-skyscanner

- changelog.md
- packages/bpk-component-calendar/src/bpk-calendar-grid.scss
Weekend separator line is not showing in calendar for Internet Explorer and Edge due to `border-collapse: collapse` CSS rule preventing `box-shadow` from working.
This is how it looks currently:
> [BPK-1096] Show weekend separator in IE and Edge.

- changelog.md
- packages/bpk-component-input/src/BpkInput-test.js
- packages/bpk-component-input/src/BpkInput.js
When using the component `BpkInput`, I would want to have access to the underlying `input` DOM node so that I can manage things like `focus` from a parent component.
The recommended way to do so in the React docs is by exposing a prop and attach it to the DOM node as a `ref` attribute: https://reactjs.org/docs/refs-and-the-dom.html#exposing-dom-refs-to-parent-components
> Exposing BpkInput underlying DOM node ref to parent components

- .eslintrc
- changelog.md
- native/packages/react-native-bpk-component-card/src/BpkCard-test.android.js
- native/packages/react-native-bpk-component-card/src/BpkCard-test.ios.js
- native/packages/react-native-bpk-component-card/src/BpkCard.android.js
- native/packages/react-native-bpk-component-card/src/BpkCard.ios.js
- native/packages/react-native-bpk-component-card/src/__snapshots__/BpkCard-test.android.js.snap
- native/packages/react-native-bpk-component-card/src/__snapshots__/BpkCard-test.ios.js.snap
added `TouchableNativeFeedback` for android, we'll now  ship two BPK cards: iOS and Android, the reason behind it is `TouchableNativeFeedback` and `TouchableHighlight` are very different so having them behaving in one file became a nightmare.
The main difference between the two (`TouchableNativeFeedback` and `TouchableHighlight`) is the `style` `TouchableNativeFeedback`does not accepts any styles therefore the Android version return a `View` wrapping it, in which userland style will be applied
Base Card
Ripple animation start
Ripple animation end
cc @jamesf3rguson  for the visual validation
iOS is unaffected by this changes
> add TouchableNativeFeedback for android

- changelog.md
- native/packages/react-native-bpk-component-horizontal-nav/readme.md
- native/packages/react-native-bpk-component-horizontal-nav/src/BpkHorizontalNav-test.common.js
- native/packages/react-native-bpk-component-horizontal-nav/src/BpkHorizontalNav.js
- native/packages/react-native-bpk-component-horizontal-nav/src/BpkHorizontalNavItem-test.common.js
- native/packages/react-native-bpk-component-horizontal-nav/src/BpkHorizontalNavItem.js
- native/packages/react-native-bpk-component-horizontal-nav/src/BpkHorizontalNavSelectedIndicator-test.android.js
- native/packages/react-native-bpk-component-horizontal-nav/src/BpkHorizontalNavSelectedIndicator-test.common.js
- native/packages/react-native-bpk-component-horizontal-nav/src/BpkHorizontalNavSelectedIndicator-test.ios.js
- native/packages/react-native-bpk-component-horizontal-nav/src/BpkHorizontalNavSelectedIndicator.js
- native/packages/react-native-bpk-component-horizontal-nav/src/__snapshots__/BpkHorizontalNav-test.android.js.snap
- native/packages/react-native-bpk-component-horizontal-nav/src/__snapshots__/BpkHorizontalNav-test.ios.js.snap
- native/packages/react-native-bpk-component-horizontal-nav/src/__snapshots__/BpkHorizontalNavItem-test.ios.js.snap
- native/packages/react-native-bpk-component-horizontal-nav/src/__snapshots__/BpkHorizontalNavSelectedIndicator-test.android.js.snap
- native/packages/react-native-bpk-component-horizontal-nav/src/__snapshots__/BpkHorizontalNavSelectedIndicator-test.ios.js.snap
- native/packages/react-native-bpk-component-horizontal-nav/src/theming.js
- native/packages/react-native-bpk-component-horizontal-nav/src/withAnimatedProps.js
- native/packages/react-native-bpk-component-horizontal-nav/stories.js
- packages/bpk-docs/src/pages/NativeHorizontalNavPage/NativeHorizontalNavPage.js
**What does this PR do?**
Previously, consumers would handle the `selected` prop on `BpkHorizontalNavItem`. If a NavItem had this prop, the NavItem would get blue text and a blue indicator underneath.
Their code would look like this:
```
<BpkHorizontalNav>
<BpkHorizontalNavItem title="One" />
<BpkHorizontalNavItem title="Two" selected />
<BpkHorizontalNavItem title="Three" />
</BpkHorizontalNav>
```
With this PR, consumers should add a `selectedId` prop to the container and `id` props to the children instead, like this:
```
<BpkHorizontalNav selectedId="1">
<BpkHorizontalNavItem title="One" id="0" />
<BpkHorizontalNavItem title="Two" id="1" />
<BpkHorizontalNavItem title="Three" id="2" />
</BpkHorizontalNav>
```
**How does it do this?**
The indicator line has been pulled out of the …
> [BPK-1092] horizontal nav animation

- native/packages/react-native-bpk-component-animate-height/src/BpkAnimateHeight.js
- native/packages/react-native-bpk-component-horizontal-nav/src/withAnimatedProps.js
- packages/bpk-tokens/formatters/react-native-value-template.js
- packages/bpk-tokens/src/android/base/animations.json
- packages/bpk-tokens/src/ios/base/animations.json
- packages/bpk-tokens/tokens/android/base.react.native.common.js
- packages/bpk-tokens/tokens/android/base.react.native.es6.js
- packages/bpk-tokens/tokens/base.ios.json
- packages/bpk-tokens/tokens/base.raw.android.json
- packages/bpk-tokens/tokens/base.raw.ios.json
- packages/bpk-tokens/tokens/base.react.native.android.js
- packages/bpk-tokens/tokens/base.react.native.ios.js
- packages/bpk-tokens/tokens/ios/base.react.native.common.js
- packages/bpk-tokens/tokens/ios/base.react.native.es6.js
React Native animations take an integer in milliseconds as their arguments, so the previous values we were using, such as `"200ms"` do not work.
This PR adds a formatter so that `duration` tokens are converted, and then consumes it in the horizontal nav.
> [no jira] Add duration type to token formatter and consume it

- dangerfile.js
Danger uses this code to advise people introducing new components:
```
if (nativeComponentIntroduced) {
message('It looks like you are introducing a native component.');
warn('Ensure the component style is extensible via `style`.');
}
```
However, when this is posted to GitHub, they're placed away from each other, which removes a lot of the context:
This PR changes the code to use `warn` for all of the message, which will make more sense:
```
if (nativeComponentIntroduced) {
warn('It looks like you are introducing a native component. Ensure the component style is extensible via `style`.');
}
```
> [no jira] Changed the way Danger reports new components

- packages/bpk-component-image/stories.js
There are two stories in `bpk-component-image` that don't work. 
After speaking with @georgegillams who clarified that this is intentional because we don't currently ship this functionality to users, I've commented out the stories for now. 
This will prevent confusion in future, as I thought they were working code that had been broken by a previous PR.
> [no jira] Remove broken stories

- packages/bpk-component-fieldset/readme.md
- packages/bpk-component-fieldset/src/BpkFieldset-test.js
- packages/bpk-component-fieldset/src/BpkFieldset.js
If BpkFieldset doesn't have a label, it will no longer include an empty BpkLabel component.
> [BPK-1094] BpkFieldset validation tweak

- changelog.md
- packages/bpk-component-modal/src/BpkModal.js
- packages/bpk-component-modal/src/bpk-modal.scss
- packages/bpk-scrim-utils/readme.md
- packages/bpk-scrim-utils/src/__snapshots__/withScrim-test.js.snap
- packages/bpk-scrim-utils/src/bpk-scrim-content.scss
- packages/bpk-scrim-utils/src/withScrim-test.js
- packages/bpk-scrim-utils/src/withScrim.js
This allows the extraction of some modal specific code and makes the component more versatile.
Only the modal needs display: flex and padding on the container, it now injects the styles it requires.
> Replace padded prop on withScrim with more generic contentClassName

- .storybook/config.js
- changelog.md
- packages/bpk-theming/bpk-themeable-text/BpkThemeableText.js
- packages/bpk-theming/bpk-themeable-text/bpk-themeable-text.scss
- packages/bpk-theming/index.js
- packages/bpk-theming/package-lock.json
- packages/bpk-theming/package.json
- packages/bpk-theming/readme.md
- packages/bpk-theming/src/BpkThemeProvider-test.js
- packages/bpk-theming/src/BpkThemeProvider.js
- packages/bpk-theming/src/__snapshots__/BpkThemeProvider-test.js.snap
- packages/bpk-theming/stories.js
- Uses CSS variables to apply theming to `BpkThemeProvider`.
- Components need updating to support theming, for now I've made one called `BpkThemeableText` which is for the storybook. When we have a themeable component, we can delete this.
- If a theme doesn't supply all of the necessary attributes for a specific component to be themed, the theme will not be applied to that component at all (same as native). You can test this by going to `stories.js` and commenting out one of the theme attributes for a theme.
> [BPK-955] Add web theming package

- packages/bpk-docs/src/components/Header/Header.js
There are some things on the _Style_ page that shouldn't be there.
As discussed with @jamesf3rguson, for now we'll just remove the link as the section is outdated anyway.
Obviously this won't prevent people accessing the links directly!
> [no jira] Hide 'style' from header

- packages/bpk-component-blockquote/readme.md
- packages/bpk-component-blockquote/src/BpkBlockquote-test.js
- packages/bpk-component-blockquote/src/themeAttributes-test.js
- packages/bpk-component-blockquote/src/themeAttributes.js
- packages/bpk-mixins/src/mixins/_typography.scss
I haven't added a changelog entry because I noticed the other PRs for theming didn't include one and assumed it's a deliberate convention.
> [BPK-991] Theme support for bpk-component-blockquote

- changelog.md
- native/packages/react-native-bpk-component-animate-height/readme.md
- native/packages/react-native-bpk-component-animate-height/src/BpkAnimateHeight.js
- native/packages/react-native-bpk-component-animate-height/src/__snapshots__/BpkAnimateHeight-test.android.js.snap
- native/packages/react-native-bpk-component-animate-height/src/__snapshots__/BpkAnimateHeight-test.ios.js.snap
- native/packages/react-native-bpk-component-animate-height/stories.js
- native/packages/react-native-bpk-component-banner-alert/src/__snapshots__/BpkBannerAlert-test.android.js.snap
- native/packages/react-native-bpk-component-banner-alert/src/__snapshots__/BpkBannerAlert-test.ios.js.snap
This PR contains the changes to BpkAnimateHeight which are required to address BPK-1084 (banner alert animations)
This presents the same issue as web animations when elements are removed from the DOM / Tree where the padding suddenly disappears causing a small jump. I think it best to address this later on. For now, user styling (such as padding) will be applied to the outer container until a better solution can be found.
>  [BPK-1084] Enhance RN BpkAnimateHeight component

- .storybook/themeableAttributes.js
- packages/bpk-component-accordion/readme.md
- packages/bpk-component-accordion/src/bpk-accordion-item.scss
- packages/bpk-component-accordion/src/themeAttributes-test.js
- packages/bpk-component-accordion/src/themeAttributes.js
- packages/bpk-component-theme-toggle/src/theming.js
- packages/bpk-docs/src/themeableAttributes.js
I changed the variables from what we initially had in mind. The same variable apply to both the title and icon in normal, active, and hover states.
Theming on the docs
cc @jamesf3rguson
> [BPK-975] Make accordions themeable

- changelog.md
- packages/bpk-component-drawer/readme.md
- packages/bpk-component-drawer/src/BpkDrawerContent-test.js
- packages/bpk-component-drawer/src/BpkDrawerContent.js
- packages/bpk-component-drawer/src/__snapshots__/BpkDrawerContent-test.js.snap
- packages/bpk-component-drawer/src/bpk-drawer-content.scss
- packages/bpk-component-drawer/stories.js
- packages/bpk-component-drawer/stories.scss
- packages/bpk-component-modal/src/BpkModal.js
- packages/bpk-component-modal/src/BpkModalDialog-test.js
- packages/bpk-component-modal/src/BpkModalDialog.js
- packages/bpk-scrim-utils/readme.md
- packages/bpk-scrim-utils/src/__snapshots__/withScrim-test.js.snap
- packages/bpk-scrim-utils/src/withScrim-test.js
- packages/bpk-scrim-utils/src/withScrim.js
For the implementation of the menu in the header, we need to inject styles into the container element of the drawer (ie. make it display: flex). This enables that and refactors bpk-scrim-utils to enable this.
It also fixes the name of the getDialogRef prop.
> Extend drawer content className

- packages/bpk-component-slider/readme.md
you can see the stray 'u' here: https://backpack.github.io/components/web/sliders#props
> Fix stray character in the readme for bpk-component-slider

- .storybook/themeableAttributes.js
- changelog.md
- packages/bpk-component-calendar/index.js
- packages/bpk-component-calendar/readme.md
- packages/bpk-component-calendar/src/bpk-calendar-date.scss
- packages/bpk-component-calendar/src/bpk-calendar-nav.scss
- packages/bpk-component-calendar/src/themeAttributes-test.js
- packages/bpk-component-calendar/src/themeAttributes.js
- packages/bpk-component-theme-toggle/src/theming.js
- packages/bpk-docs/src/pages/ThemingPage/ThemingPage.js
- packages/bpk-docs/src/themeableAttributes.js
This adds support for theming the calendar. On top of the specified themeable attributes I had to add `calendarDateTextFocusColor` and `calendarDateFocusedBorderColor` which were not accounted for.
**Note:** The Datepicker suffers from the same issues as all components that use the portal, namely it doesn't work.
cc @jamesf3rguson, @matthewdavidson
> [BPK-979] Add theming for calendar

- .storybook/themeableAttributes.js
- packages/bpk-component-pagination/index.js
- packages/bpk-component-pagination/readme.md
- packages/bpk-component-pagination/src/BpkPaginationPage.js
- packages/bpk-component-pagination/src/bpk-pagination-nudger.scss
- packages/bpk-component-pagination/src/bpk-pagination-page.scss
- packages/bpk-component-pagination/src/themeAttributes-test.js
- packages/bpk-component-pagination/src/themeAttributes.js
- packages/bpk-component-theme-toggle/src/theming.js
- packages/bpk-docs/src/themeableAttributes.js
This makes the pagination themable, two main changes:
`paginationBackgroundColorSelected` get applied to the background and border of a selected button and the cursor `pointer` has been removed
in the storybook the secondary button had a different behaviour than the docs site, now the default border is `Gray100`
both changes discussed with @jamesf3rguson 
Screenshots time!
> [BPK-1140] pagination theming

- native/package-lock.json
- native/package.json
**The issue**
When using storybook actions (or indeed any addons), we're getting an issue where triggering the action causes an error to appear.
The error message itself links to [this page](https://storybook.js.org/basics/faq/#why-is-there-no-addons-channel), which in turn links to [this issue](https://github.com/storybooks/storybook/issues/1192).
**The solution**
I tried all sorts of different changes to the code but I couldn't get it to work. In the end, through trial and error I figured out that downgrading `@storybook/react-native` by one patch version (`3.2.17` :arrow_right: `3.2.16`) sorts it out.
It's not an ideal long term solution, but it does fix things for now.
`3.3.0` of Storybook is currently in alpha, I intend to next find out if that fixes the issue, and also find out what …
> [BPK-1153] Downgrade @storybook/react-native to fix issue

- packages/bpk-component-pagination/readme.md
- packages/bpk-component-pagination/src/BpkPagination-test.js
- packages/bpk-component-pagination/src/BpkPagination.js
- packages/bpk-component-pagination/src/BpkPaginationList-test.js
- packages/bpk-component-pagination/src/BpkPaginationList.js
- packages/bpk-component-pagination/src/BpkPaginationPage.js
- packages/bpk-component-pagination/stories.js
- packages/bpk-docs/src/pages/PaginationPage/PaginationPage.js
The word `formatter` in `pageLabelFormatter` is redundant as this
is capture by the prop type being `func`.
> [No JIRA] Rename pageLabelFormatter to pageLabel

- packages/bpk-component-banner-alert/package-lock.json
- packages/bpk-component-banner-alert/package.json
`bpk-component-banner-alert` uses `react-transition-group` but does not include it as a dependency
> Add react-transition-group as an explicit dependency

- changelog.md
- packages/bpk-component-banner-alert/index.js
- packages/bpk-component-banner-alert/readme.md
- packages/bpk-component-banner-alert/src/BpkBannerAlert-test.js
- packages/bpk-component-banner-alert/src/BpkBannerAlert.js
- packages/bpk-component-banner-alert/src/__snapshots__/BpkBannerAlert-test.js.snap
- packages/bpk-component-banner-alert/src/__snapshots__/withBannerAlertState-test.js.snap
- packages/bpk-component-banner-alert/src/withBannerAlertState-test.js
- packages/bpk-component-banner-alert/src/withBannerAlertState.js
- packages/bpk-component-banner-alert/stories.js
- packages/bpk-docs/src/pages/BannerAlertsPage/BannerAlertsPage.js
Hi, as a follow up of https://github.com/Skyscanner/backpack/pull/292 I've created this initial version of the HoC to wrap the default behaviour for `dismissable` and `expandable` (I think it makes more sense and it is easier to use just one HoC wrapping both features instead of two different HoC's, one per feature).
* Remove the `expanded` state from BpkBannerAlert (it was mentioned that this was planned, to be consistent with `dismissable`)
* Create HoC with default behaviour for `dismissable` and `expandable`
* Added the prop `hideAfter` to the HoC, so it can also automatically hide the alert after a period of seconds
What to you think about this approach? If you're fine with this, I'll update the tests, create new tests for the HoC, move BpkBannerAlert into a dumb component (now that …
> Add a HOC to BpkBannerAlert to wrap default dismissable/expandable behaviour

- packages/bpk-component-datatable/package.json
- packages/bpk-component-datatable/readme.md
- packages/bpk-component-datatable/src/BpkDataTable.js
- packages/bpk-component-datatable/src/BpkDataTableColumn-test.js
- packages/bpk-component-datatable/src/BpkDataTableColumn.js
- packages/bpk-component-datatable/src/__snapshots__/BpkDataTable-test.js.snap
- packages/bpk-component-datatable/src/bpk-data-table-column.scss
- packages/bpk-component-datatable/src/hasChildrenOfType-test.js
- packages/bpk-component-datatable/src/hasChildrenOfType.js
- https://github.com/Skyscanner/backpack/commit/bf00596c8a0c941e8e6af80c90b24357f3f1aadf: add `hasChildrenOfType` util (probably a good candidate for `bpk-react-utils`) to ensure children of `BpkDataTable` are `BpkDataTableColumn`s.
- https://github.com/Skyscanner/backpack/commit/6f019c38fb25d9d9034416daa8965d54ac9b5d35: use `bpk-component-icon` for sort direction icons
> [BPK-434] use bpk-component-icon for sort direction icons

- changelog.md
- packages/bpk-component-button/src/BpkButton.js
- packages/bpk-docs/src/pages/ButtonsPage/ButtonsPage.js
This fixes the following warnings caused by `import * as React from 'react';` change:
```
console.warn node_modules/react/lib/lowPriorityWarning.js:38
Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs
console.warn node_modules/react/lib/lowPriorityWarning.js:38
Warning: Accessing createClass via the main React package is deprecated, and will be removed in React v16.0. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class v15.* is available on npm as a temporary, drop-in replacement. For more info see https://fb.me/react-create-class
```
> [nojira] Remove import * as React

- packages/bpk-component-image/readme.md
The only trace of `import * as TOKENS` in the repo now is in the `bpk-tokens/readme.md`. We could also remove that too? Thoughts?
> [BPK-1111] Use named imports of tokens in readmes

- changelog.md
- native/packages/react-native-bpk-component-banner-alert/src/BpkBannerAlert.android.js
- native/packages/react-native-bpk-component-banner-alert/src/BpkBannerAlert.ios.js
- native/packages/react-native-bpk-component-button/stories.js
- native/packages/react-native-bpk-component-icon/index.js
- native/packages/react-native-bpk-component-icon/readme.md
- native/packages/react-native-bpk-component-icon/src/BpkIcon-test.common.js
- native/packages/react-native-bpk-component-icon/src/BpkIcon.js
- native/packages/react-native-bpk-component-icon/stories.js
- native/packages/react-native-bpk-component-star-rating/src/BpkStar.js
- native/packages/react-native-bpk-component-text-input/src/BpkTextInputIcons.js
Right now I've done this in the simplest way possible. We can change it, but I thought it best to keep it simple and then we can discuss it.
We expose the mappings in an object that looks like this:
```
{
beer: 'beer',
'alert--remove': 'alert--remove',
..etc
}
```
Which means it's used like this:
```
import BpkIcon, { icons } from 'react-native-bpk-component-icon';
<BpkIcon icon={icons.beer} />
<BpkIcon icon={icons['alert--remove']} />
```
Having to use the array syntax for icon names that include hyphens is a little inelegant, so I'm wondering whether we should transform them so that it's more like this:
```
{
BEER: 'beer',
ALERT__REMOVE: 'alert--remove',
..etc
}
<BpkIcon icon={icons.BEER} />
<BpkIcon icon={icons.ALERT__REMOVE} />
```
The downside of this approach is that we'd need to …
> [BPK-1078] Expose `icons` constant from native icons and consume it

- .flowconfig
- native/packages/react-native-bpk-component-icon/src/BpkIcon.js
- native/packages/react-native-bpk-component-icon/stories.js
- package-lock.json
- package.json
- scripts/stubs/jsModuleStub.js
@matteo-hertel and I tried a number of ways to get this to work correctly, but we couldn't manage it.
So, we're ignoring all native node_modules, and are using a stub to mock any third party deps that are used in the code.
This isn't particularly great, as it means we won't get code completion for third party deps, but it does mean that we can still benefit from adding types to the public APIs.
We think that this solution is good enough as a unit of work to merge now, and then we* can look at not ignoring all node_modules down the line.
We've also added types to the native icon component.
I'll add comments inline where necessary, too.
*_by 'we' I mean 'not me'_ 🤣
> [BPK-1180] React Native support for Flow

- changelog.md
- packages/bpk-component-popover/src/bpk-popover.scss
I feel like this was deceptively simple and I don't quite trust it.
**Before:**
**After:**
~I've used percentages instead of absolute tokens - I don't know where we stand on that, so let's discuss it if necessary.~ (Discussed)
> [BPK-1069] Change popover max-width on mobile

- NPM_OWNERS
- dangerfile.js
- meta.json
- package.json
- scripts/npm/check-owners.js
- scripts/npm/get-owners.js
- scripts/npm/remove-owner.sh
- scripts/npm/update-owners.sh
After discussing it on Slack, I threw together a quick check for external contributors.
We could probably make it use the GitHub API to determine team members, but then Danger would need to be authenticated as a member of the Skyscanner organisation, which seemed like a lot to get into for a quick check. 
I figured the squad doesn't change much so it's quite low-impact to have hard-coded team members, but feel free to disagree!
I also think we're reaching the point where Danger should be split across a few different files, probably in `scripts/danger/`, but in the interest of keeping this small I thought that can be handled in another PR.
> [no-jira] Danger now only thanks external contributors

- changelog.md
- packages/bpk-component-popover/src/bpk-popover.scss
Reverts Skyscanner/backpack#426
Agreed with @matthewdavidson to temporarily revert this before release to avoid making two breaking changes in quick succession.
> Revert "[BPK-1069] Change popover max-width on mobile"

- lerna.json
- packages/bpk-tether/.eslintrc
Since [`bpk-tether`](https://github.com/Skyscanner/backpack/tree/master/packages/bpk-tether) isn't used by any other bpk package, we don't need to include it in any lerna operations anymore.
I wanna keep the source in the repo though for any bug fixes that may arise.
```
npm run bootstrap
> backpack@0.0.1 bootstrap /Users/matthewdavidson/projects/backpack
> lerna bootstrap
lerna info version 2.6.0
lerna info versioning independent
lerna info ignore bpk-tether
lerna WARN ECYCLE Encountered a cycle in the dependency graph.This may cause instability! Packages in cycle are: "bpk-docs", "react-native-bpk-component-animate-height", "react-native-bpk-component-banner-alert", "react-native-bpk-component-button", "react-native-bpk-component-horizontal-nav", "react-native-bpk-component-spinner", …
```
> [NOJIRA] Lerna ignore bpk-tether

- changelog.md
- packages/bpk-component-close-button/src/bpk-close-button.scss
Test in FF on windows/osx, edge, IE11 and chrome on windows/osx
> [BPK-1123] Close button hover / active styles now work in firefox.

- packages/bpk-component-theme-toggle/src/theming.js
This means that `bpk-logos` will be able to use `bpk-component-theme-toggle` in their test harness (same as we currently use in storybook and docs site) instead of having to duplicate the logic.
> [no jira] Add logoFillColor to theme attributes

- changelog.md
- packages/bpk-component-drawer/src/bpk-drawer-content.scss
With no visible scrim for users to press on mobile, when content overflows, scrolling will hide the close button. So, I've also made the fixed the header to the top of the drawer so that the close button is visible when scrolling.
**Browser Testing**
* Firefox ✅ 
* Chrome (Mac) ✅ 
* IE11 (Windows 10) ✅ 
* IE11 (Windows 8.1) ✅ 
* Edge ✅ 
* Safari (Mac) ✅ 
* Safari (iOS 9) ✅ 
* Safari (iOS 11) ✅ 
* Chrome (Android, Galaxy S8) ✅
> [BPK-1142] On mobile, drawer component is now 100% width

- changelog.md
- packages/bpk-component-input/package-lock.json
- packages/bpk-component-input/package.json
- packages/bpk-component-input/readme.md
- packages/bpk-component-input/src/BpkClearButton-test.js
- packages/bpk-component-input/src/BpkClearButton.js
- packages/bpk-component-input/src/BpkInput-test.js
- packages/bpk-component-input/src/BpkInput.js
- packages/bpk-component-input/src/__snapshots__/BpkClearButton-test.js.snap
- packages/bpk-component-input/src/__snapshots__/BpkInput-test.js.snap
- packages/bpk-component-input/src/bpk-clear-button.scss
- packages/bpk-component-input/src/bpk-input.scss
- packages/bpk-component-input/src/customPropTypes-test.js
- packages/bpk-component-input/src/customPropTypes.js
- packages/bpk-component-input/stories.js
- packages/bpk-component-select/readme.md
- packages/bpk-docs/src/pages/FormsPage/FormsPage.js
- packages/bpk-docs/src/pages/FormsPage/InputContainer.js
- packages/bpk-mixins/src/mixins/_forms.scss
* `BpkInput` now accepts `clearable`, `onClear` and `clearButtonLabel` props.
* `onClear` and `clearButtonLabel` are required if `clearable={true}`.
* When `clearable={true}`, a button appears when the field is focused and `value.length > 0`.
* As with modifying the input's value, actually doing the clearing is left to userland.
* However, I'm re-focussing the input when the clear button is pressed, as otherwise pressing it would un-focus it, which I think is a bad UX.
* If the input has a valid/invalid icon, the clear button will hide it when focused.
* I've set `tabIndex=-1` on the clear button to preserve tabbing between fields.
* Originally I used a `BpkCloseButton` for the button, but I needed to use a different icon (`close-circle`). After speaking with @jamesf3rguson we decided to …
> [BPK-898] Add 'clearable' and 'onClear' props to BpkInput

- packages/bpk-component-modal/readme.md
- packages/bpk-component-modal/src/BpkModal.js
- packages/bpk-component-modal/src/BpkModalDialog-test.js
- packages/bpk-component-modal/src/BpkModalDialog.js
- packages/bpk-component-modal/src/__snapshots__/BpkModal-test.js.snap
- packages/bpk-component-modal/src/__snapshots__/BpkModalDialog-test.js.snap
- packages/bpk-component-modal/src/bpk-modal-dialog.scss
- packages/bpk-component-modal/src/bpk-modal.scss
- packages/bpk-component-modal/stories.js
- adds the possibility to have a modal dialog as fullscreen for the desktop and mobile with `fullScreen` parameter 
- if `fullscreen` is defined it trumps `fullScreenOnMobile`
> [FSS-3569] - Add possibility to set fullScreen for modal dialog

- changelog.md
- packages/bpk-component-datatable/src/BpkDataTable-test.js
- packages/bpk-component-datatable/src/BpkDataTable.js
Fixes bug where `onRowClick` event handler is not triggered with the corresponding clicked element on sorted lists.
> datatable/fix: onRowClick to work with sorted rows.

- packages/bpk-docs/src/components/DocsPageBuilder/DocsPageBuilder.js
Im using a secret `headerPrefix` api used in marked here: https://github.com/chjj/marked/blob/master/lib/marked.js#L825
Old:
New:
> [BPK-1275] Fix duplicate id's on docs pages

- packages/bpk-component-datatable/readme.md
- packages/bpk-component-datatable/src/BpkDataTable-test.js
- packages/bpk-component-datatable/src/BpkDataTable.js
With this new optional parameter, the user can customize which
column is used to sort the table on the initial render.
If the value is not provided, the first column is used.
> bpkDataTable: supports changing column used for initial sorting.

- packages/bpk-component-datatable/src/BpkDataTable.js
The initial sorting chosen when clicking a column header is now
respecting the default sorting.
> bpkDataTable: default column sorting is respected on first click

- changelog.md
- packages/bpk-component-grid-toggle/readme.md
- packages/bpk-component-grid-toggle/src/BpkGridToggle-test.js
- packages/bpk-component-grid-toggle/src/BpkGridToggle.js
- packages/bpk-component-grid-toggle/src/__snapshots__/BpkGridToggle-test.js.snap
- packages/bpk-component-rtl-toggle/readme.md
- packages/bpk-component-rtl-toggle/src/BpkRtlToggle-test.js
- packages/bpk-component-rtl-toggle/src/BpkRtlToggle.js
- packages/bpk-component-rtl-toggle/src/__snapshots__/BpkRtlToggle-test.js.snap
This is so that I can add margins to them for the docs footer redesign, but good to have in general.
> [BPK-1286] Add className prop support to RTL and grid toggles

- changelog.md
- packages/bpk-component-close-button/src/bpk-close-button.scss
- packages/bpk-mixins/src/mixins/_utils.scss
This increases the touch area to 42px * 42px while keeping the outline size down.
> [BPK-1301] Increase close button touch area

- contributing.md
`brew cask install java` no longer installs Java 8 (as it is not the latest version. Java 8 is required to run the emulators, however. Java 9 causes the process to blow up with a very unhelpful error message. Therefore, the “getting-started” guide needs updating.
> [NO-JIRA] Update java install instructions in contributing.md

- changelog.md
- native/packages/react-native-bpk-component-animate-height/src/__snapshots__/BpkAnimateHeight-test.android.js.snap
- native/packages/react-native-bpk-component-animate-height/src/__snapshots__/BpkAnimateHeight-test.ios.js.snap
- native/packages/react-native-bpk-component-banner-alert/src/__snapshots__/BpkBannerAlert-test.android.js.snap
- native/packages/react-native-bpk-component-banner-alert/src/__snapshots__/BpkBannerAlert-test.ios.js.snap
- native/packages/react-native-bpk-component-button/src/__snapshots__/BpkButton-test.ios.js.snap
- native/packages/react-native-bpk-component-card/src/__snapshots__/BpkCard-test.android.js.snap
- native/packages/react-native-bpk-component-card/src/__snapshots__/BpkCard-test.ios.js.snap
- native/packages/react-native-bpk-component-horizontal-nav/src/__snapshots__/BpkHorizontalNavItem-test.ios.js.snap
- native/packages/react-native-bpk-component-text-input/src/__snapshots__/BpkTextInput-RTL-test.js.snap
- native/packages/react-native-bpk-component-text-input/src/__snapshots__/BpkTextInput-test.android.js.snap
- native/packages/react-native-bpk-component-text-input/src/__snapshots__/BpkTextInput-test.ios.js.snap
- native/packages/react-native-bpk-component-text-input/src/styles.js
- native/packages/react-native-bpk-component-text/src/BpkText.js
- native/packages/react-native-bpk-component-text/src/__snapshots__/BpkText-test.android.js.snap
- native/packages/react-native-bpk-component-text/src/__snapshots__/BpkText-test.ios.js.snap
- native/packages/react-native-bpk-component-touchable-overlay/src/__snapshots__/BpkTouchableOverlay-test.js.snap
- packages/bpk-tokens/src/android/base/typography.json
- packages/bpk-tokens/src/ios/base/typography.json
* Removed line height from BpkText.
* Deprecated the tokens.
* Updated snapshots to reflect this.
> [BPK-1320] Remove line height from native BpkText

- packages/bpk-docs/src/constants/_neo-home-page-variables.scss
- packages/bpk-docs/src/pages/NeoHomePage/home-page.scss
In accordance with @willhg, I've widened the content to occupy the maximum width available under our current breakpoints. I've also pulled in the Backpack logo to remove the overhang (for now) to provide more space to play with.
Here's how it looks at different widths - you can see it just widens things slightly. I've not included tablet and mobile widths as they're unaffected by this.
| Viewport width (px) | Before this PR | After this PR |
| ---: | --- | --- |
| 1440 |![screen shot 2018-02-21 at 10 59 28](https://user-images.githubusercontent.com/73652/36476615-52997e3a-16f6-11e8-84cb-f5fa2e52b27b.png) | ![screen shot 2018-02-21 at 10 51 09](https://user-images.githubusercontent.com/73652/36476228-324ffcc2-16f5-11e8-9b22-c27f742fb27b.png)
| 1024 | ![screen shot 2018-02-21 at 10 58 …
> [BPK-1369] Tweak new homepage design

- dangerfile.js
- native/packages/react-native-bpk-component-animate-height/src/BpkAnimateHeight-test.android.js
- native/packages/react-native-bpk-component-banner-alert/src/AnimateAndFade-test.android.js
- native/packages/react-native-bpk-component-banner-alert/src/BpkBannerAlert-test.android.js
- native/packages/react-native-bpk-component-banner-alert/src/__snapshots__/BpkBannerAlert-test.android.js.snap
- native/packages/react-native-bpk-component-button-link/src/BpkButtonLink-test.android.js
- native/packages/react-native-bpk-component-button-link/src/__snapshots__/BpkButtonLink-test.android.js.snap
- native/packages/react-native-bpk-component-button/src/BpkButton-test.android.js
- native/packages/react-native-bpk-component-button/src/__snapshots__/BpkButton-test.android.js.snap
- native/packages/react-native-bpk-component-card/src/BpkCard-test.android.js
- native/packages/react-native-bpk-component-card/src/withDivider-test.android.js
- native/packages/react-native-bpk-component-horizontal-nav/src/BpkHorizontalNav-test.android.js
- native/packages/react-native-bpk-component-horizontal-nav/src/BpkHorizontalNavItem-test.android.js
- native/packages/react-native-bpk-component-horizontal-nav/src/BpkHorizontalNavSelectedIndicator-test.android.js
- native/packages/react-native-bpk-component-horizontal-nav/src/BpkHorizontalNavSelectedIndicator-test.ios.js
- native/packages/react-native-bpk-component-horizontal-nav/src/__snapshots__/BpkHorizontalNavItem-test.android.js.snap
- native/packages/react-native-bpk-component-icon/src/BpkIcon-test.android.js
- native/packages/react-native-bpk-component-spinner/src/BpkSpinner-test.android.js
- native/packages/react-native-bpk-component-star-rating/src/BpkStar-test.android.js
- native/packages/react-native-bpk-component-star-rating/src/BpkStarRating-RTL-test.js
- native/packages/react-native-bpk-component-star-rating/src/BpkStarRating-test.android.js
- native/packages/react-native-bpk-component-switch/src/BpkSwitch-test.android.js
- native/packages/react-native-bpk-component-text-input/src/BpkTextInput-RTL-test.js
- native/packages/react-native-bpk-component-text-input/src/BpkTextInput-test.android.js
- native/packages/react-native-bpk-component-text-input/src/BpkTextInputIcons-RTL-test.js
- native/packages/react-native-bpk-component-text-input/src/BpkTextInputIcons-test.android.js
- native/packages/react-native-bpk-component-text/src/BpkText-test.android.js
- native/packages/react-native-bpk-theming/src/BpkThemeProvider-test.android.js
**NOTE: https://github.com/Skyscanner/backpack/pull/548 should be merged before this.**
@shaundon noticed that `TouchableNativeFeedback` wasn't resolving correctly in our android tests, see https://github.com/Skyscanner/backpack/pull/548#discussion_r171237280.
This PR fixes that.
> [NOJIRA] ensure touchable native feedback resolves in jest

- changelog.md
- native/ios/native.xcodeproj/project.pbxproj
- native/packages/react-native-bpk-component-phone-input/index.js
- native/packages/react-native-bpk-component-phone-input/package-lock.json
- native/packages/react-native-bpk-component-phone-input/package.json
- native/packages/react-native-bpk-component-phone-input/readme.md
- native/packages/react-native-bpk-component-phone-input/src/BpkDialingCodeList-test.android.js
- native/packages/react-native-bpk-component-phone-input/src/BpkDialingCodeList-test.common.js
- native/packages/react-native-bpk-component-phone-input/src/BpkDialingCodeList-test.ios.js
- native/packages/react-native-bpk-component-phone-input/src/BpkDialingCodeList.android.js
- native/packages/react-native-bpk-component-phone-input/src/BpkDialingCodeList.ios.js
- native/packages/react-native-bpk-component-phone-input/src/BpkDialingCodeListItem-test.android.js
- native/packages/react-native-bpk-component-phone-input/src/BpkDialingCodeListItem-test.common.js
- native/packages/react-native-bpk-component-phone-input/src/BpkDialingCodeListItem-test.ios.js
- native/packages/react-native-bpk-component-phone-input/src/BpkDialingCodeListItem.android.js
- native/packages/react-native-bpk-component-phone-input/src/BpkDialingCodeListItem.ios.js
- native/packages/react-native-bpk-component-phone-input/src/__snapshots__/BpkDialingCodeList-test.android.js.snap
- native/packages/react-native-bpk-component-phone-input/src/__snapshots__/BpkDialingCodeList-test.ios.js.snap
- native/packages/react-native-bpk-component-phone-input/src/__snapshots__/BpkDialingCodeListItem-test.android.js.snap
- native/packages/react-native-bpk-component-phone-input/src/__snapshots__/BpkDialingCodeListItem-test.ios.js.snap
- native/packages/react-native-bpk-component-phone-input/src/common-types.js
- native/packages/react-native-bpk-component-phone-input/stories.js
- native/storybook/storybook.js
Adds `BpkDialingCodeList` and `BpkDialingCodeListItem` components.
```
<BpkDiallngCodeListItem
id="44"
dialingCode="44"
name="United Kingdom"
onPress={action('BpkDialingCodeListItem pressed.')}
flag={
<Image
source={{
uri: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Flag_of_the_Democratic_Republic_of_the_Congo.svg/800px-Flag_of_the_Democratic_Republic_of_the_Congo.svg.png',
}}
/>
}
/>
```
Note that an instance of `Image` is passed in. I did it this way so that consumers are free to choose whichever type of image source they want: https://facebook.github.io/react-native/docs/images.html.
```
const CODES = [
{
id: '0',
dialingCode: '0',
name: 'Zero',
},
{
id: '1',
dialingCode: '1',
name: 'One',
},
{
id: '2',
dialingCode: '2',
name: 'Two',
},
];
<BpkDialingCodeList …
```
> [BPK-1376] DialingCodeList and DialingCodeListItem components

- native/packages/react-native-bpk-component-phone-input/src/BpkDialingCodeListItem.android.js
- native/packages/react-native-bpk-component-phone-input/src/BpkDialingCodeListItem.ios.js
- native/packages/react-native-bpk-component-phone-input/src/BpkFlag-test.common.js
- native/packages/react-native-bpk-component-phone-input/src/BpkFlag-test.ios.js
- native/packages/react-native-bpk-component-phone-input/src/BpkFlag-test.js
- native/packages/react-native-bpk-component-phone-input/src/BpkFlag.js
- native/packages/react-native-bpk-component-phone-input/src/BpkRadioIcon-test.android.js
- native/packages/react-native-bpk-component-phone-input/src/BpkRadioIcon.js
- native/packages/react-native-bpk-component-phone-input/src/__snapshots__/BpkDialingCodeListItem-test.android.js.snap
- native/packages/react-native-bpk-component-phone-input/src/__snapshots__/BpkFlag-test.ios.js.snap
- native/packages/react-native-bpk-component-phone-input/src/__snapshots__/BpkFlag-test.js.snap
- native/packages/react-native-bpk-component-phone-input/src/__snapshots__/BpkRadioIcon-test.android.js.snap
- native/packages/react-native-bpk-component-phone-input/src/common-types.js
* Made a `BpkRadioIcon` component, which is an RN implementation of Android's radio buttons. Applied it to the Android list item component.
* The flag component and logic was duplicated across iOS and Android, so I've abstracted it into its own component and added tests for it.
> [BPK-1376] BpkFlag component, BpkRadioIcon component

- native/packages/react-native-bpk-component-banner-alert/src/BpkBannerAlert.android.js
- native/packages/react-native-bpk-component-banner-alert/src/__snapshots__/BpkBannerAlert-test.android.js.snap
- native/packages/react-native-bpk-component-horizontal-nav/src/BpkHorizontalNavItem.js
- native/packages/react-native-bpk-component-horizontal-nav/src/__snapshots__/BpkHorizontalNavItem-test.android.js.snap
- native/packages/react-native-bpk-component-phone-input/src/BpkDialingCodeListItem.android.js
- native/packages/react-native-bpk-component-phone-input/src/__snapshots__/BpkDialingCodeListItem-test.android.js.snap
- native/packages/react-native-bpk-component-touchable-native-feedback/src/BpkTouchableNativeFeedback.js
The changes in #563 introduced some regressions in our use of touchable
feedback for Android. This fixes that.
> [No JIRA] Fix regressions with Andriod highlights

- changelog.md
- native/packages/react-native-bpk-component-nudger/index.js
- native/packages/react-native-bpk-component-nudger/package-lock.json
- native/packages/react-native-bpk-component-nudger/package.json
- native/packages/react-native-bpk-component-nudger/readme.md
- native/packages/react-native-bpk-component-nudger/src/BpkNudger-test.android.js
- native/packages/react-native-bpk-component-nudger/src/BpkNudger-test.common.js
- native/packages/react-native-bpk-component-nudger/src/BpkNudger-test.ios.js
- native/packages/react-native-bpk-component-nudger/src/BpkNudger.js
- native/packages/react-native-bpk-component-nudger/src/__snapshots__/BpkNudger-test.android.js.snap
- native/packages/react-native-bpk-component-nudger/src/__snapshots__/BpkNudger-test.ios.js.snap
- native/packages/react-native-bpk-component-nudger/stories.js
- native/storybook/storybook.js
* API is pretty much the same as the web version.
* I expect we'll need to change the Android version to use `BpkButtonLink` instead, because the design has the disabled button greyed out, but with no grey background. `BpkButtonLink` doesn't support `iconOnly` so if so, that'll need to come first.
> [BPK-1389] Native nudger

- native/package-lock.json
- package-lock.json
- package.json
`copy-webpack-plugin` and `uglifyjs-webpack-plugin` have dependencies on `cacache` which in-turn depends on `ssri`
`ssri` has a known vulnerability [CVE-2018-7651](https://nvd.nist.gov/vuln/detail/CVE-2018-7651) which is fixed in version `5.2.2`
I have bumped the two webpack dependencies, so new they are resolving ssri version `5.2.4` which should be safe :)
> [NO-JIRA] Update SSRI dependency due to known vulnerability

- changelog.md
- packages/bpk-component-dialog/stories.js
- packages/bpk-docs/src/pages/DialogsPage/DialogExamples.js
- packages/bpk-scrim-utils/src/__snapshots__/withScrim-test.js.snap
- packages/bpk-scrim-utils/src/withScrim-test.js
- packages/bpk-scrim-utils/src/withScrim.js
I originally though that the custom `onClose` prop type was also broken for the dialog, but it behaves as expected. The intended behaviour is that it warns if you don't provide an `onClose` handler and it's dismissible.
> [BPK-1402] - Fix `closeOnScrimClick` behaviour

- changelog.md
- packages/bpk-component-datepicker/src/BpkDatepicker-test.js
- packages/bpk-component-popover/package-lock.json
- packages/bpk-component-popover/package.json
- packages/bpk-component-popover/src/BpkPopoverPortal-test.js
- packages/bpk-component-popover/src/BpkPopoverPortal.js
- packages/bpk-component-tooltip/package-lock.json
- packages/bpk-component-tooltip/package.json
- packages/bpk-component-tooltip/src/BpkTooltipPortal.js
I've forked popper.js (see https://github.com/Skyscanner/popper.js) and published it to https://www.npmjs.com/package/@skyscanner/popper.js.
The fork contains a fix to remove the use of `global` which is problematic in OC server side rendering.
The offending code is marked for deprecation anyways, see https://github.com/FezVrasta/popper.js/blob/7ac2c0a96a0d084c3bed7dc47e7286f25f3289cf/packages/popper/src/index.js#L118
> [BPK-1400] Fix popover/tooltip compat with SSR OC

- changelog.md
- packages/bpk-scrim-utils/src/__snapshots__/withScrim-test.js.snap
- packages/bpk-scrim-utils/src/withScrim.js
In this [previous PR](https://github.com/Skyscanner/backpack/pull/578) the `onClose` prop is being extracted and not send to `WrappedComponent` anymore, therefore modals can't be closed using the close button.
> Pass "onClose" prop to the wrapped component in withScrim HOC

- native/packages/react-native-bpk-component-horizontal-nav/readme.md
- native/packages/react-native-bpk-component-horizontal-nav/src/BpkHorizontalNavItem-test.common.js
- native/packages/react-native-bpk-component-horizontal-nav/src/BpkHorizontalNavItem.js
- native/packages/react-native-bpk-component-horizontal-nav/src/__snapshots__/BpkHorizontalNavItem-test.android.js.snap
- native/packages/react-native-bpk-component-horizontal-nav/src/__snapshots__/BpkHorizontalNavItem-test.ios.js.snap
- native/packages/react-native-bpk-component-horizontal-nav/stories.js
I've also added inline comments; one thing @shaundon mentioned is to pass the small prop to the Nav components rather than Item, I tough was a good idea in the beginnign, but adding it to the item makes the intent clear so I went for it
> [BPK-1424] expose small prop in BpkNavigationItem

- native/packages/react-native-bpk-component-picker/index.js
- native/packages/react-native-bpk-component-picker/package-lock.json
- native/packages/react-native-bpk-component-picker/package.json
- native/packages/react-native-bpk-component-picker/readme.md
- native/packages/react-native-bpk-component-picker/src/BpkPicker-test.android.js
- native/packages/react-native-bpk-component-picker/src/BpkPicker-test.common.js
- native/packages/react-native-bpk-component-picker/src/BpkPicker-test.ios.js
- native/packages/react-native-bpk-component-picker/src/BpkPicker.js
- native/packages/react-native-bpk-component-picker/src/BpkPickerItem-test.android.js
- native/packages/react-native-bpk-component-picker/src/BpkPickerItem.android.js
- native/packages/react-native-bpk-component-picker/src/BpkPickerItem.ios.js
- native/packages/react-native-bpk-component-picker/src/BpkPickerMenu.android.js
- native/packages/react-native-bpk-component-picker/src/BpkPickerMenu.ios.js
- native/packages/react-native-bpk-component-picker/src/BpkPickerTrigger-test.android.js
- native/packages/react-native-bpk-component-picker/src/BpkPickerTrigger-test.common.js
- native/packages/react-native-bpk-component-picker/src/BpkPickerTrigger-test.ios.js
- native/packages/react-native-bpk-component-picker/src/BpkPickerTrigger.js
- native/packages/react-native-bpk-component-picker/src/__snapshots__/BpkPicker-test.android.js.snap
- native/packages/react-native-bpk-component-picker/src/__snapshots__/BpkPicker-test.ios.js.snap
- native/packages/react-native-bpk-component-picker/src/__snapshots__/BpkPickerItem-test.android.js.snap
- native/packages/react-native-bpk-component-picker/src/__snapshots__/BpkPickerTrigger-test.android.js.snap
- native/packages/react-native-bpk-component-picker/src/__snapshots__/BpkPickerTrigger-test.ios.js.snap
- native/packages/react-native-bpk-component-picker/stories.js
- native/storybook/storybook.js
A copy of https://github.com/Skyscanner/backpack/pull/551.
There are still some things that need to be done, there are cards for this, and they can be done in follow up stories.
**All** statefulness has been removed, now, like with modals, users handle whether the picker is open or closed, the value, etc.
There are three public facing components:
* `BpkPicker`: The wrapper component.
* `BpkPickerItem`: On iOS, this is an aliased `Picker.Item`. On Android it is a `View` that will be used in the dialog.
* `BpkPickerTrigger`: This can be optionally used by consumers as a component for rendering the trigger element. It adds the underline and the arrow icon. Can take either a string or an element. This will be split into its own package in a subsequent PR.
The components match the underlying …
> Native picker component

- native/packages/react-native-bpk-component-picker/src/BpkPickerItem.android.js
- native/packages/react-native-bpk-component-picker/src/BpkPickerMenu.android.js
- native/packages/react-native-bpk-component-picker/src/BpkPickerMenu.ios.js
- native/packages/react-native-bpk-component-picker/src/__snapshots__/BpkPicker-test.android.js.snap
- native/packages/react-native-bpk-component-picker/src/__snapshots__/BpkPicker-test.ios.js.snap
- native/packages/react-native-bpk-component-picker/src/__snapshots__/BpkPickerItem-test.android.js.snap
- native/packages/react-native-bpk-component-picker/stories.js
* When there are fewer than six options the picker is now longer full of empty space.
* The scrim is now interactive, it closes the picker when pressed.
* Picker items now have the correct ripple.
* Selected picker item is now always on screen on load, by using `initialScrollIndex` property of `FlatList`.
* Modal width and elevation now matches default Android styles.
* Now works in landscape mode on iOS.
**Note:** I don't love the magic numbers in use to calculate row height, but it's needed for `getItemLayout` and calculating the picker size. In the refactor card this should be optimised to be less fragile to styles changing.
> [BPK-1426] Add better Android behaviour

- packages/bpk-scrim-utils/src/__snapshots__/withScrim-test.js.snap
- packages/bpk-scrim-utils/src/scroll-utils.js
- packages/bpk-scrim-utils/src/withScrim.js
Mobile safari running on an iPad exhibits many problems with the fixed
scrim used in the modal when the virtual keyboard is present. This
resolves many of these issues by adding `position: fixed` to the body
when the modal and other scrim using components are presented.
Things to consider:
- Does this have a negative effect anywhere we use the scrim?
- Should we make this configurable by the user or just always apply the fix?
> [BPK-1371] Fix modal issue on iPad

- changelog.md
- packages/bpk-component-fieldset/src/BpkFieldset.js
- packages/bpk-docs/src/pages/FieldsetsPage/FieldsetsPage.js
For purposes of recreating this bug and testing changes, I added an autosuggest example to the Fieldsets page. I haven't removed it again, as there may be value in leaving it there. 
I thought about making the necessary change within `BpkAutosuggest`, but being a wrapper component it is not easy. I have therefore added a fix in the BpkFieldset which uses the value of `children.props.inputProps.id` if available. If not, it will use `children.props.id` as normal.
> [BPK-1405] Fix autosuggest id when used inside BpkFieldset

- native/packages/react-native-bpk-component-navigation-bar/package.json
- native/packages/react-native-bpk-component-navigation-bar/src/BpkNavigationBar.android.js
- native/packages/react-native-bpk-component-navigation-bar/src/BpkNavigationBar.ios.js
- native/packages/react-native-bpk-component-navigation-bar/src/common-types.js
- native/packages/react-native-bpk-theming/index.js
- native/packages/react-native-bpk-theming/package-lock.json
- native/packages/react-native-bpk-theming/package.json
- native/packages/react-native-bpk-theming/src/util-test.js
- native/packages/react-native-bpk-theming/src/util.js
Move some theming utility functions to `react-native-bpk-theming` as
they fit better in there. No changelog entry because we don't expect
consumers to use these.
> [No JIRA] Centralize theme util

- native/packages/react-native-bpk-component-animate-height/src/BpkAnimateHeight.js
- native/packages/react-native-bpk-component-animate-height/src/__snapshots__/BpkAnimateHeight-test.android.js.snap
- native/packages/react-native-bpk-component-animate-height/src/__snapshots__/BpkAnimateHeight-test.ios.js.snap
- native/packages/react-native-bpk-component-banner-alert/src/__snapshots__/AnimateAndFade-test.android.js.snap
- native/packages/react-native-bpk-component-banner-alert/src/__snapshots__/AnimateAndFade-test.ios.js.snap
- native/packages/react-native-bpk-component-banner-alert/src/__snapshots__/BpkBannerAlert-test.android.js.snap
- native/packages/react-native-bpk-component-banner-alert/src/__snapshots__/BpkBannerAlert-test.ios.js.snap
The animate height component has a lot of unnecessary renders - this is mostly due to keeping things in state that don't belong in state.
This PR attempts to remove as much from state as possible.
Also removed an extraneous view.
> [BPK-1437] Remove state from animate height component

- native/packages/react-native-bpk-component-banner-alert/src/BpkBannerAlert-test.common.js
- native/packages/react-native-bpk-component-banner-alert/src/__snapshots__/BpkBannerAlert-test.android.js.snap
- native/packages/react-native-bpk-component-banner-alert/src/__snapshots__/BpkBannerAlert-test.ios.js.snap
- native/packages/react-native-bpk-component-navigation-bar/package-lock.json
As titled - there is no need to test every prop with each alert type permutation. It's "good enough" to test them with one alert type.
Snapshot tests become less valuable when one slight change ends up failing hundreds of tests. The more cognitive load for the contributor / reviewer means more chance of issues slipping through.
> [BPK-1437] Remove redundant snapshot tests from banner alert

- native/packages/react-native-bpk-component-animate-height/src/BpkAnimateHeight-test.common.js
- native/packages/react-native-bpk-component-banner-alert/src/AnimateAndFade-test.common.js
- native/packages/react-native-bpk-component-banner-alert/src/BpkBannerAlert-test.common.js
This fixes the warning 
```
console.warn node_modules/react-native/jest/setup.js:99
Calling .measure() in the test renderer environment is not supported. Instead, mock out your components that use findNodeHandle with replacements that don't rely on the native environment.
```
jest will load each file in the `__mocks__` folder, in this case the RN Animated module will be mocked.
The Native codebase has no more warning during tests now
> [BPK-1404] fix measue warning

- packages/bpk-stylesheets/index.scss
- unreleased.md
This could happen when consumers do this in a `backpack-react-scripts` project:
```js
import 'bpk-stylesheets';
```
The `scss` files referenced inside would be processed through css modules and global utility classes (which tbh are frowned upon now) would be scoped.
An example of this in action is here: http://js.skyscnr.com/sttc/oc-registry/components/base-stylesheet/0.0.4/build/static/css/main.1e3e53e5.css
> [NOJIRA] Ensure base stylesheet globals are never scoped by css modules

- contributing.md
I chose a Nexus 5 from this list: https://material.io/devices/
I based this on it being a flagship Google phone and it having an integer/whole number pixel density (this aids RN's inspector tool to report accurate measurements).
After this is merged I'll get every team member to run:
```
$ANDROID_HOME/tools/bin/avdmanager delete avd --name "bpk-avd"
$ANDROID_HOME/tools/bin/avdmanager create avd --name "bpk-avd" --package "system-images;android-24;google_apis;x86" --device "Nexus 5"
```
Ill alos follow up with a PR to update screenshots.
> [BPK-1491] Update avd to use a sane pixel density

- packages/bpk-docs/src/constants/routes.js
- packages/bpk-docs/src/layouts/NeoSideNavLayout/NavList.js
- packages/bpk-docs/src/layouts/NeoSideNavLayout/Sidebar.js
- packages/bpk-docs/src/layouts/NeoSideNavLayout/links-sorter-test.js
- packages/bpk-docs/src/layouts/NeoSideNavLayout/links-sorter.js
- packages/bpk-docs/src/layouts/links.js
- packages/bpk-docs/src/routes/Routes.js
* Sidebar is no longer split into web/native/utilities, it's just an alphabetical list.
* Routes in the sidebar are now `/components/whatever` instead of `/components/web/whatever`. (Except utilities, wasn't sure if we wanted to do those too so I've left them out initially).
> [BPK-1346] Sidebar desegregation and new routes

- native/packages/react-native-bpk-component-section-list/index.js
- native/packages/react-native-bpk-component-section-list/package-lock.json
- native/packages/react-native-bpk-component-section-list/package.json
- native/packages/react-native-bpk-component-section-list/readme.md
- native/packages/react-native-bpk-component-section-list/src/BpkRadioIcon-test.android.js
- native/packages/react-native-bpk-component-section-list/src/BpkRadioIcon.android.js
- native/packages/react-native-bpk-component-section-list/src/BpkSectionList.js
- native/packages/react-native-bpk-component-section-list/src/BpkSectionListHeader-test.android.js
- native/packages/react-native-bpk-component-section-list/src/BpkSectionListHeader-test.common.js
- native/packages/react-native-bpk-component-section-list/src/BpkSectionListHeader-test.ios.js
- native/packages/react-native-bpk-component-section-list/src/BpkSectionListHeader.js
- native/packages/react-native-bpk-component-section-list/src/BpkSectionListItem-test.android.js
- native/packages/react-native-bpk-component-section-list/src/BpkSectionListItem-test.common.js
- native/packages/react-native-bpk-component-section-list/src/BpkSectionListItem-test.ios.js
- native/packages/react-native-bpk-component-section-list/src/BpkSectionListItem.android.js
- native/packages/react-native-bpk-component-section-list/src/BpkSectionListItem.ios.js
- native/packages/react-native-bpk-component-section-list/src/BpkSectionListItemSeparator-test.android.js
- native/packages/react-native-bpk-component-section-list/src/BpkSectionListItemSeparator-test.common.js
- native/packages/react-native-bpk-component-section-list/src/BpkSectionListItemSeparator-test.ios.js
- native/packages/react-native-bpk-component-section-list/src/BpkSectionListItemSeparator.js
- native/packages/react-native-bpk-component-section-list/src/__snapshots__/BpkRadioIcon-test.android.js.snap
- native/packages/react-native-bpk-component-section-list/src/__snapshots__/BpkSectionListHeader-test.android.js.snap
- native/packages/react-native-bpk-component-section-list/src/__snapshots__/BpkSectionListHeader-test.ios.js.snap
- native/packages/react-native-bpk-component-section-list/src/__snapshots__/BpkSectionListItem-test.android.js.snap
- native/packages/react-native-bpk-component-section-list/src/__snapshots__/BpkSectionListItem-test.ios.js.snap
- native/packages/react-native-bpk-component-section-list/src/__snapshots__/BpkSectionListItemSeparator-test.android.js.snap
- native/packages/react-native-bpk-component-section-list/src/__snapshots__/BpkSectionListItemSeparator-test.ios.js.snap
- native/packages/react-native-bpk-component-section-list/src/common-types.js
- native/packages/react-native-bpk-component-section-list/stories.js
- native/storybook/storybook.js
* New package `react-native-bpk-component-section-list`.
* Design follows UI conventions for iOS and Android. There's a JIRA to update Sketch to match this, as the Android one doesn't follow this.
* Docs and screenshots to come in a follow up PR.
> [BPK-1492] Add native BpkSectionList component

- native/packages/react-native-bpk-component-flat-list/readme.md
- native/packages/react-native-bpk-component-flat-list/src/BpkFlatListItem.android.js
- native/packages/react-native-bpk-component-flat-list/src/BpkFlatListItem.ios.js
- native/packages/react-native-bpk-component-flat-list/stories.js
- native/packages/react-native-bpk-component-section-list/readme.md
- native/packages/react-native-bpk-component-section-list/src/BpkSectionListItem.android.js
- native/packages/react-native-bpk-component-section-list/src/BpkSectionListItem.ios.js
- native/packages/react-native-bpk-component-section-list/stories.js
* Override `shouldComponentUpdate` to only compare primitive props, as comparing `onPress` was causing long lists to be very slow.
* Add a storybook example for long lists for future performance testing.
> [No JIRA] Improve performance for BpkFlatListItem and BpkSectionListItem

- native/packages/react-native-bpk-component-flat-list/readme.md
- native/packages/react-native-bpk-component-flat-list/src/BpkFlatListItem.android.js
- native/packages/react-native-bpk-component-flat-list/src/BpkFlatListItem.ios.js
- native/packages/react-native-bpk-component-flat-list/stories.js
- native/packages/react-native-bpk-component-section-list/readme.md
- native/packages/react-native-bpk-component-section-list/src/BpkSectionListItem.android.js
- native/packages/react-native-bpk-component-section-list/src/BpkSectionListItem.ios.js
- native/packages/react-native-bpk-component-section-list/stories.js
Updated storybook and readme uses of `BpkFlatList` and `BpkSectionList` so that `PureComponent` can be used for list items, negating the need for our previous overriding of `shouldComponentUpdate`. 
Thanks @tiagoengel! ⭐️
> [No JIRA] Improve performance of BpkFlatList and BpkSectionList

- packages/bpk-docs/src/components/neo/PageHead/PageHead.js
- packages/bpk-docs/src/components/neo/PageHead/PageHead.scss
The anchor links title appears on all pages, not just components and therefore does not make sense to name 'Available configurations'. 'In this section' is more generic and can apply to all pages.
> [NO-JIRA]: Change anchor links title

- packages/bpk-docs/src/components/DocsPageBuilder/NeoDocsPageBuilder.js
- packages/bpk-docs/src/components/neo/PageHead/PageHead.js
* _In this section_ now only appears if `menu.length > 0`.
* `PageHead` only appears if there's a blurb or menu.
> [No JIRA] Refine pagehead in neo

- .storybook/config.js
- packages/bpk-component-section-list/index.js
- packages/bpk-component-section-list/package-lock.json
- packages/bpk-component-section-list/package.json
- packages/bpk-component-section-list/readme.md
- packages/bpk-component-section-list/src/BpkSectionList-test.js
- packages/bpk-component-section-list/src/BpkSectionList.js
- packages/bpk-component-section-list/src/BpkSectionListItem-test.js
- packages/bpk-component-section-list/src/BpkSectionListItem.js
- packages/bpk-component-section-list/src/BpkSectionListSection-test.js
- packages/bpk-component-section-list/src/BpkSectionListSection.js
- packages/bpk-component-section-list/src/__snapshots__/BpkSectionList-test.js.snap
- packages/bpk-component-section-list/src/__snapshots__/BpkSectionListItem-test.js.snap
- packages/bpk-component-section-list/src/__snapshots__/BpkSectionListSection-test.js.snap
- packages/bpk-component-section-list/src/bpk-section-list-item.scss
- packages/bpk-component-section-list/src/bpk-section-list-section.scss
- packages/bpk-component-section-list/stories.js
- unreleased.md
* Docs to come in a separate PR.
* In future there are going to be more options for this, e.g. title, subtitle, icons. Keeping one eye on that, I think this implementation leaves it loose enough that we can support that in future without making breaking changes.
* I also created three new mixins for adding both a top and bottom border simultaneously. In the end I didn't use them (see below for why) but I figured it's good to have them anyway, now I've already made them.
* One compromise I've made wrt the design is I've only added a bottom border. I originally had a top and bottom one, but then when they stack, you get a double border where the two components touch. I've made the assumption that just a bottom one is ok, because I think there will always be an instance of the header …
> [BPK-1546] Web section list components

- packages/bpk-docs/src/components/DocsPageBuilder/ComponentScreenshots.scss
> [BPK-1583] Apply max-width to neo screenshots

- packages/bpk-docs/src/components/DocsPageBuilder/NeoDocsPageBuilder.js
- packages/bpk-docs/src/components/DocsPageBuilder/NeoDocsPageBuilder.scss
- packages/bpk-docs/src/components/neo/AlternatingPageContent/AlternatingPageContent.js
- packages/bpk-docs/src/components/neo/DocsPageWrapper/DocsPageWrapper.js
- packages/bpk-docs/src/components/neo/PageHead/PageHead.js
- packages/bpk-docs/src/components/neo/PageHead/PageHead.scss
In #704 I removed some things from `NeoDocsPageBuilder` because I thought *all* pages were now 'wrapped' (inside an instance of `DocsPageWrapper`). Turns out this was wrong, because while all _component_ pages are wrapped, tokens and other pages are not.
This PR reverts lots of the previous PR to reinstate the correct appearance. It also fixes the issue where `window.title` wasn't always updated as users moved between pages.
**Before this PR**
**After this PR**
> [BPK-1581] Fix docs title issue

- packages/bpk-component-theme-toggle/src/theming.js
- packages/bpk-docs/src/layouts/NeoSideNavLayout/NavList.js
- packages/bpk-docs/src/layouts/NeoSideNavLayout/NavList.scss
- packages/bpk-docs/src/layouts/NeoSideNavLayout/SectionsList.scss
- packages/bpk-docs/src/themeableAttributes.js
> [BPK-1580] Add missing themes for the neo sidebar

- packages/bpk-docs/src/pages/DrawerPage/DrawerPage.js
During automatic tests we found the Drawer page had the tittle added twice to the page
this PR fixes it 🎉
> [NoJira] fix drawer page double title

- packages/bpk-docs/src/pages/BackpackReactScriptsPage/BackpackReactScriptsPage.js
The link to the changelog.md file of backpack-react-scripts in the new documentation page is broken (https://backpack.github.io/using/backpack-react-scripts)
> Fix backpack-react-scripts changelog.md url in new docs site #trivial

- scripts/npm/update-owners.sh
We can now provide the user we want to add and it ignores private packages (as those fail and break the script)
> [NO-JIRA] Update `update-owners` script

- .storybook/config.js
- packages/bpk-component-map/index.js
- packages/bpk-component-map/package-lock.json
- packages/bpk-component-map/package.json
- packages/bpk-component-map/readme.md
- packages/bpk-component-map/src/BpkMap.js
- packages/bpk-component-map/stories.js
- unreleased.md
I've taken the map component from #757 and pared it back so that it's a light wrapper around `react-google-maps`.
The storybook has been updated to reflect the new format. It means that consumers have to do slightly more work, but they have more flexibility and it matches the underlying API, meaning there's less code to maintain and less documentation to write.
**To do**
**Open questions**
* Is `export * from 'react-google-maps` ok? I don't know of anywhere else we do this. Alternatively we could export everything from the package manually.
* In `BpkMap` we're applying the HOCs. Maybe even this is too much and we shouldn't do that either, and just do `export default GoogleMap`.
> [BPK-1601] Add web map component

- packages/bpk-docs/src/components/neo/DocsPageWrapper/DocsPageWrapper.js
This was borked in IE as we were using the `Array.find()` method which is not supported. I have lifted MDN's polyfil to work round this in browsers that do not have `Array.find()`.
> [BPK-1609] Fix deep linking navigation in IE

- packages/bpk-component-map/package.json
- packages/bpk-docs/package.json
- packages/bpk-docs/src/constants/routes.js
- packages/bpk-docs/src/layouts/links.js
- packages/bpk-docs/src/pages/MapPage/MapPage.js
- packages/bpk-docs/src/pages/MapPage/index.js
- packages/bpk-docs/src/routes/Routes.js
I've named the route `NEO_MAP` so as not to confuse people, but this is a Neo only thing (seeing as we now only have Neo!).
Right now there's a very minimal example, we can add more later when we add functionality on top of `react-google-maps`.
> [BPK-1601] Add docs for map component

- packages/bpk-component-navigation-bar/src/BpkNavigationBar.scss
- unreleased.md
`unset` used in the RTL selector wasn't being applied properly in IE 11. Changing to `auto` resolves this.
Screenshot before:
> [BPK-1597] Fix issue with nav bars in IE with RTL enabled

- native/packages/react-native-bpk-component-carousel/package.json
We need to wait for the new version of the `Pagination Dots` to release the carousel.
> [NO-JIRA] Update native carousel to private

- packages/bpk-docs/src/pages/BadgePage/BadgePage.js
> [BPK-1596] Fix badge docs page overflowing

- packages/bpk-component-button/readme.md
- packages/bpk-component-button/src/BpkButton-test.js
- packages/bpk-component-button/src/BpkButton.js
- packages/bpk-component-button/src/__snapshots__/BpkButton-test.js.snap
- packages/bpk-component-link/readme.md
- packages/bpk-component-link/src/BpkLink-test.js
- packages/bpk-component-link/src/BpkLink.js
- packages/bpk-component-link/src/__snapshots__/BpkLink-test.js.snap
- packages/bpk-component-loading-button/src/__snapshots__/BpkLoadingButton-test.js.snap
- unreleased.md
* Add `blank` prop to BpkButton so `rel="noopener noreferrer"` is set automatically.
* Automatically set `rel="noopener noreferrer"` also in BpkLink.
This was initiated from this Slack conversation: https://skyscanner.slack.com/archives/C0JHPDSSU/p1527687947000202
> Add "blank" prop to BpkButton

- packages/bpk-component-breakpoint/readme.md
- packages/bpk-component-breakpoint/src/BpkBreakpoint.js
- unreleased.md
About `children` prop in BpkBreakpoint:
* readme.md says it's a `node`: https://github.com/Skyscanner/backpack/blob/master/packages/bpk-component-breakpoint/readme.md
* The code says it’s a `func`: https://github.com/Skyscanner/backpack/blob/master/packages/bpk-component-breakpoint/src/BpkBreakpoint.js#L46
* `react-responsive` code says it any of both: https://github.com/contra/react-responsive/blob/master/src/index.js#L12
The inconsistency between readme.md and the code must be fixed.
Also, I guess there’s no reason in `BpkBreakpoint` for force just one of the two.
> Allow "node" as "children" in BpkBreakpoint

- packages/bpk-component-select/index.js
- packages/bpk-component-select/readme.md
- packages/bpk-component-select/src/BpkSelect-test.js
- packages/bpk-component-select/src/BpkSelect.js
- packages/bpk-component-select/src/__snapshots__/BpkSelect-test.js.snap
- packages/bpk-component-select/src/bpk-select.scss
- packages/bpk-component-select/stories.js
- unreleased.md
Docs will follow as separate PR
This adds an image render prop to the select box, if the image is set the select box will look like this
```
+------------------------+
|+----+ +--------------+ |
||    | |              | |
|+----+ +--------------+ |
+------------------------+
ASCII art By Matt
```
if no image is provided, it'll render the selecbox as it currently is (fully backward compatible)
In the storybook there is an example of usage
Note: The docked config has not been modified as we need design input for that
> [BPK-1612] select with image

- native/packages/react-native-bpk-component-carousel-indicator/stories.js
- native/packages/react-native-bpk-component-carousel/src/BpkCarousel.js
- native/packages/react-native-bpk-component-carousel/src/__snapshots__/BpkCarousel-test.android.js.snap
- native/packages/react-native-bpk-component-carousel/src/__snapshots__/BpkCarousel-test.ios.js.snap
- native/storybook/storybook.js
* Instead of `onMomentumScrollEnd`, we now use `onScroll`.
* `scrollEventThrottle` is how often `onScroll` fires. I couldn't find much conventional wisdom here on what's a good value for this that blends scroll performance with speed. It seems to perform well with the current value (tested on iOS and Android sims and we maintain 60fps), but this can be looked at further in the upcoming performance card.
> [BPK-1624] Use onScroll for carousel

- .storybook/addons.js
- .storybook/config.js
- .travis.yml
- package-lock.json
- package.json
- packages/bpk-animate-height/stories.js
This adds the built version of the storybook as part of the build process and will get deployed as part of the doc site under the `/playground` endpoint, it's a static app so it's just a folder name that can be changed.
To test it locally:
- check out this branch
- `npm i`
- `npm run docs:neo:dist`
- ☕️
- once the build is done use an http server to serve the content of the dist folder (if you don't have one installed run `npx http-server ./dist`
- go to http://127.0.0.1:8081/playground/?knob-Copy=Yes%2C%20he%20is%21&knob-Button%20copy=Is%20Matteo%20Awesome%3F&selectedKind=bpk-animate-height&selectedStory=Example&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs and you'll see the truth
> [NoJira] add storybook as part of the deployment process

- package.json
I just noticed that lint-staged is used to lint only js files. I think it would be very useful (at least for contributors) to lint also scss files.
> Lint scss files on commit

- package-lock.json
- package.json
- packages/bpk-component-image/src/withLazyLoading.js
- scripts/release-process/upcoming-changes.js
This updates prettier to the latest version (and fixes a couple of formatting errors because of the version change)
the reason for this update is not only regular housekeeping but better markdown support (https://github.com/prettier/prettier/blob/master/CHANGELOG.md#1135)
> [NoJira] update prettier

- native/packages/react-native-bpk-component-text/src/BpkText-test.ios.js
- native/packages/react-native-bpk-component-text/src/BpkText.js
- native/packages/react-native-bpk-component-text/src/__snapshots__/BpkText-test.ios.js.snap
- unreleased.md
On iOS emphasize is not supported when supplying xxl for the `textStyle`
with this change we no longer incorrectly apply a lower font weight
style in this configuration.
> [No JIRA] Improve invalid BpkText prop combo

- native/packages/react-native-bpk-component-carousel-indicator/package-lock.json
- native/packages/react-native-bpk-component-carousel-indicator/package.json
- native/packages/react-native-bpk-component-carousel-indicator/src/BpkCarouselIndicatorDot.js
- native/packages/react-native-bpk-component-carousel/src/BpkCarousel.js
- native/packages/react-native-bpk-component-carousel/src/__snapshots__/BpkCarousel-test.android.js.snap
- native/packages/react-native-bpk-component-carousel/src/__snapshots__/BpkCarousel-test.ios.js.snap
Part of this fix was done in the transitiongroup lib: see https://github.com/Skyscanner/react-native-transitiongroup/commit/da2ef6e710c85f1466cd933bb9cbd774b86a6b67
> [BPK-1640] Improve carousel indicator performance

- .travis.yml
- scripts/check-pristine-state
Unstaged changes means that something has went wrong: either the user has forgotten to check in intentional changes or we have an environmental build issue.
(script borrowed from https://github.com/Skyscanner/backpack-android/blob/master/scripts/check-pristine-state)
> [nojira] Add travis check for unstaged changes

- native/packages/react-native-bpk-component-button-link/package.json
- unreleased.md
A peer of 0.52.0 is overly strict because it doesn't match 0.53.0 etc
due to the stricter caret behaviour for pre-1.0.0 versions.
> [No JIRA] Loosen react native peer depedency

- scripts/check-pristine-state
This is so that we can do things like:
```
./check-pristine-state package-lock.json
```
And it'll ignore `some-arbitrary-path/package.json`.
> [No JIRA] Use endsWith so that ignores work in more cases

- contributing.md
- native/package.json
- readme.md
Diff is going to be quite hard to read, so I recommend just looking at the file directly: https://github.com/Skyscanner/backpack/blob/BPK-1598-contribution-guide/contributing.md
It's been separated into more of a flow. Previously it was very web heavy, with a React Native bit in its own section. With this PR, RN is integrated into the setup instructions throughout.
I'm liberally using `details` elements. May be controversial.
I've also tried to make this a lot more focused on the code side of things. I've removed a lot of the philosophical side (e.g. should `x` be in Backpack) because I feel that's covered well by our internal FAQ. 
The 'adding a new component' part has been largely left alone, as I think it's quite good already, and I'd also like to implement @k0nserv's in a future PR …
> [BPK-1598] Contribution guide improvements

- packages/bpk-docs/src/pages/CalendarPage/CalendarPage.js
- packages/bpk-docs/src/pages/CalendarPage/calendar-page.scss
[Edit by Matteo]
I've updated the css slightly to center the calendar on mobile view, it also gave me the change to finally understand how flex works:
Screenshot:
> [BPK-1596] Fix calendar docs page on narrow devices

- packages/bpk-component-map/index.js
- packages/bpk-component-map/package-lock.json
- packages/bpk-component-map/package.json
- packages/bpk-component-map/readme.md
- packages/bpk-component-map/src/BpkMap.js
- packages/bpk-component-map/src/BpkOverlayView.js
- packages/bpk-component-map/src/DefaultLoadingElement.js
- packages/bpk-component-map/src/DefaultLoadingElement.scss
- packages/bpk-component-map/src/common-types.js
- packages/bpk-component-map/src/withGoogleMapsScript.js
- packages/bpk-component-map/stories.js
- packages/bpk-docs/src/pages/MapPage/MapPage.js
- packages/bpk-docs/src/pages/MapPage/MapPage.scss
- unreleased.md
Previously, `BpkMap` was a thin layer around `GoogleMap`. Now, I've whitelisted props on it to make the API closer to the map we use in React Native. For example, `onZoomChanged()` from `GoogleMap` is now `onZoom(newZoomLevel)`.
I've also removed all the exports from `react-google-map` that we were re-exporting previously. Because one of these exports, `OverlayView`, was already in use by consumers, I've created `BpkOverlayView` to serve this use case. The code for it is based on the code that Blue Dolphin did in their app.
I've deliberately called the component `BpkOverlayView` and **not** `BpkMapMarker` to leave scope for adding a simpler marker component in future.
The readme, storybook and docs have been updated to suit this new way of doing things.
**Other things**
* Added a default …
> [BPK-1630] Enhance map component

- lerna.json
- packages/bpk-component-boilerplate/index.js
- packages/bpk-component-boilerplate/package-lock.json
- packages/bpk-component-boilerplate/package.json
- packages/bpk-component-boilerplate/readme.md
- packages/bpk-component-boilerplate/src/BpkBoilerplate-test.js
- packages/bpk-component-boilerplate/src/BpkBoilerplate.js
- packages/bpk-component-boilerplate/src/BpkBoilerplate.scss
- packages/bpk-component-boilerplate/src/__snapshots__/BpkBoilerplate-test.js.snap
- packages/bpk-component-boilerplate/stories.js
The idea here is that we can point users to this package from `contributing.md` and then it's a bit more self documenting. We can also use this ourselves.
We'll have to keep this in line with our conventions etc, but we don't change things that often, and we already have to keep the written-down guide in `contributing.md` up to date. Keeping some code up to date should be easier than keeping documentation up to date, too.
My plan is to do two more PRs after this:
1. The same as this but for React Native.
2. Refactor `contributing.md` a little more to point to these packages.
> [No JIRA] Add boilerplate package

- .storybook/config.js
- contributing.md
- native/storybook/storybook.js
- package-lock.json
- package.json
- packages/bpk-component-boilerplate/package.json
- packages/bpk-component-boilerplate/readme.md
- scripts/npm/create-component.js
Now we have the boilerplate component, here's a basic CLI for creating new components.
It does the following:
* Makes a copy of `bpk-component-boilerplate` or `react-native-bpk-component-boilerplate` with the new component name.
* Renames the files within appropriately.
* Replaces instances of `boilerplate` within files.
* Adds it to the storybook config.
* Lints the new folder and the storybook config with `--fix` to fix any formatting errors and run Prettier.
* Tells the user how to run tests and storybook.
You run it like this:
The cool thing about this is that not only is it useful for us, it also means we can remove some of `contributing.md` because it's self evident by using this CLI (for example, the part where we tell them how to add to the storybook config).
My Bash skillz aren't …
> [No JIRA] Add CLI for creating components

- packages/bpk-component-infinite-scroll/readme.md
`withInfiniteScroll` is the default export of `bpk-component-infinite-scroll`, so import statements from the documentation will fail with the following error:
```
'bpk-component-infinite-scroll' does not contain an export named 'withInfiniteScroll'.
```
This PR fixes all incorrect import statements in the infinite scroll documentation.
> Fix imports in bpk-component-infinite-scroll documentation

- dangerfile.js
I think we all feel that the above message is just visual noise at this point. We've tried a few different thresholds for it appearing and can't seem to get it right. The reality is that a lot of things we do require a lot of files to be changed! 
For example, a new component tends to involve 20-30 changes, adding docs can be ~15 now we have the native/web wrappers plus screenshots, and updating eslint involves at least 9,000,000 changes.
So, I think we should remove this check. Benefits of this:
* We do a good job of tracking PR size ourselves, so we should keep Danger for things that humans are less good at spotting (e.g. 'have you updated `unreleased.md`).
* Reducing noise from Danger means that the times it does have something to say are more powerful.
> [No JIRA] Remove large PR check from Danger

- packages/bpk-docs/src/components/DocsPageBuilder/DocsPageBuilder.js
- packages/bpk-docs/src/components/DocsPageBuilder/PlatformSwitchingContent.js
- packages/bpk-docs/src/pages/TypesettingPage/TypesettingPage.js
This adds a 'font weight' section to the _Typesetting_ page. It's already been approved by Will in person.
In order to make the copy change when the platform does, I piggybacked off of the `tokenSwitcher` logic to add a `platformSwitchingContent` prop to `DocsPageBuilder.components`. It functions exactly like `tokenMap`, except it can take any arbitrary content. It's a bit messy feeling but, y'know..it's `DocsPageBuilder.js`...
**Note:** We could do a refactor to make `tokenMap` use this new `PlatformSwitchingContent` component, but it would be a relatively large refactor, so I think it best if we handle that another time.
> [BPK-1727] Add font weight documentation

- .eslintrc
- package-lock.json
- package.json
This removes `react/destructuring-assignment` and updates `eslint-config-skyscanner-with-prettier` to the latest and greatest 
A reminder, the removed rule is not a default in `eslint-config-skyscanner-with-prettier` dependency of `eslint-config-skyscanner`
> [BPK-1725] update eslint skyscanner config with prettier

- package-lock.json
- packages/bpk-component-slider/package-lock.json
- packages/bpk-component-slider/package.json
- packages/bpk-component-slider/src/BpkSlider-test.js
- packages/bpk-component-slider/src/__snapshots__/BpkSlider-test.js.snap
- unreleased.md
The bug in BPK-1699 is resolved by upgrading to the latest version of `react-slider`. `react-slider` now has a peer dependency on React of `^16.2`, but it still works fine with React 15 in my tests
> [BPK-1699] Update react-slider version

- native/packages/react-native-bpk-component-button/index.js
- native/packages/react-native-bpk-component-button/readme.md
- native/packages/react-native-bpk-component-button/src/BpkButton-test.common.js
- native/packages/react-native-bpk-component-button/src/BpkButton.android.js
- native/packages/react-native-bpk-component-button/src/BpkButton.ios.js
- native/packages/react-native-bpk-component-button/src/__snapshots__/BpkButton-test.android.js.snap
- native/packages/react-native-bpk-component-button/src/__snapshots__/BpkButton-test.ios.js.snap
- native/packages/react-native-bpk-component-button/src/common-types.js
- native/packages/react-native-bpk-component-button/src/styles.js
- native/packages/react-native-bpk-component-button/src/utils.js
- native/packages/react-native-bpk-component-button/stories.js
- native/packages/react-native-bpk-component-nudger/src/__snapshots__/BpkNudger-test.android.js.snap
- native/packages/react-native-bpk-component-nudger/src/__snapshots__/BpkNudger-test.ios.js.snap
- unreleased.md
* Added `centerLeading` and `centerTrailing` values to the `iconAlignment` prop.
* Added story to show all the icon alignments (screenshot of it is below).
* Added `BUTTON_TYPES` and `ICON_ALIGNMENTS` exports so consumers can make use of them instead of using raw strings (updated readme, tests and stories to reflect this).
Don't look too closely at the code because it's the worst. I'm going to refactor this **soon**. Promise.
> [BPK-1750] Add new alignment props to BpkButton

- packages/bpk-component-ticket/src/bpk-ticket.scss
- packages/bpk-component-ticket/stories.js
- unreleased.md
On our docs site, the hover state isn't being applied (see https://backpack.github.io/components/ticket/?platform=web#default).
I added `z-index: 0` to the outer div and now it works ¯\\_(ツ)_/¯
This shouldn't cause any issues with existing code, as z-index is relative. Also, I added this manually to day view using Chrome dev tools and it didn't break anything.
> [BPK-1733] Small ticket improvements

- packages/bpk-component-ticket/src/bpk-ticket.scss
- unreleased.md
Reverts Skyscanner/backpack#941
This is breaking the hover shadow.
> Revert "[BPK-1733] Ticket images"

- packages/bpk-component-image/src/BpkImage.js
- packages/bpk-component-image/src/__snapshots__/BpkImage-test.js.snap
- packages/bpk-component-image/src/withLazyLoading.js
- unreleased.md
I have a video comparing before and after if you want check the difference 🙂
> [BPK-1724] Fix image loading behaviour in mobile safari

- packages/bpk-component-scrollable-calendar/index.js
- packages/bpk-component-scrollable-calendar/package-lock.json
- packages/bpk-component-scrollable-calendar/package.json
- packages/bpk-component-scrollable-calendar/readme.md
- packages/bpk-component-scrollable-calendar/src/BpkScrollableCalendar-test.js
- packages/bpk-component-scrollable-calendar/src/BpkScrollableCalendar.js
- packages/bpk-component-scrollable-calendar/src/BpkScrollableCalendar.scss
- packages/bpk-component-scrollable-calendar/src/__snapshots__/BpkScrollableCalendar-test.js.snap
- packages/bpk-component-scrollable-calendar/stories.js
- made the component private,
- removed dependencies on bpk components from package-lock
- renamed comoponent to bpk-scrollable-calendar
- added "private": true to package.json
> Fixed dependencies and changed name for Scrollable Calendar

- UNRELEASED.md
- packages/bpk-scrim-utils/src/bpk-scrim.scss
The animation for BpkScrim behind modals is not visible as the animation duration is so short. Increasing it makes the scrim fade instead of just appearing, making it less visually jarring (especially for mobile modals)
I've attached some videos below with the scrim turned red for clarity. Thoughts?
Before:
https://www.dropbox.com/s/utwkq6w5hn2fdj2/before.mov?dl=0
With no scrim:
﻿https://www.dropbox.com/s/vpopfkmb6d8a1eh/after.mov?dl=0
With a fading scrim:
﻿https://www.dropbox.com/s/n5iana9bh8xxs6m/after_2.mov?dl=0
> [NO-JIRA] Fix modal scrim animation

- packages/bpk-mixins/src/mixins/_breakpoints.scss
The examples given use parentheses, but `stylelint` is set to error with:
```
Unexpected parentheses in argumentless mixin "bpk-breakpoint-above-mobile" call   scss/at-mixin-argumentless-call-parentheses
```
> Remove Breakpoint Mixin argumentless-call-parentheses

- package.json
I think an `unreleased.md` entry is overkill as this should not affect consumers.
To test this out, you can run this command which will set the system timezone between test runs:
`npm run jest Calendar && sudo systemsetup -settimezone America/Campo_Grande && sleep 3 && npm run jest Calendar && sudo systemsetup -settimezone Australia/Adelaide && sleep 3 && npm run jest Calendar && sudo systemsetup -settimezone Europe/London`
And to run all tests:
`npm run test && sudo systemsetup -settimezone America/Campo_Grande && sleep 3 && npm run test && sudo systemsetup -settimezone Australia/Adelaide && sleep 3 && npm run test && sudo systemsetup -settimezone Europe/London`
> [BPK-1783] Fix test snapshot differences between timezones

- packages/bpk-component-popover/src/BpkPopoverPortal-test.js
- packages/bpk-react-utils/src/Portal-test.js
This PR is in preparation for upgrading to React 16. It modifies the Portal component tests to stop relying on React's rendering to happen in a certain order (`onRender` / `onOpen` are the main culprits here). Instead we rely on Enzymes `update` method to ensure all updates have been made.
> [BPK-1751] Use enzyme's `update` method

- UNRELEASED.md
- native/packages/react-native-bpk-component-phone-input/src/BpkPhoneNumberInput.js
- native/packages/react-native-bpk-component-phone-input/src/common-types.js
`PropType.shape` expect an object in (https://reactjs.org/docs/typechecking-with-proptypes.html) in the phone input we were spreading an object and somehow was working but with babel 7 that's not the case anymore so here's a fix
I've done some due diligence of checking the whole codebase for similar error  and I didn't find any
> [BPK-1855] fix prop type spreading

- UNRELEASED.md
- packages/bpk-component-datatable/src/BpkDataTable.js
To see this issue, open [any DataTable in Storybook](https://backpack.github.io/storybook/?knob-Copy=Lorem%20ipsum%20dolor%20sit%20amet%2C%20consectetuer%20adipiscing%20elit.%20Aenean%20commodo%0Aligula%20eget%20dolor.%20Aenean%20massa.%20Cum%20sociis%20natoque%20penatibus%20et%20magnis%20dis%0Aparturient%20montes%2C%20nascetur%20ridiculus%20mus.&knob-Button%20copy=Toggle%20height%21&selectedKind=bpk-component-datatable&selectedStory=Autowidth%20Example&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs) and click on any of the headers
Before:
After:
> [NO-JIRA] Fix Data table sorting

- native/packages/react-native-bpk-theming/package.json
- native/packages/react-native-bpk-theming/src/BpkThemeProvider-test.common.js
- native/packages/react-native-bpk-theming/src/__snapshots__/BpkThemeProvider-test.android.js.snap
- native/packages/react-native-bpk-theming/src/__snapshots__/BpkThemeProvider-test.ios.js.snap
- native/packages/react-native-bpk-theming/stories.js
This PR fixes the annoying cyclic dependency warning that lerna produces on `npm install` (`npm run bootstrap`).
> [NOJIRA] - Get rid of lerna cyclic dependency warning.

- packages/bpk-component-scrollable-calendar/src/bpk-scrollable-calendar-grid-list.scss
What: Fix the way height is handled for scrollable calendar grid
Why: AutoSizer did not work with original way of overriding grid's height. Now gridClassName works again.
> Fixed css (gridClassName) for scrollable calendar

- UNRELEASED.md
- packages/bpk-component-autosuggest/package-lock.json
- packages/bpk-component-autosuggest/package.json
Updates react-autosuggest to version 9.4.2 in bpk-component-autosuggest to fix the issue described in https://github.com/moroshko/react-autosuggest/pull/572
Current behaviour: After an autosuggest suggestion is selected, if the user clicks anywhere outside the autosuggest input that was used, it gains focus. If the autosuggest input was configured to lose focus after a suggestion is selected, what the user experiences is that an input that was not focused gains focus automatically.
Expected behaviour after the fix: After an autosuggest suggestion is selected, if the user clicks anywhere outside the autosuggest input that was used, it loses focus if it was focused.
> [TSS-3914] Update react-autosuggest to version 9.4.2 in bpk-component-autosuggest

- CONTRIBUTING.md
Just noticed the Node and npm versions are older than the ones defined in `package.json`
> Update Node and npm versions mentioned in CONTRIBUTING.md

- packages/bpk-component-checkbox/README.md
- packages/bpk-component-radio/README.md
Minor tweak to add in a prop defined in the component but not referred to in the readme.
> Add disabled prop to checkbox readme

- packages/bpk-docs/src/index.js
Required for pages that use promises to work on IE11 (e.g. the infinite scroll page)
> [NO-JIRA] Add promise polyfill to docs site

- README.md
The main readme is the place where to look for things, using backpack from the other side I notice how annoying is not  to have that link in the readme
> [backpack-love] Add changelog link to Readme

- UNRELEASED.md
- packages/bpk-component-badge/BadgeLayout.js
- packages/bpk-component-badge/package.json
- packages/bpk-component-badge/src/BpkBadge-test.js
- packages/bpk-component-badge/src/__snapshots__/BpkBadge-test.js.snap
- packages/bpk-component-badge/stories.js
- packages/bpk-docs/src/pages/WebBadgePage/BadgePage.js
- packages/bpk-mixins/src/mixins/_badges.scss
**Summary**
When a badge contains an icon, we constrain it to 16x16, add some margin to separate it from the text and increase the badge height to 20px.
**Details**
As our icons don't have a class name and use an inline style attribute, I've had to write some horrible CSS to target all SVGs and adds width and height using `!important`.
The only other way I can think of doing this is to add logic inside the badge component to find all children that are SVGs and then manually add a style prop to override the existing one. But it feels a bit complex when CSS can do the job.
Sidenote: Should we add a data attribute to our icon SVGs so that they can be targeted easier in the future?
> [BPK-2073] Constrain icons used inside badges to 16x16

- UNRELEASED.md
- packages/bpk-component-calendar/README.md
- packages/bpk-component-calendar/src/BpkCalendarGrid.js
- packages/bpk-component-calendar/src/Week.js
- packages/bpk-component-calendar/src/__snapshots__/composeCalendar-test.js.snap
- packages/bpk-component-calendar/src/composeCalendar-test.js
- packages/bpk-component-calendar/src/composeCalendar.js
At the moment with composeCalendar you can specify custom components for each piece of the calendar but there's no way to efficiently pass custom properties through to them. This provides a mechanism for that.
> Allow passing custom properties to calendar components

- UNRELEASED.md
- native/packages/react-native-bpk-component-touchable-overlay/README.md
- native/packages/react-native-bpk-component-touchable-overlay/src/BpkTouchableOverlay.js
We need touchable overlay to support `lg` border radius in order to achieve [BPK-2058](https://gojira.skyscanner.net/browse/BPK-2058)
> [NO-JIRA] Support touchable overlay with lg border radius

- UNRELEASED.md
- packages/bpk-component-calendar/src/BpkCalendarDate-test.js
- packages/bpk-component-calendar/src/BpkCalendarDate.js
- packages/bpk-component-calendar/src/__snapshots__/BpkCalendarDate-test.js.snap
This adds the ability to add a custom className to a BpkCalendarDate for people doing custom stuff to the calendar.
> Add className property to BpkCalendarDate

- UNRELEASED.md
- native/packages/react-native-bpk-component-navigation-bar/src/BpkNavigationBar.android.js
Using the `StatusBar`'s imperative API was causing long lasting changes
to any app using `BpkNavigationBar` on Android even after the component
was no longer being rendered. With this change the status bar is
restored when the component is unmounted.
> [No JIRA] Use StatusBar component API

- UNRELEASED.md
- native/packages/react-native-bpk-component-navigation-bar/src/BpkNavigationBar.android.js
The use of `StatusBar` causes issues when integrated into a full app and
it's not worth keeping because it makes `BpkNavigationBar` as a whole
unusable.
> [No JIRA] Remove the use of `StatusBar` on Android

- UNRELEASED.md
- packages/bpk-component-scrollable-calendar/package-lock.json
- packages/bpk-component-scrollable-calendar/package.json
- packages/bpk-component-scrollable-calendar/src/BpkScrollableCalendarGridList.js
- packages/bpk-component-scrollable-calendar/src/__snapshots__/BpkScrollableCalendar-test.js.snap
- packages/bpk-component-scrollable-calendar/src/__snapshots__/BpkScrollableCalendarGridList-test.js.snap
what: revert scrollable calendar back to using react-virtualized,
why: new implementation has a bug of not automatically scrolling to the selected day. also the experience is not good
we are working on improving the component here: 
https://gojira.skyscanner.net/browse/TSS-4044
https://gojira.skyscanner.net/browse/BPK-2083
> Revert "Use BpkInfiniteScroll instead of react-virtualized"

- README.md
Rationale: 
- Top level headings for individual links are superfluous. 
- The word "our" when referring to the changelog bugged me
> [NOJIRA] tweak docs / changelog links in README

- packages/bpk-docs/src/bag-check-bookmarklet/index.js
- packages/bpk-docs/src/constants/routes.js
- packages/bpk-docs/src/helpers/globals-helper-test.js
- packages/bpk-docs/src/helpers/globals-helper.js
- packages/bpk-docs/src/pages/BagCheckPage/BagCheckPage.js
- packages/bpk-docs/src/pages/BagCheckPage/bag-check-page.scss
- packages/bpk-docs/src/pages/BagCheckPage/index.js
- packages/bpk-docs/src/routes/Routes.js
- packages/bpk-docs/src/template.js
- webpack.config.babel.js
I've added a new page in `/bag-check-bookmarklet` that looks like this:
I've implemented this a bit different from the original implementation, which was using the raw file loader, because that meant we wouldn't be able to update the code that downloads the bookmarklet since it would be inlined there. With the current implementation we can update both the bag check lib and the code that loads it, and it will be picked up automatically by everyone that has the link.
> [BPK-2079] Activate the bagcheck link

- UNRELEASED.md
- native/packages/react-native-bpk-component-text/src/common-types.js
Removes the following warning:
```
Warning: Failed prop type: Calling PropTypes validators directly is not supported by the `prop-types` package. Use `PropTypes.checkPropTypes()` to call them. Read more at http://fb.me/use-check-prop-types
in BpkText
```
Doing a browser search in the build log yields:
_Before:_
_After:_
> [BPK-2117] Fix RN text component prop type warning

- CONTRIBUTING.md
- package.json
So we can use `npm run release` across monorepo, Android and iOS repos.
> [No JIRA] Add release script for consistency

- packages/bpk-tokens/src/android/base/typography.json
- packages/bpk-tokens/src/ios/base/box-shadows.json
- packages/bpk-tokens/src/ios/base/touchables.json
- packages/bpk-tokens/src/ios/base/typography.json
- packages/bpk-tokens/src/web/base/buttons.json
- packages/bpk-tokens/src/web/base/calendar.json
- packages/bpk-tokens/src/web/base/modals.json
- packages/bpk-tokens/src/web/base/z-index.json
- packages/bpk-tokens/tokens/base.ios.json
- packages/bpk-tokens/tokens/base.raw.android.json
- packages/bpk-tokens/tokens/base.raw.ios.json
- packages/bpk-tokens/tokens/base.raw.json
We need this to hide deprecated tokens in the docs site. According to theo's doc the meta prop is only used in transformers and removed before sending the token to formatters. https://www.npmjs.com/package/theo
**NOTE** I didn't update UNRELEASED.md because I don't think this is relevant to users.
> [BPK-2062] Move deprecated prop into the root object for tokens

- UNRELEASED.md
- packages/bpk-component-scrollable-calendar/src/BpkScrollableCalendarGridList.js
- packages/bpk-component-scrollable-calendar/src/__snapshots__/BpkScrollableCalendar-test.js.snap
- packages/bpk-component-scrollable-calendar/src/__snapshots__/BpkScrollableCalendarGridList-test.js.snap
- packages/bpk-component-scrollable-calendar/src/bpk-scrollable-calendar-grid-list.scss
- packages/bpk-component-scrollable-calendar/stories.js
Why:
1. It's unnecessary.
2. It has no className property, making it impossible to customize
with additional CSS classes.
> Remove the list--strip element from the scrollable calendar

- UNRELEASED.md
- packages/bpk-component-image/src/BpkBackgroundImage.js
- packages/bpk-component-image/src/__snapshots__/BpkBackgroundImage-test.js.snap
- packages/bpk-component-image/src/bpk-background-image.scss
- packages/bpk-component-image/stories.js
The inner content wasn't displaying because positioned elements (that is to say any elements with the CSS property `position`) are displayed in front of non-positioned elements. The image was positioned but the inner content was not. [Further reading &raquo;](https://philipwalton.com/articles/what-no-one-told-you-about-z-index/)
So I fixed this by wrapping the inner content in a positioned element.
Two possible pure-CSS ways to fix this would have been to:
1) Use the sibling selector alongside the background image to apply the positioning.
```
&__img {
@include bpk-image__img;
+ * {
position: relative;
}
}
```
2) Apply a negative z-index to the image:
```
&__img {
z-index: -1;
@include bpk-image__img;
}
```
However those feel hacky and I prefer the explicit approach of adding a wrapper.
> [BPK-2120] Fix issue with content in BpkBackgroundImage

- UNRELEASED.md
- packages/bpk-component-calendar/src/date-utils.js
- packages/bpk-component-scrollable-calendar/package-lock.json
- packages/bpk-component-scrollable-calendar/package.json
- packages/bpk-component-scrollable-calendar/src/BpkScrollableCalendar-test.js
- packages/bpk-component-scrollable-calendar/src/BpkScrollableCalendarGridList-test.js
- packages/bpk-component-scrollable-calendar/src/BpkScrollableCalendarGridList.js
- packages/bpk-component-scrollable-calendar/src/__snapshots__/BpkScrollableCalendar-test.js.snap
- packages/bpk-component-scrollable-calendar/src/__snapshots__/BpkScrollableCalendarGridList-test.js.snap
- packages/bpk-component-scrollable-calendar/stories.js
This PR doesn't actually address anything performance related, but it does replace `react-virtualised` with `react-window` (a new, cut-down version written from scratch).
The improvement in prod bundle size is approximately 64.5kb => 2.8kb!
From testing so far, performance seems to at least be similar to before. See profiling screenshots below.
Note that profiling is only available in React 16.5 - so I created [this repo](https://github.com/georgegillams/bpk-calendar-performance-react-16.5) for profiling the component.
The `react-window` API is somewhat different to `react-virtualized`. It requires the height to display at (in pixels) as well as the heights of each item.
To get the item heights, I have added code to the constructor that calculates the heights of the grids based on the …
> [BPK-2083] calendar performance

- UNRELEASED.md
- packages/bpk-component-infinite-scroll/README.md
- packages/bpk-component-infinite-scroll/src/__snapshots__/withInfiniteScroll-test.js.snap
- packages/bpk-component-infinite-scroll/src/withInfiniteScroll-test.js
- packages/bpk-component-infinite-scroll/src/withInfiniteScroll.js
Current implementation of the infinite scroll does not allow using big elements, like an animated card placeholder, as a loading component. The reason is that the pagination is only triggered if the loading component is visible at 0.99%. In small devices that may never be the case if the element is bigger than the viewport which results in a broken infinite scroll.
This PR introduces a prop to the component to require visibility of smaller parts of the element to trigger the pagination.
Default value keeps the current behaviour to avoid any potential conflict with existing usages of the component.
> add a different percentage of intersection prop for infinite scroll loading component

- UNRELEASED.md
- packages/bpk-component-scrollable-calendar/src/BpkScrollableCalendarGridList.js
To allow this to be tested, I have created a repo using react 15.
If you run the test app, you'll see an error about refs. If you copy this version of `scrollable-calendar` into `node_modules` you'll see it works 👍 
https://github.com/georgegillams/test-react-15-scroll-calendar
> [NO-JIRA] Fix scrollable calendar refs for react 15

- packages/bpk-docs/src/components/DocsPageWrapper/DocsPageWrapper.js
- packages/bpk-docs/src/helpers/storage-helper.js
- packages/bpk-docs/src/layouts/SideNavLayout/NavList.js
Behaviour:
- If a user navigates to a component page with no preference already set, it will show the first platform available. Their preference will remain unset.
- If a user navigates to a component page with a preference already set, it will show their prefered platform (iff it exists), falling back to the first one available. Their preference will not change either way.
- If a user navigates to a component page with the platform specified as a URL parameter, then the URL parameter will take precedence. Their current preference will remain, but won't be used in favour of the URL parameter.
- If a user selects a platform from the horizontal nav, their platform preference will be set/updated
- If a user selects a platform from the nav filter (Web or Native), their platform preference …
> [BPK-2168] Allow docs to remember selected platform

- UNRELEASED.md
- packages/bpk-component-calendar/src/Week-test.js
- packages/bpk-component-calendar/src/Week.js
My last commit had a bug in it. areRangesOverlapping is not inclusive
(uses strict less-than comparison) and so right now changing the selection
from the very edge doesn't work properly.
To fix it I just enlarged the range we compare against by 1ms in either
direction.
> Shift first and last date by 1ms to deal with edge cases

- packages/bpk-component-calendar/README.md
- packages/bpk-component-datepicker/README.md
As you can see here, the proptype for `daysOfWeek` should in fact be an array of week objects.
https://github.com/Skyscanner/backpack/blob/master/packages/bpk-component-calendar/src/custom-proptypes.js#L28
> [NO-JIRA] Fix date-picker README

- packages/bpk-docs/src/components/DocsPageBuilder/TokenSwitcher.js
- packages/bpk-docs/src/components/DocsPageWrapper/DocsPageWrapper.js
I realised this morning that when I completed [BPK-2168](https://github.com/Skyscanner/backpack/pull/1298) I overlooked adding the platform-selection functionality to the tokens pages, although it is just as valid there.
> Use local storage for tokens platform switching

- UNRELEASED.md
- packages/bpk-component-breakpoint/package.json
Reverts React 16.3.0 breaking change introduced in https://github.com/Skyscanner/backpack/pull/1306.
> [NOJIRA] Downgrade react-responsive

- packages/bpk-docs/src/components/Heading/Heading.scss
This only affects narrower-width devices
> [BPK-2225] Heading spacing adjustment

- package.json
With this change, `npm run submodules:reset` will undo any accidentally committed changes to submodules, allowing us to keep our PR's cleaner 👍
> [NO-JIRA] Add helpful npm script

- UNRELEASED.md
- packages/bpk-component-calendar/src/__snapshots__/BpkCalendarGridTransition-test.js.snap
- packages/bpk-component-phone-input/README.md
- packages/bpk-component-phone-input/package.json
- packages/bpk-component-phone-input/src/BpkPhoneInput-test.js
- packages/bpk-component-phone-input/src/BpkPhoneInput.js
- packages/bpk-component-phone-input/src/BpkPhoneInput.scss
- packages/bpk-component-phone-input/src/__snapshots__/BpkPhoneInput-test.js.snap
- packages/bpk-component-phone-input/stories.js
- packages/bpk-docs/src/pages/PhoneInputPage/PhoneInputPage.js
As discussed with @georgegillams and @k0nserv this is a breaking change to `BpkPhoneInput`. It adds labels to both Dialing code `BpkSelect` and Telephone number `BpkInput`.
With long labels:
> Add labels to Phone Input component

- .spelling
- UNRELEASED.md
- packages/bpk-component-breadcrumb/README.md
- packages/bpk-component-breadcrumb/src/BpkBreadcrumbItem.js
- packages/bpk-component-map/README.md
- packages/bpk-component-map/src/BpkMapMarker-test.js
- packages/bpk-component-map/src/BpkMapMarker.js
- packages/bpk-component-map/src/__snapshots__/BpkMapMarker-test.js.snap
Like in other components, it might be useful to be able to send arbitrary props to another dom element rather than the root one.
In our case, we would need to set some attribute to run some acceptance tests.
> Add "buttonProps" prop to "BpkMapMarker"

- packages/bpk-docs/src/pages/ThemingPage/ThemingPage.js
Added to the Web list:
- Breadcrumb
- Navigation bar
- Pagination
- Popover
- Scrollable calendar
Added to the RN list:
- Flat list
- Nudger
- Progress
- Section list
I also removed the `?platform=web` part of the link URLs, as the docs now respects the user's prefered platform
> [NO-JIRA] Update list of themeable components

- CHANGELOG.md
- packages/bpk-stylesheets/README.md
- packages/bpk-stylesheets/base.css
- packages/bpk-stylesheets/index.scss
(NOTE: 2nd version of this PR as CI pipeline complained about package.json being altered and a merge from upstream did not fix it.)
This is a fix in tandem with a change to base-stylesheet to stop the global scss classes being rendered with hashes.
+ [/] Check this if you have read and followed the [contributing guidelines](https://github.com/Skyscanner/backpack/blob/master/CONTRIBUTING.md)
> Fixed non-global class inside global class in scss

- UNRELEASED.md
- packages/bpk-component-tooltip/README.md
- packages/bpk-component-tooltip/src/BpkTooltipPortal.js
- packages/bpk-component-tooltip/src/__snapshots__/BpkTooltipPortal-test.js.snap
Adds the `renderTarget` to `BpkTooltipPortal` to allow it being rendered inside any DOM element, just like `BpkPopoverPortal`.
+ [X] Check this if you have read and followed the [contributing guidelines](https://github.com/Skyscanner/backpack/blob/master/CONTRIBUTING.md)
> Add renderTarget to tooltip

- packages/bpk-mixins/src/mixins/_badges.scss
I noticed a possible "bug" in `BpkBadge`: currently the color is not set (only for `destructive` and `outline`) so the font color relies on the one defined in the parent. This can lead to the component not being rendered as expected if the base font color has been changed:
I think the font color should be defined in the component, to avoid side-effects. What do you think?
The change submitted is just a proposal to clearly show what I mean. Not sure if the correct implementation should define a new token for the color, use theming...
> Add a default font color to BpkBadge

- UNRELEASED.md
- packages/bpk-mixins/src/mixins/_forms.scss
Updated the mixins to change the styling of input fields to highlight red when an invalid input is entered into the fields.
The field will add a red border and the background will change red when incorrect entry is input, please see below screenshot as result of the change.
> [BPK-2350] Text input validation

- packages/bpk-docs/src/components/DocsPageBuilder/BpkMarkdownRenderer.scss
_Note the screenshots below use an extra-wide border to make things more visible..._
Currently the borders around our MD tables are cut off by the mobile scroll container. This is due to us uising `box-shadow` to apply borders, which are not included in width calculations.
This PR adds an actual `border` to the table elements, so that the browser includes the border width when calculating the size of the element.
> [NO-JIRA] Fix readme table borders

- UNRELEASED.md
- packages/bpk-component-input/src/BpkClearButton.js
- packages/bpk-component-input/src/BpkInput-test.js
- packages/bpk-component-input/src/BpkInput.js
- packages/bpk-component-input/src/__snapshots__/BpkInput-test.js.snap
We're building a dynamic form and we want to use clearable input fields. It would be good to use the same callback for all the fields:
```
onClear = evt => {
const { onChange } = this.props;
const { name } = evt.target;
onChange(name, null);
};
```
but the event target is the svg (not the input), so `evt.target.name` doesn't contain the field name.
This PR contains two possible ways of achieving this:
* Set `evt.target.name` to the input name
* Provide a second parameter to `onClear` with the input name
Would you be fine with any of these two proposals? Is there a better way to achieve this?
> When calling `onClear`, provide input `name`

- packages/bpk-docs/src/pages/AlignmentPage/AlignmentPage.js
Documentation was missing from where `colors` would be imported but in the code examples `colors` were being used. New users like myself might get confused when reading the docs.
> updates to specify where colors is imported from

- UNRELEASED.md
- packages/bpk-mixins/src/mixins/_forms.scss
We should set `max-width` on text-areas so that they behave in a predictable way when a user resizes them in-browser.
> [NO-JIRA] Fix text area widths

- .flowconfig
- UNRELEASED.md
- package.json
- packages/bpk-component-infinite-scroll/src/withInfiniteScroll-test.flow.js
- packages/bpk-component-infinite-scroll/src/withInfiniteScroll.js
- packages/bpk-component-infinite-scroll/stories.js
I've introduced a test file for flow here, the idea is to test if required and default props are working as expected.
Lines with the `$ExpectError` annotation will suppress the error in the next line, if any, or show a warning saying there are no errors in the next line, which means the flow typing is wrong as we are expecting an error.
Because it only throw a warning in this case I have also changed the build to fail if any warnings are shown, so if we break the flow typing in any way the build will fail.
_If you are curious about how we review, please read through the [code review guidelines](https://github.com/Skyscanner/backpack/blob/master/CO …
> [NO-JIRA] Fix flow for infinite scroll

- package.json
Now that the flow command has the `--max-warnings 0` flag `npm run flow stop` was not working, it should be just `flow stop`
> [NO-JIRA] Fix publish command

- UNRELEASED.md
- packages/bpk-react-utils/src/Portal-test.js
- packages/bpk-react-utils/src/Portal.js
I have a component that renders a BpkPopover component, with a render target that exists within the component rendering the popover and is accessed via a reference:
```js
<div ref={this.renderTargetRef}>
<div ref={this.targetRef}>
...
</div>
<BpkPopover
...
target={() => this.targetRef.current}
renderTarget={() => this.renderTargetRef.current}
...
/>
</div>
```
(_both refs are created using `React.createRef`, as mentioned here: https://reactjs.org/docs/refs-and-the-dom.html_) …
> Gracefully closes popover when render target is no longer present

- .spelling
- UNRELEASED.md
- packages/bpk-component-popover/src/BpkPopoverPortal.js
The type for `React.createRef` is `() => null | T`, with `T` being a type that inherits from `HTMLElement`.
This PR updates the types for the `target` and `renderTarget` props of `bpk-component-popover` to accept this type
> Fixes types for render and renderTarget to accept refs

- packages/bpk-docs/src/pages/DatepickerPage/DatepickerPage.js
- packages/bpk-docs/src/pages/InfiniteScrollPage/InfiniteScrollPage.js
- packages/bpk-docs/src/pages/WebCalendarPage/WebCalendarPage.js
Update some imports so that when we migrate the docs code to the new repo it can be done more easily.
> [NO-JIRA] Make docs imports ready for migration

- packages/bpk-component-text/src/BpkText-test.js
- packages/bpk-component-text/src/BpkText.js
Adds Flow typed Props definition in the same style as other backpack components. 
The optional props, such as `bold`, are not marked as `bold?: boolean` as 
> Flow will make sure that foo is optional if you have a default prop for foo.
https://flow.org/en/docs/react/components/#toc-using-default-props
`className` is marked as a maybe type, `className: ?string,`, as this supports `null` values and  its default value is `null`. This is done in the same style as in existing Backpack components.
-----
_If you are curious about how we review, please read through the [code review guidelines](https://github.com/Skyscanner/backpack/blob/master/CODE_REVIEW …
> [NoJira] Add Flow types for BpkText props

- .gitignore
- .travis.yml
- package.json
Separating the storybook deploy so that we can (later) remove the docs deploy steps without affecting how storybook is deployed
> [NO-JIRA] Add storybook deploy

- .spelling
- UNRELEASED.md
- packages/bpk-component-map/README.md
- packages/bpk-component-map/src/BpkMap.js
- packages/bpk-component-map/stories.js
Previously we set [`gestureHandling`](https://developers.google.com/maps/documentation/javascript/reference/map#MapOptions.gestureHandling) to `auto`. This created an issue when maps were placed inside modals, as they _should_ have been scrollable with one finger but instead get the 'use two fingers' overlay which was a bad experience for travellers. 
This PR adds a new prop to override the gesture handling so that in situations like this, developers can manually override to get the more desirable behaviour.
Here's a video to illustrate the difference:
Please note that this only applies to touchscreens. In the above video I'm emulating a touchscreen in Chrome.
> [No JIRA] Add `greedyGestureHandling` prop to BpkMap

- UNRELEASED.md
- packages/bpk-component-checkbox/src/BpkCheckbox.js
- packages/bpk-component-checkbox/src/__snapshots__/BpkCheckbox-test.js.snap
- packages/bpk-component-fieldset/src/__snapshots__/BpkFieldset-test.js.snap
Previously, when navigating through a page, you would first see/hear this:
And then this:
Now it will only select and read it once:
> [NO-JIRA] fix checkbox accessibility

- UNRELEASED.md
- packages/bpk-component-radio/src/BpkRadio.js
- packages/bpk-component-radio/src/__snapshots__/BpkRadio-test.js.snap
Before, the text element was able to be selected and read out independently of the radio button component:
Now they are treated as one:
> [NO-JIRA] fix radio button accessibility

- UNRELEASED.md
- packages/bpk-component-datepicker/src/BpkDatepicker-test.js
- packages/bpk-component-datepicker/src/BpkDatepicker.js
- packages/bpk-component-datepicker/src/__snapshots__/BpkDatepicker-test.js.snap
After selecting a date in `BpkDatepicker`, the text cursor is placed inside the text input field (although the value can’t be changed typing in it). Adding `readOnly: true` to the `inputProps` “fixes” this behaviour (the input field is still focused, but the text cursor is not in there anymore).
> BPK-2519 Add  to datepicker's input field by default

- packages/bpk-component-calendar/src/__snapshots__/BpkCalendarGridTransition-test.js.snap
- packages/bpk-component-infinite-scroll/src/__snapshots__/withInfiniteScroll-test.js.snap
- packages/bpk-component-infinite-scroll/src/withInfiniteScroll-test.js
- packages/bpk-component-infinite-scroll/src/withInfiniteScroll.js
- packages/bpk-component-infinite-scroll/stories.js
This will allow infinite scroll to be initialise with an empty data source
As I am not creating any new functionality tests have not been added, only one snapshot
Tested locally
> Infinite Scroll Use fetch items in update data

- .github/pull_request_template.md
- dangerfile.js
- meta.json
I think we can utilise Danger more than we currently are to improve the contribution process and remind us/consumers to do certain things, like cross-browser testing.
This PR:
- Moves the 'have you read the contribution guide' message to a Danger rule that is only shown to contributors.
- Sends a nice motivational message as well as a random gif to external contributors.
- Prints a checklist of browsers to check in when components have changed.
**This is a first step.** We can put more things in here later, but I thought this would be a good way to get the ball rolling.
There's a comment below from Backpack bot showing what users would see. I changed my github username in `meta.json` so Danger would think I was external, but ordinarily only external squad members would see this.
> [No JIRA] A bit of housekeeping on Danger

- packages/bpk-component-image/src/BpkImage.js
- packages/bpk-component-image/src/__snapshots__/BpkImage-test.js.snap
This PR adds the suppressHydrationWarning flag to BpkImage, allowing for the warning to be suppressed in special circumstances.
* Adds optional `suppressHydrationWarning` prop to BpkImage component
[React Docs on the suppressHydrationWarning flag](https://reactjs.org/docs/react-dom.html#hydrate)
> Fix warning message when hydrating BpkImage

- CHANGELOG.md
- CONTRIBUTING.md
- UNRELEASED.yaml
- package-lock.json
- package.json
- packages/bpk-component-card/src/BpkCard.js
- scripts/npm/UNRELEASED_CLEAN.yaml
- scripts/npm/auto-publish.js
Can test using `node scripts/npm/auto-publish.js --testing`
(The testing flag will mean it actually skips the publish bit)
**Now:** 
**Before merging:**
**Future:**
> [BPK-2610] Improve release process

- .spelling
- UNRELEASED.yaml
- packages/bpk-component-barchart/README.md
- packages/bpk-component-barchart/src/BpkBarchart-test.js
- packages/bpk-component-barchart/src/BpkBarchart.js
- packages/bpk-component-barchart/src/__snapshots__/BpkBarchart-test.js.snap
- packages/bpk-component-barchart/stories.js
The y axis domain is currently hardcoded to 0 and the height of the
largest bar.  This results in the inability to accurately show
percentage based data or small variations in large values.
+ [x] Tests
> Add `yAxisDomain` to barchart component

- UNRELEASED.yaml
- packages/bpk-component-button/src/BpkButton-test.js
- packages/bpk-component-button/src/BpkButton.js
- packages/bpk-component-button/src/__snapshots__/BpkButton-test.js.snap
We noticed that `BpkButton` would not accept the `disabled` prop when the `href` prop is present. This was tracked down to the code not respecting the `disabled` prop when a `href` prop is present.
This change checks the `disabled` prop before considering the `href` prop.
> [ABS-2199] Disables even when href prop present

- .storybook/webpack.config.js
Storybook wasn't working in IE11. I changed the `env` setting in the Webpack config for Storybook and it seems to be ok now 😄
> [BPK-2784] Add IE11 support to Storybook webpack config

- packages/bpk-component-mobile-scroll-container/stories.js
- packages/bpk-component-mobile-scroll-container/stories.scss
Added an example of using `BpkMobileScrollContainer`'s `leadingIndicatorClassName` and `trailingIndicatorClassName` props, to demonstrate to consumers.
> [No JIRA] Add example of using classnames

- UNRELEASED.yaml
- packages/bpk-mixins/src/mixins/_typography.scss
- packages/bpk-tokens/src/web/base/aliases.json
- packages/bpk-tokens/src/web/base/typography.json
- packages/bpk-tokens/tokens/base.common.js
- packages/bpk-tokens/tokens/base.default.scss
- packages/bpk-tokens/tokens/base.es6.js
- packages/bpk-tokens/tokens/base.raw.json
- packages/bpk-tokens/tokens/base.scss
- packages/bpk-tokens/tokens/breakpoints.raw.json
- packages/bpk-tokens/tokens/travelpro.raw.json
Adding a new bpk token for font weight of 900. The name is `bpk-font-weight-black`. 
Also adding mixins similar to `bpk-font-weight-bold`.
https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight#Common_weight_name_mapping
> BPK: Add Font Weight Black

- UNRELEASED.yaml
- packages/bpk-component-rating/src/BpkRating.js
- packages/bpk-component-rating/src/BpkRating.scss
- packages/bpk-component-rating/src/__snapshots__/BpkRating-test.js.snap
This PR fixes a spacing issue betweewn the rating component and text on the vertical variants
> [BPK-2812]: Patch for spacing issues

- UNRELEASED.yaml
- packages/bpk-component-rating/README.md
- packages/bpk-component-rating/src/BpkRating-test.js
- packages/bpk-component-rating/src/BpkRating.js
- packages/bpk-component-rating/src/__snapshots__/BpkRating-test.js.snap
- packages/bpk-component-rating/stories.js
Added support to the `BpkRating` component to support title only scenario.
> [BPK-2938]: Added title only support by making subtitle optional

- .spelling
- UNRELEASED.yaml
- packages/bpk-component-star-rating/README.md
- packages/bpk-component-star-rating/index.js
- packages/bpk-component-star-rating/src/BpkStarRating-test.js
- packages/bpk-component-star-rating/src/BpkStarRating.js
- packages/bpk-component-star-rating/src/__snapshots__/BpkStarRating-test.js.snap
- packages/bpk-component-star-rating/stories.js
Adds an optional prop to bpk-component-star-rating, `roundRating`. This defaults to false - if true, the rating is rounded to the nearest half star, instead of always being rounded down.
+ [x] Tests
> [ABS-2408]: Add 'roundRating' prop to Star Ratings

- UNRELEASED.yaml
- packages/bpk-component-accordion/src/BpkAccordionItem.js
- packages/bpk-component-accordion/src/__snapshots__/BpkAccordionItem-test.js.snap
- packages/bpk-component-accordion/src/__snapshots__/withAccordionItemState-test.js.snap
+ [x] Tests
Browser support
Please complete this list of browsers that you've checked this works in.
+ [ ] IE11
+ [ ] Edge
+ [x] Safari (iOS)
+ [x] Chrome (Android)
+ [x] Chrome (Desktop)
+ [x] Firefox (Desktop)
1) ARIA role must be appropriate for the element
2) ARIA attributes must conform to valid values
3) <dl> elements must only directly contain properly-ordered <dt> and <dd> groups, <script> or <template> elements
Also Tested on Android with Talkback, functionality is exact same.
> a11y fixes for accordion

- package.json
- scripts/publish-process/publish-css-tagged-packages.js
- scripts/publish-process/transform-js-scss-css-imports.js
- scripts/publish-process/util.js
Using tags alone to distinguish which packages ship with CSS is a bad idea. A NPM package tag is a 1-1 mapping from a tag name to a specific version. This means that every time we publish a package with the tag "css" we untag the previous css version. This means that there will be no way to distinguish between versions shipping with css and not.
Instead we should ensure that the version is updated to `X.Y.Z-css.0` and then it is published with a `CSS` tag.
+ [x] Tests
> [BPK-2653] Investigate shipping CSS (#1607)

- package.json
Removes the need for https://github.com/Skyscanner/backpack/pull/1717 as `chalk` isn't actually being used (probably a holdover from `backpack-docs`).
> [No Jira] Remove unused 'chalk' dependency

- .spelling
- .storybook/addons.js
- UNRELEASED.yaml
- packages/bpk-component-calendar/index.js
- packages/bpk-component-calendar/src/BpkCalendarContainer.js
- packages/bpk-component-calendar/src/BpkCalendarGrid.js
- packages/bpk-component-calendar/src/Week.js
- packages/bpk-component-datepicker/README.md
- packages/bpk-component-datepicker/package.json
- packages/bpk-component-datepicker/src/BpkDatepicker.js
- packages/bpk-component-datepicker/stories.js
> [BPK-3256] Add `renderCalendar` prop to datepicker

- .github/pull_request_template.md
- CONTRIBUTING.md
- UNRELEASED.yaml
- packages/bpk-component-chip/README.md
- packages/bpk-component-chip/src/BpkChip-test.js
- packages/bpk-component-chip/src/BpkChip.js
- packages/bpk-component-chip/src/__snapshots__/BpkChip-test.js.snap
- packages/bpk-component-chip/stories.js
- packages/bpk-component-map/stories.js
To allow using `BpkChip` in a read-only way.
When `dismissible` is set to `false`, the close button is hidden.
> Add "dismissible" prop to BpkChip

- UNRELEASED.yaml
- packages/bpk-component-infinite-scroll/src/__snapshots__/withInfiniteScroll-test.js.snap
- packages/bpk-component-infinite-scroll/src/withInfiniteScroll-test.js
- packages/bpk-component-infinite-scroll/src/withInfiniteScroll.js
- packages/bpk-component-infinite-scroll/stories.js
infer list has ended if less than requested elements are returned from data source
+ [] `UNRELEASED.yaml`
+ [] `README.md`
+ [x] Tests
+ [] Docs (either update [backpack-docs](https://github.com/Skyscanner/backpack-docs) now, or create a follow up ticket)
> stop redundant datasource call

- package-lock.json
- package.json
- packages/bpk-component-horizontal-nav/src/BpkHorizontalNav.js
- packages/bpk-component-image/src/BpkBackgroundImage.js
- packages/bpk-component-image/src/withLazyLoading.js
- packages/bpk-component-infinite-scroll/src/withInfiniteScroll-test.flow.js
- packages/bpk-component-popover/index.js
- packages/bpk-component-popover/src/BpkPopoverPortal.js
- packages/bpk-component-popover/stories.js
- packages/bpk-component-tooltip/src/BpkTooltipPortal.js
This upgrades flow to `0.111.0`
The current version is `0.112.0` but due to a bug with types and exact types we can't upgrade to the latest without removing `...rest` spreading from all our components.
More detail here: https://github.com/facebook/flow/issues/8192
> Upgrading flow to latest version

- UNRELEASED.yaml
- packages/bpk-component-datepicker/README.md
- packages/bpk-component-datepicker/src/BpkDatepicker-test.js
- packages/bpk-component-datepicker/src/BpkDatepicker.js
- packages/bpk-component-datepicker/stories.js
Datepicker was always closed by default on the first render. I changed it to configurable by a new prop.
+ [ ] Tests (As it's a minor change i didn't include tests. In fact, a snapshot test wouldn't really help here)
> ELMO-194 Add iOpen prop to datepicker

- UNRELEASED.yaml
- packages/bpk-component-datepicker/src/BpkDatepicker.js
The previous PR introduced the bug where isOpen was passed to BpkPopover and overriding the state value.
+ [x] Tests
> ELMO-194 Datepicker - dont pass isOpen to BpkPopover

- .spelling
- packages/bpk-component-text/README.md
- packages/bpk-component-text/src/BpkText.js
* Readme for `BpkText` is missing the new `textStyle` values.
* Changed a bit the code that generates `className` in `BpkText` component, making use of `cssModules` capabilities.
> BpkText readme update

- packages/bpk-component-banner-alert/src/withBannerAlertState.js
Replaced with componentDidMount.
There should be no visible difference to the users. The alert might be shown a couple of milliseconds later than before but should be overall positive as the defined timeout should start when the component is visible rather than when React starts processing it.
+ [x] Tests
> Remove use of componentWillMount in withBannerAlertState

- UNRELEASED.yaml
- packages/bpk-tokens/formatters/bpk.react.native.es6.js.js
- packages/bpk-tokens/formatters/react-native-value-template.js
- packages/bpk-tokens/gulpfile.babel.js
- packages/bpk-tokens/src/android/base/colors.json
- packages/bpk-tokens/src/ios/base/colors.json
- packages/bpk-tokens/src/transformDarkValues.js
- packages/bpk-tokens/tokens/android/base.react.native.common.js
- packages/bpk-tokens/tokens/android/base.react.native.es6.js
- packages/bpk-tokens/tokens/base.android.xml
- packages/bpk-tokens/tokens/base.ios.json
- packages/bpk-tokens/tokens/base.raw.android.json
- packages/bpk-tokens/tokens/base.raw.ios.json
- packages/bpk-tokens/tokens/base.react.native.android.js
- packages/bpk-tokens/tokens/base.react.native.ios.js
- packages/bpk-tokens/tokens/ios/base.react.native.common.js
- packages/bpk-tokens/tokens/ios/base.react.native.es6.js
This makes both iOS and Android tokens file the same, the tokens that are not valid for one platform are exported with `undefined` (which is a valid value for all stylesheet props) so flow is happy when people import a platform specific token in a "general" file (no ios or android extension).
It also removes `secondaryColor` from RN tokens which was wrong.
+ [x] Tests
> [BPK-3208] Add flow typing to RN tokens

- .spelling
- UNRELEASED.yaml
- decisions/structured-data.md
- packages/bpk-component-breadcrumb/README.md
- packages/bpk-component-breadcrumb/src/BpkBreadcrumb-test.js
- packages/bpk-component-breadcrumb/src/BpkBreadcrumb.js
- packages/bpk-component-breadcrumb/src/__snapshots__/BpkBreadcrumb-test.js.snap
- packages/bpk-component-modal/package.json
- packages/bpk-component-navigation-stack/package.json
Adds schema meta data as an optional property for breadcrumbs
More info about structured data can be found here https://developers.google.com/search/docs/guides/intro-structured-data
Breadcrumb schema specifically is here
https://developers.google.com/search/docs/data-types/breadcrumb
+ [x] Tests
To discuss: Do we prefer the implementation here (including dangerouslySetInnerHtml) or adding an additional dependency like: https://github.com/google/react-schemaorg
> ATBT-2578 - Add schema markup for breadcrumbs

- package-lock.json
Reverts Skyscanner/backpack#1841
> Revert "[Security] Bump mixin-deep from 1.3.1 to 1.3.2"

- package-lock.json
Reverts Skyscanner/backpack#1840
> Revert "[Security] Bump https-proxy-agent from 2.2.1 to 2.2.4"

- UNRELEASED.yaml
- package-lock.json
- package.json
- packages/bpk-animate-height/src/AnimateHeight.js
- packages/bpk-component-banner-alert/src/AnimateAndFade.js
- packages/bpk-component-calendar/src/BpkCalendarContainer.js
- packages/bpk-component-calendar/src/BpkCalendarGrid.js
- packages/bpk-component-calendar/src/BpkCalendarGridTransition.js
- packages/bpk-component-datatable/src/BpkDataTable.js
- packages/bpk-component-drawer/src/BpkDrawer.js
- packages/bpk-component-flare/src/BpkContentBubble.test.js
- packages/bpk-component-flare/src/BpkFlareBar.test.js
- packages/bpk-component-image/src/BpkBackgroundImage.js
- packages/bpk-react-utils/src/Portal-test.js
React 16.3 introduced `UNSAFE_componentWillReceiveProps` as an alias for `componentWillReceiveProps`, as this will be removed in React 17 (see https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html)
Since React 16.9, there’s a warning message when using `componentWillReceiveProps` (see https://reactjs.org/blog/2019/08/08/react-v16.9.0.html#new-deprecations).
Backpack seems to be using React 16.4.2. So there should be no issue replacing `componentWillReceiveProps` with `UNSAFE_componentWillReceiveProps` as the alias was introduced in React 16.3.
+ [x] Tests
> Rename "componentWillReceiveProps" to "UNSAFE_componentWillReceiveProps"

- UNRELEASED.yaml
- packages/bpk-component-datepicker/README.md
- packages/bpk-component-datepicker/src/BpkDatepicker-test.js
- packages/bpk-component-datepicker/src/BpkDatepicker.js
- packages/bpk-component-datepicker/src/__snapshots__/BpkDatepicker-test.js.snap
- packages/bpk-component-datepicker/stories.js
- packages/bpk-component-fieldset/package.json
- packages/bpk-component-fieldset/stories.js
`BpkDatepicker` doesn't have `valid` prop, and this makes it not work correctly with `BpkFieldset`: the label becomes red and error message is displayed, but the input border doesn't change to red nor the exclamation icon is displayed
With this changes, the `valid` prop is send to the input field, so it behaves as expected:
+ [x] Tests
> Add "valid" prop to BpkDatepicker

- .flowconfig
- packages/bpk-component-code/src/BpkCodeBlock.js
- packages/bpk-react-utils/index.js
- packages/bpk-react-utils/src/TransitionInitialMount-test.js
- packages/bpk-react-utils/src/TransitionInitialMount.js
I tried adding Flow to `Portal.js` but it's an absolute BEAST and a lot of what it's doing is strictly against Flow, even though we know it's ok because it works. So many of the errors are interlinked where fixing one opens up ten more in other areas too.
To fix it, we'd either need to totally refactor it or use a lot of undesirable types like `any` to make the errors go away.
In this case I've left it alone and added Flow to the rest of the module, so there's at least _some_ value.
> [BPK-2118] Add Flow types to some of `bpk-react-utils`

- .storybook/addons.js
- UNRELEASED.yaml
- packages/bpk-component-horizontal-nav/src/BpkHorizontalNav.js
- packages/bpk-component-horizontal-nav/src/__snapshots__/BpkHorizontalNav-test.js.snap
This is a fix to add `role="tablist"` to `BpkNavigation`
> [BPK-4053]: Horizontal Nav A11y fix

- packages/bpk-svgs/src/icons/icons-test.js
When the last PR was merged, it broke the docs site. Turns out, that blank `icons.js` file in `bpk-svgs` actually has a purpose! It's used in the docs site as something to latch onto for downloading a zip file of all the icons. So, I reinstated it.
I tested this locally on a copy of the docs site and it works fine.
> [No Jira] Reinstate icons.js file, needed for docs site icon downloads

- packages/bpk-component-nudger/index.js
- packages/bpk-component-nudger/src/themeAttributes.js
I added the annotation `/* @flow strict */` to the index of BpkNudger in order to be able to use the types and avoid adding libdefs.
+ [x] Tests
> No jira/Add flow annotation to nudger

- scripts/publish-process/publish-css-tagged-packages.js
- scripts/publish-process/util.js
Upgrading the process to rather than change the versioning number and strategy, we publish css packages under new names.
> [no jira]: Changing css publish process to change name instead of version

- packages/bpk-component-navigation-bar/src/BpkNavigationBar.js
- packages/bpk-component-popover/src/BpkPopover.js
- packages/bpk-component-section-list/src/BpkSectionListSection.js
- packages/bpk-component-text/stories.js
- packages/bpk-react-utils/src/deprecated.js
PR to update components that were still using deprecated `bold` prop for BpkText
Also minor update to the `deprecated` messaging as it was pointed out by @sogame danger would not see and report the warnings so add 'Warning' so that danger can parse and report back to PR 😄  see here https://github.com/sogame/danger-plugin-toolbox/blob/master/src/rules/common/fileWarnings.js#L21
> [no jira]: Update bold prop usage

- package.json
- scripts/publish-process/transform-bpk-imports.js
This PR fixes the issue where when we release the CSS versions of the packages, the imports in the js files for Backpack components were still refering to the old package names which are not available when you install
e.g. `bpk-component-button` was being imported when it should be `bpk-component-button-css` as that is the installed version.
To test the PR I commented out the part where it actually does the publish to npm and just ran the publish:css command manually and checked the git changes that were made to verify that the imports were correct
> [no jira]: Fixing css release process to update backpack imports

- UNRELEASED.yaml
- packages/bpk-component-scrollable-calendar/src/BpkScrollableCalendarGridList.js
Remove the resize listeners otherwise we end up causing memory leaks when the component is mounted/unmounted multiple times.
+ [x] Tests
> [NO-JIRA] Remove scrollable calendar resize listeners on unmount

- .spelling
- packages/bpk-component-rating/README.md
- packages/bpk-component-rating/src/BpkRating-test.js
- packages/bpk-component-rating/src/BpkRating.js
- packages/bpk-component-rating/src/common-types.js
- packages/bpk-component-rating/stories.js
Fix for prop warnings that were being thrown by the component.
See here for example:
https://github.com/Skyscanner/backpack/pull/1935#issuecomment-665142697
> Fixed rating component warnings

- dangerfile.js
As discussed on Slack, some of our well meaning Danger notices were being ignored, which reduces the impact of the important ones.
* The browser support checklist, which we never filled in, is now a notice reminding you to check it in multiple browsers, especially IE11.
* Dependabot PRs don't get the "you're amazing thanks xoxo" messages we send to external contributors.
* "It looks like you are introducing a new component. Ensure the component style is extensible via `className`."
* "`package-lock.json` was updated. Ensure that this was intentional."
* I added a notice to reviewers that only appears for Dependabot PRs. I'm hoping that this will help give some quick instructions on how to keep the number down in future. I'm not entirely sure if my logic check (`const isPrFromDependabot = …
> [No Jira] Made some tweaks to Danger to make it less noisy

- .spelling
- UNRELEASED.yaml
- packages/bpk-component-accordion/README.md
- packages/bpk-component-accordion/index.js
- packages/bpk-component-accordion/src/BpkAccordionItem-test.js
- packages/bpk-component-accordion/src/BpkAccordionItem.js
- packages/bpk-component-accordion/src/__snapshots__/BpkAccordionItem-test.js.snap
- packages/bpk-component-accordion/stories.js
The following PR allows the support of a `weight` prop that can be passed to `BpkAccordionItem` to style the title of the accordion.
Screenshot:
> [BPK-3438]: Support bold in accordion

- .spelling
- UNRELEASED.yaml
- packages/bpk-component-datepicker/README.md
- packages/bpk-component-datepicker/src/BpkDatepicker-test.js
- packages/bpk-component-datepicker/src/BpkDatepicker.js
- packages/bpk-component-datepicker/stories.js
At the moment the isOpen state from the BpkDatePicker can be only initialised as opened or closed through a prop but the component doesn't re-render when the prop changes. To fix that I added a check in componentDidUpdate to update the state when the prop changes.
> [ZEP-688] Allow consumers of BpkDatePicker to control isOpen from the outside

- packages/bpk-component-icon/README.md
Using `currentColor` for `fill` in icons is very useful, as it allows not duplicating the same color (and makes components more reusable).
`currentColor` is not know by many people, so I though it would be good to use it in the example (adding a link to some documentation).
What do you think about this? Might not be the best way to promote its usage 😅
> Use "currentColor" as "fill" in Icon documentation

- package.json
Lately, Danger keeps reporting build log warnings in every PR — like this: https://github.com/Skyscanner/backpack/pull/1995#issuecomment-707092530.
I looked into it and it's a warning from `handlebars`. We don't use this, but it's a dependency of `jest`. Apparently they messed something up in a release and it was causing errors when `jest --coverage` is run.
I followed https://github.com/facebook/jest/issues/9396#issuecomment-573328488 to fix it, by making the coverage reports just print in text (which is how we were using it before, so nothing should change).
If it's worked, Danger shouldn't report any build log warnings on this PR.
> [No Jira] Fix warning Danger keeps reporting

- packages/bpk-component-slider/package-lock.json
- packages/bpk-component-slider/package.json
Closes #2002 
We got a Snyk PR to upgrade this dep, but I looked in the code and it's not used anywhere. I ran the tests and storybook after removing it just to be safe too.
> [No Jira] Remove unused 'create-react-class' dep from slider component

- UNRELEASED.md
- packages/bpk-component-nudger/src/BpkConfigurableNudger.js
- packages/bpk-component-nudger/src/__snapshots__/BpkNudger-test.js.snap
In local development I see errors like:
```
Warning: Received `false` for a non-boolean attribute `outline`.
If you want to write it to the DOM, pass a string instead: outline="false" or outline={value.toString()}.
If you used to conditionally omit it with outline={condition && value}, pass outline={condition ? value : undefined} instead.
in button (at BpkButtonBase.js:103)
in BpkButton (at BpkButtonSecondary.js:41)
in BpkButtonSecondary (at BpkConfigurableNudger.js:99)
in div (at BpkConfigurableNudger.js:98)
in BpkConfigurableNudger (at BpkNudger.js:48)
```
Poking around I think we are passing props unnecessarily.
Just above the changed lines we do:
```
const ButtonComponent =
buttonType === 'secondary' ? BpkButtonSecondary : BpkButtonOutline;
```
This means at the point we pass in …
> NO-JIRA: BpkNudger internal props usage adjustment

- UNRELEASED.md
- packages/bpk-component-dialog/src/__snapshots__/BpkDialog-test.js.snap
- packages/bpk-component-modal/src/BpkModalDialog.js
- packages/bpk-component-modal/src/__snapshots__/BpkModal-test.js.snap
- packages/bpk-component-modal/src/__snapshots__/BpkModalDialog-test.js.snap
- packages/bpk-component-modal/stories.js
- packages/bpk-component-navigation-bar/src/BpkNavigationBar.js
- packages/bpk-component-navigation-bar/src/__snapshots__/BpkNavigationBar-test.js.snap
A11y fix whereby aria-labelled by was incorrect when applied on the modals/dialogs
Before:
After:
> BPK-4032: Fix Modal a11y issue

- UNRELEASED.md
- packages/bpk-component-image/index.js
- packages/bpk-component-image/src/BpkBackgroundImage.js
This PR simply exports `BpkBackgroundImageProps` from `bpk-component-image` package. 
We need these props in our internal project for flow typing, and simply copying them breaks the link and can lead to
our copy becoming stale in case there's a change in future.
- ~~[x] `UNRELEASED.md`~~
- ~~[x] `README.md`~~
- ~~[x] Tests~~
- ~~[x] Docs (either update [backpack-docs](https://github.com/Skyscanner/backpack-docs) now, or create a follow up ticket)~~
> [NO-JIRA]: Export BpkBackgroundImageProps from bpk-component-image package

- .github/workflows/ci.yml
Using `keep_files: true` means that if we rename a page, the old page's index.html will still be present.
For example, https://backpack.github.io/using/status still exists even though we've deployed a new version with https://backpack.github.io/using/backpack-status.
For PR builds we want to use `keep_files` (as we don't want to remove another PR's build when we deploy) but for the main docs deploys I think we shouldn't keep files
> [NO-JIRA] Make main deploys remove old files

- UNRELEASED.md
- packages/bpk-component-datatable/src/__snapshots__/BpkDataTable-test.js.snap
- packages/bpk-component-datatable/src/bpkHeaderRenderer-test.js
- packages/bpk-component-datatable/src/bpkHeaderRenderer.js
The arrow icons being used in the datatable for sorting were inverted
> [NO-JIRA] Fix column header sorting icons in datatable

- UNRELEASED.md
- packages/bpk-component-datatable/src/BpkDataTable-test.js
- packages/bpk-component-datatable/src/BpkDataTable.js
- packages/bpk-component-datatable/src/__snapshots__/BpkDataTable-test.js.snap
While working on a feature to dynamically change the background of a row depending on a value, I noticed that `BpkDataTable` did not allow to pass a function for `rowClassName` while the original react-virtualized `Table` [does](https://github.com/bvaughn/react-virtualized/blob/master/docs/Table.md).
This PR extends the component to allow passing a function as in `Table`
> [NEON-167] DataTable rowClassName can be a function

- UNRELEASED.md
- packages/bpk-component-datatable/src/sorter.js
Update rowCount value when the props of PropSorter have changed
> NEON-154: Fix rowCount value on PropSorter, bpk-component-datatable

- .github/workflows/ci.yml
In order to deploy the storybook to our PR site it requires the use of secret tokens that are not available to forks, so the purpose of this PR is to prevent this step running on forks and causing builds to fail at this step.
How to verify change:
> Excluding storybook from deploying if on a fork

- .storybook/config.js
Fixed an issue where Relative was not loading in storybook opting the storybook site into the font loading from the `bpk-stylesheets/font` import. As some time ago font loading was removed from `bpk-stylesheet/base` and required opt in to get the fonts
> [BPK-4418]: Fixing Relative font loading by opting into font loading from bpk-stylesheets

- UNRELEASED.md
- packages/bpk-component-calendar/src/BpkCalendarContainer-test.js
- packages/bpk-component-calendar/src/BpkCalendarContainer.js
Currently the flow is:
-  with no date selected the focus outline is on the `minDate` (See `determineFocusedDate` function) 
- a date is selected on the calendar, that date has a focus outline
- then the selected date is set to `null`, the focus outline will remain on the previously selected date
The desired flow is for the final point to change to:
- then the selected date is set to `null`, the focus outline will return to the `minDate`
At a code level what is happening is:
- The new `selectedDate` prop is given to the `BpkCalendarContainer`
- It runs `UNSAFE_componentWillReceiveProps`
- That runs `focusedDateHasChanged`
As the date could be passed in as `Date.now()` but we only care about the Day, not the time, then `isSameDay` is used to compare two Date type values.
Previously the …
> [DINGO-4320]: Calendar focus on null date

- UNRELEASED.md
- packages/bpk-component-tooltip/README.md
- packages/bpk-component-tooltip/examples.js
- packages/bpk-component-tooltip/src/BpkTooltip.js
- packages/bpk-component-tooltip/src/BpkTooltipPortal-test.js
- packages/bpk-component-tooltip/src/BpkTooltipPortal.js
- packages/bpk-component-tooltip/src/__snapshots__/BpkTooltipPortal-test.js.snap
- packages/bpk-component-tooltip/stories.js
In addition to this, I'm going to add a note to the docs site page to mention that tooltips aren't a great pattern as they don't work well on touchscreens.
> [BPK-3607] Make tooltips focusable and add required ariaLabel prop

- UNRELEASED.md
- packages/bpk-component-datepicker/src/BpkDatepicker.js
- packages/bpk-component-datepicker/src/__snapshots__/BpkDatepicker-test.js.snap
- packages/bpk-component-input/src/__snapshots__/withOpenEvents-test.js.snap
- packages/bpk-component-input/src/withOpenEvents.js
The Datepicker component renders an input that when clicked opens either a popover (on desktop) or a full screen modal (mobile) containing a calendar.
On mobile the `readOnly` prop is applied to the input as a way to prevent the native keyboard opening when the input receives focus. The keyboard would be both interruptive and useless when the inputs value is controlled by the calendar component.
On iOS this works without problem, but on Android it has been found that the modal (containing the calendar) cannot be opened when a screen reader (TalkBack) is in use. The input receives accessibility focus, reads out that it is 'read only' but does not trigger either click or touch events. TalkBack seems to be trying to be clever and stopping these events from triggering due to the read only …
> DINGO-4358: Android screenreader datepicker bug

- package-lock.json
- package.json
- packages/bpk-component-button/src/BpkButton-test.js
- scripts/jest/setup.js
This PR adds a single a11y test to as a proof of concept. 
To make it work, I had to add a dependency on `@testing-library/react`, as jest-axe won't work with `react-test-renderer`. This is because it requires real HTML, not the pseudo-HTML structures generated by our tests.
As a follow up to this PR, I suggest we do two things:
We should migrate **all** our tests to use `@testing-library/react`. We shouldn't have two different test renderers, so we should standardise on this better library. It's more capable, used elsewhere in Skyscanner (like in Banana) and it's the testing library built into new repos made with `create-react-app`, so all signs point to this being the one to use.
This could be mostly automated with a regex so it isn't a lot of overhead. It would mean that our snapshots …
> [BPK-4448] Proof of concept of adding jest-axe to BpkButton tests

- UNRELEASED.md
- decisions/accessibility-tests.md
- flow-typed/npm/jest_v21.x.x.js
- packages/bpk-animate-height/src/AnimateHeight-accessibility-test.js
- packages/bpk-component-accordion/src/BpkAccordion-accessibility-test.js
- packages/bpk-component-accordion/src/BpkAccordionItem.js
- packages/bpk-component-accordion/src/__snapshots__/BpkAccordionItem-test.js.snap
- packages/bpk-component-accordion/src/__snapshots__/withAccordionItemState-test.js.snap
- packages/bpk-component-aria-live/src/BpkAriaLive-accessibility-test.js
- packages/bpk-component-autosuggest/src/BpkAutosuggest-accessibility-test.js
- packages/bpk-component-badge/src/BpkBadge-accessibility-test.js
- packages/bpk-component-button/src/BpkButton-accessibility-test.js
- packages/bpk-component-button/src/BpkButton-test.js
I migrated a few components just to validate the approach, and if we're happy with it I'll continue and do the rest.
> [KOA-4458] Add some jest-axe tests and tweak accordion to pass a11y test

- UNRELEASED.md
- packages/bpk-component-calendar/src/BpkCalendarGrid.js
This fixes an issue with iOS and iPadOS with Asssitive Technologies when changing the month from the calendar dropdown meant that voiceover would get stuck in the current selected week and unable to navigate to new date rows
To do this we check if the device is an iOS device and return the calendar without grid transitions as this was causing the bug, a follow up PR/ticket will be done to review the transitions. 
> Koa 4467 voiceover bug fix for calendar on iOS

- packages/bpk-component-calendar/package.json
`bpk-component-aria-live` is used in [`BpkCalendarNav`](https://github.com/Skyscanner/backpack/blob/ffe76cabda2cb933de143e4c51f574a78290a284/packages/bpk-component-calendar/src/BpkCalendarNav.js#L25), so I think it should be in `dependencies` and not in `devDependencies`.
> Move "bpk-component-aria-live" to "dependencies" in "bpk-component-calendar"

- UNRELEASED.md
- packages/bpk-component-nudger/examples.js
- packages/bpk-component-nudger/src/BpkConfigurableNudger.js
- packages/bpk-component-nudger/src/accessibility-test.js
Fixed failing axe tests - turns out the test only needed a `<label>` or `aria-label`.
Also modifed the storybook example for the buttons to be more descriptive and add an `aria-label` to give context of the field value and when `aria-live` updates.
> A11y fixes for nudger axe tests

- .github/workflows/ci.yml
Previously when using `DANGER_GITHUB_API_TOKEN` for the danger step it would fail due to not having the correct permissions to comment as `backpackbot` user.
Reviewing the following guidence for GH Actions from [dangerjs](https://danger.systems/js/guides/getting_started.html#setting-up-danger-to-run-on-your-ci) - it seems that danger works when you provide the default `GITHUB_ACTION` token that the CI generates at the start of each build to comment.
As you see from the below it now comments changes correct but rather than being the `backpackbot` user, it just comments as `github-actions` user. So I think its acceptable in order for this to work we don't use the `backpackbot` user for danger
> [NO JIRA]: Changing the danger env token run correctly

- packages/bpk-component-barchart/package.json
These were non-breaking for us, as they just move to using ES2015 syntax that we already support.
- https://github.com/d3/d3-path/releases
- https://github.com/d3/d3-scale/releases
Ran locally in Storybook and all seems good.
> [KOA-4564] Upgrade third-party dependencies for bar chart component

- UNRELEASED.md
- packages/bpk-tether/package.json
Ran locally and seems fine. The breaking change in 2.0 was removing something from git that we weren't using, so it's non breaking for us.
> [KOA-4570] Upgrade tether to 2.x

- packages/bpk-tokens/src/web/base/icons.json
- packages/bpk-tokens/tokens/base.raw.json
As part of the 8px spacing update #2148 - It was found that icons CSS/JS variables are currently using spacing tokens in order to determine their size. 
As such because we are not adjusting the sizing of the icons as part of the grid updates and they need to stay their same size as per icon design definition, this PR is migrating from using spacing tokens to having their correct sizing defined on the token. 
- [Not applicable as this is an internal change to the current value] `UNRELEASED.md`
- [N/A] `README.md`
- [N/A] Tests
- [N/A] Docs (either update [backpack-docs](https://github.com/Skyscanner/backpack-docs) now, or create a follow up ticket)
> [KOA_3653]: 8px spacing fixes for icons

- packages/bpk-component-skip-link/README.md
I noticed this when browsing the docs site:
https://backpack.github.io/components/skip-link?platform=web
> Fix import in the bpk-component-skip-link example

- UNRELEASED.md
- packages/bpk-tokens/src/web/base/spacing.json
- packages/bpk-tokens/tokens/base.default.scss
- packages/bpk-tokens/tokens/base.raw.json
- packages/bpk-tokens/tokens/base.scss
When we created the new spacing functions we forgot to add a deprecation warning for `bpi-spacing-xs()` as in the new spacing system this value is no longer part of the scale.
So adding this warning to alert consumers that they need to migrate away from `XS` size.
- [N/A] `README.md`
- [N/A] Docs (either update [backpack-docs](https://github.com/Skyscanner/backpack-docs) now, or create a follow up ticket)
> [NO JIRA]: Add missing deprecation warning for bpk-spacing-xs()

- UNRELEASED.md
- packages/bpk-component-banner-alert/src/BpkBannerAlertInner.js
- packages/bpk-component-banner-alert/src/__snapshots__/BpkBannerAlertInner-test.js.snap
`<BpkBannerAlert>` with `isExpandable` would result in a role of `alert button` which was being flagged as invalid
Instead I've moved the `role=alert` up to the section, rather than the `div`, which is applicable for all banner alerts, and then if it is an expandable alert, add `role=button` on the div as it used to.
This way there are two elements with a single role, rather than one element with two roles on
> Modify banner alert roles for accessibility

- UNRELEASED.md
- packages/bpk-component-banner-alert/src/BpkBannerAlertInner.js
[This change](https://github.com/Skyscanner/backpack/pull/2206) in `bpk-component-banner-alert` introduces a warning in the tests:
```
Warning: Received `false` for a non-boolean attribute `role`.
If you want to write it to the DOM, pass a string instead: role="false" or role={value.toString()}.
If you used to conditionally omit it with role={condition && value}, pass role={condition ? value : undefined} instead.
```
As suggested, this pr changes the implementation to avoid providing a boolean to `role`.
> Fix role warning in bpk-component-banner-alert

- .github/pull_request_template.md
- UNRELEASED.md
- packages/bpk-component-breakpoint/package-lock.json
- packages/bpk-component-breakpoint/package.json
`bpk-component-breakpoint` uses an older version of `react-responsive` that produces the following warnings when running locally:
This PR updates to a newer version, but still not the latest.
v6 should fix this and requires 16.3.0, while v7+ require 16.8.0 which Backpack currently does not support as a minimum version.
https://github.com/contra/react-responsive/blob/master/CHANGELOG.md#v600
> NO-JIRA: Update react-responsive to v6 in bpk-component-breakpoint

- UNRELEASED.md
- packages/bpk-component-barchart/src/BpkBarchartBar.js
- packages/bpk-component-barchart/src/BpkChartAxis.js
- packages/bpk-component-barchart/src/__snapshots__/BpkBarchartBar-test.js.snap
- packages/bpk-component-barchart/src/__snapshots__/BpkChartAxis-test.js.snap
- Axes are read out separately, although they don't really convey any information on their own
- Each bar appears as 3 elements
https://user-images.githubusercontent.com/30267516/128365054-a58ded23-ed0e-4a1b-8baa-8b995c644744.mov
- Axes are skipped
- Each bar appears as a single element
https://user-images.githubusercontent.com/30267516/128365072-8e9b637c-e9e6-495a-972c-b3331d7a0a1b.mov
> [KOA-4642] Improve the accessibility of Bar Chart

- UNRELEASED.md
- packages/bpk-component-nudger/src/BpkNudger.module.css
- packages/bpk-component-nudger/src/BpkNudger.module.scss
Before: https://backpack.github.io/storybook/?path=/story/bpk-component-nudger--default
After: https://backpack.github.io/storybook-prs/2248/?path=/story/bpk-component-nudger--default
> [KOA-3657] Update nudger component to use the new spacing grid

- UNRELEASED.md
- packages/bpk-component-paragraph/src/BpkParagraph.module.css
- packages/bpk-component-paragraph/src/BpkParagraph.module.scss
- packages/bpk-mixins/src/mixins/_typography.scss
Update paragraph component to use the new spacing grid.
Before: https://backpack.github.io/storybook/?path=/story/bpk-component-paragraph--example
After: https://backpack.github.io/storybook-prs/2250/?path=/story/bpk-component-paragraph--example
> [KOA-4549] Update paragraph component to use the new spacing grid

- UNRELEASED.md
- packages/bpk-component-image/README.md
Fixed a spelling error: we export using American English but were using some British English in the code example, which fails.
- ~[ ] Tests~
> NO-JIRA: Update spelling of withLoadingBehavior in docs

- UNRELEASED.md
- packages/bpk-component-datepicker/README.md
- packages/bpk-component-datepicker/index.js
- packages/bpk-component-scrollable-calendar/README.md
- packages/bpk-component-scrollable-calendar/index.js
When using `bpk-component-datepicker`, it feels weird doing two different imports, specially taking into account `bpk-component-calendar` might not even be used in the project, as it's just an internal dependency that users don't need to know about:
```
import BpkDatepicker from 'bpk-component-datepicker';
import { CALENDAR_SELECTION_TYPE } from 'bpk-component-calendar';
```
I think it would be better to export `CALENDAR_SELECTION_TYPE` in `bpk-component-datepicker`, so only a single export is needed (and only in the package users have installed):
```
import BpkDatepicker, { CALENDAR_SELECTION_TYPE } from 'bpk-component-datepicker';
```
What do you think about this?
> Export CALENDAR_SELECTION_TYPE from bpk-component-datepicker

- .github/dependabot.yml
- .github/workflows/ci.yml
This config was missing therefore no automatic PRs to fix issues were being raised.
The dependabot config is now setup also to be a lot less noisy similar to the backpack-docs config where it targets direct dependencies so should reduce some of the noise down and fix the critical things!
> [KOA-4727]: Adding dependabot config to open automatic PRs

- .github/workflows/ci.yml
This PR migrates away from using a 3rd party GH action to using the GH api to comment on PRs similar to the approach used by skyscanner/backpack-android when commenting on the PR
> Using GH API to post messages on PR

- packages/bpk-component-heading/README.md
- packages/bpk-component-heading/package.json
This PR adds missing deprecation work when this component was previously deprecated back in 2017!
- Adds deprecation note to BpkHeading component README.
- Sets the package to `private` so that the component is ignored during publish.
The code will then probably be removed when we ship Backpack as a single package
> [KOA-4879]: Deprecate heading component

- UNRELEASED.md
- packages/bpk-mixins/src/mixins/_typography.scss
As part of KOA-4879 we want to deprecate `heading-6` mixin as its a duplicate of `heading-5` and doesn't exist in the new typography system.
> [KOA-4879]: Deprecate bpk-heading-6 mixin

- native/README.md
This folder had been introduced 3 years ago when we split out our mobile native code to separate repos. I think given its been 3 years now people are familiar with where this is located and we can safely remove this folder and the one file to tidy up the repo.
> [NO JIRA]: Removing old native folder

- UNRELEASED.md
- packages/bpk-component-calendar/src/custom-proptypes.js
Removing the key as it's being used as an index to retrieve the selectionConfiguration props, however the props are being passed as an object and being destructured so each individual property are accessible.
> [NO-JIRA] - Remove Key Index from Calendar

- UNRELEASED.md
- packages/bpk-component-map/README.md
- packages/bpk-component-map/src/withGoogleMapsScript.js
When `preventGoogleFontsLoading` is set to `true`, Google Maps will not be able to interact, such as the markers cannot be clicked, because the whole layout is masked by a mask, so it is better to update the default value to `false` to avoid the confusion, because most of the case we want to interact on Google Maps instead of a static map
Related to the PR https://github.com/Skyscanner/backpack/pull/2423
> [BD-6033] Fixed `preventGoogleFontsLoading` making Google Maps cannot be interactive

- .naverc
- .nvmrc
- CONTRIBUTING.md
- package.json
- packages/bpk-animate-height/package-lock.json
- packages/bpk-component-accordion/package-lock.json
- packages/bpk-component-aria-live/package-lock.json
- packages/bpk-component-autosuggest/package-lock.json
- packages/bpk-component-banner-alert/package-lock.json
- packages/bpk-component-calendar/package-lock.json
- packages/bpk-component-checkbox/package-lock.json
- packages/bpk-component-chip/package-lock.json
- packages/bpk-component-datepicker/package-lock.json
- packages/bpk-component-drawer/package-lock.json
- packages/bpk-component-fieldset/package-lock.json
- packages/bpk-component-form-validation/package-lock.json
- packages/bpk-component-input/package-lock.json
- packages/bpk-component-map/package-lock.json
- packages/bpk-component-modal/package-lock.json
- packages/bpk-component-navigation-bar/package-lock.json
- packages/bpk-component-navigation-stack/package-lock.json
- packages/bpk-component-pagination/package-lock.json
- packages/bpk-component-phone-input/package-lock.json
- packages/bpk-component-popover/package-lock.json
- packages/bpk-component-radio/package-lock.json
- packages/bpk-component-rtl-toggle/package-lock.json
- packages/bpk-component-scrollable-calendar/package-lock.json
- packages/bpk-component-switch/package-lock.json
Upgrades Backpack Web to Node 14 as an interim step to move to a supported Node version.
Follow up work will be completed to upgrade libraries and implementations to fully support Node 16 as currently upgrading to Node 16 causes test failures and has some bugs in npm v8 which is a large task.
So we will break this down in order to support it properly and not make a large PRs that might be unstable or less easy to manage
> [KOA-5029]: Upgrade web to Node 14

- .spelling
- UNRELEASED.md
- packages/bpk-component-mobile-scroll-container/src/BpkMobileScrollContainer.js
We found that due to [the problem of `scrollLeft` itself](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollLeft) - **On systems using display scaling, scrollLeft may give you a decimal value** 
This will affect the logic of calculating whether the indicator is displayed or not in `BpkMobileScrollContainer`.
- Indicator will be calculated correctly when scrollLeft gets a decimal value.
- Take the ceil value of `scrollLeft`
To better show the difference, I change the indicator styles temporarily.
Problems will probably occur when:
1. Screen zoomed
2. The width of the container of BpkMobileScrollContainer is decimal.
When the problem occurs, we see that showTrailingIndicator will **always have a true value even the list have meet the end**.
| Before                        | …
> [BD-6042] Fixed the indicator style when scrollLeft is a decimal value

- UNRELEASED.md
- packages/bpk-component-rating/src/BpkRating.module.scss
Subject: New design for ReviewRating to backpack `bpk-component-rating`
Ticket:  https://gojira.skyscanner.net/browse/BD-6043
UX:  [figma](https://www.figma.com/file/irZ3YBx8vOm16ICkAr7mB3/Backpack?node-id=7986%3A7553)
Confluence:  [Backpack Rating component](https://confluence.skyscannertools.net/display/BD/Rating+component)
Visual link: https://backpack.github.io/storybook-prs/2430/?path=/story/bpk-component-rating--visual-test
- There is a RTL issue for rating value has additional padding
- Fix rating RTL issue with additional padding
- Update UNRELEASED.md
| Before                        | After                         |
| ----------------------------- | ----------------------------- |
| <img src="https://user-images.githubusercontent.com/33623220/170219040-e003b9b4-5c40-4ed1-86dd-1ed1 …
> [BD-6043] Fix rating RTL issue with additional padding

- UNRELEASED.md
- packages/bpk-component-graphic-promotion/src/BpkGraphicPromo.module.scss
[ST-4162](https://gojira.skyscanner.net/browse/ST-4162)
Centred text on the centred graphic promo to the exact centre ignoring margins.
> ST-4162: center graphic promo text

- UNRELEASED.md
- packages/bpk-component-popover/src/BpkPopoverPortal.js
- packages/bpk-component-popover/src/__snapshots__/BpkPopoverPortal-test.js.snap
- packages/bpk-component-tooltip/src/BpkTooltipPortal-test.js
- packages/bpk-component-tooltip/src/BpkTooltipPortal.js
- packages/bpk-component-tooltip/src/__snapshots__/BpkTooltipPortal-test.js.snap
- packages/bpk-react-utils/index.js
- packages/bpk-react-utils/src/Portal-test.js
- packages/bpk-react-utils/src/Portal-v1-test.js
- packages/bpk-react-utils/src/Portal-v1.js
- packages/bpk-react-utils/src/Portal.js
- packages/bpk-react-utils/src/__snapshots__/Portal-test.js.snap
- packages/bpk-react-utils/src/__snapshots__/Portal-v1-test.js.snap
Migrated popup components to native React portal implementation. Components migrated Dialog, Drawer and Modal.
For interactive components Tooltip and Popover (by extension Datepicker) migrated to remain using the previous implementation exposed through PortalV1 - this is due to a bit more of the complexities of the component which will be resolved through separate PRs to follow.
> New portal implementation for Modal, Dialog and Drawer

- UNRELEASED.md
- packages/bpk-component-graphic-promotion/package-lock.json
- packages/bpk-component-graphic-promotion/package.json
- packages/bpk-component-graphic-promotion/src/BpkGraphicPromo.js
- packages/bpk-component-graphic-promotion/src/BpkGraphicPromo.module.scss
- packages/bpk-component-graphic-promotion/src/__snapshots__/BpkGraphicPromo-test.js.snap
- packages/bpk-component-graphic-promotion/src/accessibility-test.js
[ST-4405](https://gojira.skyscanner.net/browse/ST-4405)
Graphic Promo had accessibility issues with the button nested inside an `a` tag. We need both the button and the whole card to be clickable. For accessibility users, however, we treat the whole card as one item and use `aria-hidden` to hide its contents from the screen reader.
Unfortunately, an update to `axe` seems to have broken our current implementation. Axe throws accessibility errors, which we are fixing in this PR by making the card a `div` that uses the styles of Skyscanner's card component. The `div` is clickable and can be focused on using Tab; Enter and Space click the link
> [ST-4405] Fix accessibility issues in Graphic Promo.

- .spelling
- UNRELEASED.md
- examples/bpk-component-floating-notification/examples.js
- packages/bpk-component-floating-notification/README.md
- packages/bpk-component-floating-notification/src/BpkFloatingNotification-test.js
- packages/bpk-component-floating-notification/src/BpkFloatingNotification.js
- packages/bpk-component-floating-notification/src/__snapshots__/BpkFloatingNotification-test.js.snap
- Added a new prop `onExit` which takes in a function to execute after the exit animation of the floating notification component has finished
- Added "Trigger alert" button to the Storybook examples so that users can replay the animation
- Follow up ticket [TICKET GOES HERE]
> [ST-4398] Add trigger button to Floating Notification component Storybook

- .spelling
- UNRELEASED.md
- examples/bpk-component-graphic-promotion/examples.js
- packages/bpk-component-graphic-promotion/README.md
- packages/bpk-component-graphic-promotion/src/BpkGraphicPromo.js
This adds an optional property to the Graphic Promotion component, to attach an 'id' to the 'div' wrapping the main content, rather than the top level containing 'div'. This is to uniquely identify the main content, to be used for purposes outside of Backpack.
> [ST-4451]: Add contentId to Graphic Promotion component

- UNRELEASED.md
- packages/bpk-component-popover/src/BpkPopoverPortal.js
- packages/bpk-component-tooltip/src/BpkTooltipPortal.js
It seems like `@popperjs/core` is not exporting `basePlacements`, so it's `undefined` and shows a warning in the tests. This is a screenshot of Backpack build itself:
The build for this pr doesn't contain this warning anymore.
> KOA-5436 Fix Popover and Tooltip "placement" propType

- UNRELEASED.md
- packages/bpk-component-nudger/src/BpkConfigurableNudger.js
- packages/bpk-component-nudger/src/__snapshots__/BpkNudger-test.js.snap
[Ticket](https://gojira.skyscanner.net/browse/SHIBA-1308)
[Slack Thread](https://skyscanner.slack.com/archives/C03RSTQLM5Y/p1659602802992139)
> [SHIBA-1308]: aria-live changed for bpk-component-nudger

- packages/bpk-component-graphic-promotion/src/BpkGraphicPromo-test.tsx
- packages/bpk-component-graphic-promotion/src/__snapshots__/BpkGraphicPromo-test.tsx.snap
In https://github.com/Skyscanner/backpack/pull/2535 it was requested that we set the contentId in tests by default.
This PR does so, and ensures we still have a test for when the contentId is not present (it is optional, with a default of null currently).
> KOA-5198: Tweak Graphic Promo tests

- .spelling
- UNRELEASED.md
- packages/bpk-component-list/README.md
- packages/bpk-component-list/src/BpkList-test.js
- packages/bpk-component-list/src/BpkList.js
Updates BpkList component to accept `ariaLabel`, `ariaLabelledby` and `title` props.
> [NO-JIRA] Add a11y props to BpkList

- packages/bpk-component-aria-live/src/BpkAriaLive.tsx
As we are temporarily shipping backpack as both a single package and individual packages, we change the import paths and order during the release process. Due to the `@ts-expect-error` comment in the import files, there is an extra empty line unnecessarily added in between the `react` imports which breaks the linting.
> [NO JIRA] Fix import order

- UNRELEASED.md
- examples/bpk-component-switch/examples.js
- examples/bpk-component-switch/stories.js
- packages/bpk-component-switch/README.md
- packages/bpk-component-switch/src/BpkSwitch-test.js
- packages/bpk-component-switch/src/BpkSwitch.js
- packages/bpk-component-switch/src/BpkSwitch.module.scss
- packages/bpk-component-switch/src/__snapshots__/BpkSwitch-test.js.snap
New small variant added to Backpack 
Also in this PR:
- Migrated to semantic tokens
- Deprecated Event type switch as this is no longer a supported design pattern
> [KOA-5063]: Add new smaller switch, semantic tokens and type deprecation

- CHANGELOG.md
- packages/bpk-component-content-cards/src/BpkContentCards.js
When using the `bpk-component-content-cards` component in [Banana](https://github.skyscannertools.net/dingo/banana/pull/5834/#issuecomment-844446) I noticed that there was an error in the console that `Each child in a list should have a unique "key" prop` and I realised we didn't set up the key prop correctly in the BpkContentCards component so this PR fixes that.
> [NO-JIRA] Fix broken list key prop in BpkContentCards

- UNRELEASED.md
- packages/bpk-component-graphic-promotion/src/BpkGraphicPromo.module.scss
- packages/bpk-component-image/src/BpkImage.module.scss
- packages/bpk-component-progress/README.md
- packages/bpk-component-progress/src/BpkProgress-test.js
- packages/bpk-component-progress/src/BpkProgress.js
- packages/bpk-component-progress/src/BpkProgress.module.scss
- packages/bpk-component-progress/src/__snapshots__/BpkProgress-test.js.snap
- packages/bpk-component-rating/src/BpkRating.module.scss
- packages/bpk-component-skip-link/src/BpkSkipLink.module.scss
**Changed:**
- bpk-component-graphic-promotion, bpk-component-image, bpk-component-rating, bpk-component-skip-link
- Changed components to use semantic tokens.
- bpk-component-progress:
- Migrated to semantic colours
- Removed `stepColor` prop as not being used and shouldn't be customised.
> [KOA-5596]: Group 3 semantic token update

- scripts/npm/create-component.js
Removed from create component script the bit which adds the new component to the storybook config as with Storybook v6 and its new config that is no longer needed as it will automatically import all stories which follow the format `../examples/**/stories.@(ts|js)`
> [NO JIRA] Remove storybook from create component script

- .github/workflows/ci.yml
Our CI currently sends the following warning during builds and this is due to our GH actions being outdated, so this PR solved that.
> [NO JIRA]: Upgrade actions to the latest

- .spelling
- UNRELEASED.md
- packages/bpk-component-overlay/README.md
- packages/bpk-component-overlay/src/BpkOverlay.js
- packages/bpk-component-overlay/src/__snapshots__/BpkOverlay-test.js.snap
As part of discussions with design and how we will be expecting to use this, setting the default type to be `solid` with `low` style.
> [NO-JIRA]: Update default overlay styles

- UNRELEASED.md
- packages/bpk-component-checkbox/src/BpkCheckbox.module.scss
- packages/bpk-component-radio/src/BpkRadio.module.scss
Updating the cursor of the disabled input in the `BpkCheckbox` and `BpkRadio` components to use the `not-allowed` style, as having it on the parent `<label>` wasn't enough for full coverage of the element when hovering over it, though because the label has the style, simply inheriting the value is enough to solve the issue.
[Context and video](https://skyscanner.slack.com/archives/C0JHPDSSU/p1671114670988229?thread_ts=1671114550.335799&cid=C0JHPDSSU) with the before and after example of the change. You can also see the issue in the [Backpack docs](https://backpack.github.io/components/checkbox/?platform=web) for the components.
> [NO JIRA]: Update disabled input cursor for the BpkCheckbox and BpkRadio components

- UNRELEASED.md
- packages/bpk-component-switch/src/BpkSwitch.js
This deprecated 'type' property has a default value set which causes a lot of warnings even in the case when 'type' property is not set in the code.
The idea is to remove default value from prototype and move it to the code to prevent these warnings.
> Fix bpk switch deprecated type presence

- .spelling
- UNRELEASED.md
- packages/bpk-component-pagination/src/BpkPaginationPage.js
`primary` is not a valid `BpkButton` field so I switched it to `primaryOnLight`. This was spamming the console wherever we use a `BpkPagination` component and it was making our danger checks fail, preventing us from merging PRs.
> Fix BpkPagination throwing a warning caused by incorrect BpkButton prop

- UNRELEASED.md
- packages/bpk-component-image/src/BpkImage.module.scss
This PR fixes an issue that was introduced during the colour refresh. At the time I was confused to what this was and how it worked but now reverted to its previous setting.
The idea behind the change is for setting 'no background' (transparent) when the image being supplied to the component didn't fully fill the container. E.g. rounded images or images of say cars.
An example can be seen below on the car hire page - in this instance it has been overriden to restore previous functionality.
> [no jira]: Fix image background

- examples/bpk-component-autosuggest/examples.js
- examples/bpk-component-chip/examples.js
- packages/bpk-component-content-cards/src/BpkContentCard.js
- packages/bpk-component-content-cards/src/BpkContentCards.js
We recently completed #2727 to follow the new React standards and remove React imports, however it was found that some of the automated scripts messed two of the examples of our components so don't render anymore in storybook.
This PR fixes to include the correct imports for usage and restores the lost stories, it also adds back some removed comments for our temp TS disabling
> [no-jira]: Fixing changes from recent react import change

- UNRELEASED.md
- packages/bpk-component-button/src/BpkButtonBase.js
Tested this functionality in Safari, Chrome and FF and the bug doesn't appear.
This issue was raised in 2016 and the issue closed in 2018 due to inactivity.
It's likely this bug was fixed a long time ago so any risk from old browsers still with this bug (if it was a browser bug) is very minimal
> Remove onClick wrapper for BpkButton

- UNRELEASED.md
- examples/bpk-component-calendar/examples.js
- packages/bpk-component-calendar/README.md
- packages/bpk-component-calendar/src/BpkCalendarGrid.js
- packages/bpk-component-calendar/src/BpkCalendarGridHeader.js
- packages/bpk-component-calendar/src/__snapshots__/BpkCalendarContainer-test.js.snap
- packages/bpk-component-calendar/src/__snapshots__/BpkCalendarGrid-test.js.snap
- packages/bpk-component-scrollable-calendar/src/__snapshots__/BpkScrollableCalendar-test.js.snap
- packages/bpk-component-scrollable-calendar/src/__snapshots__/BpkScrollableCalendarGrid-test.js.snap
- packages/bpk-component-scrollable-calendar/src/__snapshots__/BpkScrollableCalendarGridList-test.js.snap
While testing the calendar on Percy, we identified legacy components for displaying weekdays and the current month that are causing trouble. The components do not display on the screen and are hidden from screen readers under normal circumstances. However, they contain invalid HTML which confuses Percy, leading to irrational screenshots.
See [here](https://percy.io/4ea9fae5/flights-search-controls/builds/25407558/changed/1416658585?browser=chrome&browser_ids=34&subcategories=unreviewed%2Cchanges_requested&viewLayout=overlay&viewMode=new&width=1280&widths=359%2C1280) for the issue that this PR is going to fix.
We decided to remove these components completely since they do not seem to serve any purpose and they do more harm than good.
I tested the accessibility of the calendar and the …
> [ST-4754] Remove the problematic component from Calendar.

- UNRELEASED.md
- packages/bpk-react-utils/src/deviceDetection-test.js
- packages/bpk-react-utils/src/deviceDetection.js
Google has recently deprecated the use of `navigator.platform` for determining a device being used so moving towards the newer favoured `navigator.userAgent`
> [KOA-2617]: Update device detection utils to support latest UA string

- UNRELEASED.md
- packages/bpk-component-scrollable-calendar/src/BpkScrollableCalendarGridList.js
- packages/bpk-component-scrollable-calendar/src/__snapshots__/BpkScrollableCalendar-test.js.snap
- packages/bpk-component-scrollable-calendar/src/__snapshots__/BpkScrollableCalendarGridList-test.js.snap
There is a bug with the BpkScrollableCalendarGridList where if you hide it (ie. `display: none`) and a re-size event is fired, the `setComponentHeight()` fn will be called and the BpkScrollableCalendarGridList will copy the `outerDiv` height of 0. If another re-size event does not occur, when the calendar is no longer hidden (ie. NOT `display: none`) then the calendar will still have a height of 0, making it invisible. 
> SEARCHEXP-873: Do not set height to 0 on re-size

- .github/workflows/_build.yml
- .github/workflows/main.yml
- .github/workflows/pr.yml
- .github/workflows/release.yml
Phase 2 in build improvements for our CI. This PR aims to improve the workflow by creating a cache for storybook builds to then be used as part of our visual tests and also our storybook deployments as this same build is shared by both steps.
This can lead to a reduction of about ~10mins of overall CI time down from ~15mins
> [KOA-5932][Phase 2]: Introduce build caching for visual tests and storybook deploy

- packages/bpk-component-link/README.md
- packages/bpk-component-link/src/BpkLink-test.js
- packages/bpk-component-link/src/BpkLink.js
Wrapping the component allows us to pass through a ref prop to a `<BpkLink>` component and have the ref attach to the `<a>` tag.
This allows us to expose the DOM node to the parent and is useful - for example, to allow focusing it.
Using `forwardRef` instead of creating a custom prop like `innerRef` as it gives us a predictable API instead of something custom which might change depending on the component.
> LOOM-631: Add forwardRef to BpkLink

- packages/bpk-component-dialog/src/common-types.ts
`getApplicationElement` is designed per the README to be used with `getElementById`.
`getElementById` returns null if the element can't be found
`dialogRef` is an internal prop that isn't part of the public API, but is listed as required.
> Fix BpkDialog type

- packages/bpk-component-price/src/BpkPrice.js
- packages/bpk-component-price/src/__snapshots__/BpkPrice-test.js.snap
When isAlignRight is false, the classname is false, and thus react throws a warning. Verified this fixes it in storybook locally
> Fix BpkPrice className warning

- .github/workflows/release.yml
When originally creating caching and the process for building the storybook distribution, we relied on for the releases to reuse a previous created storybook build that was created when changes got merged to main.
This meant it relied heavily on a cache being present when releasing and if say that cache was removed it would never create a new one as the step wasn't present as it relied on main.
So this change adds that functionality back that in the instance we manually deleted the main cache or it gets autoremoved by github (which should be very rare), it will now create it and upload it.
> [NO JIRA]: Add missing build cache creation for releases

- packages/bpk-component-button/docs/migrating-from-v1-to-v2.md
- packages/bpk-component-button/index.js
It seems the import path for `BpkButtonV2` not correct, therefore update import path `BpkButtonV2` in migrating docs.
- Update import path for `BpkButtonV2` in migrating docs
- export `BUTTON_TYPES` and `SIZE_TYPES` in `packages/bpk-component-button/index.js`
> [NO JIRA] Update import path BpkButtonV2 in migrating docs

- packages/bpk-scrim-utils/src/withScrim-test.tsx
- packages/bpk-scrim-utils/src/withScrim.tsx
Related to [this change](https://github.com/Skyscanner/backpack/pull/2892). The linked change is bugged in that it removes the `lockScroll` functionality from non iOS devices/browsers. This is an error and this PR fixes this. 
1. Why wasn't this regression caught in tests? 
The tests unfortunetly didn't catch this regression as the mocks used within the unit tests were not being reset correctly. This resulted in a test that was providing false expectations. This has also been addressed within this PR. 
2. Why wasn't this caught in the manual testing done previously in the above PR?
Again unfortunetly only iPhone devices/simulators were tested, the bug only appears on _non_ iOS devices as it was believed that this is the only area of code that was being impacted. 😮‍💨 This changes has been …
> [LOOM-796]: Fix scroll behaviour for _non_ iOS devices

- .storybook/preview.js
- packages/bpk-component-breakpoint/src/BpkBreakpoint.tsx
During investigations into transpiled bundlesizes it was found that the `BpkBreakpoint` component when importing tokens for use in the component was importing a full suite of Backpack tokens into the component to only then use a subset of breakpoints.
With this change we switch to importing from the `base.es6` tokens file and only import the breakpoint object into the component, so that when we ship this it means it should be lighter and only importing the tokens it requires instead of the whole suite.
> Change imports for breakpoints into bpk-component-breakpoint

- packages/bpk-component-button/src/BpkButtonBase.js
- packages/bpk-component-button/src/BpkButtonDestructive.js
- packages/bpk-component-button/src/BpkButtonFeatured.js
- packages/bpk-component-button/src/BpkButtonLink.js
- packages/bpk-component-button/src/BpkButtonLinkOnDark.js
- packages/bpk-component-button/src/BpkButtonPrimary.js
- packages/bpk-component-button/src/BpkButtonPrimaryOnDark.js
- packages/bpk-component-button/src/BpkButtonPrimaryOnLight.js
- packages/bpk-component-button/src/BpkButtonSecondary.js
- packages/bpk-component-button/src/BpkButtonSecondaryOnDark.js
Importing ts types should be done with the type keyword. When the code is transpiled, these imports are stripped out.
If we don't add the keyword, the import of Props sticks around, and if consumers evaluate the code at all, it will fail as the module has no export named Props as it's already been stripped out.
Spotted in Remix as part of the CSS bundling. (_no idea why_)
> Fix bpkButton ts imports

- packages/bpk-stylesheets/README.md
This PR corrects the usage instructions for `bpk-stylesheets` as it's main recommended/best use is to import via JS but the docs were confusing and pointing at CSS
> Correct README.md instructions

- packages/bpk-component-chip/README.md
- packages/bpk-component-chip/src/BpkSelectableChip.tsx
- packages/bpk-component-chip/src/accessibility-test.tsx
**Context**
This PR fixes the accessibility issue when BpkSelectableChip is used as a tab. For role='tab' the aria-checked attibute is not allowed.
https://dequeuniversity.com/rules/axe/4.5/aria-allowed-attr?application=axeAPI
More details here - https://skyscanner.slack.com/archives/C01T6U38DK3/p1693906192845719
> [No Jira] Fix a11y issue for BpkSelectableChip

- packages/bpk-component-button/index.d.ts
- packages/bpk-component-button/src/BpkButtonV2/common-types.d.ts
- packages/bpk-component-button/src/BpkButtonV2/common-types.tsx
- packages/bpk-component-graphic-promotion/src/BpkGraphicPromo.tsx
- packages/bpk-component-nudger/src/BpkConfigurableNudger.tsx
- packages/bpk-component-nudger/src/common-types.d.ts
- packages/bpk-component-nudger/src/common-types.ts
Allows for the export of the ButtonV2 types to be used in TS projects as these weren't available due to the way the whole component is implemented during the transition between Button V1 and Button V2.
> [NO JIRA]: Add export of ButtonV2 types

- examples/bpk-component-datatable/examples.js
- packages/bpk-component-datatable/README.md
- packages/bpk-component-datatable/src/BpkDataTable-test.js
- packages/bpk-component-datatable/src/BpkDataTable.js
- packages/bpk-component-datatable/src/__snapshots__/BpkDataTable-test.js.snap
- packages/bpk-component-datatable/src/accessibility-test.js
- packages/bpk-component-datatable/src/common-types.js
- packages/bpk-component-datatable/src/utils.js
Data table should use values in rem so that it can scale.
- Add warning messages when value in px (i.e. no unit provided) is passed to data table. This will be removed in the future and only rem values will be allowed.
- Convert px value to rem
> [KOA-6230] Datatable uses rem values

- packages/bpk-component-datepicker/src/BpkDatepicker.d.ts
- packages/bpk-component-datepicker/src/BpkDatepicker.tsx
- packages/bpk-component-dialog/README.md
- packages/bpk-component-dialog/src/BpkDialog.tsx
- packages/bpk-component-dialog/src/common-types.d.ts
- packages/bpk-component-dialog/src/common-types.ts
This PR corrects some types that we had some issues with when we moved to TS.
- Corrects Datepicker input type to accept a ReactElement vs a shared prop across multiple components
- Improves readability of README for dialog to be clearer on the `onClose` prop
- Adds a runtime type check to ensure that the correct types and combinations are passed
- Makes the Dialog `onClose` prop optional for when dismissible is true
> [NO JIRA]: Correct types for datepicker and dialog

- packages/bpk-react-utils/src/deviceDetection-test.ts
- packages/bpk-react-utils/src/deviceDetection.ts
The purpose of this PR is to fix an issue that was found whereby on newer generation of iPad Devices, due to their hardware and architecture they now report their device from the browser as a Macintosh/MacOS device instead of an iPad in their userAgent.
Below is a capture of an iPad Pro 10th Generation and what the browser is reporting as the user agent
To solve this from others encountering the issue in the community, the way in which it looks to solve this is by checking if the device has a number of touch points to indicate it is a touch device (more than 2 because iPad gestures support up to five touches at once) and in order to ensure we still only target iPads and not cross capture iPhones or other tablets and phones, we check for Macintosh being reported in the UA string
Below are …
> [KOA-6198]: Fix iPad detection utility for newer generation devices

- packages/bpk-component-slider/src/BpkSlider-test.tsx
- packages/bpk-component-slider/src/__snapshots__/BpkSlider-test.tsx.snap
- packages/bpk-component-slider/src/accessibility-test.tsx
- packages/package-lock.json
- packages/package.json
This PR bumps the `react-slider` dependency to the latest version that solves an issue whereby when moving the slider by small increments it would snap back to the previous value rather than the new value.
The same issue that was reported to Backpack was raised with [`react-slider`](https://github.com/zillow/react-slider/issues/279) and published in `2.0.5`, so bumping to the latest and it all works as expected
> [KOA-6290][BpkSlider]: Bump react-slider to solve snap back issue

- packages/bpk-mixins/src/mixins/_forms.scss
- packages/bpk-mixins/src/mixins/_svgs.scss
The purpose of this change is to move from utilising `bpk-svgs` Sass to using the icons directly as part of work to improve build times and move away from icons in Scss.
As we want to move away from the major number of icons imported this just uses the SVG directly into the code instead of pulling from one file
> [ARGG-811]: Replaces Scss icons in Backpack

- packages/bpk-component-section-header/index.d.ts
- packages/bpk-component-section-header/src/BpkSectionHeader.tsx
Description:
Backpack Section Header was not exporting typings
Changes made: 
- Export the types for the `BackpackSectionHeader` component
> [NOJIRA] Export TS types for Section Header Component

- packages/bpk-component-modal/src/BpkModalV2/BpkModal.tsx
We noticed during some testing of the new BpkModalV2 in Acorn a bug when opening the modal:
- The modal opens and the page crashes;
- An error was logged mentioning the DialogHTML element had already an open attribute.
This seems to be a bug. It has been reported by other developers in this thread for example: https://github.com/facebook/react/issues/24399.
In summary, an open attribute is added to a dialog element when used in react (despite the fact the dialog element adds an open attribute when it opens). Therefore, this causes the modal to crash.
This PR introduces a change to remove any attribute 'open' on the dialog before opening it. This fixes the bug and the modal opens as it should.
Bug occurs in Chrome 103-114, Firefox 103-114.
> [NO-JIRA] Fix Bug on dialog with open attribute for BpkModalV2

- packages/bpk-scrim-utils/README.md
- packages/bpk-scrim-utils/src/__snapshots__/withScrimmedPortal-test.tsx.snap
- packages/bpk-scrim-utils/src/withScrimmedPortal-test.tsx
- packages/bpk-scrim-utils/src/withScrimmedPortal.tsx
Provide an `isPortalReady` prop to notify when the component inside the portal is ready to be used. This may be necessary to interact with the content of the component in a `useEffect` hook, for example to set the focus on mount.
> [ARGG-851] Fix withScrimmedPortal component for deterministic order of execution

- examples/bpk-component-card-button/examples.tsx
- examples/bpk-component-card-button/stories.ts
- packages/bpk-component-button/README.md
- packages/bpk-component-card-button/src/BpkSaveButton.tsx
- packages/bpk-component-icon/README.md
1. When the onCheckedStatus returns async rejection, the toggle style should not take effect.
2. The backpack document remains some old BpkButton usages, which is already been deprecated.
1. When the button is checked and there is async error rejection, the save button should not display toggled animation.
2. The `<BpkButton>` in all readme files should be replaced with `<BpkButtonV2>`
1. fix the button toggle issue when is async with reject
2. fix the typo in README.md since the BpkButton has been deprecated
3. Add new async with error checked example to mock and test the cases.
The `onCheckedStatus` function will return a `Promise.reject`, the button checked status should not be changed and the toggled zooming anition should not be displayed either.
| Before                        | …
> Fix async toggle style issue & BpkButton -> BpkButtonV2 in README files

- examples/bpk-component-scrollable-calendar/examples.js
- examples/bpk-component-scrollable-calendar/stories.js
- packages/bpk-component-calendar/src/BpkCalendarContainer.d.ts
- packages/bpk-component-calendar/src/BpkCalendarContainer.tsx
- packages/bpk-component-calendar/src/composeCalendar.d.ts
- packages/bpk-component-calendar/src/composeCalendar.tsx
- packages/bpk-component-scrollable-calendar/src/BpkScrollableCalendarGridList-test.tsx
- packages/bpk-component-scrollable-calendar/src/BpkScrollableCalendarGridList.d.ts
- packages/bpk-component-scrollable-calendar/src/BpkScrollableCalendarGridList.tsx
- packages/bpk-component-scrollable-calendar/src/__snapshots__/BpkScrollableCalendarGridList-test.tsx.snap
We want to be able to pass an optional heigh prop to add extra whitespace between months.
See the images below for reference.
> [SHIBA-2119] Added Optional Height Prop for Scrollable Calendar

- packages/bpk-component-autosuggest/src/BpkAutosuggestSuggestion.js
This change fixes the name of the exported component of the `BpkAutosuggestSuggestion` component, which currently causes our docs to crash as this component can't be found, See here: https://www.skyscanner.design/latest/components/autosuggest/web-1dnVX8RX
This is a strange one of how this has been working for years without modification as nothing has recently changed with this component and the naming hasn't been an issue but there is a mismatch in namings which causes storybook to not render the story. See here: https://backpack.github.io/storybook 
This fix then aligns all the naming as per our docs and fixes the error with storybook not rendering.
> [BpkAutosuggest]: Fixing autosuggest component

- packages/bpk-component-bottom-sheet/src/BpkBottomSheetInner.tsx
BpkBottomSheet throws an error in the console during use:
This property in CSSTransition is not actually required for correct functioning of the animations so it is being removed 
-------
> NOJIRA - BpkBottomSheet "out" console error fix

- packages/bpk-component-navigation-bar/src/BpkNavigationBar.tsx
- packages/bpk-component-navigation-bar/src/BpkNavigationBarButtonLink.tsx
- packages/bpk-component-navigation-bar/src/BpkNavigationBarIconButton.tsx
Follow up to #3110 - removing the `propTypes` now we have typescript in the nav bar. Separate PR as we initially thought this was a breaking change, but turns out it's not
> [DTO-4949][BpkNavigationBar] Remove prop-types from navbar

- .storybook/webpack.config.js
- examples/bpk-component-datepicker/examples.js
- examples/bpk-component-grid-toggle/stories.js
- package-lock.json
- packages/bpk-component-grid-toggle/index.js
Adds mini css extract plugin to drastically reduce the bundlesize. This ultimately allows for enableJavascript to be added to Percy config, before the JS asset was too large and presumably errors occured in upload or parsing on Percy side.
> [NOJIRA]: add mini-css-extract-plugin

- .npmrc
Add a `.npmrc` file to ensure that the public registry is always pointed to.
> [NOJIRA]: add npmrc to point to public reg

- .percy.yml
Allowing js execution within Percy evaluation. Ultimately we want to do this as we are seeing inconsistency with some of our snap with components that are particularly reliant on js presence in order to render correctly.
> [NOJIRA]: Percy add enable-javascript

- packages/bpk-component-navigation-bar/src/BpkNavigationBar.module.scss
- packages/bpk-component-navigation-bar/src/BpkNavigationBarButtonLink.module.scss
- packages/bpk-component-navigation-bar/src/BpkNavigationBarIconButton.module.scss
Removes the extra component layers that (I think 🤷 ) are no longer required. It resolves the `on-dark` issue where the `&--on-dark` classes have become un-nested.
> remove layers and resolve issues with on-dark in navbar

- packages/bpk-component-info-banner/src/BpkInfoBanner-test.tsx
- packages/bpk-component-info-banner/src/BpkInfoBanner.tsx
- packages/bpk-component-info-banner/src/BpkInfoBannerInner.tsx
- packages/bpk-component-info-banner/src/__snapshots__/BpkInfoBanner-test.tsx.snap
- packages/bpk-component-info-banner/src/__snapshots__/BpkInfoBannerDismissable-test.tsx.snap
- packages/bpk-component-info-banner/src/__snapshots__/BpkInfoBannerInner-test.tsx.snap
- packages/bpk-component-info-banner/src/__snapshots__/withBannerAlertState-test.tsx.snap
Currently when an info banner is render on a page, the screenreader will immediately switch to reading out the title text. This happens because we treat the info banner as an alert for screen readers. [The documentation](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/alert_role) says the alert role shouldn’t be used for elements rendered on page load. Since this component is used more as a styling container than an alert dialog it should only be read in the normal page flow.
https://github.com/Skyscanner/backpack/assets/22656572/e665fc0f-cfd4-440d-bd97-96b61fa4cbf9
> [DTO-5004][BpkInfoBanner] Remove Alert Role

- packages/bpk-component-breakpoint/src/BpkBreakpoint.tsx
- packages/bpk-component-breakpoint/src/__snapshots__/BpkBreakpoint-test.tsx.snap
Fix hydration mismatch error in BpkBreakpoint component. This change makes the BpkBreakpoint server-side snapshot match the snapshot initially rendered on the client.
> [ARGG-927][BpkBreakpoint] Update breakpoint to remove hydration mismatch error

- package-lock.json
- package.json
- packages/package-lock.json
- packages/package.json
The current Internal node stable version includes an update to npm 10. Additionally, the .nvmrc file pins the LTS/hydrogen version - which too expects npm 10 as a pairing.
I have previously updated [backpack-node-sass](https://github.com/Skyscanner/backpack-node-sass/pull/58) and [bpk-svgs](https://github.com/Skyscanner/bpk-svgs/pull/44). These 
The change is backwards compatible and thus this should only be a minor bump.
> ST-5444 Updating npm version to match LTS/Node stable pairing 

- examples/bpk-component-bottom-sheet/examples.tsx
- examples/bpk-component-bottom-sheet/stories.js
- packages/bpk-component-bottom-sheet/src/BpkBottomSheetInner-test.tsx
- packages/bpk-component-bottom-sheet/src/BpkBottomSheetInner.tsx
- packages/bpk-component-bottom-sheet/src/__snapshots__/BpkBottomSheetInner-test.tsx.snap
This PR fixes the accessibility issue in `BpkBottomSheet` - currently when no `title` is provided to `BpkBottomSheet`, an empty `h2` is rendered. This PR conditionally renders the `h2` tag depending on if `title` is `""` or not. 
> [THES-158] BpkBottomSheet fix empty heading - accessibility

- .github/workflows/_build.yml
- .github/workflows/main.yml
- .github/workflows/pr.yml
- .github/workflows/release.yml
This PR updates the build caching mechanism for determining if there is a new build for storybook to deploy.
Currently the way it works is looks for updates only to the `packages/` files but if someone in their PR or in additional commits to a PR update our examples in `examples/` the CI will never see this newer version to deploy as it doesn't take those files into account, so would only ever deploy old unchanged versions of the stories.
So by us adding to the hashing for generating a cache id `examples/` this will take into account if the files their also update to generate a new cache that will then be deployed
> [NO JIRA]: Update build caching key naming to account for stories updates

- examples/bpk-component-button/examples.js
- examples/bpk-component-button/stories.js
- packages/bpk-component-button/README.md
- packages/bpk-component-button/src/BpkButtonV2/BpkButton-test.tsx
- packages/bpk-component-button/src/BpkButtonV2/BpkButton.d.ts
- packages/bpk-component-button/src/BpkButtonV2/BpkButton.module.scss
- packages/bpk-component-button/src/BpkButtonV2/BpkButton.tsx
- packages/bpk-component-button/src/BpkButtonV2/common-types.d.ts
- packages/bpk-component-button/src/BpkButtonV2/common-types.tsx
- packages/bpk-mixins/_buttons.scss
Currently microsites are overriding the BpkButton styles via classname prop.
This adds the functionality to the component removing the need to use the undesirable classname prop to achieve this
| Library  | Link |
| ------------- | ------------- |
|  Material UI | https://mui.com/material-ui/api/button/ |
| Next UI | https://nextui.org/docs/components/button#button-props |
| Polaris | https://polaris.shopify.com/components/actions/button#props |
A non-exhaustive list
| Component  | Image |
| ------------- | ------------- |
| Culture Selector  | <img width=300 src="https://github.com/Skyscanner/backpack/assets/1532576/fee33a8d-0c1e-4702-b978-8103fc867b8c" />  |
| Login Modal  | <img width=300 src="https://github.com/Skyscanner/backpack/assets/1532576/2ab3c157-e886-4649-8ae9-d04f770bf4a5" …
> [LOOM-1221][BpkButton]: Add fullWidth prop to BpkButton

- packages/bpk-component-banner-alert/src/BpkBannerAlertInner.tsx
- packages/bpk-component-banner-alert/src/__snapshots__/BpkBannerAlertDismissable-test.tsx.snap
- packages/bpk-component-banner-alert/src/__snapshots__/BpkBannerAlertInner-test.tsx.snap
- packages/bpk-component-banner-alert/src/__snapshots__/withBannerAlertState-test.tsx.snap
> LOOM-1262 redundant BkpBannerAlertInner style removed and snapshots updated

- scripts/transpilation/copy-css.js
- scripts/transpilation/copy-types.js
This PR fixes the transpilation scripts to capture all nested files. Previously the logic only implemented captured those that had the name `V2` in the folder name. Which lead to with the introduction of the `BpkDialogWrapper` the CSS and types files were located in the incorrect place and causes errors at build time.
This PR now updates the scripts to capture these that don't include `V2` in the name, to correct relocate files
| Script | Before | After |
| -- | -- | -- |
| copy-types | ![copy-types with errors](https://github.com/Skyscanner/backpack/assets/8831547/9ba7893f-2901-4929-b34b-adf6f68c8d68) | ![copy-types with fix](https://github.com/Skyscanner/backpack/assets/8831547/e25163e1-eede-4d72-9af1-a0526f270256) |
| copy-css | ![copy-css with …
> [NO JIRA]: Fix transpilation scripts to capture nested files

- .github/dependabot.yml
Adding groups for dependabot PRs, the idea with this is to try some of the large groups together to see if PRs will get raised together. In turn this should lead to less overheads for Percy testing and maintainer management of deps
If this proves successful we can move to a layer further where we can bump all devDeps in one group but this does come with a risk (future discussion point)
> Creating dependabot group patterns to group dependencies for PRs

- packages/bpk-component-datatable/src/BpkDataTable-test.tsx
- packages/bpk-component-datatable/src/BpkDataTableHeader.module.scss
- packages/bpk-component-datatable/src/BpkDataTableHeader.tsx
- packages/bpk-component-datatable/src/__snapshots__/BpkDataTable-test.tsx.snap
- packages/bpk-component-datatable/src/__snapshots__/BpkDataTableHeader-test.tsx.snap
**Class 2 Backpack overrides**
Arrow alignment fixed by setting `line-height`.
Minor update to the test since the arrow up and down (svgs) are now children of the wrapper div and hence the svgs need to be clicked, not the wrapper div.
> LOOM-1277 BpkDataTableHeader

- packages/bpk-component-breadcrumb/src/BpkBreadcrumbItem.js
- packages/bpk-component-breadcrumb/src/BpkBreadcrumbItem.module.scss
- packages/bpk-component-breadcrumb/src/__snapshots__/BpkBreadcrumbItem-test.js.snap
**Add existing Bpk child component overrides to wrappers.**
Had to set a specific line height after adding the wrapper around the 16x16 or 32x32(zoomed) icon to retain the correct alignment, i.e. adding the wrapper increases the height of the right arrow icon which then affects the alignment of the right arrow within the breadcrumb.
**Without** the line height fix, the right arrows are vertically shifted up:
<kbd> ![Screenshot 2024-03-28 at 11 37 19](https://github.com/Skyscanner/backpack/assets/7976511/8446a39b-d48a-4558-beac-5113be268225) </kbd>
**With** the line height fix, the right arrows are back to where they should be centrally aligned:
<kbd> ![Screenshot 2024-03-28 at 11 39 05](https://github.com/Skyscanner/backpack/assets/7976511/c27f51f4-8269-4664-9a00-414686f5cc76) </kbd>
> LOOM-1274 BpkBreadcrumb Class 2 Overrides

- packages/bpk-component-fieldset/src/BpkFieldset.js
- packages/bpk-component-fieldset/src/__snapshots__/BpkFieldset-test.js.snap
Moved the styling from `<BpkLabel>` into a parent wrapper and updated snapshots.
> LOOM-1283 BpfFieldset Class 2 Overrides

- packages/bpk-component-dialog/src/BpkDialog.module.scss
- packages/bpk-component-dialog/src/BpkDialog.tsx
- packages/bpk-component-dialog/src/__snapshots__/BpkDialog-test.tsx.snap
Part of work moving className usage out of backpack components.
Moved className from BpkCloseButton out to wrapper span, adjusted margins slightly to compensate shift
> LOOM-1281 BpkDialog className moved to new wrapper span

- packages/bpk-component-drawer/src/BpkDrawer.js
- packages/bpk-component-drawer/src/BpkDrawerContent.js
- packages/bpk-component-drawer/src/__snapshots__/BpkDrawer-test.js.snap
- packages/bpk-component-drawer/src/__snapshots__/BpkDrawerContent-test.js.snap
**Changes:**
1. `BpkDrawer`: duplicate style removed.
2. `BpkDrawerContent`: `BpkCloseButton` styling added to a parent wrapper.
> LOOM-1282 BkpDrawerContent BpkDrawer Class 2 Overrides

- packages/bpk-component-fieldset/src/__snapshots__/BpkFieldset-test.js.snap
- packages/bpk-component-form-validation/src/BpkFormValidation.js
- packages/bpk-component-form-validation/src/__snapshots__/BpkFormValidation-test.js.snap
LOOM-1287 BpkFormValidation moved className on BpkSmallExclamationIcon to new wrapper span
> LOOM-1287 BpkFormValidation moved className

- examples/bpk-component-rating/examples.js
- packages/bpk-component-rating/README.md
It's not immediately obvious that the title attribute of the BpkRating can accept any React Node. The only 2 examples of this are images. 
> NOJIRA: Add rating example with stars

- packages/bpk-component-section-list/src/BpkSectionListItem.js
- packages/bpk-component-section-list/src/BpkSectionListItem.module.scss
- packages/bpk-component-section-list/src/__snapshots__/BpkSectionListItem-test.js.snap
1. Added `className` override to wrapper for both the `href` and `onClick`.
2. Needed to use `display: contents` on the wrapped style after adding the wrapper to retain the icon alignment.
> LOOM-1314 BpkSectionListItem Class 2 Overrides

- packages/bpk-component-mobile-scroll-container/src/BpkMobileScrollContainer-test.js
- packages/bpk-component-mobile-scroll-container/src/BpkMobileScrollContainer.js
- packages/bpk-component-mobile-scroll-container/src/BpkMobileScrollContainer.module.scss
Removed the leading and training indicators as default behavior. Users can still pass `leadingIndicatorClassName` and `trailingIndicatorClassName` to add it back in.
> [BDES-137][bpk-component-mobile-scroll-container] Removed edge fade

- packages/bpk-component-breakpoint/src/BpkBreakpoint-test.tsx
- packages/bpk-component-breakpoint/src/BpkBreakpoint.tsx
BpkBreakpoint, prior to https://github.com/Skyscanner/backpack/pull/3299 would re-render on client. This would ensure that any server rendered content would be replaced with the up to date client content. 
After the linked change this behaviour was removed, it wasn't well documented or tested for. 
This PR aims to replace that behaviour and add more comments within the code to prevent accidental removal in the future.
> [NOJIRA][BpkBreakpoint]: fix ssr re-render behaviour

- packages/bpk-component-floating-notification/src/BpkFloatingNotification.module.scss
It was discovered that the floating notification was not positioned above the Saved cards and would go under a toggle and heart buttons. This looks confusing and unfinished.
In order to address the issue, it was decided to position the toast above other elements. 
The change was minimal, the toast style now includes a `z-index` set to `2`, which puts the BPKFloatingNotification above other elements. This works across the whole page and supports RTL.
Please see the video demonstrating the original state (overlapping elements) and the solution proposed in this PR (end of the video with `z-index: 2;`).
https://github.com/Skyscanner/backpack/assets/55076036/4a6fed37-6174-431d-b9e2-54c98c54947d
> [ZOOT-992][BpkFloatingNotification] Increases floating notification's z-index to 2

- packages/bpk-component-chip-group/src/BpkChipGroup.tsx
- packages/bpk-component-chip-group/src/BpkChipGroupSingleSelect.tsx
Splitting up definitions of the group types to reduce logic
> Split definitions for group types

- examples/bpk-component-bottom-sheet/examples.tsx
- examples/bpk-component-bottom-sheet/stories.js
- examples/bpk-component-navigation-bar/examples.js
- examples/bpk-component-navigation-bar/stories.js
- packages/bpk-component-bottom-sheet/src/BpkBottomSheet.module.scss
- packages/bpk-component-bottom-sheet/src/BpkBottomSheet.tsx
- packages/bpk-component-bottom-sheet/src/__snapshots__/BpkBottomSheet-test.tsx.snap
- packages/bpk-component-modal/src/__snapshots__/BpkModal-test.tsx.snap
- packages/bpk-component-modal/src/__snapshots__/BpkModalInner-test.tsx.snap
- packages/bpk-component-navigation-bar/index.d.ts
- packages/bpk-component-navigation-bar/src/BpkNavigationBar.d.ts
- packages/bpk-component-navigation-bar/src/BpkNavigationBar.module.scss
- packages/bpk-component-navigation-bar/src/BpkNavigationBar.tsx
- packages/bpk-component-navigation-bar/src/BpkNavigationBarButtonLink.d.ts
- packages/bpk-component-navigation-bar/src/BpkNavigationBarIconButton.d.ts
- packages/bpk-component-navigation-bar/src/__snapshots__/BpkNavigationBar-test.tsx.snap
- packages/bpk-component-navigation-bar/src/themeAttributes.d.ts
It was discovered that long titles overlap the buttons on the BpkBottomSheet component. The issue arises from the underlying BpkNavigationBar component lacking handling for this scenario.
Fix improves layout based on design requirement to clamp the text with ellipsis when there is not enough space to fit without encroaching on buttons or wrapping to an additional line.
* Navigation Bar
* BottomSheet
| Tablet  | Large Mobile | Small Mobile |
| ------------- | ------------- |------------- |
| <img src="https://github.com/Skyscanner/backpack/assets/3943125/b654f195-f1dc-4d2b-a567-3ec5a62e9068" width="250"/> | <img src="https://github.com/Skyscanner/backpack/assets/3943125/810a17a9-e422-4868-9061-bb805072ba90" width="250"/> | <img src="https://github.com/Skyscanner/backpack/assets/3943125/1064 …
> [IRN-5018][BpkNavigationBar][BpkBottomSheet] Add handling for long title text

- package.json
Turns out when we made Backpack transpiled we were using `rimraf` to clean the dist folder but never had it installed directly to use.
I think this may have 'worked' because the dependency was being pulled as indirect and was local for folks who had existing clones it worked for with the dep.
However with a fresh install and setup of the repo it fails when running `npm run transpile` because the `rimraf` command isn't available. To avoid having to maintain another dep, I have switched this command to do a simple `rm -rf` for the dist folder.
> [NO JIRA] [maintenance]: Update dist clean command as we never had rimraf

- packages/bpk-component-scrollable-calendar/src/BpkScrollableCalendarGridList.module.scss
- packages/bpk-component-scrollable-calendar/src/BpkScrollableCalendarGridList.tsx
- packages/bpk-component-scrollable-calendar/src/__snapshots__/BpkScrollableCalendar-test.tsx.snap
- packages/bpk-component-scrollable-calendar/src/__snapshots__/BpkScrollableCalendarGridList-test.tsx.snap
> [LOOM-1312] [BpkScrollableCalendarGridList] Moved className to existing wrapper div

- packages/bpk-component-close-button/src/BpkCloseButton-test.js
- packages/bpk-component-close-button/src/BpkCloseButton.js
- packages/bpk-component-loading-button/src/BpkLoadingButton-test.js
- packages/bpk-component-loading-button/src/BpkLoadingButton.tsx
Several `console.error` messages caused by incorrect rest statements and prop types fixed
> [NOJIRA][BpkLoadingButton|BpkCloseButton]: fix loading console errors

- packages/bpk-component-dialog/src/BpkDialogInner.module.scss
- packages/bpk-component-dialog/src/BpkDialogInner.tsx
- packages/bpk-component-dialog/src/__snapshots__/BpkDialog-test.tsx.snap
**Class 2 Overrides**:
- Move flare overrides to wrapper.
- There is no visual test for this yet.  I can add a visual test first and then we can review this change after that if we thinks that's better?
- I've tested locally and the component matches, just needed `display: flex` on the flare:
- Before:
- After:
> LOOM-1365 BpkDialogInner

- .github/workflows/_build.yml
This PR moves Percy later in the CI process once all other testing has passed. The reason to move this to not be parallel or leave where it is, so to reduce usage of Percy to only be run once other testing is green, instead of having it run but tests fail and then having to run it again once other testing has been fixed. 
Essentially moving this to once per PR.
> [maintenance][ARGG-1144]: Move Percy later in the CI as last step

- packages/bpk-component-popover/src/BpkPopover.module.scss
- packages/bpk-component-popover/src/BpkPopover.tsx
Re-adding the popover z-index that was previously accidently removed in the recent popover update which would cause the popover to render under content.
> [BpkPopover]: Fix popover z-index for rendering over content

- packages/bpk-component-nudger/src/BpkConfigurableNudger.tsx
- packages/bpk-component-nudger/src/__snapshots__/BpkNudger-test.tsx.snap
Remove `tabIndex=-1` from nudger input component as this is not a valid attribute for an input field. 
This resolves several defects across our pages where nudgers are in use.
> [BpkNudger] Fix accessibility issue

- packages/bpk-component-breakpoint/src/BpkBreakpoint-test.tsx
- packages/bpk-component-breakpoint/src/BpkBreakpoint.tsx
Initially incorrect value (`false`) was used when using BpkBreakpoint on a client rendered application. This was due to the forced re-render functionality also doubling as client environment detection. In this PR they have been separated and thus the issue is removed.
`useEffect and useState` is used to solve forced re-rendering and `typeof window` statement is used to detect the initial `isClient` value. 
Change(s):
- use typeof check rather than boolean to determine if environment is client. Continue to support forced re-renders
> [NOJIRA][BpkBreakpoint]: Bug fix initial incorrect value of isClient on client rendered applications

- examples/bpk-component-text/examples.js
- examples/bpk-component-text/stories.js
- package-lock.json
- package.json
- packages/bpk-component-text/README.md
- packages/bpk-stylesheets/larken.scss
- packages/package-lock.json
- packages/package.json
Adds the missing Noto fallback fonts to the new Larken font-family 
(NOTE: just waiting on this PR to update token https://github.com/Skyscanner/backpack-foundations/pull/321 to merge and then can bump the package)
Fallback Fonts info https://skyscanner.atlassian.net/wiki/spaces/PD/pages/722121809/Fallback+fonts
New Larken editorial font
New Fallback Fonts in multi language using Pangrams
> [WALL-1371][BpkText] Add the Noto fallbacks for the Larken font

- examples/bpk-component-floating-notification/examples.tsx
- packages/bpk-component-floating-notification/src/BpkFloatingNotification.module.scss
- packages/bpk-component-floating-notification/src/BpkFloatingNotification.tsx
- packages/bpk-component-floating-notification/src/__snapshots__/BpkFloatingNotification-test.tsx.snap
Bug: CTA button incorrectly aligned to the left. 
Changes: 
- fix floating button cta position, 
- correct margin for text
- all stories render rather directly than require button click
> [NOJIRA][BpkFloatingNotification]: Fix CTA position

- packages/bpk-component-popover/src/BpkPopover.module.scss
Fixes a mismatch between the classname applied to a container and the CSS name as it was incorrect so not applying the CSS
> [NO JIRA][BpkPopover]: Fix popover container classname

- packages/bpk-component-horizontal-nav/src/BpkHorizontalNav.js
- packages/bpk-component-mobile-scroll-container/src/BpkMobileScrollContainer.js
- packages/bpk-scrim-utils/src/withScrim-test.tsx
- packages/bpk-scrim-utils/src/withScrim.tsx
Optimize rendering performance in componentDidMount using requestAnimationFrame
In order to improve the page's INP Score, this PR addresses performance issues related to rendering in the componentDidMount lifecycle method of three components: **BpkHorizontalNav, BpkMobileScrollContainer, and withScrim**.
Previously, the rendering logic in **componentDidMount** could cause **reflows** and impact performance. To mitigate this, **requestAnimationFrame** is now used to defer rendering until the next frame, allowing the browser to optimize layout and painting.
> [BD-8430][BpkHorizontalNav, BpkMobileScrollContainer, withScrim] Resolve reflow impact

- examples/bpk-component-text/examples.js
- package-lock.json
- package.json
- packages/bpk-component-text/src/BpkText.module.scss
- packages/bpk-component-text/src/BpkText.tsx
- packages/bpk-mixins/_typography.scss
- packages/package-lock.json
- packages/package.json
This PR includes typography updates to align Backpack with the latest [Typography Spec](https://skyscanner.atlassian.net/wiki/spaces/PD/pages/670800556/Typography+tokens).
- Updates all existing Hero text styles to match correct weight, size and line-height.
- Adds a new Hero 6 typography style.
- Exposes the new Hero 6 style through `BpkText` as `TEXT_STYLES.hero6`
- Upgrades `@skyscanner/bpk-foundations-web` to `^18.0.0`
> [WALL-1807][BpkText] Update hero text styles

- packages/bpk-component-popover/src/BpkPopover-test.tsx
- packages/bpk-component-popover/src/BpkPopover.tsx
After merging the [PR](https://github.com/Skyscanner/backpack/pull/3390), we cannot close `BpkPopover` when changing `isOpen` to false, in the previous implementation, it handles in [componentDidUpdate](https://github.com/Skyscanner/backpack/blob/main/packages/bpk-react-utils/src/Portal.tsx#L116) in the Portal component
It was caused a bug in the BpkDatepicker, the calendar cannot be closed after selecting a date even it called [onClose](https://github.com/Skyscanner/backpack/blob/main/packages/bpk-component-datepicker/src/BpkDatepicker.tsx#L169) to set `isOpen` to `false`
> [NOJIRA][BpkPopover] Fix Popover cannot be closed by changing `isOpen`

- packages/bpk-component-card-button/src/BpkSaveButton.module.scss
It was discovered that the save button does not change the cursor when a user hovers over it. This can cause confusion as it may indicate that the button is not clickable and prevent from performing an action.
The obvious solution is to enforce a pointing cursor on the heart button. This problem can be solved by adding a style change and does not require any additional logic being added to the code.
https://github.com/Skyscanner/backpack/assets/55076036/b42d1238-6dc9-46cd-96b3-0be9067926d1 
https://github.com/Skyscanner/backpack/assets/55076036/baefadb8-08dd-4c6a-913c-2f8f74a25577
> [LUNA-1589][BpkSaveButton] Updates Save Button cursor

- packages/bpk-component-popover/src/BpkPopover-test.tsx
- packages/bpk-component-popover/src/BpkPopover.tsx
Wraps the popover in `FloatingPortal` this is part of the floating ui library that allows you to determine when in the DOM you render the popover to be displayed.
Previously the popover would have been attached to the node directly adjacent to the target that triggers it, this creates an issue whereby when rendered in a small window space would cause the popover to render inside/behind content even with a `z-index` applied.
With adding this new portal to the popover it will now attach the popover to the main `body` in HTML so means it will always display over content regardless of where its contained, fixing the above issue
> [NO JIRA][BpkPopover]: Update popover to attach to body outside of target elements

- examples/bpk-component-card-button/examples.tsx
- packages/bpk-component-card-button/README.md
- packages/bpk-component-card-button/src/BpkSaveButton.tsx
- packages/bpk-component-card-button/src/__snapshots__/BpkSaveButton-test.tsx.snap
The save button behaves like a toggle button, so we should add aria-pressed to clarify this. As a benefit, we don't have to change the aria-label based on the state of the button.
Aria-label changes are poorly communicated and can confuse people using screen readers. 
- Add 'aria-pressed' to the button
- Update documentation
- Update storybook
> [ACC-568][BpkSaveButton] Accessibility improvements

- packages/bpk-component-input/src/withOpenEvents.tsx
This PR removes from the `withOpenEvents` HoC the `stopPropgation` call as when its applied blocks the keyboard interactions with the input field.
To see this in action try navigating with a keyboard to the input field here in the [datepicker example](https://backpack.github.io/storybook/?path=/story/bpk-component-datepicker--range) and try to open it using either `Space` or `Enter`, and watch as the field doesn't display the datepicker
> [NO JIRA]: remove stop propgation that blocks keyboard events

- packages/bpk-component-popover/src/BpkPopover.tsx
Within #3495 it was added to propagate the onClick to floating UI, however there was no check to see if there is an onClick present so currently if there is an onClick not provided it can cause an issue with a failure as the onClick property is not available, we don't see this as a widespread issue because when using the BpkPopover it would be expected that the target that the popover is using would have an onClick to set the state of open or not.
We saw this issue more in tests rather than in actual production issues.
> [NO JIRA][BpkPopover]: Check for onClick property in the target

- packages/bpk-component-accordion/src/BpkAccordion.js
- packages/bpk-component-accordion/src/BpkAccordionItem.js
- packages/bpk-component-accordion/src/__snapshots__/BpkAccordion-test.js.snap
- packages/bpk-component-accordion/src/__snapshots__/BpkAccordionItem-test.js.snap
- packages/bpk-component-accordion/src/__snapshots__/withAccordionItemState-test.js.snap
- packages/bpk-component-accordion/src/__snapshots__/withSingleItemAccordionState-test.js.snap
🎫 [Luna-1371](https://skyscanner.atlassian.net/browse/LUNA-1371) for reference.
There is an issue on iOS where VoiceOver reads the word "description" as it goes through the flight's filter Accordion.
We have identified that this is due to the usage of `dt` `dl` and `dd` in the component as VioceOver will read the element attached to it.
> [Luna-1372][BpkAccordion] Remove description filter

- examples/bpk-component-popover/examples.js
- examples/bpk-component-popover/stories.js
- packages/bpk-component-popover/src/BpkPopover.tsx
We had an issue where when a popover is used within a modal that meant that the popover would render outside of the modal and to the main page below, meaning it would be hidden from the view and rendered behind.
This is due to the default behvaiour without specification to render to the body. So to solve this we return a previously removed property in v34 `renderTarget`.
This property is used to specify to the `FloatingPortal`, where to attach the popover giving consumers the previous ability to specify where in the DOM to place the component when its time to render meaning that it can then be displayed within the modal and not to content behind
> [NO JIRA][BpkPopover]: Reinstate renderTarget prop for rendering in DOM at specific location

- packages/bpk-component-segmented-control/src/BpkSegmentedControl.module.scss
I noticed that in RTL, the flights tabs using `BpkSegmentedControl` have the border between non-selected segments in the wrong place. I fixed this by using `border-inline-start` instead of `border-left` in the styles, relying on the inline style direction (defined by text orientation) instead of hard-coded left/right styles.
Flights tab in RTL:
| --- | --- |
| <img width="400" alt="Screenshot 2024-07-12 at 12 24 32" src="https://github.com/user-attachments/assets/90420a1e-a24d-4681-a57f-1c489fa36ae7"> | <img width="400" alt="Screenshot 2024-07-12 at 12 24 22" src="https://github.com/user-attachments/assets/f50c3d5e-1beb-4498-9358-16cbce4f3339"> | 
> [NO-JIRA] [BpkSegmentedControl] RTL fix

- packages/bpk-component-segmented-control/src/BpkSegmentedControl.module.scss
A previous PR (https://github.com/Skyscanner/backpack/pull/3539) to fix focus state changed the border radius of the first and last element but it didn't take into consideration RTL. This is quite hard to see in storybook but can be seen in this banana percy diff - https://percy.io/09e69e44/banana/builds/35374902/changed/1933320690?browser=chrome&browser_ids=59&group_snapshots_by=similar_diff&subcategories=unreviewed%2Cchanges_requested&viewLayout=overlay&viewMode=new&width=360&widths=360%2C1280
The changes here handle RTL 
> [NO-JIRA]: [BpkSegmentedControls] Fix rtl border radius issue

- examples/bpk-component-accordion/examples.js
- examples/bpk-component-accordion/stories.js
- packages/bpk-component-accordion/src/BpkAccordionItem.js
- packages/bpk-component-accordion/src/BpkAccordionItem.module.scss
- packages/bpk-component-accordion/src/__snapshots__/BpkAccordionItem-test.js.snap
- packages/bpk-component-accordion/src/__snapshots__/withAccordionItemState-test.js.snap
- This PR fixes an issue introduced via [this PR](https://github.com/Skyscanner/backpack/pull/3553) that stopped the `divider` prop from working.
- Adds a story/example of Accordion without divider on dark.
> [WALL-2135]{BpkAccordion] Fix accordion wothout divider

- packages/bpk-component-checkbox/src/form-test.js
- packages/bpk-component-input/src/form-test.tsx
- packages/bpk-component-nudger/src/form-test.tsx
- packages/bpk-component-phone-input/src/form-test.js
- packages/bpk-component-radio/src/form-test.js
- packages/bpk-component-select/src/form-test.js
- packages/bpk-component-switch/src/form-test.js
Newly added tests under `form-test.[t|j]sx` for the following form components:
- BpkCheckbox
- BpkInput
- BpkNudger
- BpkPhoneInput
- BpkRadio
- BpkSelect
- BpkSwitch
> [LOOM-1531] Add form tests for form components

- examples/bpk-component-button/examples.tsx
- examples/bpk-component-button/stories.tsx
- examples/bpk-component-loading-button/examples.js
- examples/bpk-component-loading-button/stories.js
- packages/bpk-component-loading-button/src/BpkLoadingButton.tsx
Minor change to add the submit prop to the loading button props. Due to confusion in the past, it's probably best to make the submit prop type for the loading button explicit for consumers of Backpack as in the past, some users have set the type to be submit without knowing the submit prop exists and inherits the props from BpkButton via ...rest
> NO-JIRA: Added submit to loading button props

- examples/bpk-component-slider/examples.js
- packages/bpk-component-slider/src/BpkSlider.tsx
- packages/bpk-component-slider/src/__snapshots__/BpkSlider-test.tsx.snap
- packages/package-lock.json
- packages/package.json
The Slider currently provides a default invisible input when wrapped in a form. We don't want to use this as we can't control any aspects of this input. onChange events, custom attributes like (`type`, `form`) . I've raised a [ticket](https://github.com/radix-ui/primitives/pull/3033) to add support for an inputRef Prop to radix-ui but until then we can rely on using our own composition and defining the BubbleInput ourselves.
> [LOOM-1520][BpkSlider] Fix for Slider to support Form properly

- packages/bpk-component-slider/src/form-test.tsx
Adding a form-test to our slider component to check if it renders correctly. 
> [Loom-1535] - add form-test to bpkSlider

- packages/bpk-component-split-input/src/BpkSplitInput.tsx
Fixes an issue raised via #3565 that caused the `inputValue` state to always be a string array regardless of the type, this then causes issues whereby when putting in numbers they would be able to populate this value due to incompatible types
> [NO JIRA][BpkSplitInput]: Fix default state of inputValue

- examples/bpk-component-inset-banner/examples.tsx
The storybook stories defined for the `bpk-component-inset-banner` component are using different UI styles (banner colour and logo) than the inset banner app components. This makes the styles not aligned in the backpack docs, so we want to update the styles to match the ones used by the app versions of the component.
- [Web inset banner docs](https://www.skyscanner.design/latest/components/inset-banner/web-QHUmIW4g)
- [App inset banner docs](https://www.skyscanner.design/latest/components/inset-banner/compose-SIxM16J2)
> [NO-JIRA] [BpkInsetBanner] Update stories UI styles to match docs

- package-lock.json
- package.json
Reverts Skyscanner/backpack#3477 as newer PRs are broken for percy tests and storybook due to the CSS having loading issues
PRs with issues can be found: #3608 and #3607 
The reason we didn't see it in the original PR was because the build being used was built from a working build cache and not a new version using this config so was never picked up as the cache is built based on changes to examples and packages folders
> Revert "Bump css-loader from 6.10.0 to 7.1.2"

- examples/bpk-component-navigation-tab-group/examples.tsx
- packages/bpk-component-navigation-tab-group/README.md
- packages/bpk-component-navigation-tab-group/src/BpkNavigationTabGroup-test.tsx
- packages/bpk-component-navigation-tab-group/src/BpkNavigationTabGroup.tsx
- packages/bpk-component-navigation-tab-group/src/accessibility-test.tsx
When using BPK Nav tabs in GC header, we found MouseEvent need pass  from  BPK NavTabs
There is click event function in GC header to handle all click event in Header .
And also need tab id and nav id pros in BPK NavTabs.  For data analytics, nav tabs also need data analytics props as optional.  
> [PANGOO-2581][BpkNavigationTabGroup]Add Extra Props in BPK NavTabGroup

- examples/bpk-component-radio/examples.js
The Storybook examples used a different `name` property for the radio group. This breaks the interaction with keyboard and doesn't allow for 'tabbing into' the group and then using the arrow keys to navigate around. 
The change I made allows for the correct behaviour to show in our documentation website. In the future we should consider wrapping the example in a fieldset to give a proper Accessible sample. 
> [BpkRadio] update Storybook example

- examples/bpk-component-navigation-tab-group/examples.tsx
- packages/bpk-component-navigation-tab-group/src/BpkNavigationTabGroup.tsx
There is warning For BPK NavTabGroup.So need to fix.
> [PANGOO-2594][BpkNavigationTabGroup]Fix BPK NavTabGroup Warning

- examples/bpk-component-floating-notification/examples.tsx
A request from design has come up for the examples which are used in our documentation site don't want to persist forever and disappear just a bit longer than the default `hideAfter` value.
So this PR changes the docs sites examples from 28days to 8 seconds.
We haven't touched the values for the visual tests just so that it doesn't become flaky in Percy tests
> [NO JIRA][FloatingNotification]: Update floating notification dismiss timeout

- packages/bpk-component-navigation-tab-group/README.md
- packages/bpk-component-navigation-tab-group/src/BpkNavigationTabGroup.module.scss
- packages/bpk-component-navigation-tab-group/src/BpkNavigationTabGroup.tsx
> [NO JIRA][BpkNavigationTabGroup]Modify Navigation Tab Group A11Y

- examples/bpk-component-price/examples.js
- examples/bpk-component-price/stories.js
- packages/bpk-component-price/src/BpkPrice-test.js
- packages/bpk-component-price/src/BpkPrice.js
- packages/bpk-component-price/src/__snapshots__/BpkPrice-test.js.snap
- packages/bpk-component-price/src/common-types.js
**Description**
Currently, 16px is not available in Backpack Price. The minimun font-size available is 20px.
In this task, we should contribute to Backpack to include the 16px option, to be able to use it in our new Unified xSell components
- Added `xsmall` type and include new size in `BpkPrice`
- Updated unit test
- Updated snapshots
- Added stories
| BpkPrice xsmall | styles |
| ----------- | ----------- |
| <img width="110" alt="Screenshot 2024-10-16 at 16 12 50" src="https://github.com/user-attachments/assets/7551938e-5df5-481b-8d41-c010a5084809"> | <img width="337" alt="Screenshot 2024-10-16 at 16 12 59" src="https://github.com/user-attachments/assets/25304d42-6a77-480a-b4d8-6eae5f8372d0"> |
> CAPY-889 Add xsmall to BpkPrice component

- packages/bpk-component-switch/src/BpkSwitch.module.scss
Adding focus indicator round switch component
**Before**
https://github.com/user-attachments/assets/39613b00-8127-4bca-a4a6-f10727f592ef
**After**
https://github.com/user-attachments/assets/7501841d-af4e-4a1a-97a1-8e57ccc3cf1e
> [LUNA-2015][BpkSwitch] Adds focus indicator

- examples/bpk-component-card/examples.js
- packages/bpk-component-card/src/BpkDividedCard.module.scss
Removing the `min-height` and `min-width` and therefore letting the content decide those instead.
NOTE: added the label `major` as we are making visual changes. 
| -------- | -------- |
| <img width="644" alt="Screenshot 2024-10-29 at 15 07 30" src="https://github.com/user-attachments/assets/e7e00d7c-673a-44ce-b243-b3c46470f6db"> | <img width="644" alt="Screenshot 2024-10-29 at 15 06 54" src="https://github.com/user-attachments/assets/0c4307be-2c04-4c01-8b78-b1f1792470c6"> |
| <img width="644" alt="Screenshot 2024-10-29 at 15 07 24" src="https://github.com/user-attachments/assets/70151205-d1ff-4075-9c3e-9f8664c5f47e"> | ![Screenshot 2024-10-29 at 16 03 31](https://github.com/user-attachments/assets/52bd19c0-ff91-4093-930c-a103c0324ee7) |
Remember to include the …
> CAPY[909] Remove min width & height on BpkDividedCard

- examples/bpk-component-card/examples.js
- packages/bpk-component-card/src/BpkDividedCard.module.scss
Reverts Skyscanner/backpack#3658
This is an attempt to fix something strange where this PR has been included in the latest minor release but it not supposed to be. Github compare says that the PR is not in the release but the code changes do appear to be there.
Slack:
https://skyscanner.slack.com/archives/C0JHPDSSU/p1730363569669369
https://skyscanner.slack.com/archives/C0JHPDSSU/p1730360088402519
> Revert "CAPY[909] Remove min width & height on BpkDividedCard"

- packages/bpk-component-map/src/BpkIconMarkerBackground.js
- packages/bpk-component-map/src/__snapshots__/BpkIconMarker-test.js.snap
- packages/bpk-component-map/src/__snapshots__/BpkIconMarkerBackground-test.js.snap
> [BD-9128][BpkIconMarkerBackground] Add aria-hidden to fix a11y issue

- .eslintignore
- .gitignore
- gulpfile.js/bpk-component-spinner/gulpfile.babel.js
- gulpfile.js/bpk-component-spinner/gulpfile.js
- gulpfile.js/index.js
- packages/bpk-component-spinner/src/BpkExtraLargeSpinner.tsx
- packages/bpk-component-spinner/src/BpkLargeSpinner.tsx
- packages/bpk-component-spinner/src/BpkSpinner.tsx
- packages/bpk-component-spinner/src/themeAttributes-test.tsx
This PR fixes an issue that at generation/transpilation stage of the spinner in Backpack the code to mark the Spinner icons as `aria-hidden` is removed.
To solve this we follow the same process as the bpk-icons where gulp brings them to the project for use rather than them being pulled and transpiled from `bpk-svgs`
| -- | -- |
| ![Screenshot 2024-11-20 at 15 28 23](https://github.com/user-attachments/assets/c7776e1a-49c5-4ec2-aa98-1fd179623752) | ![Screenshot 2024-11-20 at 15 28 45](https://github.com/user-attachments/assets/c908ee10-c0d9-46d1-9855-1f4fed5b109f) |
> [NO JIRA][BpkSpinner]: Fix Spinner removing aria-hidden from element

- examples/bpk-component-button/examples.tsx
- add aria-label to icon only button to resolve accessibility defect.
> [Storybook] BpkButton, fix accessibility violation

- decisions/deprecated-api.md
- decisions/future-api.md
- decisions/release-schedule.md
Adding documentation on new release schedule & the required deprecated api and future api to handle these changes across versions.
> [ARGG-1349][documentation]: add deprecated-api, future-api and release-schedule documents

- packages/package-lock.json
- packages/package.json
`react-slider` currently errors when being used alongside Webpack and React 17.
```
Module not found: Error: Can't resolve 'react/jsx-runtime' in '.../banana/packages/webapp/node_modules/@radix-ui/react-slider/dist'
Did you mean 'jsx-runtime.js'?
BREAKING CHANGE: The request 'react/jsx-runtime' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
```
This is not fixed until React 18. At this point we still need to support React 17.
https://github.com/facebook/react/issues/20235#issuecomment-1095340542
This PR reverts to an …
> [ST-6228] [BpkSlider] Pin react-slider to version that still supports React 17

- package-lock.json
- package.json
As we have with NPM, use `>=` to allow consumers on newer versions of Node to install Backpack.
> [ST-6210] Allow Node >=18 in engines config

- examples/bpk-component-overlay/examples.js
- examples/bpk-component-overlay/stories.tsx
- packages/bpk-component-overlay/src/BpkOverlay.module.scss
- packages/bpk-component-overlay/src/BpkOverlay.tsx
- packages/bpk-component-overlay/src/__snapshots__/BpkOverlay-test.tsx.snap
JIRA: https://skyscanner.atlassian.net/browse/GRAV-1370
The new homepage hero video ad POC requires a [new video overlay](https://www.figma.com/design/o7vYhyVecpNyC92vTDPNTf/Video-Moments?node-id=2742-4578&m=dev). This PR adds that new overlay type to `BpkOverlay` as `videoTop` and `videoBottom`. 
Link to Figma video overlay design: https://www.figma.com/design/yN0hFyZlKL0Jwbpi0rEKYT/Backpack-Beta?node-id=27362-1451&m=dev 
| No overlay | Video Overlay |
| --- | --- |
| <img width="300" src="https://github.com/user-attachments/assets/c399c1c5-6a5d-4cb7-ae58-505c30d969a8" /> | <img width="1162" alt="Screenshot 2025-01-21 at 15 17 57" src="https://github.com/user-attachments/assets/d0d505d0-3fd9-4f0e-b0fc-49375a22109a" /> |
- The following checks …
> [GRAV-1370] [BpkOverlay] Add video overlay style

- examples/bpk-component-inset-banner/examples.tsx
- examples/bpk-component-inset-banner/stories.ts
- packages/bpk-component-inset-banner/README.md
- packages/bpk-component-inset-banner/src/BpkInsetBanner-test.tsx
- packages/bpk-component-inset-banner/src/BpkInsetBanner.module.scss
- packages/bpk-component-inset-banner/src/BpkInsetBanner.tsx
- packages/bpk-component-inset-banner/src/accessibility-test.tsx
JIRA: https://skyscanner.atlassian.net/browse/QUAR-497
When the `BpkInsetBanner` component was created last year we added the CTA object prop accepting a text element. Now we need to add the CTA button and popover functionality so that we can add required legal info in the adverts using the inset banner.
Props added to `CallToAction` object prop:
- `popoverMessage`: message that will be displayed inside the popover dialog when the CTA button is clicked.
- `popoverPlacement`: where the popover dialog should appear when CTA button is clicked (ex. 'top', 'bottom', etc).
- `buttonCloseLabel`: text to display in the close button of the popover dialog.
- `buttonA11yLabel`: accessibility aria label for the CTA button.
- `popverLabel`: label of the popover dialog, and if `labelTitle` is true, …
> [QUAR-497] [BpkInsetBanner] Add CTA button & popover

- packages/bpk-component-switch/src/BpkSwitch.module.scss
We noticed the focus ring around the BpkSwitch component doesn't follow the component outline. There was also inconsistent behaviour when clicking the component, sporadically showing the focus ring. 
This PR adjusts the focus ring visual style and ensures it will show up when focusing by keyboard navigation only
| Before |  After | 
| --- | --- |
| ![image](https://github.com/user-attachments/assets/1150cc50-d06e-408b-8169-c9b062006d26) | ![image](https://github.com/user-attachments/assets/0a691596-40f0-4c2e-aace-48a770f9c4d2) |
> [BpkSwitch] Adjust focus behaviour

- packages/bpk-component-mobile-scroll-container/src/BpkMobileScrollContainer.module.scss
We are looking for the reason why the `BpkMobileScrollContainer` component triggers **client crash in iOS Safari 15.x**.
In the last [PR](https://github.com/Skyscanner/backpack/pull/3701) we converted the jsx file to a stable tsx file and fixed some possible bugs, but the client crash still happened when we tried to upgrade to the latest BpkMobileScrollContainer component within the hotels-website. 
We suspected that a potentially problematic scss file was introduced in the scss packaging file, and raised this PR to remove unused `scroll-indicators` in `BpkMobileScrollContainer.module.css`
Have tested in the [storybook](https://backpack.github.io/storybook-prs/3741/?path=/story/bpk-component-mobile-scroll-container--default), won't affect original scroll feature.
Remember to include the …
> [BD-9310][BpkMobileScrollContainer] Remove unused scroll indicators

- .storybook/webpack.config.js
- package-lock.json
- package.json
- packages/bpk-stylesheets/webpack.config.babel.js
See: https://github.com/Skyscanner/backpack/pull/3629
Largely this PR is aimed at reducing the import structure of css - this has caused downstream issues and we'd like to avoid this. (other consumers of css-loader assume regarding the import structure)
Thus, this PR follows this guidance listed here: https://github.com/webpack-contrib/css-loader/blob/master/CHANGELOG.md#700-2024-04-04
For other details please see the above linked ticket.
> [NOJIRA] install and migrate to css-loader@v7

- examples/bpk-component-calendar/examples.js
- packages/bpk-component-calendar/src/BpkCalendarGrid-test.tsx
- packages/bpk-component-calendar/src/BpkCalendarGrid.tsx
- packages/bpk-component-calendar/src/__snapshots__/BpkCalendarContainer-test.tsx.snap
- packages/bpk-component-calendar/src/__snapshots__/BpkCalendarGrid-test.tsx.snap
- packages/bpk-component-scrollable-calendar/src/BpkScrollableCalendarGrid.tsx
- packages/bpk-component-scrollable-calendar/src/__snapshots__/BpkScrollableCalendar-test.tsx.snap
- packages/bpk-component-scrollable-calendar/src/__snapshots__/BpkScrollableCalendarGrid-test.tsx.snap
- packages/bpk-component-scrollable-calendar/src/__snapshots__/BpkScrollableCalendarGridList-test.tsx.snap
The BpkCalendarGrid have some accessibility issues. This causes some high severity issues on the [Opex report](https://skyscanner.atlassian.net/wiki/spaces/RIRP/pages/1308246211/2025-02-17+-+UX+Platform#id-2025-02-17-UXPlatform-Accessibility) in [AQA](https://aqa.usablenet.com/#/audit/skyscanner/suites/TS11196/a11yMonitors/A159802-1739509200009/T163052/step1/details/view/AI5/info).
- WAI-ARIA grid role doesn't have an accessible name
- User interface component doesn't have an accessible name
> Test in storybook for BpkCalendarGrid changes
|  Before   |   After      |   
| ----------------------- | ------------------------ | 
| <img src="https://github.com/user-attachments/assets/6b093bc2-bf20-48c8-99a3-a2c826a81016" width=300/> | <img …
> [ACC-632][BpkCalendarGrid]: Fix accessibility issue - grid has no accessible name

- packages/bpk-component-mobile-scroll-container/src/BpkMobileScrollContainer.tsx
In some browsers not supported by Browserslist, such as Safari 15.7.1 - it will not appear in the list when configuring [Safari >= 15](https://browsersl.ist/#q=Safari+%3E%3D+15), and after bundling with the [Nx webpack plugins](https://nx.dev/recipes/webpack/webpack-plugins), the reference to `debounce` may be lost, causing an exception error.
To solve the compatibility issue of using `debounce`, bind it to an instance property to ensure that the correct reference can always be obtained.
> [BD-9310][BpkMobileScrollContainer] Optimize the use of debounce for compatibility

- packages/bpk-component-info-banner/src/BpkInfoBanner-test.tsx
- packages/bpk-component-info-banner/src/BpkInfoBanner.module.scss
- packages/bpk-component-info-banner/src/BpkInfoBannerExpandable-test.tsx
- packages/bpk-component-info-banner/src/BpkInfoBannerInner.tsx
- packages/bpk-component-info-banner/src/__snapshots__/BpkInfoBanner-test.tsx.snap
- packages/bpk-component-info-banner/src/__snapshots__/BpkInfoBannerDismissable-test.tsx.snap
- packages/bpk-component-info-banner/src/__snapshots__/BpkInfoBannerInner-test.tsx.snap
- packages/bpk-component-info-banner/src/__snapshots__/withBannerAlertState-test.tsx.snap
- packages/bpk-component-info-banner/src/withBannerAlertState-test.tsx
Fix a11y issue - element with button role can not be operable via keyboard
We identified this issue in hotels day-view:
1. Change the toggle button from `<button>` to `<div>` and not clickable.
2. Change the expendable header to a `<button>`.
3. Style adjustments to maintain the original appearance.
> [BD-9484][BpkInfoBannerExpandable] Fix an a11y issue

- packages/bpk-stylesheets/README.md
This PR updates the docs for use of bpk-stylesheets based on the build tools that we are using in Skyscanner.
By default if you use the default JS export when using say vite it will not transpile the Sass and imports so intead you need to use the pre-transpiled code which exists under the `base.js` and `base.css` files, this is to ensure that in the output bundles the compiled css files have the removed `:global` declarations and operate at a base style
> [LOOM-2050]: Updating docs for different build tools usage

- packages/bpk-component-chip-group/src/Nudger.module.scss
> We noticed that the spacing between the nudgers and the chips is 12px (8px+4p) while it [should be 8px](https://www.figma.com/design/irZ3YBx8vOm16ICkAr7mB3/Backpack-Components?node-id=30119-41685&t=PwBcT7Q8ucoRaEw2-0).  Potentially the easiest (but maybe not the best?) fix would be to reduce the margin-inline-end  to 4px (bpk-spacing-sm).
[Slack thread](https://skyscanner.slack.com/archives/C0JHPDSSU/p1740996283806069)
> [NO-JIRA][BpkChipGroup] Align nudger margins in rail chip group with design

- packages/bpk-component-inset-banner/README.md
- packages/bpk-component-inset-banner/src/BpkInsetBanner-test.tsx
- packages/bpk-component-inset-banner/src/BpkInsetBanner.tsx
- packages/bpk-component-popover/src/BpkPopover.module.scss
- packages/bpk-component-popover/src/BpkPopover.tsx
JIRA: https://skyscanner.atlassian.net/browse/QUAR-706
Thread with context: https://skyscanner.slack.com/archives/C0JHPDSSU/p1740574285075669
When trying to use the `BpkInsetBanner` with CTA popover in the Banana booking panel page, there were 2 other backpack components on the page with higher z-index taking priority and preventing the popover of the inset banner from showing. To fix this we decided to add a custom z-index prop (`zIndexCustom `) to the inset banner component that gets passed to the popover component (via `zIndexValue` prop). If a z-index value is provided then that can be used for the popover, otherwise the default z-index of `900` is used.
| Before (default `z-index: 900`) | After (custom `z-index: 1100`) |
| --- | --- |
| <img width="400" alt="Screenshot 2025-03-04 at …
> [QUAR-706][BpkPopover & BpkInsetBanner] Add custom z-index value

- packages/bpk-component-drawer/src/BpkDrawer.tsx
- packages/bpk-component-drawer/src/BpkDrawerContent.module.scss
- packages/bpk-component-drawer/src/BpkDrawerContent.tsx
- packages/bpk-component-drawer/src/__snapshots__/BpkDrawer-test.tsx.snap
[[MAT-2306]](https://skyscanner.atlassian.net/browse/MAT-2306)
[BpkDrawer](https://www.skyscanner.design/latest/components/drawer/web-QAxL5e0N) needs a code contribution:
- Any width can be applied by consumers. This essentially means removing the 400px max-width and allowing any width.
- Update transition into duration-base for both entering and exiting
[MAT-2306]: https://skyscanner.atlassian.net/browse/MAT-2306?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MAT-2306][BpkDrawer] Update BpkDrawer by allowing dynamic width and animation

- examples/bpk-component-segmented-control/examples.module.scss
- examples/bpk-component-segmented-control/examples.tsx
- examples/bpk-component-segmented-control/stories.tsx
- packages/bpk-component-segmented-control/src/BpkSegmentedControl.module.scss
- packages/bpk-component-segmented-control/src/BpkSegmentedControl.tsx
[JIRA](https://skyscanner.atlassian.net/browse/GOOSE-148)
This PR contains changes required for the Segmented Control component to be used by the Flights Search Controls date switcher.
Specifically, this PR...
- Switches CSS Flex with CSS Grid so that the tab items maintain equal widths when used and centred within a flex container.
- Removes style `text-overflow` from control item, as it was agreed that consumers should be in charge of how the content is displayed within each item, and not enforce via this component.
- A11y fixes including ([context](https://skyscanner.slack.com/archives/C0JHPDSSU/p1742283184632619?thread_ts=1742227344.368179&cid=C0JHPDSSU)):
- Removal of `radiogroup` role. This is because the component does not behave as would be expected for radio group so removing for …
> [GOOSE-148][BpkSegmentedControl] Refactor for use by Flights Search Controls

- examples/bpk-component-overlay/examples.js
- examples/bpk-component-overlay/stories.tsx
- packages/bpk-component-overlay/src/BpkOverlay.module.scss
- packages/bpk-component-overlay/src/BpkOverlay.tsx
- packages/bpk-component-overlay/src/__snapshots__/BpkOverlay-test.tsx.snap
Jira: https://skyscanner.atlassian.net/browse/QUAR-801
In January we added the video overlay style for the BpkOverlay component in https://github.com/Skyscanner/backpack/pull/3717 to be used in the homepage video advert POC. In the next version of the ad we have to align the video overlay with the [backpack heavy overlay design](https://www.figma.com/design/irZ3YBx8vOm16ICkAr7mB3/Backpack-Components?node-id=11552-10364&t=DpBVMfaxOntH0kNp-11). 
- Slack thread in #backpack-design-chat for context: https://skyscanner.slack.com/archives/CUQ587E5D/p1743775241236679
- Video homepage ad design: https://www.figma.com/design/o7vYhyVecpNyC92vTDPNTf/Video-Moments?node-id=2622-16895&t=ugMReV4E1xVklJKZ-0
We're renaming the overlay type from `video` to `heavy`, which would normally be a breaking change …
> [QUAR-801][BpkOverlay] Update video overlay to align with heavy overlay design

- examples/bpk-component-link/examples.js
- examples/bpk-component-link/stories.js
- packages/bpk-component-link/src/BpkLink.js
- packages/bpk-component-link/src/BpkLink.module.scss
- packages/bpk-mixins/_buttons.scss
- packages/bpk-mixins/_typography.scss
[Jira -- Explicit Link](https://skyscanner.atlassian.net/jira/polaris/projects/VDL2/ideas/view/6107461?issueViewLayout=sidebar&issueViewSection=overview&selectedIssue=VDL2-34)
**Description**:
1. update the bpk-link to the new explicit bpk-link style;
2. add a new boolean prop "implicit" to bpk-link to enable using old design;
3. add a new "bpk-link--implicit" example and update the propTypes and defaultProps.
> [BD-9545][BpkLink] Add bpk-link--explicit for the new bpk-link design.

- examples/bpk-component-price/examples.js
- examples/bpk-component-price/stories.js
- packages/bpk-component-price/src/BpkPrice-test.js
- packages/bpk-component-price/src/BpkPrice.js
[BD-9736](https://skyscanner.atlassian.net/browse/BD-9736)
In some user case, some crawlers need to inspect the real price(not the previous price). So it will be convenient that we provide a data attribute to the price element(not the whole BpkPrice Component). This pr will add a prop: `dataPriceYourPick`. if set it true, then it will append a data attribute: `data-price-your-pick="true"` to the price element.
[BD-9736]: https://skyscanner.atlassian.net/browse/BD-9736?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BD-9736] [BpkPrice] Append data attribute to Price Element

- examples/bpk-component-inset-banner/examples.tsx
- examples/bpk-component-inset-banner/stories.ts
- packages/bpk-component-inset-banner/README.md
- packages/bpk-component-inset-banner/src/BpkInsetBanner.module.scss
- packages/bpk-component-inset-banner/src/BpkInsetBanner.tsx
We noticed that in our sponsored booking panel ad that uses the bpk inset banner, on iPhones the popover is cutoff at the end due to the width of the popover being too large. There's also an issue with the width of certain partner logos being too big and pushing content out of the banner.
| Popover UI issue on iPhone |
| --- |
| <img width="200" alt="Screenshot 2025-04-22 at 13 10 58" src="https://github.com/user-attachments/assets/7915cbb4-92fa-4e6a-b45d-4cf353f13e34" /> |
- Added a `popoverWidth` prop to pass a string width value (so that either pixel or rem values can be passed) to the popover
- Added a max width of 120px for logos in mobile screen sizes
- Added 1rem margin to the right of the popover so it isn't stuck to the right side of the screen like it currently is.
| Before | …
> [NO-JIRA][BpkInsetBanner] Fix UI issues

- packages/bpk-component-chip-group/src/Nudger.tsx
There is an intermittent edge case where the right hand nudger is never disabled due to `1px` calculation error, which may occurs depending on a combination of parents width and screen width. Unfortunately, I was not able to find the pattern that causes the issue, but looking for some external references the suggestion is to introduce a threshold of 2 pixels before evaluating nudgers conditions.
| - | - |
| <video src="https://github.com/user-attachments/assets/d6576307-632e-4a56-a54b-019d981a9bac" /> | <video src="https://github.com/user-attachments/assets/aa44c51c-dcb1-41db-8d06-bd0481bd9956" /> |
> [CAPY-1169][BpkChipGroup]: Set Chip Group Nudgers edge threshold

- packages/bpk-component-image/src/BpkBackgroundImage.tsx
- packages/bpk-component-image/src/__snapshots__/BpkBackgroundImage-test.tsx.snap
- packages/bpk-component-image/src/withLoadingBehavior.tsx
This PR fixes the position of the loading spinner for `bpk-background-image` by fixing the class names from `bpk-image-*` to `bpk-background-image-*`.
| - | - |
| ![Screenshot 2025-05-07 at 13 00 17](https://github.com/user-attachments/assets/9a799224-69e9-4c2e-909d-af11412e7f56) | ![Screenshot 2025-05-07 at 12 59 59](https://github.com/user-attachments/assets/2d041d0d-8d3c-4ae3-88ef-54575444a908) |
> [CAPY-1378][BpkImage]: Fixing bpk-background-image loading spinner position

- dangerfile.ts
This PR removes the danger warning about type files not being updated when component js files are changed.
As the `.d.ts` files are only generated at build/publish this warning is confusing to new PRs as its a warning that cannot be actioned, so removing this will reduce PR noise and align with the functionality of the repo
> [NO-JIRA][maintenance]: Remove no longer required danger warning

- examples/bpk-component-navigation-tab-group/examples.tsx
- examples/bpk-component-navigation-tab-group/stories.tsx
- packages/bpk-component-navigation-tab-group/src/BpkNavigationTabGroup-test.tsx
- packages/bpk-component-navigation-tab-group/src/BpkNavigationTabGroup.tsx
We would like to prevent the tab selection in case the tab is an anchor supposed to open links in a new browser tab.
> [CAPY-1253][BpkNavigationTabGroup]: Prevent NavigationTabGroup selection when tab opens a new browser tab

- packages/bpk-component-segmented-control/src/BpkSegmentedControl-test.tsx
- packages/bpk-component-segmented-control/src/BpkSegmentedControl.tsx
CLOV-252, adjust segmented control
To ensure we make the segmented control more accessible we're setting a group role and adding an aria-label that is settable using the label prop.
> [BpkSegmentedControl] adjust role and add label prop

- packages/bpk-component-scrollable-calendar/src/BpkScrollableCalendarGrid.tsx
- packages/bpk-component-scrollable-calendar/src/__snapshots__/BpkScrollableCalendar-test.tsx.snap
- packages/bpk-component-scrollable-calendar/src/__snapshots__/BpkScrollableCalendarGrid-test.tsx.snap
- packages/bpk-component-scrollable-calendar/src/__snapshots__/BpkScrollableCalendarGridList-test.tsx.snap
The month labels were all set to be H1. For accessibility, there can only be a single H1 per page. We assume that the page that includes this calendar will always have an H1 as page title and the calendar should be at least H2. 
In the future we can consider to let the consumer pass the appropriate heading level for the calendar grid.
> [BpkScrollableCalendarGrid] Adjust month heading from H1 to H2

- examples/bpk-component-inset-banner-v2/examples.tsx
- examples/bpk-component-inset-banner-v2/stories.ts
This PR adds the missing variant combinations for the BpkInsetBannerSponsored component to ensure coverage of both `onLight` and `onDark` themes with and without images.
Our examples only demonstrated:
- `onLight` variant without an image
- `onDark` variant with an image
Added the following examples:
1. `WithCtaTextAndBottomSheetExampleV2Dark` - Shows the inset banner in `onDark` variant without an image
2. `WithImageAndBottomSheetExampleV2Light` - Shows the inset banner in `onLight` variant with an image
Now the component has coverage for all combinations:
- onLight + no image ✅
- onLight + image ✅
- onDark + no image ✅
- onDark + image ✅
- Created two new component examples in examples.tsx
- Added corresponding story exports in stories.ts
- Maintained consistent styling and conventions …
> [QUAR-864][BpkInsetBannerSponsored]-add new examples for sponsored banners with and without images

- packages/bpk-component-rating/src/BpkRating-test.tsx
- packages/bpk-component-rating/src/BpkRating.tsx
The BpkRating only has two required props. However, the previous changes(#2184 and #3872) made two props required by mistake. This PR is to fix this issue.
**Props explanation**: https://backpack.github.io/storybook/iframe.html?args=&id=bpk-component-rating--documentation&viewMode=docs
> [NO-JIRA][BpkRating] Fixed the issue where some BpkRating attributes were required

- examples/bpk-component-card-list/examples.tsx
- packages/bpk-component-card-list/src/BpkCardListRowRail/BpkCardListCarousel.tsx
- packages/bpk-component-card-list/src/BpkCardListRowRail/BpkCardListRowRailContainer.tsx
- packages/bpk-component-card-list/src/common-types.ts
1. When change `initiallyShownCards`, the `currentIndex` should be update
2. Update  buffer size dynamically to guarantee the last shown indicator corresponding card is rendered.
https://github.com/user-attachments/assets/c7abf56f-3c63-4f21-ae64-4f9f9f6b1669
https://github.com/user-attachments/assets/44c21363-48f9-40b8-a0d9-a1a7d12eac72
wing changes:
> [CLOV-402][BpkCardList] Fix cardlist initially shown cards change issue

- packages/bpk-component-inset-banner/src/BpkInsetBannerV2/BpkInsetBannerSponsored.tsx
This PR adds the `closeOnScrimClick` prop to the BpkBottomSheet component in BpkInsetBannerSponsored. This change makes the Bottom Sheet close when users click outside of it (on the background/scrim), bringing its behavior in line with the BpkPopover component used in the original BpkInsetBanner.
> [QUAR-991] [BpkInsetBannerSponsored] Add closeOnScrimClick prop to BpkBottomSheet

- examples/bpk-component-text/examples.js
- examples/bpk-component-text/examples.module.scss
- packages/bpk-component-text/README.md
- packages/bpk-component-text/index.ts
- packages/bpk-component-text/src/BpkText-test.tsx
- packages/bpk-component-text/src/BpkText.module.scss
- packages/bpk-component-text/src/BpkText.tsx
**Context**
BpkText’s lack of default or token-based color support leads to widespread manual style overrides (average 14.88% per major page), undermining VDL consistency and reducing design system reliability and maintainability across Skyscanner products.
We have added color prop so that consumer can change `BpkText` color by config but not override before, and want to constraint for `BpkText` color prop only allowed BPK text color tokens.
**Changes**
- Add `BpkText` color prop with leverage css classname, replaces inline style-based color prop with CSS class-based approach using predefined tokens
- Exports `TEXT_COLORS` constants and `TextColor` type for consumer use
- Updates tests and documentation to reflect the new color prop implementation
Remember to include the following …
> [CLOVER-532][BpkText] Add BpkText color prop with leverage css classname

- examples/bpk-component-modal/examples.tsx
- examples/bpk-component-modal/stories.tsx
- packages/bpk-component-modal/src/BpkModalInner.tsx
When we wrongly set the `onDark` prop to `BpkButtonLink` before([original PR](https://github.com/Skyscanner/backpack/pull/3447/files#diff-df999835b1d554fe1ab9384a45253714a087966c76a54f3e00e1869ca698430dR154 )), but actually, we don't have `onDark` in  `BpkButtonLink`, but `alternate` instead https://github.com/Skyscanner/backpack/blob/9d698eaf7e0ddbb14d8f87c613f957167b58cc08/packages/bpk-component-link/src/BpkButtonLink.js#L36
this would also cause an warning  in dev  when comsumer uses BpkModal
|before| after|
|---|---|
|<img width="300" alt="image" src="https://github.com/user-attachments/assets/6d1c3735-13f8-4cea-91a8-f270e4bcfbe2" />|<img width="300" height="458" alt="image" src="https://github.com/user-attachments/assets/ed6080b7-46bd-45ff-a48a-de5df569de6e" />|
Remember to include …
> [NOJIRA][BpkModal]fix closeText style of BpkModal in dark mode

- packages/bpk-component-image/src/BpkBackgroundImage-test.tsx
- packages/bpk-component-image/src/BpkBackgroundImage.tsx
Using `UNSAFE_componentWillReceiveProps` in strict mode is not recommended and may indicate bugs in your code. See https://reactjs.org/link/unsafe-component-lifecycles for details.
Remove UNSAFE_componentWillReceiveProps usage
> [CLOVER-701][BpkBackgroundImage] Remove UNSAFE_componentWillReceiveProps usage

- package.json
- packages/bpk-component-button/src/BpkButton.tsx
- packages/bpk-component-button/src/BpkButtonBase.tsx
- packages/bpk-component-button/src/common-types.ts
- packages/bpk-component-checkbox/src/BpkCheckbox.js
- packages/bpk-component-fieldset/src/BpkFieldset.js
- packages/bpk-component-flare/src/BpkContentBubble.js
- packages/bpk-component-flare/src/BpkFlareBar.js
- packages/bpk-component-form-validation/src/BpkFormValidation.js
- packages/bpk-component-info-banner/src/BpkInfoBannerInner.tsx
- packages/bpk-component-label/src/BpkLabel.js
- packages/bpk-component-link/src/BpkButtonLink.js
- packages/bpk-component-link/src/BpkLink.js
- packages/bpk-component-list/src/BpkList.js
- packages/bpk-component-list/src/BpkListItem.js
- packages/bpk-component-price/src/BpkPrice.js
- packages/bpk-component-radio/src/BpkRadio.js
- packages/bpk-component-select/src/BpkSelect.js
- packages/bpk-component-star-rating/src/BpkInteractiveStar.js
- packages/bpk-component-star-rating/src/BpkInteractiveStarRating.js
- packages/bpk-component-star-rating/src/BpkStar.js
- packages/bpk-component-star-rating/src/BpkStarRating.js
- packages/bpk-component-table/src/BpkTable.js
- packages/bpk-component-table/src/BpkTableCell.js
- packages/bpk-component-table/src/BpkTableHeadCell.js
- packages/bpk-component-textarea/src/BpkTextarea.js
> [WOODPECKER-3717]Remove defaultProps

- packages/bpk-component-input/src/BpkInput.figma.tsx
This pull request introduces a new integration file to connect the `BpkInput ` component with Figma using Code Connect. This enables designers and developers to preview and configure the component directly in Figma with mapped props.
Figma integration:
* Added a new file `BpkInput.figma.tsx` that connects the `BpkInput` component to Figma using the Code Connect API, mapping component props to Figma controls and providing a usage example for visualisation.
> [BpkInput][CLOV-740] Code connect to Figma
